treefmt alias

diff --git a/Bin/project/git/geet b/Bin/project/git/geet
--- a/Bin/project/git/geet
+++ b/Bin/project/git/geet
@@ -105,6 +105,11 @@ establish_defaults() {
   #| Message
   default_msg="Updated via geet"
   log_fmt="-1 --pretty=%B"
+
+  #| Treefmt
+  treefmt_cmd="$(command -v treefmt >/dev/null 2>&1 && "treefmt")"
+  [ "$treefmt_cmd" ] && [ -f "$TREEFMT_CONFIG" ] &&
+    treefmt_cmd="$treefmt_cmd --config-file $TREEFMT_CONFIG"
 }
 
 establish_environment() {
@@ -654,17 +659,15 @@ execute_git_actions() {
   [ "$(git status --porcelain)" ] || return 0
 
   #@ Lint
-  type treefmt >/dev/null 2>&1 && {
-    [ "$ci" ] &&
-      tfmt_args="$tfmt_args --ci"
-    # tfmt_args="$tfmt_args --no-cache --fail-on-change"
-
-    [ -f "$TREEFMT_CONFIG" ] &&
-      tfmt_args="$tfmt_args --config-file $TREEFMT_CONFIG"
-
-    eval treefmt "$tfmt_args" || return 1
-    # eval treefmt "$tfmt_args"
+  [ "$treefmt_cmd" ] && {
+    if [ "$ci" ]; then
+      eval "$(treefmt_cmd --ci)" || return 1
+      # eval "$(treefmt_cmd  --no-cache --fail-on-change)" || return 1
+    else
+      eval "$treefmt_cmd"
+    fi
   }
+
   #@ Update the local repository
   [ "$pull" ] && git pull --quiet
 
