Why is the command not working?

diff --git a/Bin/shellscript/project/nix/rebuild_nixos b/Bin/shellscript/project/nix/rebuild_nixos
--- a/Bin/shellscript/project/nix/rebuild_nixos
+++ b/Bin/shellscript/project/nix/rebuild_nixos
@@ -65,35 +65,37 @@ parse_arguments() {
 }
 
 validate_environment() {
+
   #@ Navigate to the directory where the flake is located
   if [ -n "${flake_root}" ]; then
     #@ Get the absolute path to the flake directory
-    if realpath --version /dev/null 2>&1; then
+    if command -v realpath >/dev/null 2>&1; then
       flake_root="$(realpath "${flake_root}")"
-    elif readlink --version /dev/null 2>&1; then
+    elif readlink -f >/dev/null 2>&1; then
       flake_root="$(readlink -f "${flake_root}")"
     else
       flake_root="$(cd "${flake_root}" 2>/dev/null && pwd)"
     fi
-
-    [ -f "${flake_root}/flake.nix" ] || exit 1
-    if \cd "${flake_root}"; then
-
-      #@ Check git status and encourage commit, fail if there are changes
-      git_changes_to_commit="$(${CMD_GIT} status --porcelain 2>/dev/null)"
-
-      #@ Update the nothing_to_commit flag if there are no changes
-      if [ -n "${git_changes_to_commit}" ]; then
-        printf "Please commit the following changes first:\n"
-        git status --short
-        return 1
-      fi
-    else
-      printf "Failed to navigate to flake directory: %s\n" "${flake_root}"
-      exit 1
-    fi
   else
     return 0
+  fi
+
+  #@ Check the repository status
+  # [ -f "${flake_root}/flake.nix" ] || exit 1
+  if \cd "${flake_root}"; then
+
+    #@ Check git status and encourage commit, fail if there are changes
+    git_changes_to_commit="$(${CMD_GIT} status --porcelain 2>/dev/null)"
+
+    #@ Update the nothing_to_commit flag if there are no changes
+    if [ -n "${git_changes_to_commit}" ]; then
+      printf "Please commit the following changes first:\n"
+      git status --short
+      return 1
+    fi
+  else
+    printf "Failed to navigate to flake directory: %s\n" "${flake_root}"
+    # exit 1
   fi
 }
 
