formatting down

diff --git a/Bin/project/formatters/fmtree b/Bin/project/formatters/fmtree
--- a/Bin/project/formatters/fmtree
+++ b/Bin/project/formatters/fmtree
@@ -1,23 +1,34 @@
 #!/bin/sh
 
 main() {
+  trap drop_env EXIT
   init_env
   parse_arguments "$@"
   execute_process
-  drop_env
 }
 
 init_env() {
-  _cmd="$(command -v treefmt 2>&1)"
-  _cfg="$DOTS_CFG/treefmt/treefmt.toml"
-  _root="$(pwd)"
-  _ci=1
-  _args="--allow-missing-formatter"
-  _dry=
+  FMTREE_CMD="$(command -v treefmt 2>&1)"
+  FMTREE_CFG="$DOTS_CFG/treefmt/treefmt.toml"
+  FMTREE_DIR="$(pwd)"
+  FMTREE_ARG="--allow-missing-formatter"
+  FMTREE_DRY=0
+  FMTREE_CI=1
+  DELIMITER="$(printf '\037')"
+  IFS="$DELIMITER"
+  VERBOSITY="${VERBOSITY:-4}"
 }
 
 drop_env() {
-  unset _cmd _cfg _root _ci _args
+  unset FMTREE_CMD
+  unset FMTREE_CFG
+  unset FMTREE_DIR
+  unset FMTREE_ARG
+  unset FMTREE_DRY
+  unset FMTREE_CI
+  unset DELIMITER
+  unset IFS
+  unset VERBOSITY
 }
 
 parse_arguments() {
@@ -29,7 +40,7 @@ parse_arguments() {
         exit 1
       }
 
-      _cfg="$2"
+      FMTREE_CFG="$2"
       shift
       ;;
     --root)
@@ -43,14 +54,17 @@ parse_arguments() {
         exit 1
       }
 
-      _args="${_args:+$_args }--tree-root $2"
+      FMTREE_ARG="${FMTREE_ARG:+$FMTREE_ARG${DELIMITER}}--tree-root $2"
       shift
       ;;
     --debug | --dry*)
-      _dry=1
+      FMTREE_DRY=1
+      ;;
+    -d | --verbose)
+      VERBOSITY=4
       ;;
     *)
-      _args="${_args:+$_args }$1"
+      FMTREE_ARG="${FMTREE_ARG:+$FMTREE_ARG${DELIMITER}}$1"
       ;;
     esac
     shift
@@ -59,15 +73,15 @@ parse_arguments() {
 
 execute_process() {
   #@ Validate command
-  [ "$_cmd" ] || {
+  [ "$FMTREE_CMD" ] || {
     printf "Error: treefmt not found." >&2
     return 1
   }
 
   #@ Validate config
-  [ "$_cfg" ] && {
-    if [ -f "$_cfg" ]; then
-      _cfg="--config-file $_cfg"
+  [ "$FMTREE_CFG" ] && {
+    if [ -f "$FMTREE_CFG" ]; then
+      FMTREE_CFG="--config-file $FMTREE_CFG"
     else
       printf "Error: Config file not found." >&2
       return 1
@@ -75,9 +89,9 @@ execute_process() {
   }
 
   #@ Validate tree root
-  [ "$_root" ] && {
-    if [ -d "$_root" ]; then
-      _root="--tree-root $_root"
+  [ "$FMTREE_DIR" ] && {
+    if [ -d "$FMTREE_DIR" ]; then
+      FMTREE_DIR="--tree-root $FMTREE_DIR"
     else
       printf "Error: Root directory not found." >&2
       return 1
@@ -85,16 +99,23 @@ execute_process() {
   }
 
   #@ Add the --ci flag if specified
-  [ "$_ci" ] && _args="${_args:+$_args }--ci"
+  case "$FMTREE_CI" in 0 | '' | false | no) ;; *)
+    FMTREE_ARG="${FMTREE_ARG:+$FMTREE_ARG${DELIMITER}}--ci"
+    # FMTREE_ARG="${FMTREE_ARG:+$FMTREE_ARG${DELIMITER}}--no-cache --fail-on-change"
+    ;;
+  esac
 
   #@ Build the final command
-  _cmd="$(printf "%s %s %s %s" "$_cmd" "$_cfg" "$_root" "$_args")"
+  FMTREE_CMD="$(printf "%s %s %s %s" \
+    "$FMTREE_CMD" "$FMTREE_CFG" "$FMTREE_DIR" \
+    "$(printf "%s" "$FMTREE_ARG" | tr "$DELIMITER" " ")")"
 
   #@ Print command
-  printf '\033[1;36m[ INFO ]\033[0m Executing command => %s\n' "$_cmd"
+  [ "$VERBOSITY" -ge 4 ] &&
+    printf '\033[1;36m[ INFO ]\033[0m Executing command => %s\n' "$FMTREE_CMD"
 
   #@ Run command
-  [ "$_dry" ] || eval "$_cmd"
+  [ "$FMTREE_DRY" -eq 0 ] && eval "$FMTREE_CMD"
 }
 
 main "$@"
