set treefmt as the default formatter in vscode

diff --git a/Bin/shellscript/packages/alias/shHarden b/Bin/shellscript/packages/alias/shHarden
--- a/Bin/shellscript/packages/alias/shHarden
+++ b/Bin/shellscript/packages/alias/shHarden
@@ -2,113 +2,113 @@
 
 #/> Script Entry-point                              <\
 main() { #@ Run the application
-  #> Initialization
-  init_metadata
-  parse_arguments "$@"
+	#> Initialization
+	init_metadata
+	parse_arguments "$@"
 
-  #> Validation
-  validate_environment
+	#> Validation
+	validate_environment
 
-  #> Termination
-  run_process
+	#> Termination
+	run_process
 }
 
 #/> Initialization                                  <\
 init_metadata() { #@ Initalize bin_name metadata
-  required_arg="shellscript binary file"
-  SCRIPT_NAME="$(basename "$0")"
-  SCRIPT_VERSION="1.0.0"
-  SCRIPT_AUTHOR="Craole"
-  SCRIPT_USAGE="$SCRIPT_NAME [OPTIONS] <$required_arg>"
-  SCRIPT_DESCRIPTION="allows the user to specify a binary bin_name to check with shellharden"
+	required_arg="shellscript binary file"
+	SCRIPT_NAME="$(basename "$0")"
+	SCRIPT_VERSION="1.0.0"
+	SCRIPT_AUTHOR="Craole"
+	SCRIPT_USAGE="$SCRIPT_NAME [OPTIONS] <$required_arg>"
+	SCRIPT_DESCRIPTION="allows the user to specify a binary bin_name to check with shellharden"
 }
 
 parse_arguments() { #@ Parse command-line arguments
-  # echo "1: $1"
+	# echo "1: $1"
 
-  while [ "$#" -gt 0 ]; do
-    case $1 in
-    -h | --help)
-      display_info --usage
-      exit 0
-      ;;
-    -v | --version)
-      display_info --version
-      exit 0
-      ;;
-    -b | --bin | -p | --path)
-      binary="$2"
-      shift
-      ;;
-    --suggest | --syntax | --transform | --check | --replace)
-      shellharden_opt="$1"
-      ;;
-    *) binary="$1" ;;
-    esac
-    shift
-  done
+	while [ "$#" -gt 0 ]; do
+		case $1 in
+		-h | --help)
+			display_info --usage
+			exit 0
+			;;
+		-v | --version)
+			display_info --version
+			exit 0
+			;;
+		-b | --bin | -p | --path)
+			binary="$2"
+			shift
+			;;
+		--suggest | --syntax | --transform | --check | --replace)
+			shellharden_opt="$1"
+			;;
+		*) binary="$1" ;;
+		esac
+		shift
+	done
 }
 
 #/> Validation                                      <\
 validate_environment() { #@ Run various validation checks
 
-  #@ Check if a path is provided as an argument
-  if [ "$binary" ]; then
-    binary="$(pathof "$binary")"
-  else
-    display_info --error-arg
-    exit 1
-  fi
+	#@ Check if a path is provided as an argument
+	if [ "$binary" ]; then
+		binary="$(pathof "$binary")"
+	else
+		display_info --error-arg
+		exit 1
+	fi
 
 }
 
 #/> Execution                                       <\
 run_process() { #@ Lint with Shellharden
 
-  if
-    ! shellharden --check "$binary" &&
-      [ "$shellharden_opt" = "--replace" ]
-  then
-    cp --backup=numbered "$binary" "$binary".bac || {
-      display_info --error-bac "$binary"
-      exit 1
-    }
-  fi
+	if
+		! shellharden --check "$binary" &&
+			[ "$shellharden_opt" = "--replace" ]
+	then
+		cp --backup=numbered "$binary" "$binary".bac || {
+			display_info --error-bac "$binary"
+			exit 1
+		}
+	fi
 
-  if [ "$shellharden_opt" ]; then
-    binary_harden="shellharden $shellharden_opt $binary"
-  else
-    binary_harden="shellharden $binary"
-  fi
+	if [ "$shellharden_opt" ]; then
+		binary_harden="shellharden $shellharden_opt $binary"
+	else
+		binary_harden="shellharden $binary"
+	fi
 
-  display_info --output "$binary_harden"
-  eval "$binary_harden"
+	display_info --output "$binary_harden"
+	eval "$binary_harden"
 }
 
 #/> Output Management                               <\
 display_info() { #@ Display infoirmation
-  case "$1" in
-  --error-arg)
-    printf "%s required \nUsage: %s\n" \
-      "$required_arg" "$SCRIPT_USAGE"
-    ;;
-  --error-bac)
-    printf "Failed to archive file\n"
-    ;;
-  --output)
-    # if [ "$shellharden_opt" ]; then
-    #   printf "%s via %s\n" "$binary" "$shellharden_opt"
-    # else
-    #   printf "%s\n" "$binary"
-    # fi
-    printf "%s\n" "$binary_harden"
+	case "$1" in
+	--error-arg)
+		printf "%s required \nUsage: %s\n" \
+			"$required_arg" "$SCRIPT_USAGE"
+		;;
+	--error-bac)
+		printf "Failed to archive file\n"
+		;;
+	--output)
+		# if [ "$shellharden_opt" ]; then
+		#   printf "%s via %s\n" "$binary" "$shellharden_opt"
+		# else
+		#   printf "%s\n" "$binary"
+		# fi
+		printf "%s\n" "$binary_harden"
 
-    ;;
-  --version)
-    printf "%s" "$SCRIPT_VERSION"
-    ;;
-  --usage)
-    cat <<USAGE
+		;;
+	--version)
+		printf "%s" "$SCRIPT_VERSION"
+		;;
+	--usage)
+		cat <<USAGE
 Debin_nameion:
 '$SCRIPT_NAME' by $SCRIPT_AUTHOR $SCRIPT_DESCRIPTION
 
@@ -139,9 +139,9 @@ Examples:
 
 For more information on the available options, see the shellharden documentation.
 USAGE
-    ;;
-  *) printf "%s\n" "$*" ;;
-  esac
+		;;
+	*) printf "%s\n" "$*" ;;
+	esac
 }
 
 main "$@"
diff --git a/Bin/shellscript/project/git/gitini1 b/Bin/shellscript/project/git/gitini1
--- a/Bin/shellscript/project/git/gitini1
+++ b/Bin/shellscript/project/git/gitini1
@@ -2,23 +2,23 @@
 # TODO: Merge with geet
 
 main() {
-  #| Establish Environment
-  define_metadata
-  define_defaults
-  parse_arguments "$@"
+	#| Establish Environment
+	define_metadata
+	define_defaults
+	parse_arguments "$@"
 
-  #| Validate Environment
-  validate_dependencies
+	#| Validate Environment
+	validate_dependencies
 
-  #| Execute Process
-  if [ "$debug" ]; then
-    execute_tests
-  elif [ "$info" ]; then
-    get_platform
-    execute_info
-  else
-    execute_process
-  fi
+	#| Execute Process
+	if [ "$debug" ]; then
+		execute_tests
+	elif [ "$info" ]; then
+		get_platform
+		execute_info
+	else
+		execute_process
+	fi
 }
 
 # @ ============================================================= @ #
@@ -26,126 +26,126 @@ main() {
 # @ ============================================================= @ #
 
 define_metadata() {
-  _cmd_PATH="$(pathof "$0")"
-  _cmd_NAME="$(basename "$_cmd_PATH")"
-  _cmd_HOME="$(dirname -- "$_cmd_PATH")"
-  _cmd_VERSION="1.0"
-  _cmd_DESCRIPTION="Simplifies the git update process"
-  _cmd_DEPENDENCIES="git, bat"
+	_cmd_PATH="$(pathof "$0")"
+	_cmd_NAME="$(basename "$_cmd_PATH")"
+	_cmd_HOME="$(dirname -- "$_cmd_PATH")"
+	_cmd_VERSION="1.0"
+	_cmd_DESCRIPTION="Simplifies the git update process"
+	_cmd_DEPENDENCIES="git, bat"
 }
 
 define_defaults() {
-  unset \
-    name email branch message repo \
-    info verbose debug
+	unset \
+		name email branch message repo \
+		info verbose debug
 
-  default_branch="main"
-  scopes="local, global, system, worktree"
-  icon_for_update="🔃"
-  icon_for_init="🆕"
-  exit_code=0
+	default_branch="main"
+	scopes="local, global, system, worktree"
+	icon_for_update="🔃"
+	icon_for_init="🆕"
+	exit_code=0
 
-  [ "$GEET_DIR" ] || GEET_DIR="$(get_dir)"
-  [ "$GEET_DIR" ] || GEET_PLATFORM="$(get_platform)"
-  [ "$GEET_OWNER" ] || GEET_OWNER="$(get_owner)"
-  [ "$GEET_NAME" ] || GEET_NAME="$(get_repo_name)"
-  [ "$GEET_USER" ] || GEET_USER="$(get_user_name)"
-  [ "$GEET_EMAIL" ] || GEET_EMAIL="$(get_user_email)"
-  [ "$GEET_URL" ] || GEET_URL="$(get_remote_url)"
-  [ "$GEET_PAT" ] || GEET_PAT="$(get_pat)"
-  [ "$GEET_BRANCH" ] || GEET_BRANCH="$(get_branch)"
-  [ "$GEET_MESSAGE" ] || GEET_MESSAGE="$(get_commit_message)"
-  [ "$GEET_STORE_CREDENTIALS" ] || GEET_STORE_CREDENTIALS=true
-  [ "$GEET_INCLUDE_SUBMODULES" ] || GEET_INCLUDE_SUBMODULES=true
-  [ "$GEET_SCOPE" ] || GEET_SCOPE="local"
+	[ "$GEET_DIR" ] || GEET_DIR="$(get_dir)"
+	[ "$GEET_DIR" ] || GEET_PLATFORM="$(get_platform)"
+	[ "$GEET_OWNER" ] || GEET_OWNER="$(get_owner)"
+	[ "$GEET_NAME" ] || GEET_NAME="$(get_repo_name)"
+	[ "$GEET_USER" ] || GEET_USER="$(get_user_name)"
+	[ "$GEET_EMAIL" ] || GEET_EMAIL="$(get_user_email)"
+	[ "$GEET_URL" ] || GEET_URL="$(get_remote_url)"
+	[ "$GEET_PAT" ] || GEET_PAT="$(get_pat)"
+	[ "$GEET_BRANCH" ] || GEET_BRANCH="$(get_branch)"
+	[ "$GEET_MESSAGE" ] || GEET_MESSAGE="$(get_commit_message)"
+	[ "$GEET_STORE_CREDENTIALS" ] || GEET_STORE_CREDENTIALS=true
+	[ "$GEET_INCLUDE_SUBMODULES" ] || GEET_INCLUDE_SUBMODULES=true
+	[ "$GEET_SCOPE" ] || GEET_SCOPE="local"
 }
 
 get_dir() {
-  # # TODO: This looks messy
-  # case "$1" in
-  # -q | --quiet)
-  #   [ "$(git rev-parse --show-toplevel 2>/dev/null)" ] >/dev/null
-  #   ;;
-  # *)
-  #   git rev-parse --show-toplevel 2>/dev/null
-  #   ;;
-  # esac
-  git rev-parse --show-toplevel 2>/dev/null
+	# # TODO: This looks messy
+	# case "$1" in
+	# -q | --quiet)
+	#   [ "$(git rev-parse --show-toplevel 2>/dev/null)" ] >/dev/null
+	#   ;;
+	# *)
+	#   git rev-parse --show-toplevel 2>/dev/null
+	#   ;;
+	# esac
+	git rev-parse --show-toplevel 2>/dev/null
 }
 
 get_config() {
-  git config --list --"${scope}" 2>/dev/null
+	git config --list --"${scope}" 2>/dev/null
 }
 
 get_remote_url() {
-  git config --get remote.origin.url 2>/dev/null
+	git config --get remote.origin.url 2>/dev/null
 }
 
 get_platform() {
-  get_remote_url | sed \
-    "s#https://[^@]\+@##; s#git@\([^:]\+\):.*#\1#; s#https\?://##; s#/.*##"
+	get_remote_url | sed \
+		"s#https://[^@]\+@##; s#git@\([^:]\+\):.*#\1#; s#https\?://##; s#/.*##"
 }
 
 get_owner() {
-  get_remote_url | sed --quiet \
-    "s#.*$(get_platform)[:/]\([^/]\+\)/.*#\1#p"
+	get_remote_url | sed --quiet \
+		"s#.*$(get_platform)[:/]\([^/]\+\)/.*#\1#p"
 }
 
 get_user_name() {
-  from_url="$(
-    get_remote_url | sed --quiet 's#https://\([^:]\+\):.*@.*#\1#p'
-  )"
-  from_config="$(git config --get user.name)"
-  from_owner="$(get_owner)"
-  from_system="${USER:-"$USERNAME"}"
+	from_url="$(
+		get_remote_url | sed --quiet 's#https://\([^:]\+\):.*@.*#\1#p'
+	)"
+	from_config="$(git config --get user.name)"
+	from_owner="$(get_owner)"
+	from_system="${USER:-"$USERNAME"}"
 
-  if [ "$from_url" ]; then
-    result="$from_url"
-  elif [ "$from_config" ]; then
-    result="$from_config"
-  elif [ "$from_owner" ]; then
-    result="$from_owner"
-  elif [ "$from_system" ]; then
-    result="$from_system"
-  fi
+	if [ "$from_url" ]; then
+		result="$from_url"
+	elif [ "$from_config" ]; then
+		result="$from_config"
+	elif [ "$from_owner" ]; then
+		result="$from_owner"
+	elif [ "$from_system" ]; then
+		result="$from_system"
+	fi
 
-  printf "%s" "$result"
+	printf "%s" "$result"
 }
 
 get_user_email() {
-  git config --get user.email 2>/dev/null
-  # TODO: as a fallback, fetch the public one if possible based on the user.name or repo url
+	git config --get user.email 2>/dev/null
+	# TODO: as a fallback, fetch the public one if possible based on the user.name or repo url
 }
 
 get_repo_name() {
-  get_remote_url | sed --quiet "s#.*/\([^/]\+\)\.git#\1#p"
+	get_remote_url | sed --quiet "s#.*/\([^/]\+\)\.git#\1#p"
 }
 
 get_pat() {
-  result="$(get_remote_url | sed "s#https://[^:]\+:\([^@]\+\)@.*#\1#")"
-  [ "$(get_remote_url)" != "$result" ] && printf "%s" "$result"
+	result="$(get_remote_url | sed "s#https://[^:]\+:\([^@]\+\)@.*#\1#")"
+	[ "$(get_remote_url)" != "$result" ] && printf "%s" "$result"
 }
 
 get_branch() {
-  git rev-parse --abbrev-ref HEAD 2>/dev/null | grep -v HEAD ||
-    git describe --exact-match HEAD 2>/dev/null ||
-    git branch --show-current 2>/dev/null ||
-    git branch 2>/dev/null | sed --quiet 's/^\* //p' 2>/dev/null ||
-    printf "%s" "$default_branch"
+	git rev-parse --abbrev-ref HEAD 2>/dev/null | grep -v HEAD ||
+		git describe --exact-match HEAD 2>/dev/null ||
+		git branch --show-current 2>/dev/null ||
+		git branch 2>/dev/null | sed --quiet 's/^\* //p' 2>/dev/null ||
+		printf "%s" "$default_branch"
 }
 
 get_commit_message() {
-  if git log >/dev/null 2>&1; then
-    previous_message="$(git log -1 --pretty=%B)"
+	if git log >/dev/null 2>&1; then
+		previous_message="$(git log -1 --pretty=%B)"
 
-    [ "$(git log --oneline | wc -l)" -eq 1 ] &&
-      [ "$previous_message" = "$icon_for_init" ] &&
-      previous_message="$icon_for_update"
-  else
-    previous_message="$icon_for_init"
-  fi
+		[ "$(git log --oneline | wc -l)" -eq 1 ] &&
+			[ "$previous_message" = "$icon_for_init" ] &&
+			previous_message="$icon_for_update"
+	else
+		previous_message="$icon_for_init"
+	fi
 
-  printf "%s" "$previous_message"
+	printf "%s" "$previous_message"
 }
 
 # @ ============================================================= @ #
@@ -153,55 +153,55 @@ get_commit_message() {
 # @ ============================================================= @ #
 
 parse_list() {
-  printf "%s" "$*" | tr -s -c '[:alnum:]' ' '
+	printf "%s" "$*" | tr -s -c '[:alnum:]' ' '
 }
 
 parse_arguments() {
-  [ "$#" -eq 0 ] && info=true
+	[ "$#" -eq 0 ] && info=true
 
-  while [ "$#" -ge 1 ]; do
-    case $1 in
-    -h | --help)
-      console_log "$(define_usage)" --ll
-      exit 0
-      ;;
-    -v | --version)
-      console_log "$_cmd_VERSION" --ll
-      exit 0
-      ;;
-    -d | --verbose | --debug) verbose=true ;;
-    -i | --info) info=true ;;
-    -n | --name)
-      if [ -z "$2" ]; then
-        console_log --error "No name provided for -n or --name option." --ll
-        exit 1
-      else
-        GEET_NAME="$2"
-      fi
-      ;;
-    -e | --email)
-      if [ -z "$2" ]; then
-        console_log --error "No email provided for -e or --email option." --ll
-        exit 1
-      else
-        GEET_EMAIL="$2"
-      fi
-      ;;
-    -b | --branch) GEET_BRANCH="$2" ;;
-    -m | --message) GEET_MESSAGE="$2" ;;
-    -s | --scope) GEET_SCOPE="$2" ;;
-    -c | --store-creds) GEET_STORE_CREDENTIALS=true ;;
-    -*)
-      console_log --error "Unknown Option:" "$1"
-      console_log "Use -h or --help to display the usage guide." --ll
-      exit 1
-      ;;
-    *) message="$message $1" ;;
-    esac
-    shift
-  done
+	while [ "$#" -ge 1 ]; do
+		case $1 in
+		-h | --help)
+			console_log "$(define_usage)" --ll
+			exit 0
+			;;
+		-v | --version)
+			console_log "$_cmd_VERSION" --ll
+			exit 0
+			;;
+		-d | --verbose | --debug) verbose=true ;;
+		-i | --info) info=true ;;
+		-n | --name)
+			if [ -z "$2" ]; then
+				console_log --error "No name provided for -n or --name option." --ll
+				exit 1
+			else
+				GEET_NAME="$2"
+			fi
+			;;
+		-e | --email)
+			if [ -z "$2" ]; then
+				console_log --error "No email provided for -e or --email option." --ll
+				exit 1
+			else
+				GEET_EMAIL="$2"
+			fi
+			;;
+		-b | --branch) GEET_BRANCH="$2" ;;
+		-m | --message) GEET_MESSAGE="$2" ;;
+		-s | --scope) GEET_SCOPE="$2" ;;
+		-c | --store-creds) GEET_STORE_CREDENTIALS=true ;;
+		-*)
+			console_log --error "Unknown Option:" "$1"
+			console_log "Use -h or --help to display the usage guide." --ll
+			exit 1
+			;;
+		*) message="$message $1" ;;
+		esac
+		shift
+	done
 
-  message="${message# }"
+	message="${message# }"
 }
 
 # @ ============================================================= @ #
@@ -209,54 +209,54 @@ parse_arguments() {
 # @ ============================================================= @ #
 
 validate_dependencies() {
-  # | Set default values for local variables
-  missing_deps=""
-  missing_deps_count=0
+	# | Set default values for local variables
+	missing_deps=""
+	missing_deps_count=0
 
-  # | Validate dependencies as executable files
-  for dependency in $(parse_list "$_cmd_DEPENDENCIES"); do
-    pathof "$dependency" --is-executable ||
-      if [ -n "$missing_deps" ]; then
-        missing_deps="$missing_deps, $dependency"
-      else
-        missing_deps="$dependency"
-      fi
-  done
+	# | Validate dependencies as executable files
+	for dependency in $(parse_list "$_cmd_DEPENDENCIES"); do
+		pathof "$dependency" --is-executable ||
+			if [ -n "$missing_deps" ]; then
+				missing_deps="$missing_deps, $dependency"
+			else
+				missing_deps="$dependency"
+			fi
+	done
 
-  # | Continue the program if dependency paths are validated
-  [ "$missing_deps" ] || return
+	# | Continue the program if dependency paths are validated
+	[ "$missing_deps" ] || return
 
-  # | Count the number of missing dependencies
-  missing_deps_count="$(
-    console_log "$missing_deps" |
-      tr ',' '\n' | wc -l
-  )"
+	# | Count the number of missing dependencies
+	missing_deps_count="$(
+		console_log "$missing_deps" |
+			tr ',' '\n' | wc -l
+	)"
 
-  # | Update the error message based on the count
-  msg="Missing dependency"
-  [ "$missing_deps_count" -gt 1 ] && msg="Missing dependencies"
+	# | Update the error message based on the count
+	msg="Missing dependency"
+	[ "$missing_deps_count" -gt 1 ] && msg="Missing dependencies"
 
-  # | Halt the program and report missing dependencies
-  # TODO: Fix console_log to print each dependency on a new line
-  console_log --error "$msg" "$missing_deps"
-  exit_code=2
-  exit "$exit_code"
+	# | Halt the program and report missing dependencies
+	# TODO: Fix console_log to print each dependency on a new line
+	console_log --error "$msg" "$missing_deps"
+	exit_code=2
+	exit "$exit_code"
 }
 
 validate_message() {
-  # Strip the name and email from the message
-  if [ -n "$name" ]; then
-    message=$(printf "%s" "$message" | sed "s/$name //g")
-  fi
+	# Strip the name and email from the message
+	if [ -n "$name" ]; then
+		message=$(printf "%s" "$message" | sed "s/$name //g")
+	fi
 
-  if [ -n "$email" ]; then
-    message=$(printf "%s" "$message" | sed "s/$email //g")
-  fi
+	if [ -n "$email" ]; then
+		message=$(printf "%s" "$message" | sed "s/$email //g")
+	fi
 
-  case "$message" in "$name" | "$email" | "$branch")
-    unset message
-    ;;
-  esac
+	case "$message" in "$name" | "$email" | "$branch")
+		unset message
+		;;
+	esac
 }
 
 # validate_email() {
@@ -282,43 +282,43 @@ validate_message() {
 # @ ============================================================= @ #
 
 updates_pending() {
-  [ "$(git status --porcelain)" ]
+	[ "$(git status --porcelain)" ]
 }
 
 set_config() {
-  while [ "$#" -ge 1 ]; do
-    case "$1" in
-    --key) key="$2" ;;
-    --val) val="$2" ;;
-    esac
-    shift
-  done
+	while [ "$#" -ge 1 ]; do
+		case "$1" in
+		--key) key="$2" ;;
+		--val) val="$2" ;;
+		esac
+		shift
+	done
 
-  [ "$key" ] && [ "$val" ] &&
-    eval "git config --${scope}" "$key" "$val"
+	[ "$key" ] && [ "$val" ] &&
+		eval "git config --${scope}" "$key" "$val"
 }
 
 set_dir() {
-  if git init --initial-branch="$branch" >/dev/null 2>&1; then
-    [ "$verbose" ] && console_log --info "GIT_DIR" "$(get_dir)"
-  else
-    console_log --error "Failed to rename branch."
-    return 2
-  fi
+	if git init --initial-branch="$branch" >/dev/null 2>&1; then
+		[ "$verbose" ] && console_log --info "GIT_DIR" "$(get_dir)"
+	else
+		console_log --error "Failed to rename branch."
+		return 2
+	fi
 }
 
 set_branch() {
-  if git branch --move --force "$branch" >/dev/null 2>&1; then
-    [ "$verbose" ] && console_log --info "Branch" "$(get_branch)"
-  else
-    console_log --error "Failed to initialize the repository."
-    return 2
-  fi
+	if git branch --move --force "$branch" >/dev/null 2>&1; then
+		[ "$verbose" ] && console_log --info "Branch" "$(get_branch)"
+	else
+		console_log --error "Failed to initialize the repository."
+		return 2
+	fi
 }
 
 set_credential_store() {
-  [ "$store_creds" ] &&
-    eval "git config --${scope} credential.helper store" 2>/dev/null
+	[ "$store_creds" ] &&
+		eval "git config --${scope} credential.helper store" 2>/dev/null
 }
 
 # set_remote_origin() {
@@ -327,18 +327,18 @@ set_credential_store() {
 # }
 
 set_message() {
-  validate_message
-  get_message
-  message="${message:-$previous_message}"
-  [ "$verbose" ] && console_log --info "Message" "$previous_message"
+	validate_message
+	get_message
+	message="${message:-$previous_message}"
+	[ "$verbose" ] && console_log --info "Message" "$previous_message"
 }
 
 set_email() {
-  [ "$email" ] && set_config --key "user.email" --val "$email"
+	[ "$email" ] && set_config --key "user.email" --val "$email"
 }
 
 set_name() {
-  [ "$name" ] && set_config --key "user.name" --val "$name"
+	[ "$name" ] && set_config --key "user.name" --val "$name"
 }
 
 # @ ============================================================= @ #
@@ -346,77 +346,77 @@ set_name() {
 # @ ============================================================= @ #
 
 execute_info() {
-  if [ "$GEET_DIR" ]; then
-    # TODO: Improve output
-    console_log --info "DIR           " "$GEET_DIR"
-    console_log --info "PLATFORM      " "$GEET_PLATFORM"
-    console_log --info "OWNER         " "$GEET_OWNER"
-    console_log --info "NAME          " "$GEET_NAME"
-    console_log --info "USER          " "$GEET_USER"
-    console_log --info "EMAIL         " "$GEET_EMAIL"
-    console_log --info "BRANCH        " "$GEET_BRANCH"
-    console_log --info "URL           " "$GEET_URL"
-    [ "$GEET_PAT" ] &&
-      console_log --info "PAT           " "$GEET_PAT"
-    # console_log --info "SUBMODULES    " "$(get_submodules)"
-    # set_message
-    console_log --info "MESSAGE       " "$GEET_MESSAGE" --ll
-  else
-    console_log "This directory has not been initialized for git"
-  fi
+	if [ "$GEET_DIR" ]; then
+		# TODO: Improve output
+		console_log --info "DIR           " "$GEET_DIR"
+		console_log --info "PLATFORM      " "$GEET_PLATFORM"
+		console_log --info "OWNER         " "$GEET_OWNER"
+		console_log --info "NAME          " "$GEET_NAME"
+		console_log --info "USER          " "$GEET_USER"
+		console_log --info "EMAIL         " "$GEET_EMAIL"
+		console_log --info "BRANCH        " "$GEET_BRANCH"
+		console_log --info "URL           " "$GEET_URL"
+		[ "$GEET_PAT" ] &&
+			console_log --info "PAT           " "$GEET_PAT"
+		# console_log --info "SUBMODULES    " "$(get_submodules)"
+		# set_message
+		console_log --info "MESSAGE       " "$GEET_MESSAGE" --ll
+	else
+		console_log "This directory has not been initialized for git"
+	fi
 }
 
 execute_process() {
-  if get_dir --quiet; then
-    [ "$branch" ] && [ "$(get_branch)" = "$branch" ] &&
-      set_branch
-  else
-    branch="${branch:-"$default_branch"}"
-    set_dir
-  fi
+	if get_dir --quiet; then
+		[ "$branch" ] && [ "$(get_branch)" = "$branch" ] &&
+			set_branch
+	else
+		branch="${branch:-"$default_branch"}"
+		set_dir
+	fi
 
-  set_credential_store
-  set_email
-  set_name
-  set_message
+	set_credential_store
+	set_email
+	set_name
+	set_message
 
-  # | Validate && Update
-  if
-    get_user_name >/dev/null 2>&1 &&
-      get_user_email >/dev/null 2>&1 &&
-      get_branch >/dev/null 2>&1
-  then
-    updates_pending && {
-      git add --all
-      git commit --quiet --message="$message"
-      [ "$verbose" ] && console_log "$message"
-    }
-  else
-    exit_code="$?"
-  fi
+	# | Validate && Update
+	if
+		get_user_name >/dev/null 2>&1 &&
+			get_user_email >/dev/null 2>&1 &&
+			get_branch >/dev/null 2>&1
+	then
+		updates_pending && {
+			git add --all
+			git commit --quiet --message="$message"
+			[ "$verbose" ] && console_log "$message"
+		}
+	else
+		exit_code="$?"
+	fi
 
-  execute_info
+	execute_info
 
-  exit "$exit_code"
+	exit "$exit_code"
 }
 
 define_usage() {
 
-  title="$_cmd_NAME ($_cmd_VERSION)"
-  border="::-----------------------------------------------------------------::"
-  padding=$(((${#border} - ${#title}) / 2))
-  heading="$(printf "%*s\n" $((padding + ${#title})) "$title")"
-  note="$(
-    fold -s -w $((${#border} - 6)) <<'NOTE' | sed 's/^/    /'
+	title="$_cmd_NAME ($_cmd_VERSION)"
+	border="::-----------------------------------------------------------------::"
+	padding=$(((${#border} - ${#title}) / 2))
+	heading="$(printf "%*s\n" $((padding + ${#title})) "$title")"
+	note="$(
+		fold -s -w $((${#border} - 6)) <<'NOTE' | sed 's/^/    /'
  can be run with or without options. If options are not provided, it will attempt to perform a commit with the current repository state and default configurations.
 
 If the repository is not initialized, the script will initialize it with the specified branch. If both local and global configurations exist, the local configurations take precedence.
 
 Also, if both an option and its corresponding environment variable are set, the option value takes precedence.
 NOTE
-  )"
+	)"
 
-  cat <<USAGE_GUIDE
+	cat <<USAGE_GUIDE
 $border
 $heading
 $border
diff --git a/Bin/shellscript/template/Getopt b/Bin/shellscript/template/Getopt
--- a/Bin/shellscript/template/Getopt
+++ b/Bin/shellscript/template/Getopt
@@ -33,38 +33,38 @@ unset TEMP
 
 while true; do
 	case "$1" in
-		'-a'|'--a-long')
-			echo 'Option a'
-			shift
-			continue
+	'-a' | '--a-long')
+		echo 'Option a'
+		shift
+		continue
 		;;
-		'-b'|'--b-long')
-			echo "Option b, argument '$2'"
-			shift 2
-			continue
+	'-b' | '--b-long')
+		echo "Option b, argument '$2'"
+		shift 2
+		continue
 		;;
-		'-c'|'--c-long')
-			# c has an optional argument. As we are in quoted mode,
-			# an empty parameter will be generated if its optional
-			# argument is not found.
-			case "$2" in
-				'')
-					echo 'Option c, no argument'
-				;;
-				*)
-					echo "Option c, argument '$2'"
-				;;
-			esac
-			shift 2
-			continue
-		;;
-		'--')
-			shift
-			break
-		;;
+	'-c' | '--c-long')
+		# c has an optional argument. As we are in quoted mode,
+		# an empty parameter will be generated if its optional
+		# argument is not found.
+		case "$2" in
+		'')
+			echo 'Option c, no argument'
+			;;
 		*)
-			echo 'Internal error!' >&2
-			exit 1
+			echo "Option c, argument '$2'"
+			;;
+		esac
+		shift 2
+		continue
+		;;
+	'--')
+		shift
+		break
+		;;
+	*)
+		echo 'Internal error!' >&2
+		exit 1
 		;;
 	esac
 done
diff --git a/Bin/shellscript/utility/files/pathman b/Bin/shellscript/utility/files/pathman
--- a/Bin/shellscript/utility/files/pathman
+++ b/Bin/shellscript/utility/files/pathman
@@ -2,294 +2,294 @@
 # shellcheck disable=SC2031
 
 main() {
-  initialize_env
-  parse_arguments "$@" || return 1
-  perform_action
+	initialize_env
+	parse_arguments "$@" || return 1
+	perform_action
 }
 
 initialize_env() {
-  #@ set defaults
-  verbosity=0
-  action="show"
-  bins=""
-  debug=""
-  delimiter="$(printf '\037')"
+	#@ set defaults
+	verbosity=0
+	action="show"
+	bins=""
+	debug=""
+	delimiter="$(printf '\037')"
 
-  #@ Cache command checks at startup
-  HAS_REALPATH=0
-  HAS_FD=0
-  command -v realpath >/dev/null 2>&1 && HAS_REALPATH=1
-  command -v fd >/dev/null 2>&1 && HAS_FD=1
-  command -v bat >/dev/null 2>&1 && HAS_BAT=1
+	#@ Cache command checks at startup
+	HAS_REALPATH=0
+	HAS_FD=0
+	command -v realpath >/dev/null 2>&1 && HAS_REALPATH=1
+	command -v fd >/dev/null 2>&1 && HAS_FD=1
+	command -v bat >/dev/null 2>&1 && HAS_BAT=1
 }
 parse_arguments() {
-  while [ "$#" -gt 0 ]; do
-    case "$1" in
-    --debug)
-      debug="debug"
-      ;;
-    --error) verbosity=1 ;;
-    --quiet) verbosity=0 ;;
-    --show)
-      action="show"
-      ;;
-    --clean)
-      action="clean"
-      ;;
-    --action)
-      if [ "$2" ]; then
-        action="$2"
-        shift
-      else
-        printf "'%s' requires an argument [ append | prepend | show ]\n" "$1"
-        return 1
-      fi
-      ;;
-    --append)
-      action="append"
-      ;;
-    --prepend)
-      action="prepend"
-      ;;
-    --dir*)
-      if [ "$2" ]; then
-        shift
-        if [ "$bins" ]; then
-          bins="$(printf '%s%s%s' "$bins" "$delimiter" "$(resolved_path "$1")")"
-        else
-          bins="$(resolved_path "$1")"
-        fi
-      else
-        printf "'%s' requires an argument\n" "$1"
-        return 1
-      fi
-      ;;
-    *)
-      if [ -f "$1" ]; then
-        make_exec "$1"
-        return 0
-      elif [ "$bins" ]; then
-        bins="$(printf '%s%s%s' "$bins" "$delimiter" "$(resolved_path "$1")")"
-      else
-        bins="$(resolved_path "$1")"
-      fi
-      ;;
-    esac
-    shift
-  done
+	while [ "$#" -gt 0 ]; do
+		case "$1" in
+		--debug)
+			debug="debug"
+			;;
+		--error) verbosity=1 ;;
+		--quiet) verbosity=0 ;;
+		--show)
+			action="show"
+			;;
+		--clean)
+			action="clean"
+			;;
+		--action)
+			if [ "$2" ]; then
+				action="$2"
+				shift
+			else
+				printf "'%s' requires an argument [ append | prepend | show ]\n" "$1"
+				return 1
+			fi
+			;;
+		--append)
+			action="append"
+			;;
+		--prepend)
+			action="prepend"
+			;;
+		--dir*)
+			if [ "$2" ]; then
+				shift
+				if [ "$bins" ]; then
+					bins="$(printf '%s%s%s' "$bins" "$delimiter" "$(resolved_path "$1")")"
+				else
+					bins="$(resolved_path "$1")"
+				fi
+			else
+				printf "'%s' requires an argument\n" "$1"
+				return 1
+			fi
+			;;
+		*)
+			if [ -f "$1" ]; then
+				make_exec "$1"
+				return 0
+			elif [ "$bins" ]; then
+				bins="$(printf '%s%s%s' "$bins" "$delimiter" "$(resolved_path "$1")")"
+			else
+				bins="$(resolved_path "$1")"
+			fi
+			;;
+		esac
+		shift
+	done
 }
 
 perform_action() {
-  case "$action" in
-  append | prepend)
-    #@ Validate that a directory was provided
-    if [ -z "$bins" ]; then
-      printf "ERROR: No path provided\n"
-      return 1
-    fi
+	case "$action" in
+	append | prepend)
+		#@ Validate that a directory was provided
+		if [ -z "$bins" ]; then
+			printf "ERROR: No path provided\n"
+			return 1
+		fi
 
-    add_to_path
-    ;;
-  clean)
-    clean_path
-    ;;
-  show)
-    show_bins "$PATH"
-    ;;
-  esac
+		add_to_path
+		;;
+	clean)
+		clean_path
+		;;
+	show)
+		show_bins "$PATH"
+		;;
+	esac
 }
 
 resolved_path() {
-  [ "$HAS_REALPATH" = 1 ] && realpath "$1" && return
+	[ "$HAS_REALPATH" = 1 ] && realpath "$1" && return
 
-  if [ -d "$1" ]; then
-    (cd -- "$1" && pwd)
-  else
-    dir="$(cd "$(dirname "$1")" && pwd)"
-    printf '%s/%s\n' "$dir" "$(basename "$1")"
-  fi
+	if [ -d "$1" ]; then
+		(cd -- "$1" && pwd)
+	else
+		dir="$(cd "$(dirname "$1")" && pwd)"
+		printf '%s/%s\n' "$dir" "$(basename "$1")"
+	fi
 }
 
 recursive_paths() {
-  dirs="$(printf '%s' "$*" | tr "$delimiter" '\n')"
+	dirs="$(printf '%s' "$*" | tr "$delimiter" '\n')"
 
-  for dir in $dirs; do
-    if [ "$HAS_FD" = 1 ]; then
-      #@ Add the results from fd
-      fd . "$dir"
+	for dir in $dirs; do
+		if [ "$HAS_FD" = 1 ]; then
+			#@ Add the results from fd
+			fd . "$dir"
 
-      #@ Include the lookup directory
-      printf "%s\n" "$dir"
-    else
-      #@ Fallback to find
-      find "$dir"
-    fi
-  done | sort
+			#@ Include the lookup directory
+			printf "%s\n" "$dir"
+		else
+			#@ Fallback to find
+			find "$dir"
+		fi
+	done | sort
 }
 
 os_type() {
-  case "$(uname -a | tr '[:upper:]' '[:lower:]')" in
-  *linux*) os_type="linux" ;;
-  *darwin*) os_type="mac" ;;
-  *) os_type="windows" ;;
-  esac
+	case "$(uname -a | tr '[:upper:]' '[:lower:]')" in
+	*linux*) os_type="linux" ;;
+	*darwin*) os_type="mac" ;;
+	*) os_type="windows" ;;
+	esac
 
-  #TODO This is utterly inadequete, just temporary
-  printf "%s" "$os_type"
+	#TODO This is utterly inadequete, just temporary
+	printf "%s" "$os_type"
 }
 add_to_path_ORIG() {
-  [ "$debug" ] && {
-    counter=1
-    recursive_paths "$bins" | while IFS= read -r bin_path; do
-      printf "  %4d %s\n" "$counter" "$bin_path"
-      #@ Increment the counter
-      counter=$((counter + 1))
-    done
-    return 0
-  }
+	[ "$debug" ] && {
+		counter=1
+		recursive_paths "$bins" | while IFS= read -r bin_path; do
+			printf "  %4d %s\n" "$counter" "$bin_path"
+			#@ Increment the counter
+			counter=$((counter + 1))
+		done
+		return 0
+	}
 
-  #@ Update PATH directories recursively
-  recursive_paths "$bins" | while IFS= read -r bin_path; do
-    [ -d "$bin_path" ] &&
-      case ":${PATH}:" in
-      *:"$bin_path":*) ;;
-      *)
-        case "$action" in
-        prepend)
-          PATH="${bin_path}${PATH:+:$PATH}"
-          _action="Appended"
-          ;;
-        append)
-          PATH="${PATH:+$PATH:}${bin_path}"
-          _action="Perpended"
-          ;;
-        esac
+	#@ Update PATH directories recursively
+	recursive_paths "$bins" | while IFS= read -r bin_path; do
+		[ -d "$bin_path" ] &&
+			case ":${PATH}:" in
+			*:"$bin_path":*) ;;
+			*)
+				case "$action" in
+				prepend)
+					PATH="${bin_path}${PATH:+:$PATH}"
+					_action="Appended"
+					;;
+				append)
+					PATH="${PATH:+$PATH:}${bin_path}"
+					_action="Perpended"
+					;;
+				esac
 
-        [ "$verbosity" -gt 1 ] &&
-          printf "    %s to PATH: %s\n" "$_action" "${bin_path}"
-        ;;
-      esac
+				[ "$verbosity" -gt 1 ] &&
+					printf "    %s to PATH: %s\n" "$_action" "${bin_path}"
+				;;
+			esac
 
-    #@ Make scripts executable
-    [ -f "$bin_path" ] &&
-      case "$(os_type)" in windows) ;;
-      *)
-        chmod_status=0
-        chmod +x "$bin_path" >/dev/null 2>&1
-        chmod_status=$?
+		#@ Make scripts executable
+		[ -f "$bin_path" ] &&
+			case "$(os_type)" in windows) ;;
+			*)
+				chmod_status=0
+				chmod +x "$bin_path" >/dev/null 2>&1
+				chmod_status=$?
 
-        [ "$verbosity" -gt 1 ] && {
-          if [ "$chmod_status" -eq 0 ]; then
-            printf "    Script initialized: %s\n" "${bin_path}"
-          else
-            printf "    Failed to make %s executable: %s\n" "${bin_path}" "$chmod_status"
-          fi
-        }
-        ;;
-      esac
+				[ "$verbosity" -gt 1 ] && {
+					if [ "$chmod_status" -eq 0 ]; then
+						printf "    Script initialized: %s\n" "${bin_path}"
+					else
+						printf "    Failed to make %s executable: %s\n" "${bin_path}" "$chmod_status"
+					fi
+				}
+				;;
+			esac
 
-  done
+	done
 
-  #@ Return the new PATH
-  printf "%s\n" "$PATH"
+	#@ Return the new PATH
+	printf "%s\n" "$PATH"
 }
 
 show_bins() {
-  printf "%s\n" "${1:-"$PATH"}" | tr ':' '\n' |
-    eval "$(if [ "$HAS_BAT" ]; then
-      printf "bat --color=always --style=grid --plain --number"
-    else
-      printf "nl -s '  ' | less"
-    fi)"
+	printf "%s\n" "${1:-"$PATH"}" | tr ':' '\n' |
+		eval "$(if [ "$HAS_BAT" ]; then
+			printf "bat --color=always --style=grid --plain --number"
+		else
+			printf "nl -s '  ' | less"
+		fi)"
 }
 
 is_absolute_path() {
-  case "$1" in
-  /*) return 0 ;; # Path starts with /, so it's absolute
-  *) return 1 ;;  # Otherwise, it's not absolute
-  esac
+	case "$1" in
+	/*) return 0 ;; # Path starts with /, so it's absolute
+	*) return 1 ;;  # Otherwise, it's not absolute
+	esac
 }
 
 clean_path() {
-  #DOC 1. printf '%s\n' "${PATH-}"
-  #DOC   - Prints PATH safely
-  #DOC   - Handles empty PATH with - modifier
-  #DOC
-  #DOC 2. tr ':' '\n'
-  #DOC   - Converts PATH separators to newlines
-  #DOC   - Creates one path per line
-  #DOC
-  #DOC 3. grep '^/'
-  #DOC   - Filters for absolute paths only
-  #DOC   - ^/ matches paths starting with /
-  #DOC   - Automatically removes invalid paths
-  #DOC
-  #DOC 4. paste -s -d ':'
-  #DOC   - -s serializes input into single line
-  #DOC   - -d ':' joins with : delimiter
-  #DOC   - Reconstructs PATH format
+	#DOC 1. printf '%s\n' "${PATH-}"
+	#DOC   - Prints PATH safely
+	#DOC   - Handles empty PATH with - modifier
+	#DOC
+	#DOC 2. tr ':' '\n'
+	#DOC   - Converts PATH separators to newlines
+	#DOC   - Creates one path per line
+	#DOC
+	#DOC 3. grep '^/'
+	#DOC   - Filters for absolute paths only
+	#DOC   - ^/ matches paths starting with /
+	#DOC   - Automatically removes invalid paths
+	#DOC
+	#DOC 4. paste -s -d ':'
+	#DOC   - -s serializes input into single line
+	#DOC   - -d ':' joins with : delimiter
+	#DOC   - Reconstructs PATH format
 
-  printf '%s\n' "${PATH-}" | tr ':' '\n' | grep '^/' | paste -s -d ':'
+	printf '%s\n' "${PATH-}" | tr ':' '\n' | grep '^/' | paste -s -d ':'
 }
 
 make_exec() {
-  _file=$1
-  chmod_status=0
-  chmod +x "$_file" >/dev/null 2>&1
-  chmod_status=$?
-  [ "$verbosity" -gt 1 ] && {
-    if [ "$chmod_status" -eq 0 ]; then
-      printf "    Script initialized: %s\n" "${_file}"
-    else
-      printf "    Failed to make %s executable: %s\n" "${_file}" "$chmod_status"
-    fi
-  }
+	_file=$1
+	chmod_status=0
+	chmod +x "$_file" >/dev/null 2>&1
+	chmod_status=$?
+	[ "$verbosity" -gt 1 ] && {
+		if [ "$chmod_status" -eq 0 ]; then
+			printf "    Script initialized: %s\n" "${_file}"
+		else
+			printf "    Failed to make %s executable: %s\n" "${_file}" "$chmod_status"
+		fi
+	}
 }
 
 add_to_path() {
-  tmp_path=$(mktemp) || return 1
-  recursive_paths "$bins" >"$tmp_path"
+	tmp_path=$(mktemp) || return 1
+	recursive_paths "$bins" >"$tmp_path"
 
-  if [ "$debug" ]; then
-    counter=1
-    while IFS= read -r bin_path; do
-      printf "  %4d %s\n" "$counter" "$bin_path"
-      counter=$((counter + 1))
-    done <"$tmp_path"
-    rm "$tmp_path"
-    return 0
-  fi
+	if [ "$debug" ]; then
+		counter=1
+		while IFS= read -r bin_path; do
+			printf "  %4d %s\n" "$counter" "$bin_path"
+			counter=$((counter + 1))
+		done <"$tmp_path"
+		rm "$tmp_path"
+		return 0
+	fi
 
-  while IFS= read -r bin_path; do
-    [ -d "$bin_path" ] &&
-      case ":${PATH}:" in
-      *:"$bin_path":*) ;;
-      *)
-        case "$action" in
-        prepend)
-          PATH="${bin_path}${PATH:+:$PATH}"
-          _action="Appended"
-          ;;
-        append)
-          PATH="${PATH:+$PATH:}${bin_path}"
-          _action="Perpended"
-          ;;
-        esac
-        [ -d "$bin_path" ] && umask 022 && chmod 755 "$bin_path" #TODO: This is not working. Files created after running the script are not automatically executable.
-        [ "$verbosity" -gt 1 ] &&
-          printf "    %s to PATH: %s\n" "$_action" "${bin_path}"
-        ;;
-      esac
+	while IFS= read -r bin_path; do
+		[ -d "$bin_path" ] &&
+			case ":${PATH}:" in
+			*:"$bin_path":*) ;;
+			*)
+				case "$action" in
+				prepend)
+					PATH="${bin_path}${PATH:+:$PATH}"
+					_action="Appended"
+					;;
+				append)
+					PATH="${PATH:+$PATH:}${bin_path}"
+					_action="Perpended"
+					;;
+				esac
+				[ -d "$bin_path" ] && umask 022 && chmod 755 "$bin_path" #TODO: This is not working. Files created after running the script are not automatically executable.
+				[ "$verbosity" -gt 1 ] &&
+					printf "    %s to PATH: %s\n" "$_action" "${bin_path}"
+				;;
+			esac
 
-    [ -f "$bin_path" ] &&
-      case "$(os_type)" in windows) ;;
-      *) make_exec "$bin_path" ;;
-      esac
-  done <"$tmp_path"
+		[ -f "$bin_path" ] &&
+			case "$(os_type)" in windows) ;;
+			*) make_exec "$bin_path" ;;
+			esac
+	done <"$tmp_path"
 
-  rm "$tmp_path"
-  [ "$verbosity" -gt 1 ] && show_bins
-  export PATH
+	rm "$tmp_path"
+	[ "$verbosity" -gt 1 ] && show_bins
+	export PATH
 }
 
 #@ Execute the main function with the provided argument
diff --git a/Bin/shellscript/utility/location b/Bin/shellscript/utility/location
--- a/Bin/shellscript/utility/location
+++ b/Bin/shellscript/utility/location
@@ -1,291 +1,291 @@
 #!/bin/sh
 
 main() {
-  parse_arguments "$@"
-  parse_location
-  get_info
+	parse_arguments "$@"
+	parse_location
+	get_info
 }
 
 tests() {
-  run_test() {
-    while [ "$#" -gt 0 ]; do
-      case "$1" in
-      --num) test_num="$2" ;;
-      --loc) test_loc="$2" ;;
-      --opt) test_opt="$2" ;;
-      esac
-      shift
-    done
+	run_test() {
+		while [ "$#" -gt 0 ]; do
+			case "$1" in
+			--num) test_num="$2" ;;
+			--loc) test_loc="$2" ;;
+			--opt) test_opt="$2" ;;
+			esac
+			shift
+		done
 
-    printf "\nTest %s: %s\n" "$test_num" "$test_loc"
-    printf "%s\n" "$(eval "main" "$test_loc" "$test_opt" | sed 's/^/\t/')"
-  }
+		printf "\nTest %s: %s\n" "$test_num" "$test_loc"
+		printf "%s\n" "$(eval "main" "$test_loc" "$test_opt" | sed 's/^/\t/')"
+	}
 
-  run_test \
-    --num 1 \
-    --loc "18.0238691, -77.5040135" \
-    --opt "--get coordinates --name"
+	run_test \
+		--num 1 \
+		--loc "18.0238691, -77.5040135" \
+		--opt "--get coordinates --name"
 
-  run_test \
-    --num 2 \
-    --loc "Mandeville, Jamaica" \
-    --opt "--get latitude --longitude --name class"
+	run_test \
+		--num 2 \
+		--loc "Mandeville, Jamaica" \
+		--opt "--get latitude --longitude --name class"
 }
 
 parse_arguments() {
-  #@ Set defaults
-  verbosity=info
-  output=coordinates
-  location=""
+	#@ Set defaults
+	verbosity=info
+	output=coordinates
+	location=""
 
-  #@ Parse arguments
-  while [ $# -gt 0 ]; do
-    case "$1" in
-    -h | --help) show_usage ;;
-    -v | --version) show_version ;;
-    --verbose=*) verbosity="${1#*=}" ;;
-    --verbose)
-      if [ -n "$2" ]; then
-        verbosity="$2"
-        shift
-      else
-        verbosity=debug
-      fi
-      ;;
-    --error) verbosity=error ;;
-    --warn) verbosity=warn ;;
-    --info) verbosity=info ;;
-    --debug) verbosity=debug ;;
-    --trace) verbosity=trace ;;
-    --quiet) verbosity=quiet ;;
-    --all | all | "--get all")
-      output="all"
-      ;;
-    --id | id | "--get id")
-      case "$output" in *id*) ;;
-      '') output="id" ;;
-      *) output="${output}, id" ;;
-      esac
-      ;;
-    --latitude | latitude | "--get latitude")
-      case "$output" in *latitude*) ;;
-      '') output="latitude" ;;
-      *) output="${output}, latitude" ;;
-      esac
-      ;;
-    --longitude | longitude | "--get longitude")
-      case "$output" in *longitude*) ;;
-      '') output="longitude" ;;
-      *) output="${output}, longitude" ;;
-      esac
-      ;;
-    --coordinates | coordinates | "--get coordinates")
-      case "$output" in *coordinates*) ;;
-      '') output="coordinates" ;;
-      *) output="${output}, coordinates" ;;
-      esac
-      ;;
-    --class | class | "--get class")
-      case "$output" in *class*) ;;
-      '') output="class" ;;
-      *) output="${output}, class" ;;
-      esac
-      ;;
-    --type | type | "--get type")
-      case "$output" in *type*) ;;
-      '') output="type" ;;
-      *) output="${output}, type" ;;
-      esac
-      ;;
-    --rank | rank | "--get rank")
-      case "$output" in *rank*) ;;
-      '') output="rank" ;;
-      *) output="${output}, rank" ;;
-      esac
-      ;;
-    --importance | importance | "--get importance")
-      case "$output" in *importance*) ;;
-      '') output="importance" ;;
-      *) output="${output}, importance" ;;
-      esac
-      ;;
-    --name | name | "--get name")
-      case "$output" in *name*) ;;
-      '') output="name" ;;
-      *) output="${output}, name" ;;
-      esac
-      ;;
-    --road | road | "--get road")
-      case "$output" in *road*) ;;
-      '') output="road" ;;
-      *) output="${output}, road" ;;
-      esac
-      ;;
-    --town | town | "--get town")
-      case "$output" in *town*) ;;
-      '') output="town" ;;
-      *) output="${output}, town" ;;
-      esac
-      ;;
-    --county | county | "--get county")
-      case "$output" in *county*) ;;
-      '') output="county" ;;
-      *) output="${output}, county" ;;
-      esac
-      ;;
-    --postalcode | postalcode | "--get postalcode")
-      case "$output" in *postalcode*) ;;
-      '') output="postalcode" ;;
-      *) output="${output}, postalcode" ;;
-      esac
-      ;;
-    --state | state | "--get state")
-      case "$output" in *state*) ;;
-      '') output="state" ;;
-      *) output="${output}, state" ;;
-      esac
-      ;;
-    --country | country | "--get country")
-      case "$output" in *country*) ;;
-      '') output="country" ;;
-      *) output="${output}, country" ;;
-      esac
-      ;;
-    --countrycode | countrycode | "--get countrycode")
-      case "$output" in *countrycode*) ;;
-      '') output="countrycode" ;;
-      *) output="${output}, countrycode" ;;
-      esac
-      ;;
-    --boundary | boundary | "--get boundary")
-      case "$output" in *boundary*) ;;
-      '') output="boundary" ;;
-      *) output="${output}, boundary" ;;
-      esac
-      ;;
-    --*) ;;
-    *)
-      if [ "$location" ]; then
-        location="$location $1"
-      else
-        location="$1"
-      fi
-      ;;
-    esac
-    shift
-  done
+	#@ Parse arguments
+	while [ $# -gt 0 ]; do
+		case "$1" in
+		-h | --help) show_usage ;;
+		-v | --version) show_version ;;
+		--verbose=*) verbosity="${1#*=}" ;;
+		--verbose)
+			if [ -n "$2" ]; then
+				verbosity="$2"
+				shift
+			else
+				verbosity=debug
+			fi
+			;;
+		--error) verbosity=error ;;
+		--warn) verbosity=warn ;;
+		--info) verbosity=info ;;
+		--debug) verbosity=debug ;;
+		--trace) verbosity=trace ;;
+		--quiet) verbosity=quiet ;;
+		--all | all | "--get all")
+			output="all"
+			;;
+		--id | id | "--get id")
+			case "$output" in *id*) ;;
+			'') output="id" ;;
+			*) output="${output}, id" ;;
+			esac
+			;;
+		--latitude | latitude | "--get latitude")
+			case "$output" in *latitude*) ;;
+			'') output="latitude" ;;
+			*) output="${output}, latitude" ;;
+			esac
+			;;
+		--longitude | longitude | "--get longitude")
+			case "$output" in *longitude*) ;;
+			'') output="longitude" ;;
+			*) output="${output}, longitude" ;;
+			esac
+			;;
+		--coordinates | coordinates | "--get coordinates")
+			case "$output" in *coordinates*) ;;
+			'') output="coordinates" ;;
+			*) output="${output}, coordinates" ;;
+			esac
+			;;
+		--class | class | "--get class")
+			case "$output" in *class*) ;;
+			'') output="class" ;;
+			*) output="${output}, class" ;;
+			esac
+			;;
+		--type | type | "--get type")
+			case "$output" in *type*) ;;
+			'') output="type" ;;
+			*) output="${output}, type" ;;
+			esac
+			;;
+		--rank | rank | "--get rank")
+			case "$output" in *rank*) ;;
+			'') output="rank" ;;
+			*) output="${output}, rank" ;;
+			esac
+			;;
+		--importance | importance | "--get importance")
+			case "$output" in *importance*) ;;
+			'') output="importance" ;;
+			*) output="${output}, importance" ;;
+			esac
+			;;
+		--name | name | "--get name")
+			case "$output" in *name*) ;;
+			'') output="name" ;;
+			*) output="${output}, name" ;;
+			esac
+			;;
+		--road | road | "--get road")
+			case "$output" in *road*) ;;
+			'') output="road" ;;
+			*) output="${output}, road" ;;
+			esac
+			;;
+		--town | town | "--get town")
+			case "$output" in *town*) ;;
+			'') output="town" ;;
+			*) output="${output}, town" ;;
+			esac
+			;;
+		--county | county | "--get county")
+			case "$output" in *county*) ;;
+			'') output="county" ;;
+			*) output="${output}, county" ;;
+			esac
+			;;
+		--postalcode | postalcode | "--get postalcode")
+			case "$output" in *postalcode*) ;;
+			'') output="postalcode" ;;
+			*) output="${output}, postalcode" ;;
+			esac
+			;;
+		--state | state | "--get state")
+			case "$output" in *state*) ;;
+			'') output="state" ;;
+			*) output="${output}, state" ;;
+			esac
+			;;
+		--country | country | "--get country")
+			case "$output" in *country*) ;;
+			'') output="country" ;;
+			*) output="${output}, country" ;;
+			esac
+			;;
+		--countrycode | countrycode | "--get countrycode")
+			case "$output" in *countrycode*) ;;
+			'') output="countrycode" ;;
+			*) output="${output}, countrycode" ;;
+			esac
+			;;
+		--boundary | boundary | "--get boundary")
+			case "$output" in *boundary*) ;;
+			'') output="boundary" ;;
+			*) output="${output}, boundary" ;;
+			esac
+			;;
+		--*) ;;
+		*)
+			if [ "$location" ]; then
+				location="$location $1"
+			else
+				location="$1"
+			fi
+			;;
+		esac
+		shift
+	done
 
-  #@ Set verbosity level
-  case "$QUIET" in
-  true | 1 | on) verbosity=0 ;;
-  esac
+	#@ Set verbosity level
+	case "$QUIET" in
+	true | 1 | on) verbosity=0 ;;
+	esac
 
-  case "$(
-    printf "%s" "${verbosity:-"${VERBOSITY:-$VERBOSE}"}" |
-      tr '[:upper:]' '[:lower:]'
-  )" in
-  quiet | false | 0) verbosity=0 ;;
-  error | fatal | 1) verbosity=1 ;;
-  warn | warning | 2) verbosity=2 ;;
-  info | normal | 3) verbosity=3 ;;
-  debug | verbose | 4) verbosity=4 ;;
-  trace | all | true | 5)
-    verbosity=5
-    set -o xtrace # this can probably be temporary if we customize the trace messages
-    ;;
-  *)
-    verbosity=3 #? Set default to INFO
-    ;;
-  esac
+	case "$(
+		printf "%s" "${verbosity:-"${VERBOSITY:-$VERBOSE}"}" |
+			tr '[:upper:]' '[:lower:]'
+	)" in
+	quiet | false | 0) verbosity=0 ;;
+	error | fatal | 1) verbosity=1 ;;
+	warn | warning | 2) verbosity=2 ;;
+	info | normal | 3) verbosity=3 ;;
+	debug | verbose | 4) verbosity=4 ;;
+	trace | all | true | 5)
+		verbosity=5
+		set -o xtrace # this can probably be temporary if we customize the trace messages
+		;;
+	*)
+		verbosity=3 #? Set default to INFO
+		;;
+	esac
 
-  [ "$verbosity" -ge 4 ] && {
-    printf "DEBUG: Verbosity: %s\n" "$verbosity"
-    printf "DEBUG: Location: %s\n" "$location"
-    printf "DEBUG: Output: %s\n" "$output"
-  }
+	[ "$verbosity" -ge 4 ] && {
+		printf "DEBUG: Verbosity: %s\n" "$verbosity"
+		printf "DEBUG: Location: %s\n" "$location"
+		printf "DEBUG: Output: %s\n" "$output"
+	}
 }
 
 parse_location() {
-  #@ Prepare the location string and API URL
-  location=$(printf "%s" "$location" | tr -s ' ' '+')
-  if [ -z "$location" ]; then
-    printf "Error: Location not provided." >&2
-    return 1
-  else
-    # url="https://nominatim.openstreetmap.org/search?q=${location}&format=json"
-    url="https://nominatim.openstreetmap.org/search?q=${location}&format=jsonv2&limit=1&addressdetails=1"
+	#@ Prepare the location string and API URL
+	location=$(printf "%s" "$location" | tr -s ' ' '+')
+	if [ -z "$location" ]; then
+		printf "Error: Location not provided." >&2
+		return 1
+	else
+		# url="https://nominatim.openstreetmap.org/search?q=${location}&format=json"
+		url="https://nominatim.openstreetmap.org/search?q=${location}&format=jsonv2&limit=1&addressdetails=1"
 
-    [ "$verbosity" -ge 4 ] && {
-      printf "Location: %s\n" "$location"
-      printf "Api URL: %s\n" "$url"
-    }
-  fi
+		[ "$verbosity" -ge 4 ] && {
+			printf "Location: %s\n" "$location"
+			printf "Api URL: %s\n" "$url"
+		}
+	fi
 
-  #@ Fetch the response
-  res=$(curl --silent "$url")
-  [ "$verbosity" -ge 4 ] && printf "Response: %s\n" "$res"
+	#@ Fetch the response
+	res=$(curl --silent "$url")
+	[ "$verbosity" -ge 4 ] && printf "Response: %s\n" "$res"
 
-  #@ Validate response
-  if [ -z "$res" ] || [ "$res" = "[]" ]; then
-    printf "Error: Failed to resolve location '%s'." "$location" >&2
-    return 1
-  fi
+	#@ Validate response
+	if [ -z "$res" ] || [ "$res" = "[]" ]; then
+		printf "Error: Failed to resolve location '%s'." "$location" >&2
+		return 1
+	fi
 
-  #@ Parse the response into key-value pair variables
-  data="$res"
+	#@ Parse the response into key-value pair variables
+	data="$res"
 
-  #@ Reset variables
-  unset place_id latitude longitude class type rank importance name name_detailed boundingbox
+	#@ Reset variables
+	unset place_id latitude longitude class type rank importance name name_detailed boundingbox
 
-  #@ Parse the response
-  place_id=$(parse_json "$data" "place_id")
-  [ "$verbosity" -ge 4 ] && printf "DEBUG: ID = %s\n" "$place_id"
+	#@ Parse the response
+	place_id=$(parse_json "$data" "place_id")
+	[ "$verbosity" -ge 4 ] && printf "DEBUG: ID = %s\n" "$place_id"
 
-  latitude=$(parse_json "$data" "lat")
-  [ "$verbosity" -ge 4 ] && printf "DEBUG: Latitude = %s\n" "$latitude"
+	latitude=$(parse_json "$data" "lat")
+	[ "$verbosity" -ge 4 ] && printf "DEBUG: Latitude = %s\n" "$latitude"
 
-  longitude=$(parse_json "$data" "lon")
-  [ "$verbosity" -ge 4 ] && printf "DEBUG: Longitude = %s\n" "$longitude"
+	longitude=$(parse_json "$data" "lon")
+	[ "$verbosity" -ge 4 ] && printf "DEBUG: Longitude = %s\n" "$longitude"
 
-  class=$(parse_json "$data" "class")
-  [ "$verbosity" -ge 4 ] && printf "DEBUG: Class = %s\n" "$class"
+	class=$(parse_json "$data" "class")
+	[ "$verbosity" -ge 4 ] && printf "DEBUG: Class = %s\n" "$class"
 
-  type=$(parse_json "$data" "type")
-  [ "$verbosity" -ge 4 ] && printf "DEBUG: Type = %s\n" "$type"
+	type=$(parse_json "$data" "type")
+	[ "$verbosity" -ge 4 ] && printf "DEBUG: Type = %s\n" "$type"
 
-  rank=$(parse_json "$data" "place_rank")
-  [ "$verbosity" -ge 4 ] && printf "DEBUG: Rank = %s\n" "$rank"
+	rank=$(parse_json "$data" "place_rank")
+	[ "$verbosity" -ge 4 ] && printf "DEBUG: Rank = %s\n" "$rank"
 
-  importance=$(parse_json "$data" "importance")
-  [ "$verbosity" -ge 4 ] && printf "DEBUG: Importance = %s\n" "$importance"
+	importance=$(parse_json "$data" "importance")
+	[ "$verbosity" -ge 4 ] && printf "DEBUG: Importance = %s\n" "$importance"
 
-  name=$(parse_json "$data" "display_name")
-  [ "$verbosity" -ge 4 ] && printf "DEBUG: Name = %s\n" "$name"
+	name=$(parse_json "$data" "display_name")
+	[ "$verbosity" -ge 4 ] && printf "DEBUG: Name = %s\n" "$name"
 
-  address=$(parse_json "$data" "address")
-  [ "$verbosity" -ge 4 ] && printf "DEBUG: Address = %s\n" "$address"
+	address=$(parse_json "$data" "address")
+	[ "$verbosity" -ge 4 ] && printf "DEBUG: Address = %s\n" "$address"
 
-  boundingbox=$(parse_json "$data" "boundingbox")
-  [ "$verbosity" -ge 4 ] && printf "DEBUG: Bounding box = %s\n" "$boundingbox"
+	boundingbox=$(parse_json "$data" "boundingbox")
+	[ "$verbosity" -ge 4 ] && printf "DEBUG: Bounding box = %s\n" "$boundingbox"
 }
 
 parse_json() {
-  json="$1"
-  key="$2"
+	json="$1"
+	key="$2"
 
-  via_bin() {
-    path="$DOTS_BIN/utility/parse_json"
-    [ -x "$path" ] || return 1
-    "$path" "$json" "$key"
-  }
-  via_jq() {
-    command -v jq >/dev/null 2>&1 || return 1
-    printf "%s" "$json" | jq -r ".[0].$key"
-  }
+	via_bin() {
+		path="$DOTS_BIN/utility/parse_json"
+		[ -x "$path" ] || return 1
+		"$path" "$json" "$key"
+	}
+	via_jq() {
+		command -v jq >/dev/null 2>&1 || return 1
+		printf "%s" "$json" | jq -r ".[0].$key"
+	}
 
-  via_awk() {
-    #@ Fallback to POSIX-compliant parsing with awk. Howeever it doersn't handle lists well and only returns the first item.
-    printf "%s" "$json" | awk -v key="$key" '
+	via_awk() {
+		#@ Fallback to POSIX-compliant parsing with awk. Howeever it doersn't handle lists well and only returns the first item.
+		printf "%s" "$json" | awk -v key="$key" '
       BEGIN { RS="[{},]" }
       {
         gsub(/^[ \n\t]+|[ \n\t]+$/, "")  # Trim whitespace
@@ -315,104 +315,104 @@ parse_json() {
         }
       }
     '
-  }
+	}
 
-  via_bin || via_jq || via_awk
+	via_bin || via_jq || via_awk
 }
 
 to_lower() {
-  #DOC Converts a string to lowercase
-  #DOC Args:
-  #DOC   $1 - String to convert
-  #DOC Returns:
-  #DOC   Lowercase string on success
-  #DOC Example:
-  #DOC   lower_text=$(to_lower "HELLO")
+	#DOC Converts a string to lowercase
+	#DOC Args:
+	#DOC   $1 - String to convert
+	#DOC Returns:
+	#DOC   Lowercase string on success
+	#DOC Example:
+	#DOC   lower_text=$(to_lower "HELLO")
 
-  [ "$*" ] || return
+	[ "$*" ] || return
 
-  printf "%s" "$*" | tr '[:upper:]' '[:lower:]' 2>/dev/null || {
-    printf "ERROR: Failed to convert string to lowercase\n" >&2
-    return 1
-  }
+	printf "%s" "$*" | tr '[:upper:]' '[:lower:]' 2>/dev/null || {
+		printf "ERROR: Failed to convert string to lowercase\n" >&2
+		return 1
+	}
 }
 
 get_info() {
-  get_all() {
-    printf "%s" "$data"
-    printf "%s,%s" "$latitude" "$longitude"
-  }
+	get_all() {
+		printf "%s" "$data"
+		printf "%s,%s" "$latitude" "$longitude"
+	}
 
-  get_coordinates() {
+	get_coordinates() {
 
-    printf "%s" "$data"
-  }
+		printf "%s" "$data"
+	}
 
-  echo "Location: $location"
-  echo "Output: $output"
+	echo "Location: $location"
+	echo "Output: $output"
 
-  case "$output" in
-  *all*)
-    get_all
-    ;;
-  *coordinates*)
-    printf "%s,%s" "$latitude" "$longitude"
-    ;;
-  esac
-  # case "$output" in
-  # coordinates)
-  #   printf "%s,%s" "$latitude" "$longitude"
-  #   ;;
-  # id)
-  #   printf "%s" "$place_id"
-  #   ;;
-  # latitude)
-  #   printf "%s" "$latitude"
-  #   ;;
-  # longitude)
-  #   printf "%s" "$longitude"
-  #   ;;
-  # class)
-  #   printf "%s" "$class"
-  #   ;;
-  # type)
-  #   printf "%s" "$type"
-  #   ;;
-  # rank)
-  #   printf "%s" "$rank"
-  #   ;;
-  # importance)
-  #   printf "%s" "$importance"
-  #   ;;
-  # name)
-  #   printf "%s" "$name"
-  #   ;;
-  # name_detailed)
-  #   printf "%s" "$name_detailed"
-  #   ;;
-  # boundingbox)
-  #   printf "%s" "$boundingbox"
-  #   ;;
-  # *)
-  #   printf "ERROR: Invalid output format\n" >&2
-  #   return 1
-  #   ;;
-  # esac
-  case "$output" in
-  *all*) get_all ;;
-  *) ;;
-  esac
-  # [ "$place_id" ] && get_id
-  # [ "$latitude" ] && get_latitude
-  # [ "$longitude" ] && get_longitude
-  # [ "$coordinates" ] && get_coordinates
-  # [ "$class" ] && get_class
-  # [ "$type" ] && get_type
-  # [ "$rank" ] && get_rank
-  # [ "$importance" ] && get_importance
-  # [ "$name" ] && get_name
-  # [ "$name_detailed" ] && get_name_detailed
-  # [ "$boundingbox" ] && get_boundingbox
+	case "$output" in
+	*all*)
+		get_all
+		;;
+	*coordinates*)
+		printf "%s,%s" "$latitude" "$longitude"
+		;;
+	esac
+	# case "$output" in
+	# coordinates)
+	#   printf "%s,%s" "$latitude" "$longitude"
+	#   ;;
+	# id)
+	#   printf "%s" "$place_id"
+	#   ;;
+	# latitude)
+	#   printf "%s" "$latitude"
+	#   ;;
+	# longitude)
+	#   printf "%s" "$longitude"
+	#   ;;
+	# class)
+	#   printf "%s" "$class"
+	#   ;;
+	# type)
+	#   printf "%s" "$type"
+	#   ;;
+	# rank)
+	#   printf "%s" "$rank"
+	#   ;;
+	# importance)
+	#   printf "%s" "$importance"
+	#   ;;
+	# name)
+	#   printf "%s" "$name"
+	#   ;;
+	# name_detailed)
+	#   printf "%s" "$name_detailed"
+	#   ;;
+	# boundingbox)
+	#   printf "%s" "$boundingbox"
+	#   ;;
+	# *)
+	#   printf "ERROR: Invalid output format\n" >&2
+	#   return 1
+	#   ;;
+	# esac
+	case "$output" in
+	*all*) get_all ;;
+	*) ;;
+	esac
+	# [ "$place_id" ] && get_id
+	# [ "$latitude" ] && get_latitude
+	# [ "$longitude" ] && get_longitude
+	# [ "$coordinates" ] && get_coordinates
+	# [ "$class" ] && get_class
+	# [ "$type" ] && get_type
+	# [ "$rank" ] && get_rank
+	# [ "$importance" ] && get_importance
+	# [ "$name" ] && get_name
+	# [ "$name_detailed" ] && get_name_detailed
+	# [ "$boundingbox" ] && get_boundingbox
 }
 
 # main "$@"
