set treefmt as the default formatter in vscode

diff --git a/Bin/shellscript/packages/alias/VScode b/Bin/shellscript/packages/alias/VScode
--- a/Bin/shellscript/packages/alias/VScode
+++ b/Bin/shellscript/packages/alias/VScode
@@ -18,7 +18,7 @@ set -eu
 : "${codeNIX:=--extension some-nix-extension}"
 
 usage() {
-  cat <<EOF >&2
+	cat <<EOF >&2
 Usage: $0 [option] [arguments...]
 
 Options:
@@ -29,56 +29,56 @@ Options:
 
 If an unrecognized option is provided, all arguments are passed to the VS Code command.
 EOF
-  exit 1
+	exit 1
 }
 
 parse_arguments() {
-  if [ "$#" -eq 0 ]; then
-    process_core "$(pwd)"
-  fi
+	if [ "$#" -eq 0 ]; then
+		process_core "$(pwd)"
+	fi
 
-  case "$1" in
-  -D | --dots)
-    #@ Expand the DOTS configuration and pass remaining args.
-    shift
-    process_core "$codeDOTS" "$@"
-    ;;
-  -R | --rust)
-    shift
-    process_core "$codeRUST" "$@"
-    ;;
-  -N | --nix)
-    shift
-    process_core "$codeNIX" "$@"
-    ;;
-  -h | --help)
-    usage
-    ;;
-  *)
-    process_core "$@"
-    ;;
-  esac
+	case "$1" in
+	-D | --dots)
+		#@ Expand the DOTS configuration and pass remaining args.
+		shift
+		process_core "$codeDOTS" "$@"
+		;;
+	-R | --rust)
+		shift
+		process_core "$codeRUST" "$@"
+		;;
+	-N | --nix)
+		shift
+		process_core "$codeNIX" "$@"
+		;;
+	-h | --help)
+		usage
+		;;
+	*)
+		process_core "$@"
+		;;
+	esac
 }
 
 process_core() {
-  #@ List Visual Studio Code variants in order of preference.
-  for cmd in code-insiders code code-oss codium; do
-    if command -v "$cmd" >/dev/null 2>&1; then
-      "$cmd" "$@" &
-      printf "Launched %s with arguments: %s\n" "$cmd" "$*"
-      return 0
-    fi
-  done
+	#@ List Visual Studio Code variants in order of preference.
+	for cmd in code-insiders code code-oss codium; do
+		if command -v "$cmd" >/dev/null 2>&1; then
+			"$cmd" "$@" &
+			printf "Launched %s with arguments: %s\n" "$cmd" "$*"
+			return 0
+		fi
+	done
 
-  #@ Fallback: Try Flatpak if available.
-  if command -v flatpak >/dev/null 2>&1 && flatpak info visualstudio.code >/dev/null 2>&1; then
-    flatpak run visualstudio.code "$@" &
-    printf "Launched Flatpak version of Visual Studio Code with arguments: %s\n" "$*"
-    return 0
-  fi
+	#@ Fallback: Try Flatpak if available.
+	if command -v flatpak >/dev/null 2>&1 && flatpak info visualstudio.code >/dev/null 2>&1; then
+		flatpak run visualstudio.code "$@" &
+		printf "Launched Flatpak version of Visual Studio Code with arguments: %s\n" "$*"
+		return 0
+	fi
 
-  printf "🟥 Visual Studio Code not found.\n" >&2
-  return 1
+	printf "🟥 Visual Studio Code not found.\n" >&2
+	return 1
 }
 
 parse_arguments "$@"
diff --git a/Bin/shellscript/packages/defaults/SHell b/Bin/shellscript/packages/defaults/SHell
--- a/Bin/shellscript/packages/defaults/SHell
+++ b/Bin/shellscript/packages/defaults/SHell
@@ -24,42 +24,42 @@
 # esac
 
 __shell__() {
-  pid="$$"
+	pid="$$"
 
-  set -- sh bash zsh ksh ash dash csh tcsh pdksh mksh fish nu psh rc scsh bournesh wish Wish login
-  unset echo env sed ps lsof awk getconf
+	set -- sh bash zsh ksh ash dash csh tcsh pdksh mksh fish nu psh rc scsh bournesh wish Wish login
+	unset echo env sed ps lsof awk getconf
 
-  # getconf _POSIX_VERSION  # reliable test for availability of POSIX system?
-  PATH="$(PATH=/usr/bin:/bin:/usr/sbin:/sbin getconf PATH)"
-  # shellcheck disable=SC2181
-  [ $? -ne 0 ] && {
-    echo "'getconf PATH' failed"
-    exit 1
-  }
-  export PATH
+	# getconf _POSIX_VERSION  # reliable test for availability of POSIX system?
+	PATH="$(PATH=/usr/bin:/bin:/usr/sbin:/sbin getconf PATH)"
+	# shellcheck disable=SC2181
+	[ $? -ne 0 ] && {
+		echo "'getconf PATH' failed"
+		exit 1
+	}
+	export PATH
 
-  type lsof 1>/dev/null 2>&1 || {
-    echo "lsof is required for this operation"
-    exit 1
-  }
+	type lsof 1>/dev/null 2>&1 || {
+		echo "lsof is required for this operation"
+		exit 1
+	}
 
-  awkstr="$(echo "$@" | sed 's/\([^ ]\{1,\}\)/|\/\1/g; s/ /$/g' | sed 's/^|//; s/$/$/')"
+	awkstr="$(echo "$@" | sed 's/\([^ ]\{1,\}\)/|\/\1/g; s/ /$/g' | sed 's/^|//; s/$/$/')"
 
-  ppid="$(env -i PATH="${PATH}" ps -p "$pid" -o ppid=)"
-  [ "${ppid}"X = ""X ] && {
-    echo "no ppid found"
-    exit 1
-  }
+	ppid="$(env -i PATH="${PATH}" ps -p "$pid" -o ppid=)"
+	[ "${ppid}"X = ""X ] && {
+		echo "no ppid found"
+		exit 1
+	}
 
-  # shellcheck disable=SC2086
-  lsofstr="$(lsof -p $ppid)" ||
-    {
-      printf "%s\n" "lsof failed" "try: sudo lsof -p \`ps -p \$\$ -o ppid=\`"
-      exit 1
-    }
+	# shellcheck disable=SC2086
+	lsofstr="$(lsof -p $ppid)" ||
+		{
+			printf "%s\n" "lsof failed" "try: sudo lsof -p \`ps -p \$\$ -o ppid=\`"
+			exit 1
+		}
 
-  printf "%s\n" "${lsofstr}" |
-    LC_ALL=C awk -v var="${awkstr}" '$NF ~ var {print $NF}'
+	printf "%s\n" "${lsofstr}" |
+		LC_ALL=C awk -v var="${awkstr}" '$NF ~ var {print $NF}'
 
 }
 
diff --git a/Bin/shellscript/project/rust/cgoo b/Bin/shellscript/project/rust/cgoo
--- a/Bin/shellscript/project/rust/cgoo
+++ b/Bin/shellscript/project/rust/cgoo
@@ -1,9 +1,9 @@
 #!/bin/sh
 
 main() {
-  scr_name="$(basename "$0")"
-  scr_guide="$(
-    cat <<EOF
+	scr_name="$(basename "$0")"
+	scr_guide="$(
+		cat <<EOF
 Usage:
   $(basename "$0") <MODES> [COMMAND/OPTION] -- <ARGUMENTS>
 
@@ -51,331 +51,331 @@ Package Commands:
   -u <PACKAGE>          Uninstall packages from the system
 
 EOF
-  )"
-  parse_arguments "$@"
-  process
+	)"
+	parse_arguments "$@"
+	process
 }
 display_usage() {
-  if [ "$#" -eq 0 ]; then
-    #@ No arguments
-    exit_code=0
-  else
-    if [ "$1" -eq "$1" ] 2>/dev/null; then
-      #@ The first argument is a number
-      exit_code="$1"
-      shift
-    else
-      #@ The first argument is not a number
-      exit_code=1
-    fi
-  fi
-  #@ Display the error or custom message
-  [ "$*" ] &&
-    if [ "$exit_code" -ne 0 ]; then
-      printf "Error: %s\n\n" "$*"
-    else
-      printf "%s\n\n" "$*"
-    fi
+	if [ "$#" -eq 0 ]; then
+		#@ No arguments
+		exit_code=0
+	else
+		if [ "$1" -eq "$1" ] 2>/dev/null; then
+			#@ The first argument is a number
+			exit_code="$1"
+			shift
+		else
+			#@ The first argument is not a number
+			exit_code=1
+		fi
+	fi
+	#@ Display the error or custom message
+	[ "$*" ] &&
+		if [ "$exit_code" -ne 0 ]; then
+			printf "Error: %s\n\n" "$*"
+		else
+			printf "%s\n\n" "$*"
+		fi
 
-  #@ Display the usage guide
-  printf "%s\n" "$scr_guide"
+	#@ Display the usage guide
+	printf "%s\n" "$scr_guide"
 
-  #@ Terminate
-  exit "${exit_code:-0}"
+	#@ Terminate
+	exit "${exit_code:-0}"
 }
 
 cargo_cmd() {
-  #@ Check if cargo is installed
-  cargo --help >/dev/null 2>&1 || {
-    printf "%s\n%s" \
-      "Please ensure 'cargo' is installed and in your PATH." \
-      "See https://www.rust-lang.org/tools/install for more information."
-    exit 1
-  }
+	#@ Check if cargo is installed
+	cargo --help >/dev/null 2>&1 || {
+		printf "%s\n%s" \
+			"Please ensure 'cargo' is installed and in your PATH." \
+			"See https://www.rust-lang.org/tools/install for more information."
+		exit 1
+	}
 
-  if [ "$2" ]; then
-    printf "cargo watch --quiet --clear --exec \"%s\"" "$1"
-  else
-    printf "cargo %s" "$1"
-  fi
+	if [ "$2" ]; then
+		printf "cargo watch --quiet --clear --exec \"%s\"" "$1"
+	else
+		printf "cargo %s" "$1"
+	fi
 }
 
 get_option() {
-  while [ $# -gt 0 ]; do
-    case $1 in
-    -p* | --p*)
-      [ "$2" ] &&
-        if [ "$2" -eq "$2" ] 2>/dev/null; then
-          position="$2"
-          shift
-        else
-          printf "Error: Position not a number\n"
-          printf "Invalid position: %s\n" "$2"
-          exit 66 #? Developer Error - Script Logic Error
-        fi
+	while [ $# -gt 0 ]; do
+		case $1 in
+		-p* | --p*)
+			[ "$2" ] &&
+				if [ "$2" -eq "$2" ] 2>/dev/null; then
+					position="$2"
+					shift
+				else
+					printf "Error: Position not a number\n"
+					printf "Invalid position: %s\n" "$2"
+					exit 66 #? Developer Error - Script Logic Error
+				fi
 
-      ;;
-    -o* | --o*)
-      [ "$2" ] && {
-        options="$2"
-        shift
-      }
-      ;;
-    *)
-      options="${options:-$1}"
-      position="${position:-$2}"
-      ;;
-    esac
-    shift
-  done
+			;;
+		-o* | --o*)
+			[ "$2" ] && {
+				options="$2"
+				shift
+			}
+			;;
+		*)
+			options="${options:-$1}"
+			position="${position:-$2}"
+			;;
+		esac
+		shift
+	done
 
-  #@ Update position
-  case "$options" in --*) offset=2 ;; -*) offset=1 ;; esac
-  position="$(("${position:-1}" + offset))"
+	#@ Update position
+	case "$options" in --*) offset=2 ;; -*) offset=1 ;; esac
+	position="$(("${position:-1}" + offset))"
 
-  #@ Debug
-  # echo "Options: ${#options} [$options] | Position: $position | Offset: $offset"
+	#@ Debug
+	# echo "Options: ${#options} [$options] | Position: $position | Offset: $offset"
 
-  #@ Return the option
-  if [ "$position" -gt "${#options}" ]; then
-    printf "Error: Position out of range\n"
-    printf "Invalid Position: %s | Max Position: %s | Actual Option: %s\n" \
-      "$position" "${#options}" "$options"
-    exit 66 #? Developer Error - Script Logic Error
-  else
-    printf "%s\n" "$options" | cut -c "$position"
-  fi
+	#@ Return the option
+	if [ "$position" -gt "${#options}" ]; then
+		printf "Error: Position out of range\n"
+		printf "Invalid Position: %s | Max Position: %s | Actual Option: %s\n" \
+			"$position" "${#options}" "$options"
+		exit 66 #? Developer Error - Script Logic Error
+	else
+		printf "%s\n" "$options" | cut -c "$position"
+	fi
 
 }
 
 parse_arguments() {
 
-  internal() {
-    [ $# -eq 0 ] && display_usage 1 "Missing arguments"
+	internal() {
+		[ $# -eq 0 ] && display_usage 1 "Missing arguments"
 
-    case "$1" in -h | --help) display_usage ;; esac
+		case "$1" in -h | --help) display_usage ;; esac
 
-    for argument in "$@"; do
-      #@ Modes
-      case "$argument" in --debug)
-        debug=true
-        verbose=true
-        ;;
-      esac
-      case "$argument" in -D)
-        verbose=true
-        verbosity="--verbose"
-        ;;
-      esac
-      case "$argument" in -*Q*) verbosity="--quiet" ;; esac
-      case "$argument" in -*W*) watch=true ;; esac
-      case "$argument" in -*R*) release=true ;; esac
-      case "$argument" in -*H*) display_usage ;; esac
-    done
-  } && internal "$@"
+		for argument in "$@"; do
+			#@ Modes
+			case "$argument" in --debug)
+				debug=true
+				verbose=true
+				;;
+			esac
+			case "$argument" in -D)
+				verbose=true
+				verbosity="--verbose"
+				;;
+			esac
+			case "$argument" in -*Q*) verbosity="--quiet" ;; esac
+			case "$argument" in -*W*) watch=true ;; esac
+			case "$argument" in -*R*) release=true ;; esac
+			case "$argument" in -*H*) display_usage ;; esac
+		done
+	} && internal "$@"
 
-  external() {
-    while [ $# -gt 0 ]; do
-      case "$1" in
-      -a*)
-        #> Command
-        cmd="add"
+	external() {
+		while [ $# -gt 0 ]; do
+			case "$1" in
+			-a*)
+				#> Command
+				cmd="add"
 
-        #> Option
-        case "$(get_option "$1")" in
-        h)
-          opt="--help"
-          ;;
-        esac
+				#> Option
+				case "$(get_option "$1")" in
+				h)
+					opt="--help"
+					;;
+				esac
 
-        #> Argument
-        unset arg
-        ;;
-      -b*)
-        cmd="build"
+				#> Argument
+				unset arg
+				;;
+			-b*)
+				cmd="build"
 
-        case "$(get_option --opt "$1" --pos 2)" in
-        h)
-          opt="--help"
-          ;;
-        b)
-          if [ "$2" ]; then
-            opt="--bin"
-          else
-            opt="--bins"
-          fi
-          ;;
-        e)
-          if [ "$2" ]; then
-            opt="--example"
-          else
-            opt="--examples"
-          fi
-          ;;
-        l)
-          opt="--lib"
-          ;;
-        n)
-          if [ "$2" ]; then
-            opt="--bench"
-          else
-            opt="--benches"
-          fi
-          ;;
-        t)
-          if [ "$2" ]; then
-            opt="--test"
-          else
-            opt="--test $(basename "$PWD")"
-          fi
-          ;;
-        r | a) opt="--all-targets --all-features --release" ;;
-        w)
-          opt="--workspace"
-          ;;
-        x)
-          opt="--exclude"
-          ;;
-        esac
+				case "$(get_option --opt "$1" --pos 2)" in
+				h)
+					opt="--help"
+					;;
+				b)
+					if [ "$2" ]; then
+						opt="--bin"
+					else
+						opt="--bins"
+					fi
+					;;
+				e)
+					if [ "$2" ]; then
+						opt="--example"
+					else
+						opt="--examples"
+					fi
+					;;
+				l)
+					opt="--lib"
+					;;
+				n)
+					if [ "$2" ]; then
+						opt="--bench"
+					else
+						opt="--benches"
+					fi
+					;;
+				t)
+					if [ "$2" ]; then
+						opt="--test"
+					else
+						opt="--test $(basename "$PWD")"
+					fi
+					;;
+				r | a) opt="--all-targets --all-features --release" ;;
+				w)
+					opt="--workspace"
+					;;
+				x)
+					opt="--exclude"
+					;;
+				esac
 
-        while [ $# -gt 1 ]; do
-          case "$2" in --) break ;; -*) ;; *) opt="$opt $2" ;; esac
-          shift
-        done
-        ;;
-      -c*)
-        #@ Command
-        cmd="clean"
+				while [ $# -gt 1 ]; do
+					case "$2" in --) break ;; -*) ;; *) opt="$opt $2" ;; esac
+					shift
+				done
+				;;
+			-c*)
+				#@ Command
+				cmd="clean"
 
-        #@ Options
-        case "$(get_option "$1")" in
-        h) opt="--help" ;;
-        p)
-          shift
-          opt="$opt $*"
-          ;;
-        esac
+				#@ Options
+				case "$(get_option "$1")" in
+				h) opt="--help" ;;
+				p)
+					shift
+					opt="$opt $*"
+					;;
+				esac
 
-        #@ Arguments
-        unset arg
-        ;;
-      -r*)
-        cmd="run"
+				#@ Arguments
+				unset arg
+				;;
+			-r*)
+				cmd="run"
 
-        case "$(get_option --opt "$1" --pos 2)" in
-        h) opt="--help" ;;
-        b) opt="--bin" ;;
-        e) opt="--example" ;;
-        j) opt="--jobs" ;;
-        p) opt="--package" ;;
-        o) opt="--profile" ;;
-        t) opt="--target" ;;
-        d) opt="--target-dir" ;;
-        r | a) opt="--all-features --release" ;;
-        u | g) opt="--unit-graph" ;;
-        esac
+				case "$(get_option --opt "$1" --pos 2)" in
+				h) opt="--help" ;;
+				b) opt="--bin" ;;
+				e) opt="--example" ;;
+				j) opt="--jobs" ;;
+				p) opt="--package" ;;
+				o) opt="--profile" ;;
+				t) opt="--target" ;;
+				d) opt="--target-dir" ;;
+				r | a) opt="--all-features --release" ;;
+				u | g) opt="--unit-graph" ;;
+				esac
 
-        while [ $# -gt 1 ]; do
-          case "$2" in -*) ;; *) opt="$opt $2" ;; esac
-          shift
-        done
-        ;;
-      -t*)
-        cmd="test"
+				while [ $# -gt 1 ]; do
+					case "$2" in -*) ;; *) opt="$opt $2" ;; esac
+					shift
+				done
+				;;
+			-t*)
+				cmd="test"
 
-        case "$(get_option --opt "$1" --pos 2)" in
-        h)
-          opt="--help"
-          ;;
-        b)
-          if [ "$2" ]; then
-            opt="--bin"
-          else
-            opt="--bins"
-          fi
-          ;;
-        e)
-          if [ "$2" ]; then
-            opt="--example"
-          else
-            opt="--examples"
-          fi
-          ;;
-        l)
-          opt="--lib"
-          ;;
-        n)
-          if [ "$2" ]; then
-            opt="--bench"
-          else
-            opt="--benches"
-          fi
-          ;;
-        t)
-          if [ "$2" ]; then
-            opt="--test"
-          else
-            opt="--test $(basename "$PWD")"
-          fi
-          ;;
-        a)
-          opt="--all-targets --all-features"
-          ;;
-        w)
-          opt="--workspace"
-          ;;
-        x)
-          opt="--exclude"
-          ;;
-        esac
+				case "$(get_option --opt "$1" --pos 2)" in
+				h)
+					opt="--help"
+					;;
+				b)
+					if [ "$2" ]; then
+						opt="--bin"
+					else
+						opt="--bins"
+					fi
+					;;
+				e)
+					if [ "$2" ]; then
+						opt="--example"
+					else
+						opt="--examples"
+					fi
+					;;
+				l)
+					opt="--lib"
+					;;
+				n)
+					if [ "$2" ]; then
+						opt="--bench"
+					else
+						opt="--benches"
+					fi
+					;;
+				t)
+					if [ "$2" ]; then
+						opt="--test"
+					else
+						opt="--test $(basename "$PWD")"
+					fi
+					;;
+				a)
+					opt="--all-targets --all-features"
+					;;
+				w)
+					opt="--workspace"
+					;;
+				x)
+					opt="--exclude"
+					;;
+				esac
 
-        while [ $# -gt 1 ]; do
-          case "$2" in --) break ;; -*) ;; *) opt="$opt $2" ;; esac
-          shift
-        done
+				while [ $# -gt 1 ]; do
+					case "$2" in --) break ;; -*) ;; *) opt="$opt $2" ;; esac
+					shift
+				done
 
-        [ "$3" ] && shift
+				[ "$3" ] && shift
 
-        arg="--nocapture --exact"
-        while [ $# -gt 1 ]; do
-          case "$2" in --) break ;; -*) ;; *) arg="$arg $2" ;; esac
-          shift
-        done
-        ;;
-      *)
-        case $1 in
-        -*D* | -*Q* | -*R* | -*W* | -H | --debug) ;;
-        *) cmd="$cmd $1" ;;
-        esac
-        ;;
-      esac
-      shift
-    done
-  } && external "$@"
+				arg="--nocapture --exact"
+				while [ $# -gt 1 ]; do
+					case "$2" in --) break ;; -*) ;; *) arg="$arg $2" ;; esac
+					shift
+				done
+				;;
+			*)
+				case $1 in
+				-*D* | -*Q* | -*R* | -*W* | -H | --debug) ;;
+				*) cmd="$cmd $1" ;;
+				esac
+				;;
+			esac
+			shift
+		done
+	} && external "$@"
 }
 
 process() {
-  #@ Join the command parts
-  [ "$opt" ] || opt="$verbosity $opt"
-  [ "$release" ] && opt="$opt --release"
-  [ "$arg" ] && arg=" -- $arg"
-  cmd="$cmd $opt $arg"
+	#@ Join the command parts
+	[ "$opt" ] || opt="$verbosity $opt"
+	[ "$release" ] && opt="$opt --release"
+	[ "$arg" ] && arg=" -- $arg"
+	cmd="$cmd $opt $arg"
 
-  #@ Ensure watch is used only on test and run commands
-  case "$cmd" in "test "* | "run "*) ;; *) unset watch ;; esac
+	#@ Ensure watch is used only on test and run commands
+	case "$cmd" in "test "* | "run "*) ;; *) unset watch ;; esac
 
-  #@ Update the command according to the mode
-  cmd="$(cargo_cmd "$cmd" "$watch")"
+	#@ Update the command according to the mode
+	cmd="$(cargo_cmd "$cmd" "$watch")"
 
-  #@ Display the command
-  [ "$verbose" ] && printf "/> %s\n" "$cmd"
+	#@ Display the command
+	[ "$verbose" ] && printf "/> %s\n" "$cmd"
 
-  #@ Execute the command
-  [ "$debug" ] || eval "$cmd"
+	#@ Execute the command
+	[ "$debug" ] || eval "$cmd"
 }
 
 if [ -x "$PWD/cgo.sh" ]; then
-  ./cgo.sh "$@"
+	./cgo.sh "$@"
 else
-  main "$@"
+	main "$@"
 fi
diff --git a/Bin/shellscript/tasks/xmonad.init b/Bin/shellscript/tasks/xmonad.init
--- a/Bin/shellscript/tasks/xmonad.init
+++ b/Bin/shellscript/tasks/xmonad.init
@@ -8,45 +8,45 @@ _msg_success="$(printf "⚙️  Installing \'%s\' via %s." "$_cmd" "$_man")"
 _msg_failure="$(printf "💀  No package manager found to install \'%s\'." "$_cmd")"
 
 __error__() {
-  printf '%s\n' "$_msg_failure"
-  exit 1
+	printf '%s\n' "$_msg_failure"
+	exit 1
 }
 
 __install__() {
-  [ "$_man" ] || __error__
+	[ "$_man" ] || __error__
 
-  printf '%s\n' "$_msg_success"
+	printf '%s\n' "$_msg_success"
 
-  case "$_man" in
-  paru)
-    paru \
-      --sync --needed --quiet --noconfirm \
-      git xorg-server xorg-apps xorg-xinit xorg-xmessage libx11 libxft libxinerama libxrandr libxss pkgconf
-    ;;
-  yay)
-    yay \
-      --sync --needed --quiet --noconfirm \
-      git xorg-server xorg-apps xorg-xinit xorg-xmessage libx11 libxft libxinerama libxrandr libxss pkgconf
-    ;;
-  pacman)
-    sudo pacman \
-      --sync --needed --quiet --noconfirm \
-      git xorg-server xorg-apps xorg-xinit xorg-xmessage libx11 libxft libxinerama libxrandr libxss pkgconf
-    ;;
-  dnf)
-    sudo dnf install \
-      git \
-      libX11-devel libXft-devel libXinerama-devel libXrandr-devel libXScrnSaver-devel
-    ;;
-  xbps-install)
-    sudo xbps-install \
-      git \
-      ncurses-libtinfo-libs ncurses-libtinfo-devel \
-      libX11-devel libXft-devel libXinerama-devel libXrandr-devel libXScrnSaver-devel \
-      pkg-config
-    ;;
-  *) ;;
-  esac
+	case "$_man" in
+	paru)
+		paru \
+			--sync --needed --quiet --noconfirm \
+			git xorg-server xorg-apps xorg-xinit xorg-xmessage libx11 libxft libxinerama libxrandr libxss pkgconf
+		;;
+	yay)
+		yay \
+			--sync --needed --quiet --noconfirm \
+			git xorg-server xorg-apps xorg-xinit xorg-xmessage libx11 libxft libxinerama libxrandr libxss pkgconf
+		;;
+	pacman)
+		sudo pacman \
+			--sync --needed --quiet --noconfirm \
+			git xorg-server xorg-apps xorg-xinit xorg-xmessage libx11 libxft libxinerama libxrandr libxss pkgconf
+		;;
+	dnf)
+		sudo dnf install \
+			git \
+			libX11-devel libXft-devel libXinerama-devel libXrandr-devel libXScrnSaver-devel
+		;;
+	xbps-install)
+		sudo xbps-install \
+			git \
+			ncurses-libtinfo-libs ncurses-libtinfo-devel \
+			libX11-devel libXft-devel libXinerama-devel libXrandr-devel libXScrnSaver-devel \
+			pkg-config
+		;;
+	*) ;;
+	esac
 }
 
 __install__
diff --git a/Bin/shellscript/utility/files/symbiolink b/Bin/shellscript/utility/files/symbiolink
--- a/Bin/shellscript/utility/files/symbiolink
+++ b/Bin/shellscript/utility/files/symbiolink
@@ -7,7 +7,7 @@ _cmd_VERSION="1.0"
 _cmd_DESCRIPTION="Create a symbolic link between files"
 _cmd_DEPENDENCIES="coreutils."
 _cmd_USAGEGUIDE="$(
-  cat <<USAGE_GUIDE
+	cat <<USAGE_GUIDE
 |---------------------------------------------------->
   $_cmd_NAME>=> $_cmd_DESCRIPTION
 |---------------------------------------------------->
@@ -34,67 +34,67 @@ __version__() { printf "%s\n" "$_cmd_VERSION"; }
 
 #@ Accept user options/flags
 __opts__() {
-  case "$1" in
-  -h | --help)
-    __help__
-    exit
-    ;;
-  -v | --version)
-    __version__
-    exit
-    ;;
-  -d | --verbose) verbose=true ;;
-  -q | --quiet) unset verbose ;;
-  -f | --force | --reset) force=true ;;
-  -s | --src | --source | --origin)
-    src_path="$2"
-    shift
-    ;;
-  -l | --lnk | --link | --destination)
-    lnk_path="$2"
-    shift
-    ;;
-  -*) __error__ --invalid-opt "$1" ;;
-  *) ;;
-  esac
+	case "$1" in
+	-h | --help)
+		__help__
+		exit
+		;;
+	-v | --version)
+		__version__
+		exit
+		;;
+	-d | --verbose) verbose=true ;;
+	-q | --quiet) unset verbose ;;
+	-f | --force | --reset) force=true ;;
+	-s | --src | --source | --origin)
+		src_path="$2"
+		shift
+		;;
+	-l | --lnk | --link | --destination)
+		lnk_path="$2"
+		shift
+		;;
+	-*) __error__ --invalid-opt "$1" ;;
+	*) ;;
+	esac
 }
 
 __init__() {
 
-  #| Arguments
-  #@ Skip arguments if source and link paths provided
-  if [ ! "$src_path" ] || [ ! "$lnk_path" ]; then
+	#| Arguments
+	#@ Skip arguments if source and link paths provided
+	if [ ! "$src_path" ] || [ ! "$lnk_path" ]; then
 
-    #@ Expect arguments
-    [ "$#" -gt 0 ] || __error__ --args "$#"
+		#@ Expect arguments
+		[ "$#" -gt 0 ] || __error__ --args "$#"
 
-    #@ Loop through arguments
-    while [ "$#" -gt 0 ]; do
-      __opts__ "$@"
-      shift
-    done
+		#@ Loop through arguments
+		while [ "$#" -gt 0 ]; do
+			__opts__ "$@"
+			shift
+		done
 
-    #@ Source and Link
-    [ "$src_path" ] || __error__ --args-source
-    [ "$lnk_path" ] || __error__ --args-link
-  fi
+		#@ Source and Link
+		[ "$src_path" ] || __error__ --args-source
+		[ "$lnk_path" ] || __error__ --args-link
+	fi
 
-  #| Source
-  #@ Ensure source is valid
-  [ -e "$src_path" ] || __error__ --source "$src_path"
+	#| Source
+	#@ Ensure source is valid
+	[ -e "$src_path" ] || __error__ --source "$src_path"
 
-  #| Link
-  #@ Declare the destination directory
-  lnk_parent="$(dirname "$lnk_path")"
-  lnk_lineage="$lnk_parent"
+	#| Link
+	#@ Declare the destination directory
+	lnk_parent="$(dirname "$lnk_path")"
+	lnk_lineage="$lnk_parent"
 
-  #@ Find the first valid parent directory
-  while [ ! -d "$lnk_lineage" ]; do
-    lnk_lineage="$(dirname "$lnk_lineage")"
-  done
+	#@ Find the first valid parent directory
+	while [ ! -d "$lnk_lineage" ]; do
+		lnk_lineage="$(dirname "$lnk_lineage")"
+	done
 
-  #@ Check destination ownership
-  [ -O "$lnk_lineage" ] && owned=true
+	#@ Check destination ownership
+	[ -O "$lnk_lineage" ] && owned=true
 }
 
 # ===================================================================
@@ -103,140 +103,140 @@ __init__() {
 
 __archive__() {
 
-  #@ Skip unless user requested
-  { [ "$force" ] && [ -e "$lnk_path" ]; } || return
+	#@ Skip unless user requested
+	{ [ "$force" ] && [ -e "$lnk_path" ]; } || return
 
-  #@ Store archive path in a variable
-  link_archive="${lnk_path}.bac"
+	#@ Store archive path in a variable
+	link_archive="${lnk_path}.bac"
 
-  #@ Use sudo if necessary to move the link
-  if [ "$owned" ]; then
-    mv --force "$lnk_path" "$link_archive"
-  else
-    sudo mv --force "$lnk_path" "$link_archive"
-  fi
+	#@ Use sudo if necessary to move the link
+	if [ "$owned" ]; then
+		mv --force "$lnk_path" "$link_archive"
+	else
+		sudo mv --force "$lnk_path" "$link_archive"
+	fi
 
-  #@ Show detailed information
-  __msg__ --archived
+	#@ Show detailed information
+	__msg__ --archived
 }
 
 __mkdir__() {
-  #@ Skip if destination directory found
-  [ -d "$lnk_parent" ] && return
+	#@ Skip if destination directory found
+	[ -d "$lnk_parent" ] && return
 
-  #@ Create directory if missing
-  while [ ! -d "$lnk_parent" ]; do
-    printf \
-      "The destination directory doesnt exist: %s\nShould we create it? [y|N]\n" \
-      "$lnk_parent"
+	#@ Create directory if missing
+	while [ ! -d "$lnk_parent" ]; do
+		printf \
+			"The destination directory doesnt exist: %s\nShould we create it? [y|N]\n" \
+			"$lnk_parent"
 
-    case "$(read_char)" in
-    [Yy])
-      #@ Make directory
-      if [ "$owned" ]; then
-        mkdir --parents "$lnk_parent"
-      else
-        sudo mkdir --parents "$lnk_parent"
-      fi
-      ;;
-    *)
-      printf "Exiting...\n"
-      exit 1
-      ;;
-    esac
-  done
+		case "$(read_char)" in
+		[Yy])
+			#@ Make directory
+			if [ "$owned" ]; then
+				mkdir --parents "$lnk_parent"
+			else
+				sudo mkdir --parents "$lnk_parent"
+			fi
+			;;
+		*)
+			printf "Exiting...\n"
+			exit 1
+			;;
+		esac
+	done
 
-  #@ Show detailed information
-  __msg__ --dired
+	#@ Show detailed information
+	__msg__ --dired
 }
 
 __link__() {
-  #@ Exit if the target/link resolves to the source
-  [ "$(pathof "$lnk_path")" = "$(pathof "$src_path")" ] && {
-    __msg__ --valid
-    __exit__ --success
-  }
+	#@ Exit if the target/link resolves to the source
+	[ "$(pathof "$lnk_path")" = "$(pathof "$src_path")" ] && {
+		__msg__ --valid
+		__exit__ --success
+	}
 
-  #@ Ensure the is nested if the source is a file
-  [ -f "$src_path" ] && lnk_lineage="$lnk_parent"
+	#@ Ensure the is nested if the source is a file
+	[ -f "$src_path" ] && lnk_lineage="$lnk_parent"
 
-  #@ Create link using sudo, if necessay
-  if [ "$owned" ]; then
-    ln --symbolic "$src_path" "$lnk_path"
-  else
-    sudo ln --symbolic "$src_path" "$lnk_path"
-  fi
+	#@ Create link using sudo, if necessay
+	if [ "$owned" ]; then
+		ln --symbolic "$src_path" "$lnk_path"
+	else
+		sudo ln --symbolic "$src_path" "$lnk_path"
+	fi
 
-  #@ Show detailed information
-  [ -e "$lnk_path" ] && {
-    __msg__ --linked
-    __exit__ --success
-  }
+	#@ Show detailed information
+	[ -e "$lnk_path" ] && {
+		__msg__ --linked
+		__exit__ --success
+	}
 }
 
 # ===================================================================
 #@                             OUTPUT                              @#
 # ===================================================================
 __msg__() {
-  #@ Display messages based on verbosity
-  [ "$verbose" ] || return
+	#@ Display messages based on verbosity
+	[ "$verbose" ] || return
 
-  linked="$lnk_path ==> $src_path"
+	linked="$lnk_path ==> $src_path"
 
-  case $1 in
-  --valid) msg="Valid Link: $linked" ;;
-  --linked) msg="Established Link: $linked" ;;
-  --owned) msg="The destination directory is owned by the current user." ;;
-  --args) msg="::❗:: 2 arguments were expected but $# was given.\n" ;;
-  --no-source) msg="Source is undefined" ;;
-  --no-link) msg="Link is undefined" ;;
-  --create-parent) msg="Destination directory doesnt exist: $lnk_parent" ;;
-  esac
+	case $1 in
+	--valid) msg="Valid Link: $linked" ;;
+	--linked) msg="Established Link: $linked" ;;
+	--owned) msg="The destination directory is owned by the current user." ;;
+	--args) msg="::❗:: 2 arguments were expected but $# was given.\n" ;;
+	--no-source) msg="Source is undefined" ;;
+	--no-link) msg="Link is undefined" ;;
+	--create-parent) msg="Destination directory doesnt exist: $lnk_parent" ;;
+	esac
 
-  printf "%s\n" "$msg"
+	printf "%s\n" "$msg"
 }
 
 __error__() {
-  case $1 in
-  --args)
-    shift
-    printf "::❗:: 2 arguments were expected but %s was given.\n" "$@"
-    # __msg__ --args "$@"
-    ;;
-  --args-source) __msg__ --no-source ;;
-  --args-link) __msg__ --no-link ;;
-  --source)
-    shift
-    printf "Invalid source: %s\n" "$@"
-    ;;
-  --exists)
-    shift
-    [ "$verbose" ] && printf "Path Exists: %s\n" "$@"
-    ;;
-  --missing)
-    shift
-    [ "$verbose" ] && printf "Path Missing: %s\n" "$@"
-    ;;
-  --linkdir)
-    shift
-    printf "Destination directory doesnt exist: %s\n" "$(dirname "$@")"
-    ;;
-  --invalid-opt)
-    shift
-    printf "Unknown Option: %s\n" "$@"
-    ;;
-  *) ;;
-  esac
+	case $1 in
+	--args)
+		shift
+		printf "::❗:: 2 arguments were expected but %s was given.\n" "$@"
+		# __msg__ --args "$@"
+		;;
+	--args-source) __msg__ --no-source ;;
+	--args-link) __msg__ --no-link ;;
+	--source)
+		shift
+		printf "Invalid source: %s\n" "$@"
+		;;
+	--exists)
+		shift
+		[ "$verbose" ] && printf "Path Exists: %s\n" "$@"
+		;;
+	--missing)
+		shift
+		[ "$verbose" ] && printf "Path Missing: %s\n" "$@"
+		;;
+	--linkdir)
+		shift
+		printf "Destination directory doesnt exist: %s\n" "$(dirname "$@")"
+		;;
+	--invalid-opt)
+		shift
+		printf "Unknown Option: %s\n" "$@"
+		;;
+	*) ;;
+	esac
 
-  __help__
-  __exit__ --failure
+	__help__
+	__exit__ --failure
 }
 
 __exit__() {
-  case "$1" in
-  --success) exit 0 ;;
-  --failure) exit 1 ;;
-  esac
+	case "$1" in
+	--success) exit 0 ;;
+	--failure) exit 1 ;;
+	esac
 }
 
 # ===================================================================
@@ -244,35 +244,35 @@ __exit__() {
 # ===================================================================
 
 __process__() {
-  #@ Archive
-  __archive__
+	#@ Archive
+	__archive__
 
-  #@ Create destination parent directories
-  __mkdir__
+	#@ Create destination parent directories
+	__mkdir__
 
-  #@ Link
-  [ -e "$lnk_path" ] || __link__
+	#@ Link
+	[ -e "$lnk_path" ] || __link__
 }
 
 __test__() {
-  echo "Source:  $src_path"
-  echo "Link:    $lnk_path"
-  echo "LinkDIR: $lnk_parent"
-  echo "Owned:   $owned"
-  echo "Reset:   $force"
-  echo "Verbose: $verbose"
-  echo "MkDir:   $_MKDIR"
-  # __error__ --args
-  [ -e "$lnk_parent" ] && ls "$lnk_parent"
-  [ -e "$link_archive" ] && echo "ARCHIVING $link_archive"
-  [ -e "$lnk_path" ] || echo "LINKING: $lnk_path" to "$src_path"
+	echo "Source:  $src_path"
+	echo "Link:    $lnk_path"
+	echo "LinkDIR: $lnk_parent"
+	echo "Owned:   $owned"
+	echo "Reset:   $force"
+	echo "Verbose: $verbose"
+	echo "MkDir:   $_MKDIR"
+	# __error__ --args
+	[ -e "$lnk_parent" ] && ls "$lnk_parent"
+	[ -e "$link_archive" ] && echo "ARCHIVING $link_archive"
+	[ -e "$lnk_path" ] || echo "LINKING: $lnk_path" to "$src_path"
 
 }
 
 __main__() {
-  __init__ "$@"
-  # __test__
-  __process__
+	__init__ "$@"
+	# __test__
+	__process__
 }
 
 __main__ "$@"
diff --git a/Bin/shellscript/utility/output/align b/Bin/shellscript/utility/output/align
--- a/Bin/shellscript/utility/output/align
+++ b/Bin/shellscript/utility/output/align
@@ -1,12 +1,12 @@
 #!/bin/sh
 
 initialize_script() {
-  __information() {
-    scr_name="align"
-    scr_version="0.2"
-    scr_description="simple STDOUT horizontal line text alignment script."
-    scr_usage="$(
-      txtBarber "
+	__information() {
+		scr_name="align"
+		scr_version="0.2"
+		scr_description="simple STDOUT horizontal line text alignment script."
+		scr_usage="$(
+			txtBarber "
         Usage: $scr_name [OPTIONS] [TEXT]
         Description: $scr_name is a $scr_description
 
@@ -31,226 +31,226 @@ initialize_script() {
           - The options \`--pad\`, \`--padl\`, and \`--padr\` require an argument which must be a single character.
           - The \`--width\` option requires an argument which must be a positive integer representing the terminal width.
       "
-    )"
-  } && __information
+		)"
+	} && __information
 
-  __variables() {
-    unset verbose alignment pad_char pad_char_l pad_char_r text text_length buffer padding_length term_width padding_right padding_left padding
-    term_width="${term_width:-$(get_len --term)}"
-    exit_code=0
-  } && __variables
+	__variables() {
+		unset verbose alignment pad_char pad_char_l pad_char_r text text_length buffer padding_length term_width padding_right padding_left padding
+		term_width="${term_width:-$(get_len --term)}"
+		exit_code=0
+	} && __variables
 
 }
 
 parse_arguments() {
-  while [ $# -gt 0 ]; do
-    case "$1" in
-    -h | --help)
-      show_usage_guide
-      ;;
-    -v | --version)
-      print_version
-      exit
-      ;;
-    -d | --verbose) verbose=true ;;
-    -c | --center) alignment="center" ;;
-    -r | --right) alignment="right" ;;
-    -l | --left) alignment="left" ;;
-    -p | --pad | --char)
-      if [ "$2" ]; then
-      
-        validate_var \
-          --lbl "Padding Character" \
-          --var "$2" &&
-          pad_char="$2"
-        shift
-      else
-        show_usage_guide \
-          --lbl "Padding Character Error" \
-          --msg "Missing argument for '$1'." \
-          --opt "$1" \
-          --var "<CHAR>" \
-          --fatal
-      fi
-      ;;
-    --padl)
-      if [ "$2" ]; then
-        validate_var \
-          --lbl "Left Padding Character" \
-          --var "$2" &&
-          pad_char="$2"
-        shift
-      else
-        show_usage_guide \
-          --lbl "Padding Character [Left] Error" \
-          --msg "Missing argument for '$1'." \
-          --opt "$1" \
-          --var "<CHAR>" \
-          --fatal
-      fi
-      ;;
-    --padr)
-      label="Padding Character [Right]"
-      pad_char_r="$(
-        validate_var \
-          --lbl "Right Padding Character" \
-          --opt "$1" \
-          --var "$2" \
-          --type
-      )"
-      echo "$pad_char_r"
-      exit
-      # if [ "$2" ]; then
-      #   validate_var "$2"
-      #   # pad_char="$2"
-      #   shift
-      # else
-      #   show_usage_guide \
-      #     --lbl "$label" \
-      #     --msg "Missing argument for '$1'." \
-      #     --opt "$1" \
-      #     --var "<CHAR>" \
-      #     --fatal
-      # fi
-      ;;
-    --width)
-      if [ "$2" ]; then
-        term_width="$2"
-        shift
-      else
-        [ "$verbose" ] && printf "Error: Missing argument for %s\n" "$1"
-      fi
-      ;;
-    *) text="$1" ;;
-    esac
-    shift
-  done
+	while [ $# -gt 0 ]; do
+		case "$1" in
+		-h | --help)
+			show_usage_guide
+			;;
+		-v | --version)
+			print_version
+			exit
+			;;
+		-d | --verbose) verbose=true ;;
+		-c | --center) alignment="center" ;;
+		-r | --right) alignment="right" ;;
+		-l | --left) alignment="left" ;;
+		-p | --pad | --char)
+			if [ "$2" ]; then
+
+				validate_var \
+					--lbl "Padding Character" \
+					--var "$2" &&
+					pad_char="$2"
+				shift
+			else
+				show_usage_guide \
+					--lbl "Padding Character Error" \
+					--msg "Missing argument for '$1'." \
+					--opt "$1" \
+					--var "<CHAR>" \
+					--fatal
+			fi
+			;;
+		--padl)
+			if [ "$2" ]; then
+				validate_var \
+					--lbl "Left Padding Character" \
+					--var "$2" &&
+					pad_char="$2"
+				shift
+			else
+				show_usage_guide \
+					--lbl "Padding Character [Left] Error" \
+					--msg "Missing argument for '$1'." \
+					--opt "$1" \
+					--var "<CHAR>" \
+					--fatal
+			fi
+			;;
+		--padr)
+			label="Padding Character [Right]"
+			pad_char_r="$(
+				validate_var \
+					--lbl "Right Padding Character" \
+					--opt "$1" \
+					--var "$2" \
+					--type
+			)"
+			echo "$pad_char_r"
+			exit
+			# if [ "$2" ]; then
+			#   validate_var "$2"
+			#   # pad_char="$2"
+			#   shift
+			# else
+			#   show_usage_guide \
+			#     --lbl "$label" \
+			#     --msg "Missing argument for '$1'." \
+			#     --opt "$1" \
+			#     --var "<CHAR>" \
+			#     --fatal
+			# fi
+			;;
+		--width)
+			if [ "$2" ]; then
+				term_width="$2"
+				shift
+			else
+				[ "$verbose" ] && printf "Error: Missing argument for %s\n" "$1"
+			fi
+			;;
+		*) text="$1" ;;
+		esac
+		shift
+	done
 }
 
 set_environment() {
 
-  label="Terminal Width"
-  term_width="${term_width:-$(get_len --term)}"
-  is_number "$term_width" "$label"
+	label="Terminal Width"
+	term_width="${term_width:-$(get_len --term)}"
+	is_number "$term_width" "$label"
 
-  label="Text Length"
-  text_length="$(get_len "$text")"
-  is_number "$text_length" "$label"
+	label="Text Length"
+	text_length="$(get_len "$text")"
+	is_number "$text_length" "$label"
 
-  label="Buffer Length"
-  if [ "$alignment" = "center" ]; then
-    buffer_length=2
-  else
-    buffer_length=1
-  fi
+	label="Buffer Length"
+	if [ "$alignment" = "center" ]; then
+		buffer_length=2
+	else
+		buffer_length=1
+	fi
 
-  label="Padding Character"
-  default_char=" "
-  pad_char_l="${pad_char_l:-${pad_char:-${pad_char_r:-$default_char}}}"
-  pad_char_r="${pad_char_r:-${pad_char:-${pad_char_l:-$default_char}}}"
+	label="Padding Character"
+	default_char=" "
+	pad_char_l="${pad_char_l:-${pad_char:-${pad_char_r:-$default_char}}}"
+	pad_char_r="${pad_char_r:-${pad_char:-${pad_char_l:-$default_char}}}"
 
-  # [ "$pad_char_l" ] && validate_var "$pad_char_l" "Left $label"
-  # [ "$pad_char_r" ] && validate_var "$pad_char_r" "Right $label"
+	# [ "$pad_char_l" ] && validate_var "$pad_char_l" "Left $label"
+	# [ "$pad_char_r" ] && validate_var "$pad_char_r" "Right $label"
 
-  label="Padding"
-  [ "$term_width" -gt "$text_length" ] && padding_length=$(((term_width - text_length - buffer_length) / buffer_length))
-  padding_left="$(repeat_char "$pad_char_l" "$padding_length")"
-  padding_right="$(repeat_char "$pad_char_r" "$padding_length")"
+	label="Padding"
+	[ "$term_width" -gt "$text_length" ] && padding_length=$(((term_width - text_length - buffer_length) / buffer_length))
+	padding_left="$(repeat_char "$pad_char_l" "$padding_length")"
+	padding_right="$(repeat_char "$pad_char_r" "$padding_length")"
 }
 
 repeat_char() {
-  char="$1"
-  reps="$2"
-  printf "%-${reps}s" | tr " " "$char"
+	char="$1"
+	reps="$2"
+	printf "%-${reps}s" | tr " " "$char"
 }
 
 is_number() {
-  var="$1"
-  lbl="$2"
+	var="$1"
+	lbl="$2"
 
-  case $var in
-  '' | *[!0-9]*)
-    #TODO use pout for error handling to replace printf and exit
-    # printf "%s '%s', is not a valid number\n" "$lbl" "$var"
-    [ "$verbose" ] &&
-      embellish \
-        --reset --underline --bg-red --fg-white \
-        "$lbl Error:" \
-        --reset --space --bold --red --italic \
-        "$var" \
-        --reset --space \
-        "is not a valid number." \
-        --reset --new-line
-    exit 1
-    ;;
-  *) return 0 ;;
-  esac
+	case $var in
+	'' | *[!0-9]*)
+		#TODO use pout for error handling to replace printf and exit
+		# printf "%s '%s', is not a valid number\n" "$lbl" "$var"
+		[ "$verbose" ] &&
+			embellish \
+				--reset --underline --bg-red --fg-white \
+				"$lbl Error:" \
+				--reset --space --bold --red --italic \
+				"$var" \
+				--reset --space \
+				"is not a valid number." \
+				--reset --new-line
+		exit 1
+		;;
+	*) return 0 ;;
+	esac
 }
 
 is_single_char() {
-  var="$1"
-  lbl="$2"
+	var="$1"
+	lbl="$2"
 
-  if [ -z "$var" ]; then
-    embellish \
-      --reset --underline --bg-red --fg-white \
-      "$lbl Error:" \
-      --reset --space \
-      "missing character" \
-      --reset --new-line
-    exit 1
-  fi
+	if [ -z "$var" ]; then
+		embellish \
+			--reset --underline --bg-red --fg-white \
+			"$lbl Error:" \
+			--reset --space \
+			"missing character" \
+			--reset --new-line
+		exit 1
+	fi
 
-  case $var in
-  # Printable characters, including whitespace
-  [[:print:]]) return 0 ;;
-  *)
-    #TODO use pout for error handling to replace printf and exit
-    # printf "%s '%s', is not a valid single character\n" "$lbl" "$var"
-    embellish \
-      The \
-      --reset --space --bold --red --italic \
-      "$(printf "%s" "$lbl" | tr '[:upper:]' '[:lower:]')" \
-      --reset --space --underline --bg-red --fg-white \
-      ["$var"] \
-      --reset --space \
-      "is not a single character." \
-      --reset --new-line
+	case $var in
+	# Printable characters, including whitespace
+	[[:print:]]) return 0 ;;
+	*)
+		#TODO use pout for error handling to replace printf and exit
+		# printf "%s '%s', is not a valid single character\n" "$lbl" "$var"
+		embellish \
+			The \
+			--reset --space --bold --red --italic \
+			"$(printf "%s" "$lbl" | tr '[:upper:]' '[:lower:]')" \
+			--reset --space --underline --bg-red --fg-white \
+			["$var"] \
+			--reset --space \
+			"is not a single character." \
+			--reset --new-line
 
-    exit 1
-    ;;
-  esac
+		exit 1
+		;;
+	esac
 }
 
 validate_var() {
-  func_name="validate_var"
-  func_usage="$func_name [OPTIONS] <Value>"
-  while [ $# -gt 0 ]; do
-    case $1 in
-    --lbl | --opt | --var | --type)
-      #@ Remove the leading hyphens from the option
-      variable_name=${1#--}
+	func_name="validate_var"
+	func_usage="$func_name [OPTIONS] <Value>"
+	while [ $# -gt 0 ]; do
+		case $1 in
+		--lbl | --opt | --var | --type)
+			#@ Remove the leading hyphens from the option
+			variable_name=${1#--}
 
-      #@ Assign the value of $2 to the extracted variable name
-      if [ "$2" ]; then
-        eval "$variable_name=\"\$2\""
-        shift
-      else
-        printf "Error: Missing argument for %s\n" "$1"
-      fi
-      ;;
-    --*)
-      #TODO Use show_usage_guide
-      echo "Unknown option: $1"
-      ;;
-    *) var="$1" ;;
-    esac
-    shift
-  done
+			#@ Assign the value of $2 to the extracted variable name
+			if [ "$2" ]; then
+				eval "$variable_name=\"\$2\""
+				shift
+			else
+				printf "Error: Missing argument for %s\n" "$1"
+			fi
+			;;
+		--*)
+			#TODO Use show_usage_guide
+			echo "Unknown option: $1"
+			;;
+		*) var="$1" ;;
+		esac
+		shift
+	done
 
-  printf "type %s | opt %s | var %s | lbl %s" \
-    "$type" "$opt" "$var" "$lbl"
-  # [ "$var" ] || show_usage_guide --fatal
+	printf "type %s | opt %s | var %s | lbl %s" \
+		"$type" "$opt" "$var" "$lbl"
+	# [ "$var" ] || show_usage_guide --fatal
 }
 # if [ "$" ];then
 # case $var in
@@ -322,115 +322,115 @@ validate_var() {
 # }
 
 get_len() {
-  case $1 in
-  --term) stty size 2>/dev/null | awk '{print $2}' ;;
-  *) printf "%s" "${#1}" ;;
-  esac
+	case $1 in
+	--term) stty size 2>/dev/null | awk '{print $2}' ;;
+	*) printf "%s" "${#1}" ;;
+	esac
 }
 
 print_padded_text() {
-  if [ "$padding_left" ] || [ "$padding_right" ]; then
-    case "$alignment" in
-    center)
-      printf \
-        "%s %s %s\n" \
-        "${padding:-$padding_left}" \
-        "$text" \
-        "${padding:-$padding_right}"
-      ;;
-    right)
-      printf "%s %s\n" "$padding_left" "$text"
-      ;;
-    left | *)
-      printf "%s %s\n" "$text" "$padding_right"
-      ;;
-    esac
-  else
-    printf "%s\n" "$text"
-  fi
+	if [ "$padding_left" ] || [ "$padding_right" ]; then
+		case "$alignment" in
+		center)
+			printf \
+				"%s %s %s\n" \
+				"${padding:-$padding_left}" \
+				"$text" \
+				"${padding:-$padding_right}"
+			;;
+		right)
+			printf "%s %s\n" "$padding_left" "$text"
+			;;
+		left | *)
+			printf "%s %s\n" "$text" "$padding_right"
+			;;
+		esac
+	else
+		printf "%s\n" "$text"
+	fi
 }
 
 show_usage_guide() {
-  case $1 in
-  -*)
-    while [ $# -gt 0 ]; do
-      case $1 in
-      -x | --fatal) exit_code="${2:-1}" ;;
-      --*)
-        #@ Assign the value of $2 to the extracted variable name
-        if [ "$2" ]; then
-          eval "$variable_name=\"\$2\""
-          shift
-        else
-          #TODO: handle better
-          printf "Error: Missing argument for %s\n" "$1"
-        fi
-        ;;
-      esac
-      shift
-    done
+	case $1 in
+	-*)
+		while [ $# -gt 0 ]; do
+			case $1 in
+			-x | --fatal) exit_code="${2:-1}" ;;
+			--*)
+				#@ Assign the value of $2 to the extracted variable name
+				if [ "$2" ]; then
+					eval "$variable_name=\"\$2\""
+					shift
+				else
+					#TODO: handle better
+					printf "Error: Missing argument for %s\n" "$1"
+				fi
+				;;
+			esac
+			shift
+		done
 
-    #/> Label
-    embellish \
-      --reset --underline --bg-red --fg-white \
-      --space "${lbl:-$label} Error" --space \
-      --reset --new-line
+		#/> Label
+		embellish \
+			--reset --underline --bg-red --fg-white \
+			--space "${lbl:-$label} Error" --space \
+			--reset --new-line
 
-    #/> Message
-    [ "$msg" ] && embellish "$msg" --reset --new-line
+		#/> Message
+		[ "$msg" ] && embellish "$msg" --reset --new-line
 
-    #/> Usage Guide
-    [ "$var" ] && [ "$opt" ] && embellish \
-      "Usage: $scr_name $opt" \
-      --space --red \
-      "$var" \
-      --reset --space \
-      "[TEXT]" \
-      --reset --new-line
+		#/> Usage Guide
+		[ "$var" ] && [ "$opt" ] && embellish \
+			"Usage: $scr_name $opt" \
+			--space --red \
+			"$var" \
+			--reset --space \
+			"[TEXT]" \
+			--reset --new-line
 
-    #/> Additional information
-    embellish \
-      --reset --new-line \
-      "For more information, run" \
-      --reset --space --bold --italic \
-      "$scr_name --help" \
-      --reset --new-line
-    ;;
-  *) printf "%s\n" "$scr_usage" ;;
-  esac
+		#/> Additional information
+		embellish \
+			--reset --new-line \
+			"For more information, run" \
+			--reset --space --bold --italic \
+			"$scr_name --help" \
+			--reset --new-line
+		;;
+	*) printf "%s\n" "$scr_usage" ;;
+	esac
 
-  exit "$exit_code"
+	exit "$exit_code"
 }
 
 print_version() {
-  printf "%s\n" "$scr_version"
+	printf "%s\n" "$scr_version"
 }
 
 print_verbose_info() {
-  [ "$verbose" ] || return
-  cat <<EOF
+	[ "$verbose" ] || return
+	cat <<EOF
          Alignment: $alignment
     Terminal Width: $term_width characters
        Text Length: $text_length character(s)
             Buffer: $buffer_length space(s)
 EOF
-  if [ "$padding" ]; then
-    cat <<EOF
+	if [ "$padding" ]; then
+		cat <<EOF
          Padding: $padding_length reps of '$pad_char'
 EOF
-  else
-    cat <<EOF
+	else
+		cat <<EOF
            Padding: $padding_length reps of '$pad_char_r' and '$pad_char_l'
 EOF
-  fi
+	fi
 }
 
 main() {
-  initialize_script
-  parse_arguments "$@"
-  set_environment
-  print_verbose_info
-  print_padded_text
+	initialize_script
+	parse_arguments "$@"
+	set_environment
+	print_verbose_info
+	print_padded_text
 }
 
 main "$@"
