shfmt options

diff --git a/Bin/shellscript/base/DeployConfig b/Bin/shellscript/base/DeployConfig
--- a/Bin/shellscript/base/DeployConfig
+++ b/Bin/shellscript/base/DeployConfig
@@ -8,7 +8,7 @@ _cmd_DESCRIPTION="$(printf "creates symbolic links for application configuration
 _cmd_DEPENDENCIES="weHave, symbiolink, pout"
 _cmd_USAGE="$_cmd_NAME [OPTIONS] [APP|SRC|CTX]"
 _cmd_GUIDE="$(
-  cat <<USAGE_GUIDE
+  cat << USAGE_GUIDE
 $_cmd_NAME [$_cmd_VERSION] creates symbolic links for application configurations.
 It uses variables set in the context file to deploy links.
 
@@ -62,23 +62,23 @@ parse_arguments() {
 
   for arg in "$@"; do
     case "$arg" in
-    -d | --verbose) verbose=true ;;
-    -f | --force) force=true ;;
-    -q | --quiet) unset verbose ;;
+      -d | --verbose) verbose=true ;;
+      -f | --force) force=true ;;
+      -q | --quiet) unset verbose ;;
     esac
   done
 
   while [ "$#" -gt 0 ]; do
     case "$1" in
-    -h) pout --usage ;;
-    --help) pout --help ;;
-    -v | --version) pout --version ;;
-    -a | --app) APP="$2" ;;
-    -s | --src) SRC="$2" ;;
-    -l | --lnk) LNK="$2" ;;
-    -c | --ctx) CTX="$2" ;;
-    -*) pout --error --invalid-opt "$1" ;;
-    *) CTX="$1" ;;
+      -h) pout --usage ;;
+      --help) pout --help ;;
+      -v | --version) pout --version ;;
+      -a | --app) APP="$2" ;;
+      -s | --src) SRC="$2" ;;
+      -l | --lnk) LNK="$2" ;;
+      -c | --ctx) CTX="$2" ;;
+      -*) pout --error --invalid-opt "$1" ;;
+      *) CTX="$1" ;;
     esac
     shift
   done
@@ -110,37 +110,37 @@ validate_arguments() {
 
 pout() { #@ Print out to the terminal
   case $1 in
-  --usage) printf "Usage: %s\n" "$_cmd_USAGE" ;;
-  --help) printf "%s\n" "$_cmd_GUIDE" ;;
-  --warning)
-    #> Print the warning heading with space before and after
-    printf "%*sINFO [%s]:%*s" 3 "" "$_cmd_NAME" 1 ""
+    --usage) printf "Usage: %s\n" "$_cmd_USAGE" ;;
+    --help) printf "%s\n" "$_cmd_GUIDE" ;;
+    --warning)
+      #> Print the warning heading with space before and after
+      printf "%*sINFO [%s]:%*s" 3 "" "$_cmd_NAME" 1 ""
 
-    #> Print the warning message
-    case $2 in
-    --name) printf "Consider defining the '_NAME' variable in '%s', defaulting to '%s'\n" "$ctx" "$_NAME" ;;
-    esac
-    ;;
-  --error)
-    #> Print the error heading with space before and after
-    printf "%*sERROR [%s]:%*s" 3 "" "$_cmd_NAME" 1 ""
+      #> Print the warning message
+      case $2 in
+        --name) printf "Consider defining the '_NAME' variable in '%s', defaulting to '%s'\n" "$ctx" "$_NAME" ;;
+      esac
+      ;;
+    --error)
+      #> Print the error heading with space before and after
+      printf "%*sERROR [%s]:%*s" 3 "" "$_cmd_NAME" 1 ""
 
-    #> Print the error message
-    case $2 in
-    --ctx) printf "The config file '%s' is missing" "$3" ;;
-    --src) printf "Ensure the '_HOME' variable is set for '%s'" "$3" ;;
-    --app) printf "Please ensure '%s' is installed and in PATH" "$3" ;;
-    --arg) printf "The name/conf of the app was not provided\n%*s%s" 18 "" "$(pout --usage)" ;;
-    esac
+      #> Print the error message
+      case $2 in
+        --ctx) printf "The config file '%s' is missing" "$3" ;;
+        --src) printf "Ensure the '_HOME' variable is set for '%s'" "$3" ;;
+        --app) printf "Please ensure '%s' is installed and in PATH" "$3" ;;
+        --arg) printf "The name/conf of the app was not provided\n%*s%s" 18 "" "$(pout --usage)" ;;
+      esac
 
-    #> Terminate the script
-    exit 1
-    ;;
+      #> Terminate the script
+      exit 1
+      ;;
   esac
 }
 
 weHave() { #@ Check if a command exists
-  type "$1" >/dev/null 2>&1
+  type "$1" > /dev/null 2>&1
 }
 
 collect_vars() { #@ Read the variables from the context file or arguments
@@ -163,21 +163,21 @@ collect_vars() { #@ Read the variables from the context file or arguments
 
 validate() {
   case $1 in
-  --home)
-    [ "$_HOME" ] || pout --error --src "$app"
-    ;;
-  --name)
-    [ "$_NAME" ] || _NAME="$app"
-    pout --warning --name
-    ;;
-  --app)
-    weHave "$_CMD" || pout --error --app "$_NAME"
-    ;;
-  --all)
-    validate --home
-    validate --app
-    validate --name
-    ;;
+    --home)
+      [ "$_HOME" ] || pout --error --src "$app"
+      ;;
+    --name)
+      [ "$_NAME" ] || _NAME="$app"
+      pout --warning --name
+      ;;
+    --app)
+      weHave "$_CMD" || pout --error --app "$_NAME"
+      ;;
+    --all)
+      validate --home
+      validate --app
+      validate --name
+      ;;
   esac
 
 }
diff --git a/Bin/shellscript/base/murda b/Bin/shellscript/base/murda
--- a/Bin/shellscript/base/murda
+++ b/Bin/shellscript/base/murda
@@ -14,18 +14,18 @@ display_info() { [ "$verbose" ] && printf "%s\n" "$*"; }
 # Parse options
 while [ $# -gt 0 ]; do
   case "$1" in
-  -h | --help) usage ;;
-  -v | --version) printf "%s\n" "1.0" ;;
-  -d | --verbose) verbose=true ;;
-  -q | --quiet) unset verbose ;;
-  -*)
-    printf "Invalid option: %s\n" "$1"
-    usage
-    exit 1
-    ;;
-  *)
-    break
-    ;;
+    -h | --help) usage ;;
+    -v | --version) printf "%s\n" "1.0" ;;
+    -d | --verbose) verbose=true ;;
+    -q | --quiet) unset verbose ;;
+    -*)
+      printf "Invalid option: %s\n" "$1"
+      usage
+      exit 1
+      ;;
+    *)
+      break
+      ;;
   esac
   shift
 done
diff --git a/Bin/shellscript/environment/PushPop b/Bin/shellscript/environment/PushPop
--- a/Bin/shellscript/environment/PushPop
+++ b/Bin/shellscript/environment/PushPop
@@ -6,7 +6,7 @@ scr_VERSION="1.0"
 scr_DESCRIPTION="jumps into a directory, runs a command and returns to the original directory or one specified by the user"
 scr_DEPENDENCIES="coreutils"
 scr_USAGE="$(
-  cat <<USAGE
+  cat << USAGE
   $scr_NAME ($scr_VERSION)
   $scr_AUTHOR
 
@@ -45,23 +45,23 @@ parse_arguments() {
   #@ Parse command-line arguments
   while [ $# -gt 0 ]; do
     case $1 in
-    -h | --help) end_process --usage ;;
-    -v | --version) end_process --version ;;
-    -q | --quiet) verbosity="quiet" ;;
-    -d=* | --verbose=*) verbosity="${1#*=}" ;;
-    -d | --verbose)
-      case "$2" in
-      */*) ;;
-      *)
-        if [ "$2" ]; then
-          verbosity="$2"
-          shift
-        fi
+      -h | --help) end_process --usage ;;
+      -v | --version) end_process --version ;;
+      -q | --quiet) verbosity="quiet" ;;
+      -d=* | --verbose=*) verbosity="${1#*=}" ;;
+      -d | --verbose)
+        case "$2" in
+          */*) ;;
+          *)
+            if [ "$2" ]; then
+              verbosity="$2"
+              shift
+            fi
+            ;;
+        esac
         ;;
-      esac
-      ;;
-    -*) end_process --error opt "$1" ;;
-    *) ;;
+      -*) end_process --error opt "$1" ;;
+      *) ;;
     esac
     shift
   done
@@ -77,14 +77,14 @@ parse_arguments() {
   icon="${icon:-$icon_success}"
 
   case "$verbosity" in
-  0 | quiet) verbosity=0 ;;
-  1 | error | debug) verbosity=1 ;;
-  2 | info | *) verbosity=2 ;;
+    0 | quiet) verbosity=0 ;;
+    1 | error | debug) verbosity=1 ;;
+    2 | info | *) verbosity=2 ;;
   esac
 }
 
 usage() {
-  cat <<-EOF
+  cat <<- EOF
 		Usage: $scr_NAME [options]
 
 		Options:
@@ -110,56 +110,56 @@ error() {
 # Parse command line options
 while [ $# -gt 0 ]; do
   case "$1" in
-  -v | --version)
-    version
-    exit 0
-    ;;
-  -h | --help)
-    usage
-    exit 0
-    ;;
-  -q | --quiet) verbosity=0 ;;
-  -d | --debug | --verbose)
-    case "$2" in
-    "")
-      verbosity=2
+    -v | --version)
+      version
+      exit 0
       ;;
-    info)
-      verbosity=1
+    -h | --help)
+      usage
+      exit 0
       ;;
-    error)
-      verbosity=3
+    -q | --quiet) verbosity=0 ;;
+    -d | --debug | --verbose)
+      case "$2" in
+        "")
+          verbosity=2
+          ;;
+        info)
+          verbosity=1
+          ;;
+        error)
+          verbosity=3
+          ;;
+        quiet)
+          verbosity=0
+          ;;
+        *)
+          error "Invalid verbosity level: $2"
+          ;;
+      esac
+      shift
       ;;
-    quiet)
-      verbosity=0
+    -R | --rd | --cd)
+      returnDIR="$2"
+      shift
+      ;;
+    -W | --wd)
+      WorkDIR="$2"
+      shift
+      ;;
+    -c | --command)
+      Command="$2"
+      shift
       ;;
     *)
-      error "Invalid verbosity level: $2"
+      if [ "$WorkDIR" = "" ]; then
+        WorkDIR="$1"
+      elif [ "$Command" = "" ]; then
+        Command="$1"
+      else
+        error "Invalid option: $1"
+      fi
       ;;
-    esac
-    shift
-    ;;
-  -R | --rd | --cd)
-    returnDIR="$2"
-    shift
-    ;;
-  -W | --wd)
-    WorkDIR="$2"
-    shift
-    ;;
-  -c | --command)
-    Command="$2"
-    shift
-    ;;
-  *)
-    if [ "$WorkDIR" = "" ]; then
-      WorkDIR="$1"
-    elif [ "$Command" = "" ]; then
-      Command="$1"
-    else
-      error "Invalid option: $1"
-    fi
-    ;;
   esac
   shift
 done
@@ -174,7 +174,7 @@ if [ "$Command" = "" ]; then
 fi
 
 # Change to work directory
-if ! cd "$WorkDIR" >/dev/null; then
+if ! cd "$WorkDIR" > /dev/null; then
   error "Could not change to directory $WorkDIR"
 fi
 
@@ -188,6 +188,6 @@ if ! eval "$Command"; then
 fi
 
 # Change back to return directory
-if ! cd "$returnDIR" >/dev/null; then
+if ! cd "$returnDIR" > /dev/null; then
   error "Could not change back to directory $returnDIR"
 fi
diff --git a/Bin/shellscript/packages/manager/pacInstall b/Bin/shellscript/packages/manager/pacInstall
--- a/Bin/shellscript/packages/manager/pacInstall
+++ b/Bin/shellscript/packages/manager/pacInstall
@@ -2,7 +2,7 @@
 # |> _______________________________________________ <|
 
 __usageUpdate__() {
-  cat <<EOF
+  cat << EOF
             UGAGE:= update <[options]>
 |> ----------------------------------------------- <|
         -A  --all        Update all installed
@@ -26,36 +26,36 @@ __arch__() {
     while true; do
       read -p "Should we update the package mirrors, this may take some time? [y/N]?" yn
       case $yn in
-      [Yy]*)
-        mirror
+        [Yy]*)
+          mirror
 
-        # >>= Dependencies =<< #
-        # Required: https://xyne.archlinux.ca/projects/reflector
-        # edit /etc/xdg/reflector/reflector.conf
+          # >>= Dependencies =<< #
+          # Required: https://xyne.archlinux.ca/projects/reflector
+          # edit /etc/xdg/reflector/reflector.conf
 
-        # >>= Notification =<<
+          # >>= Notification =<<
 
-        OUTPUT() {
-          echo "${blue}::${reset} $msg"
-          notify-send "$msg"
-        }
-        clear
+          OUTPUT() {
+            echo "${blue}::${reset} $msg"
+            notify-send "$msg"
+          }
+          clear
 
-        # >>= Service =<< #
-        # systemctl enable reflector.timer
-        # systemctl start reflector.timer
-        msg="🕓 Mirrorlist weekly update timer set"
-        OUTPUT "$msg"
+          # >>= Service =<< #
+          # systemctl enable reflector.timer
+          # systemctl start reflector.timer
+          msg="🕓 Mirrorlist weekly update timer set"
+          OUTPUT "$msg"
 
-        # >>= Update =<<
-        msg="🔃 Syncing mirrors based on $(tput smul)/etc/xdg/reflector/reflector.conf$(tput rmul)"
-        OUTPUT "$msg"
-        # systemctl start reflector.service # Update mirrors immediatly
-        msg="⌛ The package mirrorlist has been updated"
-        OUTPUT "$msg"
-        ;;
-      [Nn]*) break ;;
-      *) break ;;
+          # >>= Update =<<
+          msg="🔃 Syncing mirrors based on $(tput smul)/etc/xdg/reflector/reflector.conf$(tput rmul)"
+          OUTPUT "$msg"
+          # systemctl start reflector.service # Update mirrors immediatly
+          msg="⌛ The package mirrorlist has been updated"
+          OUTPUT "$msg"
+          ;;
+        [Nn]*) break ;;
+        *) break ;;
       esac
     done
   }
@@ -177,42 +177,42 @@ eval set -- "$options"
 
 while true; do
   case $1 in
-  -A | --all)
-    __rustupUpdate__
-    if [ "$OS" = ArchLinux ]; then
-      __pacmanUpdate__
-      __paruUpdate__
-      __yayUpdate__
-    elif [ "$OS_TYPE" = Windows ]; then
-      __chocolateyUpdate__
-      __wingetUpdate__
-      __gitutilsUpdate__
-    elif [ "$OS" = Ubuntu ]; then
-      __flatpakUpdate__
-      __snapUpdate__
-    fi
-    ;;
-  -r | --rustup) __rustupUpdate__ "$@" ;;
-  -P | --pacman) __pacmanUpdate__ "$@" ;;
-  -p | --paru) __paruUpdate__ "$@" ;;
-  -y | --yay) __yayUpdate__ "$@" ;;
-  -f | --flatpak) __flatpakUpdate__ "$@" ;;
-  -s | --snap) __snapUpdate__ "$@" ;;
-  -w | --winget) __wingetUpdate__ "$@" ;;
-  -c | --choco) __chocolateyUpdate__ "$@" ;;
-  -g | --gits) __gitutilsUpdate__ ;;
-  --)
-    shift
-    break
-    ;;
-  -h | --help)
-    __usage__
-    exit 0
-    ;;
-  *)
-    echo "Internal error!"
-    exit 1
-    ;;
+    -A | --all)
+      __rustupUpdate__
+      if [ "$OS" = ArchLinux ]; then
+        __pacmanUpdate__
+        __paruUpdate__
+        __yayUpdate__
+      elif [ "$OS_TYPE" = Windows ]; then
+        __chocolateyUpdate__
+        __wingetUpdate__
+        __gitutilsUpdate__
+      elif [ "$OS" = Ubuntu ]; then
+        __flatpakUpdate__
+        __snapUpdate__
+      fi
+      ;;
+    -r | --rustup) __rustupUpdate__ "$@" ;;
+    -P | --pacman) __pacmanUpdate__ "$@" ;;
+    -p | --paru) __paruUpdate__ "$@" ;;
+    -y | --yay) __yayUpdate__ "$@" ;;
+    -f | --flatpak) __flatpakUpdate__ "$@" ;;
+    -s | --snap) __snapUpdate__ "$@" ;;
+    -w | --winget) __wingetUpdate__ "$@" ;;
+    -c | --choco) __chocolateyUpdate__ "$@" ;;
+    -g | --gits) __gitutilsUpdate__ ;;
+    --)
+      shift
+      break
+      ;;
+    -h | --help)
+      __usage__
+      exit 0
+      ;;
+    *)
+      echo "Internal error!"
+      exit 1
+      ;;
   esac
   shift
 done
diff --git a/Bin/shellscript/project/git/geet b/Bin/shellscript/project/git/geet
--- a/Bin/shellscript/project/git/geet
+++ b/Bin/shellscript/project/git/geet
@@ -16,7 +16,7 @@ establish_metadata() {
   _cmd_DEPENDENCIES="git, cd, pwd, dirname, basename, command, printf, tr"
   _cmd_USAGE="$_cmd_NAME [OPTIONS] <MESSAGE>"
   _cmd_USAGEGUIDE="$(
-    cat <<USAGE_GUIDE
+    cat << USAGE_GUIDE
 ::------------------------------------------------------------::
                           $_cmd_NAME ($_cmd_VERSION)
 ::------------------------------------------------------------::
@@ -92,14 +92,14 @@ establish_defaults() {
 
   #| Paths
   #TODO: this doesn't wor because it need eval
-  git rev-parse --show-superproject-working-tree >/dev/null 2>&1 &&
-    git_dir_super="$(git rev-parse --show-superproject-working-tree)"
+  git rev-parse --show-superproject-working-tree > /dev/null 2>&1 \
+    && git_dir_super="$(git rev-parse --show-superproject-working-tree)"
 
-  git rev-parse --show-toplevel >/dev/null 2>&1 &&
-    git_dir="$(git rev-parse --show-toplevel)"
+  git rev-parse --show-toplevel > /dev/null 2>&1 \
+    && git_dir="$(git rev-parse --show-toplevel)"
 
-  git remote get-url origin >/dev/null 2>&1 &&
-    actual_repo="$(git remote get-url origin)"
+  git remote get-url origin > /dev/null 2>&1 \
+    && actual_repo="$(git remote get-url origin)"
 
   target_repo="${target_repo:-$actual_repo}"
   geet_dir="${git_dir_super:-$git_dir}"
@@ -124,100 +124,100 @@ establish_environment() {
   #@ Parse arguments from CLI arguments
   while [ "$#" -ge 1 ]; do
     case "$1" in
-    -P | --path)
-      [ -d "$2" ] && {
-        geet_dir="$2"
-        shift
-      }
-      ;;
-    -p | --pull)
-      pull=1
-      ;;
-    -i | --ignore)
-      ignore=1
-      ;;
-    -D | --diff)
-      diff=1
-      ;;
-    -s | --status)
-      status=1
-      ;;
-    -a | --add)
-      add=1
-      ;;
-    -c | --commit)
-      commit=1
-      [ "$2" ] && {
+      -P | --path)
+        [ -d "$2" ] && {
+          geet_dir="$2"
+          shift
+        }
+        ;;
+      -p | --pull)
+        pull=1
+        ;;
+      -i | --ignore)
+        ignore=1
+        ;;
+      -D | --diff)
+        diff=1
+        ;;
+      -s | --status)
+        status=1
+        ;;
+      -a | --add)
+        add=1
+        ;;
+      -c | --commit)
+        commit=1
+        [ "$2" ] && {
+          msg="$2"
+          shift
+        }
+        ;;
+      -u | --push)
+        push=1
+        ;;
+      -R | --sub* | --recurse)
+        recurse=1
+        [ "$2" ] && {
+          submodule="$2"
+          shift
+        }
+        ;;
+      -q | --quiet)
+        unset verbose
+        ;;
+      --gitisuper | --git-dir-super)
+        get_geet_dir=1
+        ;;
+      --gitis | --git-dir)
+        get_git_dir=1
+        ;;
+      -h | --help)
+        display_info --usage
+        ;;
+      -v | --version)
+        display_info --version
+        ;;
+      -vv | --verbose)
+        verbose=1
+        ;;
+      -d | --debug)
+        debug=1
+        ;;
+      -m | --m*)
         msg="$2"
-        shift
-      }
-      ;;
-    -u | --push)
-      push=1
-      ;;
-    -R | --sub* | --recurse)
-      recurse=1
-      [ "$2" ] && {
-        submodule="$2"
-        shift
-      }
-      ;;
-    -q | --quiet)
-      unset verbose
-      ;;
-    --gitisuper | --git-dir-super)
-      get_geet_dir=1
-      ;;
-    --gitis | --git-dir)
-      get_git_dir=1
-      ;;
-    -h | --help)
-      display_info --usage
-      ;;
-    -v | --version)
-      display_info --version
-      ;;
-    -vv | --verbose)
-      verbose=1
-      ;;
-    -d | --debug)
-      debug=1
-      ;;
-    -m | --m*)
-      msg="$2"
-      ;;
-    --ci) ci=1 ;;
-    -*) ;;
-      # TODO: Add support for initalization
-      # --key)
-      # 	[ "$2" ] || display_info --error "SSH Key required"
-      # 	key="$2"
-      # 	;;
-      # -r | --repo)
-      # 	[ "$2" ] || display_info --error \
-      # 		"Git repository required"
-      # 	target_repo="$2"
-      # 	;;
-      # --user)
-      # 	[ "$2" ] ||
-      # 		display_info --error \
-      # 			"A git repository url is required"
-      # 	user="$2"
-      # 	;;
-      # --email)
-      # 	[ "$2" ] ||
-      # 		display_info --error \
-      # 			Aye"A git repository url is required"
-      # 	email="$2"
-      # 	;;
-      # --dir)
-      # 	[ "$2" ] || display_info --error \
-      # 		"A local git directory is required"
-      # 	dir="$2"
-      # ;;
-    *)
-      msg="$1"
-      ;;
+        ;;
+      --ci) ci=1 ;;
+      -*) ;;
+        # TODO: Add support for initalization
+        # --key)
+        # 	[ "$2" ] || display_info --error "SSH Key required"
+        # 	key="$2"
+        # 	;;
+        # -r | --repo)
+        # 	[ "$2" ] || display_info --error \
+        # 		"Git repository required"
+        # 	target_repo="$2"
+        # 	;;
+        # --user)
+        # 	[ "$2" ] ||
+        # 		display_info --error \
+        # 			"A git repository url is required"
+        # 	user="$2"
+        # 	;;
+        # --email)
+        # 	[ "$2" ] ||
+        # 		display_info --error \
+        # 			Aye"A git repository url is required"
+        # 	email="$2"
+        # 	;;
+        # --dir)
+        # 	[ "$2" ] || display_info --error \
+        # 		"A local git directory is required"
+        # 	dir="$2"
+        # ;;
+      *)
+        msg="$1"
+        ;;
     esac
 
     shift
@@ -235,8 +235,8 @@ establish_validators() {
 
     #@ Validate dependencies as executable files
     for dependency in $(parse_alnum "$_cmd_DEPENDENCIES"); do
-      command -v "$dependency" >/dev/null 2>&1 ||
-        if [ "$missing_deps" ]; then
+      command -v "$dependency" > /dev/null 2>&1 \
+        || if [ "$missing_deps" ]; then
           missing_deps="$missing_deps, $dependency"
         else
           missing_deps="$dependency"
@@ -248,8 +248,8 @@ establish_validators() {
 
     #@ Count the number of missing dependencies
     missing_deps_count="$(
-      printf "%s\n" "$missing_deps" |
-        tr ',' '\n' | wc -l
+      printf "%s\n" "$missing_deps" \
+        | tr ',' '\n' | wc -l
     )"
 
     #@ Update the error message based on the count
@@ -335,14 +335,14 @@ establish_validators() {
       read -r response
 
       case "$response" in
-      [yY])
-        return 0
-        ;;
-      *)
-        logline --error \
-          "Invalid Submodule. See valid submodules" "$@"
-        exit 1
-        ;;
+        [yY])
+          return 0
+          ;;
+        *)
+          logline --error \
+            "Invalid Submodule. See valid submodules" "$@"
+          exit 1
+          ;;
       esac
     fi
 
@@ -364,7 +364,7 @@ establish_utilities() {
     paragraph=""
     delimiter=" |> "
 
-    if type notify-send >/dev/null 2>&1; then
+    if type notify-send > /dev/null 2>&1; then
       notifier="notify-send"
     fi
 
@@ -373,110 +373,110 @@ establish_utilities() {
 
     #@ Tag the last line to prevent printing a blank line
     case "$@" in
-    *"-last"* | *"-l"* | *"-fatal"*)
-      last_line=1
-      ;;
-    *"--new"* | *"-n"*)
-      unset last_line
-      ;;
+      *"-last"* | *"-l"* | *"-fatal"*)
+        last_line=1
+        ;;
+      *"--new"* | *"-n"*)
+        unset last_line
+        ;;
     esac
 
     #@ Parse options
     while [ "$#" -ge 1 ]; do
       case "$1" in
-      --info | --error | --warn*)
-        special=1
-        case "$1" in
-        --info)
-          [ "$verbose" ] && label="INFO: "
-          code="${code:-0}"
-          ;;
-        --warn*)
-          label="WARN: "
-          code="${code:-1}"
-          ;;
-        --error)
-          label="ERROR: "
-          code="${code:-1}"
-          ;;
-        esac
+        --info | --error | --warn*)
+          special=1
+          case "$1" in
+            --info)
+              [ "$verbose" ] && label="INFO: "
+              code="${code:-0}"
+              ;;
+            --warn*)
+              label="WARN: "
+              code="${code:-1}"
+              ;;
+            --error)
+              label="ERROR: "
+              code="${code:-1}"
+              ;;
+          esac
 
-        [ "$#" -eq 2 ] && info="${label}${2}"
-        [ "$#" -gt 2 ] && {
-          label="${label}${2}"
-          info="${label}${delimiter}${3}"
+          [ "$#" -eq 2 ] && info="${label}${2}"
+          [ "$#" -gt 2 ] && {
+            label="${label}${2}"
+            info="${label}${delimiter}${3}"
 
-          #@ Generate padding to place before each info
-          len_label="${#label}"
-          len_delim="${#delimiter}"
-          padding_length=$((len_label + len_delim))
-          info_padding="$(printf "%-${padding_length}s")"
+            #@ Generate padding to place before each info
+            len_label="${#label}"
+            len_delim="${#delimiter}"
+            padding_length=$((len_label + len_delim))
+            info_padding="$(printf "%-${padding_length}s")"
 
-          #@ Append additional info with leading padding and new line
-          while [ "$#" -gt 3 ]; do
-            case "$4" in -*) break ;; esac
-            info="$(printf "%s\n%s%s" "$info" "$info_padding" "$4")"
+            #@ Append additional info with leading padding and new line
+            while [ "$#" -gt 3 ]; do
+              case "$4" in -*) break ;; esac
+              info="$(printf "%s\n%s%s" "$info" "$info_padding" "$4")"
+              shift
+            done
+          }
+          ;;
+        --code)
+          special=1
+          case "$2" in '' | *[!0-9]*) code=1 ;; *) code="$2" ;; esac
+          ;;
+        --fatal)
+          special=1
+          fatal=1
+          case "$2" in '' | *[!0-9]*) code=1 ;; *) code="$2" ;; esac
+          ;;
+        --note)
+          special=1
+          info="Note: "
+          while [ "$#" -gt 1 ]; do
+            case "$2" in -*) break ;; esac
+            info="${info}${2}"
             shift
           done
-        }
-        ;;
-      --code)
-        special=1
-        case "$2" in '' | *[!0-9]*) code=1 ;; *) code="$2" ;; esac
-        ;;
-      --fatal)
-        special=1
-        fatal=1
-        case "$2" in '' | *[!0-9]*) code=1 ;; *) code="$2" ;; esac
-        ;;
-      --note)
-        special=1
-        info="Note: "
-        while [ "$#" -gt 1 ]; do
-          case "$2" in -*) break ;; esac
-          info="${info}${2}"
-          shift
-        done
-        ;;
-      --notify) notify=1 ;;
-      --delim*)
-        delimiter="$(printf "%s" "$2")"
-        ;;
-      -l | --last | --line-last) ;;
-      -n | --line | --line-new)
-        [ "$2" ] && {
-          info="$(printf "%s\n%s" "$info" "$2")"
-          shift
-        }
-        ;;
-      -p | --paragraph)
-        [ "$2" ] && {
-          info="$(printf "%s\n%s" "$info" "$2")"
-          shift
-        }
-        paragraph=1
-        ;;
-      -s | --space)
-        [ "$2" ] && {
-          info="$(printf "%s %s" "$info" "$2")"
-          shift
-        }
-        ;;
-      -j | --join)
-        [ "$2" ] && {
-          info="$(printf "%s%s" "$info" "$2")"
-          shift
-        }
-        ;;
-      -*) ;;
-      *)
-        [ "$special" ] ||
-          if [ "$info" ]; then
-            info="${info} ${1}"
-          else
-            info="$1"
-          fi
-        ;;
+          ;;
+        --notify) notify=1 ;;
+        --delim*)
+          delimiter="$(printf "%s" "$2")"
+          ;;
+        -l | --last | --line-last) ;;
+        -n | --line | --line-new)
+          [ "$2" ] && {
+            info="$(printf "%s\n%s" "$info" "$2")"
+            shift
+          }
+          ;;
+        -p | --paragraph)
+          [ "$2" ] && {
+            info="$(printf "%s\n%s" "$info" "$2")"
+            shift
+          }
+          paragraph=1
+          ;;
+        -s | --space)
+          [ "$2" ] && {
+            info="$(printf "%s %s" "$info" "$2")"
+            shift
+          }
+          ;;
+        -j | --join)
+          [ "$2" ] && {
+            info="$(printf "%s%s" "$info" "$2")"
+            shift
+          }
+          ;;
+        -*) ;;
+        *)
+          [ "$special" ] \
+            || if [ "$info" ]; then
+              info="${info} ${1}"
+            else
+              info="$1"
+            fi
+          ;;
       esac
       shift
     done
@@ -496,33 +496,33 @@ establish_utilities() {
   display_info() {
     while [ "$#" -ge 1 ]; do
       case "$1" in
-      --usage)
-        logline "$_cmd_USAGEGUIDE"
-        exit=1
-        ;;
-      --version)
-        logline "$_cmd_VERSION"
-        exit=1
-        ;;
-      --error*)
-        exit=1
-        [ "$verbose" ] && return
-        case "$1" in
-        *path) printf "Invalid path: %s" "$2" ;;
-        *sym) printf "Circular symbolic link: %s" "$2" ;;
-        *info) printf "Invalid verbosity level: %s" "$2" ;;
-        *arg) printf "<target_path> required \nUsage: %s\n" "$_cmd_USAGE" ;;
-        *opt) printf "Unrecognized option: %s" "$2" ;;
-        *cd) printf "Change directory operation failed" ;;
-        esac
-        ;;
-      # --error)
-      #   code="$2" && shift 2
-      #   logline --error "$@" -ll
-      #   exit=1
-      #   ;;
-      --code) code="$2" ;;
-      *) logline --info "$@" -ll ;;
+        --usage)
+          logline "$_cmd_USAGEGUIDE"
+          exit=1
+          ;;
+        --version)
+          logline "$_cmd_VERSION"
+          exit=1
+          ;;
+        --error*)
+          exit=1
+          [ "$verbose" ] && return
+          case "$1" in
+            *path) printf "Invalid path: %s" "$2" ;;
+            *sym) printf "Circular symbolic link: %s" "$2" ;;
+            *info) printf "Invalid verbosity level: %s" "$2" ;;
+            *arg) printf "<target_path> required \nUsage: %s\n" "$_cmd_USAGE" ;;
+            *opt) printf "Unrecognized option: %s" "$2" ;;
+            *cd) printf "Change directory operation failed" ;;
+          esac
+          ;;
+        # --error)
+        #   code="$2" && shift 2
+        #   logline --error "$@" -ll
+        #   exit=1
+        #   ;;
+        --code) code="$2" ;;
+        *) logline --info "$@" -ll ;;
       esac
       shift
     done
@@ -537,10 +537,10 @@ establish_utilities() {
     #@ Input validation
     while [ "$#" -gt 0 ]; do
       case "$1" in
-      --get-home) get_home=1 ;;
-      --get-name) get_name=1 ;;
-      --path | --target) _path="$2" ;;
-      *) _path="$1" ;;
+        --get-home) get_home=1 ;;
+        --get-name) get_name=1 ;;
+        --path | --target) _path="$2" ;;
+        *) _path="$1" ;;
       esac
       shift
     done
@@ -550,7 +550,7 @@ establish_utilities() {
 
     #@ Change to directory containing the link/file
     #@ Get absolute path of the directory
-    _dir="$(cd "$_dir" 2>/dev/null && pwd)" || return 1
+    _dir="$(cd "$_dir" 2> /dev/null && pwd)" || return 1
 
     #@ Resolve symbolic links recursively
     while [ -L "$_dir/$_name" ]; do
@@ -560,20 +560,20 @@ establish_utilities() {
           -maxdepth 1 \
           -name "$_name" \
           -printf "%l\n" \
-          2>/dev/null
+          2> /dev/null
       )"
       [ "$_target" ] || break
 
       #@ Handle relative vs absolute paths in symlink target
       case "$_target" in
-      /*) #@ Absolute path
-        _dir="$(dirname "$_target")"
-        _name="$(basename "$_target")"
-        ;;
-      *) #@ Relative path
-        _dir="$(cd "$_dir" && cd "$(dirname "$_target")" && pwd)"
-        _name="$(basename "$_target")"
-        ;;
+        /*) #@ Absolute path
+          _dir="$(dirname "$_target")"
+          _name="$(basename "$_target")"
+          ;;
+        *) #@ Relative path
+          _dir="$(cd "$_dir" && cd "$(dirname "$_target")" && pwd)"
+          _name="$(basename "$_target")"
+          ;;
       esac
     done
 
@@ -596,20 +596,20 @@ establish_utilities() {
     url="$1"
 
     case "$url" in
-    *://*:*@*) # URLs with credentials like https://user:pass@host
-      printf '%s' "${url}" | sed -E 's/(.*:)[^@]*(@.*)/\1*****\2/'
-      ;;
-    *@*) # SSH URLs like git@github.com:user/repo.git
-      #TODO: This is not working
-      printf '%s' "${url}" | sed -E 's/(@[^:]*):(.*)/@\1:\2/'
-      ;;
-    *) # Plain URLs like https://github.com/user/repo.git or relative paths
-      printf '%s' "${url}"
-      ;;
+      *://*:*@*) # URLs with credentials like https://user:pass@host
+        printf '%s' "${url}" | sed -E 's/(.*:)[^@]*(@.*)/\1*****\2/'
+        ;;
+      *@*) # SSH URLs like git@github.com:user/repo.git
+        #TODO: This is not working
+        printf '%s' "${url}" | sed -E 's/(@[^:]*):(.*)/@\1:\2/'
+        ;;
+      *) # Plain URLs like https://github.com/user/repo.git or relative paths
+        printf '%s' "${url}"
+        ;;
     esac
   }
   work_in() {
-    cd "$1" >/dev/null 2>&1 || {
+    cd "$1" > /dev/null 2>&1 || {
       logline --error \
         "Failed to access the directory" \
         "$1"
@@ -620,15 +620,15 @@ establish_utilities() {
   run_in_dir() {
     while [ "$#" -ge 1 ]; do
       case "$1" in
-      --return) return_dir="$2" ;;
-      --target) target_dir="$2" ;;
-      --command) cmd="$2" ;;
+        --return) return_dir="$2" ;;
+        --target) target_dir="$2" ;;
+        --command) cmd="$2" ;;
       esac
       shift
     done
 
     cd_to() {
-      cd "$1" >/dev/null 2>&1 || {
+      cd "$1" > /dev/null 2>&1 || {
         logline --error \
           "Failed to access the directory" \
           "$1"
@@ -655,7 +655,7 @@ execute_git_actions() {
   [ -n "$ignore" ] && git rm -r --force --cached .
 
   #@ Skip if there are no changes
-  git status --porcelain >/dev/null 2>&1 || return 0
+  git status --porcelain > /dev/null 2>&1 || return 0
 
   #@ Lint
   # treefmt_wrapper || return 1
@@ -681,10 +681,10 @@ execute_git_actions() {
 }
 
 update_message() {
-  last_msg="$(git log >/dev/null 2>&1 && eval git log "$log_fmt")"
+  last_msg="$(git log > /dev/null 2>&1 && eval git log "$log_fmt")"
   default_msg="${last_msg:-"$default_msg"}"
-  [ "$msg" ] ||
-    if [ "$debug" ]; then
+  [ "$msg" ] \
+    || if [ "$debug" ]; then
       msg="$default_msg"
     else
       printf "Enter a commit message [Default: %s ]: " "$default_msg" && read -r msg
diff --git a/Bin/shellscript/project/git/geet_with_deps b/Bin/shellscript/project/git/geet_with_deps
--- a/Bin/shellscript/project/git/geet_with_deps
+++ b/Bin/shellscript/project/git/geet_with_deps
@@ -15,7 +15,7 @@ establish_metadata() {
   _cmd_DESCRIPTION="Simplifies the git update process"
   _cmd_DEPENDENCIES="git"
   _cmd_USAGEGUIDE="$(
-    cat <<USAGE_GUIDE
+    cat << USAGE_GUIDE
 ::------------------------------------------------------------::
                           $_cmd_NAME ($_cmd_VERSION)
 ::------------------------------------------------------------::
@@ -87,14 +87,14 @@ establish_defaults() {
   verbose="${verbose:-true}"
 
   # | Paths
-  git rev-parse --show-superproject-working-tree >/dev/null 2>&1 &&
-    git_dir_super="$(git rev-parse --show-superproject-working-tree)"
+  git rev-parse --show-superproject-working-tree > /dev/null 2>&1 \
+    && git_dir_super="$(git rev-parse --show-superproject-working-tree)"
 
-  git rev-parse --show-toplevel >/dev/null 2>&1 &&
-    git_dir="$(git rev-parse --show-toplevel)"
+  git rev-parse --show-toplevel > /dev/null 2>&1 \
+    && git_dir="$(git rev-parse --show-toplevel)"
 
-  git remote get-url origin >/dev/null 2>&1 &&
-    actual_repo="$(git remote get-url origin)"
+  git remote get-url origin > /dev/null 2>&1 \
+    && actual_repo="$(git remote get-url origin)"
 
   target_repo="${target_repo:-$actual_repo}"
   geet_dir="${git_dir_super:-$git_dir}"
@@ -116,94 +116,94 @@ establish_environment() {
   # | Parse arguments from CLI arguments
   while [ "$#" -ge 1 ]; do
     case "$1" in
-    -p | --pull)
-      pull=true
-      ;;
-    -i | --ignore)
-      ignore=true
-      ;;
-    -D | --diff)
-      diff=true
-      ;;
-    -s | --status)
-      status=true
-      ;;
-    -a | --add)
-      add=true
-      ;;
-    -c | --commit)
-      commit=true
-      [ "$2" ] && {
+      -p | --pull)
+        pull=true
+        ;;
+      -i | --ignore)
+        ignore=true
+        ;;
+      -D | --diff)
+        diff=true
+        ;;
+      -s | --status)
+        status=true
+        ;;
+      -a | --add)
+        add=true
+        ;;
+      -c | --commit)
+        commit=true
+        [ "$2" ] && {
+          msg="$2"
+          shift
+        }
+        ;;
+      -u | --push)
+        push=true
+        ;;
+      -R | --sub* | --recurse)
+        recurse=true
+        [ "$2" ] && {
+          submodule="$2"
+          shift
+        }
+        ;;
+      -q | --quiet)
+        unset verbose
+        ;;
+      --gitisuper)
+        get_geet_dir=true
+        ;;
+      --gitis)
+        get_git_dir=true
+        ;;
+      -h | --help)
+        display_info --usage
+        ;;
+      -v | --version)
+        display_info --version
+        ;;
+      -vv | --verbose)
+        verbose=true
+        ;;
+      -d | --debug)
+        debug=true
+        ;;
+      -m | --m*)
         msg="$2"
-        shift
-      }
-      ;;
-    -u | --push)
-      push=true
-      ;;
-    -R | --sub* | --recurse)
-      recurse=true
-      [ "$2" ] && {
-        submodule="$2"
-        shift
-      }
-      ;;
-    -q | --quiet)
-      unset verbose
-      ;;
-    --gitisuper)
-      get_geet_dir=true
-      ;;
-    --gitis)
-      get_git_dir=true
-      ;;
-    -h | --help)
-      display_info --usage
-      ;;
-    -v | --version)
-      display_info --version
-      ;;
-    -vv | --verbose)
-      verbose=true
-      ;;
-    -d | --debug)
-      debug=true
-      ;;
-    -m | --m*)
-      msg="$2"
-      ;;
-    --ci) ci=true ;;
-    -*) ;;
-      # TODO: Add support for initalization
-      # --key)
-      # 	[ "$2" ] || display_info --error "SSH Key required"
-      # 	key="$2"
-      # 	;;
-      # -r | --repo)
-      # 	[ "$2" ] || display_info --error \
-      # 		"Git repository required"
-      # 	target_repo="$2"
-      # 	;;
-      # --user)
-      # 	[ "$2" ] ||
-      # 		display_info --error \
-      # 			"A git repository url is required"
-      # 	user="$2"
-      # 	;;
-      # --email)
-      # 	[ "$2" ] ||
-      # 		display_info --error \
-      # 			Aye"A git repository url is required"
-      # 	email="$2"
-      # 	;;
-      # --dir)
-      # 	[ "$2" ] || display_info --error \
-      # 		"A local git directory is required"
-      # 	dir="$2"
-      # ;;
-    *)
-      msg="$1"
-      ;;
+        ;;
+      --ci) ci=true ;;
+      -*) ;;
+        # TODO: Add support for initalization
+        # --key)
+        # 	[ "$2" ] || display_info --error "SSH Key required"
+        # 	key="$2"
+        # 	;;
+        # -r | --repo)
+        # 	[ "$2" ] || display_info --error \
+        # 		"Git repository required"
+        # 	target_repo="$2"
+        # 	;;
+        # --user)
+        # 	[ "$2" ] ||
+        # 		display_info --error \
+        # 			"A git repository url is required"
+        # 	user="$2"
+        # 	;;
+        # --email)
+        # 	[ "$2" ] ||
+        # 		display_info --error \
+        # 			Aye"A git repository url is required"
+        # 	email="$2"
+        # 	;;
+        # --dir)
+        # 	[ "$2" ] || display_info --error \
+        # 		"A local git directory is required"
+        # 	dir="$2"
+        # ;;
+      *)
+        msg="$1"
+        ;;
     esac
 
     shift
@@ -224,8 +224,8 @@ validate_dependencies() {
 
   # | Validate dependencies as executable files
   for dependency in $_cmd_DEPENDENCIES; do
-    pathof "$dependency" --is-executable ||
-      if [ -n "$missing_deps" ]; then
+    pathof "$dependency" --is-executable \
+      || if [ -n "$missing_deps" ]; then
         missing_deps="$missing_deps, $dependency"
       else
         missing_deps="$dependency"
@@ -237,8 +237,8 @@ validate_dependencies() {
 
   # | Count the number of missing dependencies
   missing_deps_count="$(
-    printf "%s\n" "$missing_deps" |
-      tr ',' '\n' | wc -l
+    printf "%s\n" "$missing_deps" \
+      | tr ',' '\n' | wc -l
   )"
 
   # | Update the error message based on the count
@@ -325,14 +325,14 @@ validate_submodules() {
     read -r response
 
     case "$response" in
-    [yY])
-      return 0
-      ;;
-    *)
-      console_log --error \
-        "Invalid Submodule. See valid submodules" "$@"
-      exit 1
-      ;;
+      [yY])
+        return 0
+        ;;
+      *)
+        console_log --error \
+          "Invalid Submodule. See valid submodules" "$@"
+        exit 1
+        ;;
     esac
   fi
 
@@ -344,20 +344,20 @@ validate_submodules() {
 display_info() {
   while [ "$#" -ge 1 ]; do
     case "$1" in
-    --usage)
-      console_log --ll "$_cmd_USAGEGUIDE"
-      exit=true
-      ;;
-    --version)
-      console_log --ll "$_cmd_VERSION"
-      exit=true
-      ;;
-    --error)
-      code="$2" && shift 2
-      console_log --error "$@" -ll
-      exit=true
-      ;;
-    --code) code="$2" ;;
+      --usage)
+        console_log --ll "$_cmd_USAGEGUIDE"
+        exit=true
+        ;;
+      --version)
+        console_log --ll "$_cmd_VERSION"
+        exit=true
+        ;;
+      --error)
+        code="$2" && shift 2
+        console_log --error "$@" -ll
+        exit=true
+        ;;
+      --code) code="$2" ;;
     esac
     shift
   done
@@ -366,7 +366,7 @@ display_info() {
 }
 
 work_in() {
-  cd "$1" >/dev/null 2>&1 || {
+  cd "$1" > /dev/null 2>&1 || {
     console_log --error \
       "Failed to access the directory" \
       "$1"
@@ -388,8 +388,8 @@ execute_git_actions() {
   [ "$(git status --porcelain)" ] || return 0
 
   # | Lint
-  type treefmt >/dev/null 2>&1 &&
-    if [ "$ci" ]; then
+  type treefmt > /dev/null 2>&1 \
+    && if [ "$ci" ]; then
       treefmt --no-cache --fail-on-change || return 1
       # TODO: There is a --ci flag in treefmt that simplifies this, check and use it
     else
diff --git a/Bin/shellscript/project/ruby/ruby_gc b/Bin/shellscript/project/ruby/ruby_gc
--- a/Bin/shellscript/project/ruby/ruby_gc
+++ b/Bin/shellscript/project/ruby/ruby_gc
@@ -7,21 +7,21 @@ gem=""
 # Parse options
 while [ "$#" -gt 0 ]; do
   case $2 in
-  -f | --force)
-    force=true
-    ;;
-  -A | --all)
-    uninstall_all=true
-    ;;
-  -g | --gem)
-    gem="$2"
-    uninstall_all=false
-    ;;
-  -*)
-    printf "Invalid option: %s\n" "$2" >&2
-    exit 1
-    ;;
-  *) gem="$1" ;;
+    -f | --force)
+      force=true
+      ;;
+    -A | --all)
+      uninstall_all=true
+      ;;
+    -g | --gem)
+      gem="$2"
+      uninstall_all=false
+      ;;
+    -*)
+      printf "Invalid option: %s\n" "$2" >&2
+      exit 1
+      ;;
+    *) gem="$1" ;;
   esac
 done
 
diff --git a/Bin/shellscript/utility/kwote b/Bin/shellscript/utility/kwote
--- a/Bin/shellscript/utility/kwote
+++ b/Bin/shellscript/utility/kwote
@@ -11,29 +11,29 @@ qm="'"
 # Parse the command-line options
 while [ $# -gt 0 ]; do
   case "$1" in
-  -s | --single) qm="'" ;;
-  -d | --double) qm='"' ;;
-  -b | --backtick) qm='`' ;;
-  -c | --code) qm='```' ;;
-  -t | --tilde) qm="~" ;;
-  -a | --at) qm="@" ;;
-  -H | --hash) qm="#" ;;
-  -h | --help)
-    usage
-    exit 0
-    ;;
-  --) # End of options
-    shift
-    break
-    ;;
-  -*)
-    printf "%s: invalid option -- '%s'\n" "$0" "${1#-}" >&2
-    usage >&2
-    exit 1
-    ;;
-  *)
-    break
-    ;;
+    -s | --single) qm="'" ;;
+    -d | --double) qm='"' ;;
+    -b | --backtick) qm='`' ;;
+    -c | --code) qm='```' ;;
+    -t | --tilde) qm="~" ;;
+    -a | --at) qm="@" ;;
+    -H | --hash) qm="#" ;;
+    -h | --help)
+      usage
+      exit 0
+      ;;
+    --) # End of options
+      shift
+      break
+      ;;
+    -*)
+      printf "%s: invalid option -- '%s'\n" "$0" "${1#-}" >&2
+      usage >&2
+      exit 1
+      ;;
+    *)
+      break
+      ;;
   esac
   shift
 done
diff --git a/Bin/shellscript/utility/output/pad b/Bin/shellscript/utility/output/pad
--- a/Bin/shellscript/utility/output/pad
+++ b/Bin/shellscript/utility/output/pad
@@ -42,43 +42,43 @@ padding=5
 align="both"
 while [ $# -gt 0 ]; do
   case "$1" in
-  --left)
-    align="left"
-    shift
-    ;;
-  --right)
-    align="right"
-    shift
-    ;;
-  --padding)
-    if [ -n "$2" ] && [ "$2" -eq "$2" ] 2>/dev/null; then
-      padding="$2"
-      shift 2
-    else
-      printf "Error: --padding option requires a numeric value.\n" >&2
-      exit 1
-    fi
-    ;;
-  *)
-    input_text="$1"
-    shift
-    ;;
+    --left)
+      align="left"
+      shift
+      ;;
+    --right)
+      align="right"
+      shift
+      ;;
+    --padding)
+      if [ -n "$2" ] && [ "$2" -eq "$2" ] 2> /dev/null; then
+        padding="$2"
+        shift 2
+      else
+        printf "Error: --padding option requires a numeric value.\n" >&2
+        exit 1
+      fi
+      ;;
+    *)
+      input_text="$1"
+      shift
+      ;;
   esac
 done
 
 # Print the text with the specified alignment and padding
 case "$align" in
-left)
-  print_with_padding "$input_text" "$padding"
-  ;;
-right)
-  print_with_padding "$input_text" "$padding"
-  ;;
-both)
-  print_with_padding "$input_text" "$padding"
-  ;;
-*)
-  printf "Error: Invalid alignment option.\n" >&2
-  exit 1
-  ;;
+  left)
+    print_with_padding "$input_text" "$padding"
+    ;;
+  right)
+    print_with_padding "$input_text" "$padding"
+    ;;
+  both)
+    print_with_padding "$input_text" "$padding"
+    ;;
+  *)
+    printf "Error: Invalid alignment option.\n" >&2
+    exit 1
+    ;;
 esac
diff --git a/Bin/shellscript/utility/output/pout-repeat b/Bin/shellscript/utility/output/pout-repeat
--- a/Bin/shellscript/utility/output/pout-repeat
+++ b/Bin/shellscript/utility/output/pout-repeat
@@ -18,7 +18,7 @@ set_defaults() {
 }
 
 is_valid_num() {
-  validate --positive "$1" >/dev/null 2>&1
+  validate --positive "$1" > /dev/null 2>&1
 }
 
 print_guide() {
@@ -43,23 +43,23 @@ print_guide() {
 print_usage() {
   while [ "$#" -ge 1 ]; do
     case "$1" in
-    --args)
-      msg="$(
-        printf "Incorrect number of arguments. " >&2
-        printf "Expected at least %s but got %s\n" "${expected_args}" "$2" >&2
-      )"
-      ;;
-    --pos)
-      msg="$(
-        printf "Unable to distinguih the pattern from the number of repetitions\n" >&2
-      )"
-      ;;
-    --reps)
-      msg="$(printf "Number of repetitions not defined\n" >&2)"
-      ;;
-    *)
-      exit_code="${1:-1}"
-      ;;
+      --args)
+        msg="$(
+          printf "Incorrect number of arguments. " >&2
+          printf "Expected at least %s but got %s\n" "${expected_args}" "$2" >&2
+        )"
+        ;;
+      --pos)
+        msg="$(
+          printf "Unable to distinguih the pattern from the number of repetitions\n" >&2
+        )"
+        ;;
+      --reps)
+        msg="$(printf "Number of repetitions not defined\n" >&2)"
+        ;;
+      *)
+        exit_code="${1:-1}"
+        ;;
     esac
     shift
   done
@@ -86,9 +86,9 @@ parse_arguments() {
   #@ Script Options
   for arg in "$@"; do
     case "${arg}" in
-    -h) print_usage 0 ;;
-    --help) print_guide ;;
-    *) ;;
+      -h) print_usage 0 ;;
+      --help) print_guide ;;
+      *) ;;
     esac
   done
 
@@ -98,41 +98,41 @@ parse_arguments() {
   #@ Process Options
   while [ "$#" -ge 1 ]; do
     case "$1" in
-    -d | --verbose | --debug)
-      debug=1
-      ;;
-    -n | --num* | -r | --rep*)
-      is_valid_num "$2" || print_usage --reps
-      repetitions="$2"
-      shift
-      ;;
-    -p | --pat* | -c | --char* | --str*)
-      [ -n "$2" ] || print_usage --args
-      pattern="$2"
-      shift
-      ;;
-    -l | --line)
-      pattern="\n"
-      repetitions="${2:-1}"
-      break
-      ;;
-    -s | --space)
-      pattern=" "
-      repetitions="${2:-1}"
-      break
-      ;;
-    *)
-      #@ Handle positional arguments
-      if [ -z "${repetitions}" ] && [ -z "${pattern}" ]; then
-        if is_valid_num "$1"; then
-          pattern="$2"
-          repetitions="$1"
-        elif is_valid_num "$2"; then
-          pattern="$1"
-          repetitions="$2"
+      -d | --verbose | --debug)
+        debug=1
+        ;;
+      -n | --num* | -r | --rep*)
+        is_valid_num "$2" || print_usage --reps
+        repetitions="$2"
+        shift
+        ;;
+      -p | --pat* | -c | --char* | --str*)
+        [ -n "$2" ] || print_usage --args
+        pattern="$2"
+        shift
+        ;;
+      -l | --line)
+        pattern="\n"
+        repetitions="${2:-1}"
+        break
+        ;;
+      -s | --space)
+        pattern=" "
+        repetitions="${2:-1}"
+        break
+        ;;
+      *)
+        #@ Handle positional arguments
+        if [ -z "${repetitions}" ] && [ -z "${pattern}" ]; then
+          if is_valid_num "$1"; then
+            pattern="$2"
+            repetitions="$1"
+          elif is_valid_num "$2"; then
+            pattern="$1"
+            repetitions="$2"
+          fi
         fi
-      fi
-      ;;
+        ;;
     esac
     shift
   done
diff --git a/Bin/shellscript/utility/path_convert b/Bin/shellscript/utility/path_convert
--- a/Bin/shellscript/utility/path_convert
+++ b/Bin/shellscript/utility/path_convert
@@ -3,7 +3,7 @@
 
 scr_name="path_convert"
 scr_usage=$(
-  cat <<HELP
+  cat << HELP
 USAGE:
   $scr_name [OPTIONS] [STRING]
 
@@ -53,32 +53,32 @@ parse_input() {
 
   while [ $# -gt 0 ]; do
     case "$1" in
-    -h | --help)
-      print_help
-      exit
-      ;;
-    -d | --verbose)
-      verbosity=2
-      ;;
-    -p | --prefix)
-      input_prefix="$2"
-      shift
-      ;;
-    -c | --clip)
-      clip=true
-      ;;
-    -q | --quiet)
-      verbosity=0
-      ;;
-    *)
-      if [ "$1" ]; then
-        input_path="$1"
-        input_path_type="$(get_path_type "$input_path")"
-      else
-        printf "%s\n" "$scr_usage"
-        exit 1
-      fi
-      ;;
+      -h | --help)
+        print_help
+        exit
+        ;;
+      -d | --verbose)
+        verbosity=2
+        ;;
+      -p | --prefix)
+        input_prefix="$2"
+        shift
+        ;;
+      -c | --clip)
+        clip=true
+        ;;
+      -q | --quiet)
+        verbosity=0
+        ;;
+      *)
+        if [ "$1" ]; then
+          input_path="$1"
+          input_path_type="$(get_path_type "$input_path")"
+        else
+          printf "%s\n" "$scr_usage"
+          exit 1
+        fi
+        ;;
     esac
     shift
   done
@@ -127,8 +127,8 @@ get_clean_path() {
 
 get_path_type() {
   case $1 in
-  *:*) printf "Windows" ;;
-  *) printf "Unix" ;;
+    *:*) printf "Windows" ;;
+    *) printf "Unix" ;;
   esac
 }
 
@@ -143,31 +143,31 @@ parse_path() {
 
     printf "SOURCE: %s\n" "$source_path"
     printf "FORMAT: %s\n" "$source_path_format"
-    [ "$parsed_root" ] &&
-      printf "ROOT: %s\n" "$(get_to_the_root)"
+    [ "$parsed_root" ] \
+      && printf "ROOT: %s\n" "$(get_to_the_root)"
 
   }
 
   parse_path__env() {
     while [ $# -gt 0 ]; do
       case $1 in
-      --root) parsed_root=true ;;
-      *)
-        if [ "$1" ]; then
-          source_path="$(get_clean_path "$1")"
-        else
-          printf "Missing path to parse\n"
-          return 1
-        fi
-        ;;
+        --root) parsed_root=true ;;
+        *)
+          if [ "$1" ]; then
+            source_path="$(get_clean_path "$1")"
+          else
+            printf "Missing path to parse\n"
+            return 1
+          fi
+          ;;
       esac
       shift
     done
 
     #@ Set the path format
     case "$source_path" in
-    [a-zA-Z]:*) source_path_format="Windows" ;;
-    *) source_path_format="Unix" ;;
+      [a-zA-Z]:*) source_path_format="Windows" ;;
+      *) source_path_format="Unix" ;;
     esac
 
     #@ Split the path by separators "/"
@@ -264,17 +264,17 @@ parse_path() {
 
 get_path_root() {
   case $1 in
-  --win)
-    if cd "$2" >/dev/null 2>&1; then
-      [ "$(get_path_type "$(pwd -W)")" = Windows ] &&
-        pwd -W
-    else
-      echo "Invalid path"
-      return 1
-    fi
-    ;;
-  --unix) cd "$2" && pwd ;;
-  *) cd "$1" && pwd -W ;;
+    --win)
+      if cd "$2" > /dev/null 2>&1; then
+        [ "$(get_path_type "$(pwd -W)")" = Windows ] \
+          && pwd -W
+      else
+        echo "Invalid path"
+        return 1
+      fi
+      ;;
+    --unix) cd "$2" && pwd ;;
+    *) cd "$1" && pwd -W ;;
   esac
 }
 
@@ -285,62 +285,62 @@ validate_path() {
   #@ Parse the path input
   while [ $# -gt 0 ]; do
     case "$1" in
-    -q | --quiet) quiet=true ;;
-    -w | --win*) path_type="Windows" ;;
-    -u | --unix) path_type="Unix" ;;
-    *)
-      #@ Check if the path is empty
-      if [ "$1" ]; then
-        path="$(get_clean_path "$1")"
-      else
-        msg="Missing path string"
-        exit_code=1
-        return "$exit_code"
-      fi
-      ;;
+      -q | --quiet) quiet=true ;;
+      -w | --win*) path_type="Windows" ;;
+      -u | --unix) path_type="Unix" ;;
+      *)
+        #@ Check if the path is empty
+        if [ "$1" ]; then
+          path="$(get_clean_path "$1")"
+        else
+          msg="Missing path string"
+          exit_code=1
+          return "$exit_code"
+        fi
+        ;;
     esac
     shift
   done
 
   #@ Check for Windows path then default to Unix
   case "${path_type:-$(get_path_type "$path")}" in
-  Windows)
-    #@ Validate the Windows path
-    case "$path" in
-    [A-Za-z]:*)
-      #@ Add a trailing slash if the path ends with colon (eg. C: = C:/)
-      [ "${path#"${path%?}"}" = ":" ] && path="${path}/"
-      ;;
-    *)
-      #@ Extract the drive letter (e.g., C)
-      drive=${path%%:*}
+    Windows)
+      #@ Validate the Windows path
+      case "$path" in
+        [A-Za-z]:*)
+          #@ Add a trailing slash if the path ends with colon (eg. C: = C:/)
+          [ "${path#"${path%?}"}" = ":" ] && path="${path}/"
+          ;;
+        *)
+          #@ Extract the drive letter (e.g., C)
+          drive=${path%%:*}
 
-      #@ Validate the drive letter (e.g., C)
-      if [ "$drive" ]; then
-        if [ "${#drive}" -ne 1 ]; then
-          err="Invalid drive letter length"
-        elif ! printf "%s" "$drive" |
-          grep --extended-regexp --quiet "'^[A-Za-z]$'"; then
-          err="Invalid drive letter"
-        fi
-        msg="$(printf "%s |> %s" "$err" "$path" | grep --color=always "$drive")"
-      else
-        msg="$(printf "Missing drive letter |> %s" "$path")"
-      fi
+          #@ Validate the drive letter (e.g., C)
+          if [ "$drive" ]; then
+            if [ "${#drive}" -ne 1 ]; then
+              err="Invalid drive letter length"
+            elif ! printf "%s" "$drive" \
+              | grep --extended-regexp --quiet "'^[A-Za-z]$'"; then
+              err="Invalid drive letter"
+            fi
+            msg="$(printf "%s |> %s" "$err" "$path" | grep --color=always "$drive")"
+          else
+            msg="$(printf "Missing drive letter |> %s" "$path")"
+          fi
 
-      # #@ Return an error message and exit code
-      # [ "$quiet" ] || printf "%s" "$msg"
-      exit_code=1
+          # #@ Return an error message and exit code
+          # [ "$quiet" ] || printf "%s" "$msg"
+          exit_code=1
+          ;;
+      esac
       ;;
-    esac
-    ;;
-  Unix)
-    #@ Validate the Windows path
-    #TODO Implement error checking logic.
-    # err="Unix path"
-    # printf "%s" "$err"
-    # return 1
-    ;;
+    Unix)
+      #@ Validate the Windows path
+      #TODO Implement error checking logic.
+      # err="Unix path"
+      # printf "%s" "$err"
+      # return 1
+      ;;
   esac
 
   #@ Return an error message or valid path
@@ -355,8 +355,8 @@ convert_path() {
 
   based_on_type() {
     case "$path_type" in
-    Windows) to_unix ;;
-    Unix) to_windows ;;
+      Windows) to_unix ;;
+      Unix) to_windows ;;
     esac
   }
 
@@ -375,20 +375,20 @@ convert_path() {
         fi
       done
 
-      [ "$path_root" ] ||
-        case "$(get_clean_path "$path")" in
-        home/*)
-          path_root="$(
-            get_path_root --win "$(dirname "$HOME")"
-          )"
-          # get_path_root --win "$HOME" && {
-          #   path_root="$(dirname "$HOME")"
-          #   drive_letter="$(get_path_tld "$win_home_dir")"
-          # }
+      [ "$path_root" ] \
+        || case "$(get_clean_path "$path")" in
+          home/*)
+            path_root="$(
+              get_path_root --win "$(dirname "$HOME")"
+            )"
+            # get_path_root --win "$HOME" && {
+            #   path_root="$(dirname "$HOME")"
+            #   drive_letter="$(get_path_tld "$win_home_dir")"
+            # }
 
-          # drive_letter="$path_root/${path#*home/}"
-          ;;
-          # *) drive_letter="$path" ;;
+            # drive_letter="$path_root/${path#*home/}"
+            ;;
+            # *) drive_letter="$path" ;;
         esac
     }
 
@@ -423,8 +423,8 @@ convert_path() {
     done
 
     drive="$(
-      printf "%s:" "$drive_letter" |
-        tr '[:lower:]' '[:upper:]'
+      printf "%s:" "$drive_letter" \
+        | tr '[:lower:]' '[:upper:]'
     )"
     path="${drive}${remaining_path}"
   }
@@ -440,30 +440,30 @@ convert_path() {
     else
       #@ Set the path root as the user's home directory
       case "$path" in
-      home/* | *:/home/*)
-        path_root="$(get_path_root "$HOME")"
-        path="$path_root/${path#*home/}"
-        ;;
-      *)
-        # # path="$path_root${path}"
-        # path="C:/${path}"
-        path="$(get_clean_path "$path")"
+        home/* | *:/home/*)
+          path_root="$(get_path_root "$HOME")"
+          path="$path_root/${path#*home/}"
+          ;;
+        *)
+          # # path="$path_root${path}"
+          # path="C:/${path}"
+          path="$(get_clean_path "$path")"
 
-        # Extract the drive (e.g. c: from /c:/)
-        drive="$(get_path_tld "$path")"
+          # Extract the drive (e.g. c: from /c:/)
+          drive="$(get_path_tld "$path")"
 
-        # Extract the drive letter (e.g. c from c:)
-        drive_letter="$(
-          printf "%s" "${drive%:}" | tr '[:upper:]' '[:lower:]'
-        )"
+          # Extract the drive letter (e.g. c from c:)
+          drive_letter="$(
+            printf "%s" "${drive%:}" | tr '[:upper:]' '[:lower:]'
+          )"
 
-        # Update the path and include a leading slash
-        path="${drive_letter}${path#"${drive}"}"
+          # Update the path and include a leading slash
+          path="${drive_letter}${path#"${drive}"}"
 
-        # Update the path with the prefix
-        prefix="/$(get_clean_path "${prefix:-mnt}")"
-        path="${prefix}/${path}"
-        ;;
+          # Update the path with the prefix
+          prefix="/$(get_clean_path "${prefix:-mnt}")"
+          path="${prefix}/${path}"
+          ;;
       esac
     fi
   }
@@ -485,17 +485,17 @@ parse_output() {
   fi
 
   case "$verbosity" in
-  0) ;;
-  1) ;;
-  *)
-    printf "Input Path   |> %s\n" "$input_path"
-    printf "Input Type   |> %s\n" "$input_path_type"
-    [ "$input_prefix" ] && printf "Input Prefix |> %s\n" "$input_prefix"
-    printf "Output Path  |> %s\n" "$output_path"
-    printf "Output Type  |> %s\n" "$output_path_type"
-    [ "$exit_code" -gt 0 ] && printf "Exit Code    |> %s\n" "$exit_code"
-    [ "$check_type" ] && printf "Check Type   |> %s\n" "$check_type"
-    ;;
+    0) ;;
+    1) ;;
+    *)
+      printf "Input Path   |> %s\n" "$input_path"
+      printf "Input Type   |> %s\n" "$input_path_type"
+      [ "$input_prefix" ] && printf "Input Prefix |> %s\n" "$input_prefix"
+      printf "Output Path  |> %s\n" "$output_path"
+      printf "Output Type  |> %s\n" "$output_path_type"
+      [ "$exit_code" -gt 0 ] && printf "Exit Code    |> %s\n" "$exit_code"
+      [ "$check_type" ] && printf "Check Type   |> %s\n" "$check_type"
+      ;;
   esac
 
   [ "$clip" ] && send_to_clipboard "$path"
diff --git a/Bin/shellscript/utility/path_convert1 b/Bin/shellscript/utility/path_convert1
--- a/Bin/shellscript/utility/path_convert1
+++ b/Bin/shellscript/utility/path_convert1
@@ -4,7 +4,7 @@
 scr_name="path_convert"
 scr_description="Determine the given path and convert it to work on the next OS between Windows and Unix."
 scr_usage=$(
-  cat <<'HELP'
+  cat << 'HELP'
 Usage: $scr_name [OPTIONS] [PATH to CONVERT]
 
 DESCRIPTION:
@@ -52,61 +52,61 @@ parse_input() {
 
   while [ $# -gt 0 ]; do
     case "$1" in
-    -h | --help)
-      print_help
-      exit
-      ;;
-    -d | --verbose)
-      verbosity=2
-      ;;
-    -p | --prefix)
-      prefix="$2"
-      shift
-      ;;
-    -c | --clip)
-      clip=true
-      ;;
-    -q | --quiet)
-      verbosity=0
-      ;;
-    *)
-      validate_path --quiet "$1" || exit 1
+      -h | --help)
+        print_help
+        exit
+        ;;
+      -d | --verbose)
+        verbosity=2
+        ;;
+      -p | --prefix)
+        prefix="$2"
+        shift
+        ;;
+      -c | --clip)
+        clip=true
+        ;;
+      -q | --quiet)
+        verbosity=0
+        ;;
+      *)
+        validate_path --quiet "$1" || exit 1
 
-      input_path="$(validate_path "$1")"
-      # input_path_type="$(validate_path --type "$input_path")"
+        input_path="$(validate_path "$1")"
+        # input_path_type="$(validate_path --type "$input_path")"
 
-      # # Check for path argument
-      # if [ "$1" ]; then
-      #   validate_path "$1" || exit 1
-      # else
-      #   error="Missing Path Argument"
-      #   label="Input Path"
-      #   sample="C:\\Users\\John\\.bashrc or /home/John/.bashrc"
-      #   exit_type="exit"
-      #   exit_code=1
-      #   message="$(
-      #     printf "%s Error: %s\n" "$label" "$error"
-      #     printf "Expected: Path (eg. %s )\n" "$sample"
-      #   )"
-      # Check for path argument
-      # if validate_path "$1"; then
-      #   input_path="$1"
-      #   input_path_type="$(validate_path --type "$input_path")"
-      # else
-      #   error="Missing Path Argument"
-      #   label="Input Path"
-      #   sample="C:\\Users\\John\\.bashrc or /home/John/.bashrc"
-      #   exit_type="exit"
-      #   exit_code=1
-      #   message="$(
-      #     printf "%s Error: %s\n" "$label" "$error"
-      #     printf "Expected: Path (eg. %s )\n" "$sample"
-      #   )"
+        # # Check for path argument
+        # if [ "$1" ]; then
+        #   validate_path "$1" || exit 1
+        # else
+        #   error="Missing Path Argument"
+        #   label="Input Path"
+        #   sample="C:\\Users\\John\\.bashrc or /home/John/.bashrc"
+        #   exit_type="exit"
+        #   exit_code=1
+        #   message="$(
+        #     printf "%s Error: %s\n" "$label" "$error"
+        #     printf "Expected: Path (eg. %s )\n" "$sample"
+        #   )"
+        # Check for path argument
+        # if validate_path "$1"; then
+        #   input_path="$1"
+        #   input_path_type="$(validate_path --type "$input_path")"
+        # else
+        #   error="Missing Path Argument"
+        #   label="Input Path"
+        #   sample="C:\\Users\\John\\.bashrc or /home/John/.bashrc"
+        #   exit_type="exit"
+        #   exit_code=1
+        #   message="$(
+        #     printf "%s Error: %s\n" "$label" "$error"
+        #     printf "Expected: Path (eg. %s )\n" "$sample"
+        #   )"
 
-      #   printf "%s\n" "$message"
-      #   eval "$exit_type" "$exit_code"
-      # fi
-      ;;
+        #   printf "%s\n" "$message"
+        #   eval "$exit_type" "$exit_code"
+        # fi
+        ;;
     esac
     shift
   done
@@ -122,45 +122,45 @@ validate_path() {
 
   while [ $# -gt 0 ]; do
     case "$1" in
-    --quiet) check_path=true ;;
-    --type) check_type=true ;;
-    -w | --win*) path_type="Windows" ;;
-    -u | --unix) path_type="Unix" ;;
-    *)
-      # Check for path argument
-      if [ "$1" ]; then
-        # path="$1"
-        case "$path" in
-        *\\*) path="$(printf "%s" "$1" | tr '\\' '/')" ;;
-        *//*) path="$(printf "%s" "$1" | tr -s "/")" ;;
-        !*/*)
-          printf "Slash missing in path: %s\n" "$1"
+      --quiet) check_path=true ;;
+      --type) check_type=true ;;
+      -w | --win*) path_type="Windows" ;;
+      -u | --unix) path_type="Unix" ;;
+      *)
+        # Check for path argument
+        if [ "$1" ]; then
+          # path="$1"
+          case "$path" in
+            *\\*) path="$(printf "%s" "$1" | tr '\\' '/')" ;;
+            *//*) path="$(printf "%s" "$1" | tr -s "/")" ;;
+            !*/*)
+              printf "Slash missing in path: %s\n" "$1"
+              return 1
+              ;;
+              # {
+              #   regex='^(\.|/)?[a-zA-Z0-9_-]+(/[a-zA-Z0-9_:./-]+)*$'
+              #   [ "$path" = "/" ] ||
+              #     printf "%s" "$path" |
+              #     grep --extended-regexp --quiet "$regex"
+              # } || {
+              # regex='[^a-zA-Z0-9_.:/-]'
+              # printf \
+              #   "Invalid characters found in the path: '%s'\nPath: %s\n\n" \
+              #   "$(
+              #     printf "%s" "$path" |
+              #       grep --extended-regexp --only-matching "$regex" |
+              #       uniq | tr '\n' ' '
+              #   )" \
+              #   "$path"
+              # return 1
+              # }
+              # ;;
+          esac
+        else
+          printf "Missing Path Argument"
           return 1
-          ;;
-          # {
-          #   regex='^(\.|/)?[a-zA-Z0-9_-]+(/[a-zA-Z0-9_:./-]+)*$'
-          #   [ "$path" = "/" ] ||
-          #     printf "%s" "$path" |
-          #     grep --extended-regexp --quiet "$regex"
-          # } || {
-          # regex='[^a-zA-Z0-9_.:/-]'
-          # printf \
-          #   "Invalid characters found in the path: '%s'\nPath: %s\n\n" \
-          #   "$(
-          #     printf "%s" "$path" |
-          #       grep --extended-regexp --only-matching "$regex" |
-          #       uniq | tr '\n' ' '
-          #   )" \
-          #   "$path"
-          # return 1
-          # }
-          # ;;
-        esac
-      else
-        printf "Missing Path Argument"
-        return 1
-      fi
-      ;;
+        fi
+        ;;
     esac
     shift
   done
@@ -188,17 +188,17 @@ validate_path() {
 
 parse_output() {
   case "$verbosity" in
-  0) ;;
-  1)
-    printf "%s\n" "$output_path"
-    ;;
-  *)
-    printf "Path Input: %s\n" "$input_path"
-    printf "Path Input Type: %s\n" "$input_path_type"
-    printf "Path Output: %s\n" "$output_path"
-    echo "EXIT CODE: $exit_code"
-    echo "Check Type: $check_type"
-    ;;
+    0) ;;
+    1)
+      printf "%s\n" "$output_path"
+      ;;
+    *)
+      printf "Path Input: %s\n" "$input_path"
+      printf "Path Input Type: %s\n" "$input_path_type"
+      printf "Path Output: %s\n" "$output_path"
+      echo "EXIT CODE: $exit_code"
+      echo "Check Type: $check_type"
+      ;;
   esac
 
   [ "$clip" ] && send_to_clipboard "$path"
@@ -213,10 +213,10 @@ convert_to_linux_path() {
   path="$1"
 
   case "$path" in
-  *:/*)
-    printf "Invalid windows path (%s) missing :/" "$path"
-    return 1
-    ;;
+    *:/*)
+      printf "Invalid windows path (%s) missing :/" "$path"
+      return 1
+      ;;
   esac
 
   # Replace backslashes with forward slashes
@@ -237,8 +237,8 @@ convert_to_linux_path() {
 
   # Check if the drive letter contains only one letter and has a length of 1
   if
-    [ "${#drive}" -eq 1 ] &&
-      printf "%s" "$drive" | grep -Eq '^[A-Za-z]$'
+    [ "${#drive}" -eq 1 ] \
+      && printf "%s" "$drive" | grep -Eq '^[A-Za-z]$'
   then
     # Remove the colon from the drive letter
     drive=${drive%:}
@@ -322,8 +322,9 @@ validate_nix_path() {
   path=${path%/} # Remove trailing slash
   path=/${path}  # Re-add leading slash
   path=$(
-    printf "%s" "$path" |
-      tr '\\' '/' |
+    printf "%s" "$path" \
+      | tr '\\' '/' \
+      |
       # Convert backslashes to forward slashes
       tr -s "/" # Remove repeated slashes
   )
@@ -334,9 +335,9 @@ validate_nix_path() {
   regex='^(\.|/)?[a-zA-Z0-9_-]+(/[a-zA-Z0-9_./-]+)*$'
 
   if
-    [ "$path" = "/" ] ||
-      printf "%s" "$path" |
-      grep --extended-regexp --quiet "$regex"
+    [ "$path" = "/" ] \
+      || printf "%s" "$path" \
+      | grep --extended-regexp --quiet "$regex"
   then
     # Return the valid path
     printf "%s\n" "$path"
@@ -345,9 +346,9 @@ validate_nix_path() {
     regex='[^a-zA-Z0-9_./-]'
 
     invalid_chars=$(
-      printf "%s" "$path" |
-        grep --extended-regexp --only-matching "$regex" |
-        uniq | tr '\n' ' '
+      printf "%s" "$path" \
+        | grep --extended-regexp --only-matching "$regex" \
+        | uniq | tr '\n' ' '
     )
     printf \
       "Invalid characters found in the path: '%s'\nPath: %s\n" \
@@ -373,8 +374,9 @@ validate_win_path() {
   if printf "%s" "$path" | grep --quiet '\\//'; then
     #@ Manage problematic slashes
     path=$(
-      printf "%s" "$path" |
-        tr '\\' '/' |
+      printf "%s" "$path" \
+        | tr '\\' '/' \
+        |
         # Convert backslashes to forward slashes
         tr -s "/" # Remove repeated slashes
     )
@@ -420,9 +422,9 @@ validate_win_path() {
   regex='^/[A-Za-z]:/'
 
   if
-    [ "$path" = "/" ] ||
-      printf "%s" "$path" |
-      grep --extended-regexp --quiet "$regex"
+    [ "$path" = "/" ] \
+      || printf "%s" "$path" \
+      | grep --extended-regexp --quiet "$regex"
   then
     # Return the valid path
     printf "%s\n" "$path"
@@ -433,9 +435,9 @@ validate_win_path() {
     printf \
       "Invalid characters found in the path: '%s'\nPath: %s\n\n" \
       "$(
-        printf "%s" "$path" |
-          grep --extended-regexp --only-matching "$regex" |
-          uniq | tr '\n' ' '
+        printf "%s" "$path" \
+          | grep --extended-regexp --only-matching "$regex" \
+          | uniq | tr '\n' ' '
       )" \
       "$path"
     return 1
diff --git a/Bin/shellscript/utility/path_convert4 b/Bin/shellscript/utility/path_convert4
--- a/Bin/shellscript/utility/path_convert4
+++ b/Bin/shellscript/utility/path_convert4
@@ -3,7 +3,7 @@
 
 scr_name="path_convert"
 scr_usage=$(
-  cat <<HELP
+  cat << HELP
 USAGE:
   $scr_name [OPTIONS] [STRING]
 
@@ -53,32 +53,32 @@ parse_input() {
 
   while [ $# -gt 0 ]; do
     case "$1" in
-    -h | --help)
-      print_help
-      exit
-      ;;
-    -d | --verbose)
-      verbosity=2
-      ;;
-    -p | --prefix)
-      input_prefix="$2"
-      shift
-      ;;
-    -c | --clip)
-      clip=true
-      ;;
-    -q | --quiet)
-      verbosity=0
-      ;;
-    *)
-      if [ "$1" ]; then
-        input_path="$1"
-        input_path_type="$(get_path_type "$input_path")"
-      else
-        printf "%s\n" "$scr_usage"
-        exit 1
-      fi
-      ;;
+      -h | --help)
+        print_help
+        exit
+        ;;
+      -d | --verbose)
+        verbosity=2
+        ;;
+      -p | --prefix)
+        input_prefix="$2"
+        shift
+        ;;
+      -c | --clip)
+        clip=true
+        ;;
+      -q | --quiet)
+        verbosity=0
+        ;;
+      *)
+        if [ "$1" ]; then
+          input_path="$1"
+          input_path_type="$(get_path_type "$input_path")"
+        else
+          printf "%s\n" "$scr_usage"
+          exit 1
+        fi
+        ;;
     esac
     shift
   done
@@ -125,8 +125,8 @@ get_path_pure() {
 
 get_path_type() {
   case $1 in
-  *:*) printf "Windows" ;;
-  *) printf "Unix" ;;
+    *:*) printf "Windows" ;;
+    *) printf "Unix" ;;
   esac
 }
 
@@ -137,9 +137,9 @@ get_path_tld() {
 
 get_path_root() {
   case $1 in
-  --win) cd "$2" && pwd -W ;;
-  --unix) cd "$2" && pwd ;;
-  *) cd "$1" && pwd -W ;;
+    --win) cd "$2" && pwd -W ;;
+    --unix) cd "$2" && pwd ;;
+    *) cd "$1" && pwd -W ;;
   esac
 }
 
@@ -152,63 +152,63 @@ validate_path() {
   #@ Parse the path input
   while [ $# -gt 0 ]; do
     case "$1" in
-    -q | --quiet) quiet=true ;;
-    -w | --win*) path_type="Windows" ;;
-    -u | --unix) path_type="Unix" ;;
-    *)
-      #@ Check if the path is empty
-      if [ "$1" ]; then
-        path="$(get_path_pure "$1")"
-      else
-        printf "Missing path string"
-        return 1
-      fi
-      ;;
+      -q | --quiet) quiet=true ;;
+      -w | --win*) path_type="Windows" ;;
+      -u | --unix) path_type="Unix" ;;
+      *)
+        #@ Check if the path is empty
+        if [ "$1" ]; then
+          path="$(get_path_pure "$1")"
+        else
+          printf "Missing path string"
+          return 1
+        fi
+        ;;
     esac
     shift
   done
 
   #@ Check for Windows path then default to Unix
   case "${path_type:-$(get_path_type "$path")}" in
-  Windows)
-    #@ Validate the Windows path
-    case "$path" in
-    [A-Za-z]:*)
-      #@ Add a trailing slash if the path ends with colon (eg. C: = C:/)
-      [ "${path#"${path%?}"}" = ":" ] &&
-        path="${path}/"
+    Windows)
+      #@ Validate the Windows path
+      case "$path" in
+        [A-Za-z]:*)
+          #@ Add a trailing slash if the path ends with colon (eg. C: = C:/)
+          [ "${path#"${path%?}"}" = ":" ] \
+            && path="${path}/"
+          ;;
+        *)
+          #@ Extract the drive letter (e.g., C)
+          drive=${path%%:*}
+
+          #@ Validate the drive letter (e.g., C)
+          if [ -z "$drive" ]; then
+            err="Missing Windows drive letter"
+          elif ! printf "%s" "$drive" \
+            | grep --extended-regexp --quiet "'^[A-Za-z]$'"; then
+            err="Invalid character(s) in Windows drive letter"
+          elif [ "${#drive}" -ne 1 ]; then
+            err="Invalid length of Windows drive letter"
+          fi
+
+          #@ Print drive letter error message if not in quiet mode
+          [ "$quiet" ] \
+            || printf "%s %s" "$err" "$path" \
+            | grep --color=always "$drive"
+
+          #@ Return an error code
+          return 1
+          ;;
+      esac
       ;;
-    *)
-      #@ Extract the drive letter (e.g., C)
-      drive=${path%%:*}
-
-      #@ Validate the drive letter (e.g., C)
-      if [ -z "$drive" ]; then
-        err="Missing Windows drive letter"
-      elif ! printf "%s" "$drive" |
-        grep --extended-regexp --quiet "'^[A-Za-z]$'"; then
-        err="Invalid character(s) in Windows drive letter"
-      elif [ "${#drive}" -ne 1 ]; then
-        err="Invalid length of Windows drive letter"
-      fi
-
-      #@ Print drive letter error message if not in quiet mode
-      [ "$quiet" ] ||
-        printf "%s %s" "$err" "$path" |
-        grep --color=always "$drive"
-
-      #@ Return an error code
-      return 1
+    Unix)
+      #@ Validate the Windows path
+      #TODO Implement error checking logic.
+      # err="Unix path"
+      # printf "%s" "$err"
+      # return 1
       ;;
-    esac
-    ;;
-  Unix)
-    #@ Validate the Windows path
-    #TODO Implement error checking logic.
-    # err="Unix path"
-    # printf "%s" "$err"
-    # return 1
-    ;;
   esac
 
   #@ Return valid path
@@ -254,30 +254,30 @@ convert_path() {
     else
       #@ Set the path root as the user's home directory
       case "$path" in
-      home/* | *:/home/*)
-        path_root="$(get_path_root "$HOME")"
-        path="$path_root/${path#*home/}"
-        ;;
-      *)
-        # # path="$path_root${path}"
-        # path="C:/${path}"
-        path="$(get_path_pure "$path")"
+        home/* | *:/home/*)
+          path_root="$(get_path_root "$HOME")"
+          path="$path_root/${path#*home/}"
+          ;;
+        *)
+          # # path="$path_root${path}"
+          # path="C:/${path}"
+          path="$(get_path_pure "$path")"
 
-        # Extract the drive (e.g. c: from /c:/)
-        drive="$(get_path_tld "$path")"
+          # Extract the drive (e.g. c: from /c:/)
+          drive="$(get_path_tld "$path")"
 
-        # Extract the drive letter (e.g. c from c:)
-        drive_letter="$(
-          printf "%s" "${drive%:}" | tr '[:upper:]' '[:lower:]'
-        )"
+          # Extract the drive letter (e.g. c from c:)
+          drive_letter="$(
+            printf "%s" "${drive%:}" | tr '[:upper:]' '[:lower:]'
+          )"
 
-        # Update the path and include a leading slash
-        path="${drive_letter}${path#"${drive}"}"
+          # Update the path and include a leading slash
+          path="${drive_letter}${path#"${drive}"}"
 
-        # Update the path with the prefix
-        prefix="/$(get_path_pure "${prefix:-mnt}")"
-        path="${prefix}/${path}"
-        ;;
+          # Update the path with the prefix
+          prefix="/$(get_path_pure "${prefix:-mnt}")"
+          path="${prefix}/${path}"
+          ;;
       esac
       # return
     fi
@@ -285,8 +285,8 @@ convert_path() {
 
   #@ Convert the path
   case "$path_type" in
-  Windows) to_unix ;;
-  Unix) to_windows ;;
+    Windows) to_unix ;;
+    Unix) to_windows ;;
   esac
 
   #@ Return the converted path
@@ -299,17 +299,17 @@ parse_output() {
   output_path_type="$(get_path_type "$output_path")"
 
   case "$verbosity" in
-  0) ;;
-  1) ;;
-  *)
-    printf "Input Path   |> %s\n" "$input_path"
-    printf "Input Type   |> %s\n" "$input_path_type"
-    [ "$input_prefix" ] && printf "Input Prefix |> %s\n" "$input_prefix"
-    printf "Output Path  |> %s\n" "$output_path"
-    printf "Output Type  |> %s\n" "$output_path_type"
-    [ "$exit_code" -gt 0 ] && printf "Exit Code    |>  %s\n" "$exit_code"
-    [ "$check_type" ] && printf "Check Type   |>  %s\n" "$check_type"
-    ;;
+    0) ;;
+    1) ;;
+    *)
+      printf "Input Path   |> %s\n" "$input_path"
+      printf "Input Type   |> %s\n" "$input_path_type"
+      [ "$input_prefix" ] && printf "Input Prefix |> %s\n" "$input_prefix"
+      printf "Output Path  |> %s\n" "$output_path"
+      printf "Output Type  |> %s\n" "$output_path_type"
+      [ "$exit_code" -gt 0 ] && printf "Exit Code    |>  %s\n" "$exit_code"
+      [ "$check_type" ] && printf "Check Type   |>  %s\n" "$check_type"
+      ;;
   esac
 
   [ "$clip" ] && send_to_clipboard "$path"
diff --git a/Bin/shellscript/utility/sshIt b/Bin/shellscript/utility/sshIt
--- a/Bin/shellscript/utility/sshIt
+++ b/Bin/shellscript/utility/sshIt
@@ -7,18 +7,18 @@ appVersion="0.10"
 init_scr_env() {
   while [ "$#" -ge 1 ]; do
     case "$1" in
-    -h | --help)
-      __help__
-      exit
-      ;;
-    -v | --version)
-      __version__
-      exit
-      ;;
-    *)
-      # echo "Var: $1"
-      __valid_env__ "$1"
-      ;;
+      -h | --help)
+        __help__
+        exit
+        ;;
+      -v | --version)
+        __version__
+        exit
+        ;;
+      *)
+        # echo "Var: $1"
+        __valid_env__ "$1"
+        ;;
     esac
     shift
   done
@@ -37,49 +37,49 @@ __error__() {
 
   args=$(printf "%s" "$1" | tr '[:upper:]' '[:lower:]')
   case "$args" in
-  --required)
-    printf "This is %srequired%s" "$clr_error" "$tfx_reset"
-    exit 1
-    ;;
-  --selection)
-    printf "Invalid Selection"
-    ;;
-  --naked)
-    printf \
-      "Invalid character(s): %s%s%s" \
-      "$clr_error" "$_invalid" "$tfx_reset"
-    exit 1
-    ;;
-  --character)
-    printf \
-      "Invalid characters were removed: \n🟥 %s \n✅ %s" \
-      "$_invalid" "$_valid"
-    ;;
-  --env)
-    shift
-    printf \
-      "The %sENV file%s path is invalid: %s" \
-      "$clr_error" "$tfx_reset" "$1"
-    # __ui__ --file
-    ;;
-  --id_exists)
-    shift
-    printf \
-      "This %sidentity file%s already exists: %s" \
-      "$clr_error" "$tfx_reset" "$1"
-    __ui__ --id_exists
-    ;;
-  --file)
-    shift
-    printf "Invalid File: %s" "$1"
-    __ui__ --file
-    ;;
-  --path)
-    shift
-    printf "Invalid Path: %s" "$1"
-    __ui__ --path
-    ;;
-    # ;;
+    --required)
+      printf "This is %srequired%s" "$clr_error" "$tfx_reset"
+      exit 1
+      ;;
+    --selection)
+      printf "Invalid Selection"
+      ;;
+    --naked)
+      printf \
+        "Invalid character(s): %s%s%s" \
+        "$clr_error" "$_invalid" "$tfx_reset"
+      exit 1
+      ;;
+    --character)
+      printf \
+        "Invalid characters were removed: \n🟥 %s \n✅ %s" \
+        "$_invalid" "$_valid"
+      ;;
+    --env)
+      shift
+      printf \
+        "The %sENV file%s path is invalid: %s" \
+        "$clr_error" "$tfx_reset" "$1"
+      # __ui__ --file
+      ;;
+    --id_exists)
+      shift
+      printf \
+        "This %sidentity file%s already exists: %s" \
+        "$clr_error" "$tfx_reset" "$1"
+      __ui__ --id_exists
+      ;;
+    --file)
+      shift
+      printf "Invalid File: %s" "$1"
+      __ui__ --file
+      ;;
+    --path)
+      shift
+      printf "Invalid Path: %s" "$1"
+      __ui__ --path
+      ;;
+      # ;;
   esac
 
   printf "%s\n" "$tfx_reset"
@@ -93,109 +93,109 @@ __ui__() {
 
   opts=$(printf "%s" "$*" | tr '[:upper:]' '[:lower:]')
   case "$opts" in
-  --host)
-    printf "%s " "${italic}Who is the ${success}host$tfx_reset?"
-    read -r _INPUT
-    __valid_name__ "$_INPUT"
-    sshHost="$_valid"
-    ;;
-  --user)
-    printf "%s " "${italic}Who is the ${info}user$tfx_reset?"
-    read -r _INPUT
-    __valid_name__ "$_INPUT"
-    sshName="$_valid"
-    ;;
-  --hostname)
-    printf "%s " "${italic}What is the ${info}hostname$tfx_reset?"
-    read -r _INPUT
-    __valid_name__ "$_INPUT"
-    sshHostName="$_valid"
-    ;;
-  --id_new)
-    printf "%s " "${italic}Where should the ${info}Identity File$tfx_reset be saved?"
-    read -r _INPUT
-    __valid_id__ "$_INPUT"
-    __valid_pathname__ "$_INPUT"
-    sshID="$_valid"
-    ;;
-  --id_default)
-    printf "%s " "${italic}Save the ${info}Identity File$tfx_reset to the default location? [Y|n]
+    --host)
+      printf "%s " "${italic}Who is the ${success}host$tfx_reset?"
+      read -r _INPUT
+      __valid_name__ "$_INPUT"
+      sshHost="$_valid"
+      ;;
+    --user)
+      printf "%s " "${italic}Who is the ${info}user$tfx_reset?"
+      read -r _INPUT
+      __valid_name__ "$_INPUT"
+      sshName="$_valid"
+      ;;
+    --hostname)
+      printf "%s " "${italic}What is the ${info}hostname$tfx_reset?"
+      read -r _INPUT
+      __valid_name__ "$_INPUT"
+      sshHostName="$_valid"
+      ;;
+    --id_new)
+      printf "%s " "${italic}Where should the ${info}Identity File$tfx_reset be saved?"
+      read -r _INPUT
+      __valid_id__ "$_INPUT"
+      __valid_pathname__ "$_INPUT"
+      sshID="$_valid"
+      ;;
+    --id_default)
+      printf "%s " "${italic}Save the ${info}Identity File$tfx_reset to the default location? [Y|n]
             ${defaultID}"
-    read -r OPT
-    case $OPT in
-    n* | N*)
-      __ui__ --id_new
+      read -r OPT
+      case $OPT in
+        n* | N*)
+          __ui__ --id_new
+          ;;
+        y* | Y* | *)
+          _INPUT="${defaultID}"
+          ;;
+      esac
       ;;
-    y* | Y* | *)
-      _INPUT="${defaultID}"
+    --id_exists)
+      printf "%s " "${italic}Overwrite the current ${bold}identity$tfx_reset file [${bold}N$tfx_reset|y]?"
+      read -r OPT
+      case $OPT in
+        y* | Y*)
+          _RESET=true
+          printf "%s" "Existing identity file archived"
+          ;;
+        n* | N*)
+          __ui__ --id_new
+          ;;
+        *)
+          __error__ --selection
+          __ui__ --id_exists
+          ;;
+      esac
       ;;
-    esac
-    ;;
-  --id_exists)
-    printf "%s " "${italic}Overwrite the current ${bold}identity$tfx_reset file [${bold}N$tfx_reset|y]?"
-    read -r OPT
-    case $OPT in
-    y* | Y*)
-      _RESET=true
-      printf "%s" "Existing identity file archived"
+    --env)
+      printf "%s " "${italic}What is the path to the ${info}ENV$tfx_reset file?"
+      read -r _INPUT
+      __valid_env__ "$_INPUT"
       ;;
-    n* | N*)
-      __ui__ --id_new
+    --file)
+      printf "%s " "${italic}Please enter a valid path to the ${bold}file$tfx_reset."
+      read -r _INPUT
+      __valid_file__ "$_INPUT"
       ;;
-    *)
-      __error__ --selection
-      __ui__ --id_exists
+    --path)
+      printf "%s " "${italic}Please enter a valid ${bold}path$tfx_reset."
+      read -r _INPUT
+      __valid_pathname__ "$_INPUT"
       ;;
-    esac
-    ;;
-  --env)
-    printf "%s " "${italic}What is the path to the ${info}ENV$tfx_reset file?"
-    read -r _INPUT
-    __valid_env__ "$_INPUT"
-    ;;
-  --file)
-    printf "%s " "${italic}Please enter a valid path to the ${bold}file$tfx_reset."
-    read -r _INPUT
-    __valid_file__ "$_INPUT"
-    ;;
-  --path)
-    printf "%s " "${italic}Please enter a valid ${bold}path$tfx_reset."
-    read -r _INPUT
-    __valid_pathname__ "$_INPUT"
-    ;;
-  --confirm)
-    #| Print content before the ID
-    printf "%s
+    --confirm)
+      #| Print content before the ID
+      printf "%s
         Continue with this SSH config? [Y|n]?
   |> ---------------------------------------- <|
               Host | $sshHost
           Hostname | $sshHostName
               User | $sshName\n"
 
-    #| Wrap if ID length exceeds 22 characters"
-    ID_len="${#sshID}"
-    if [ "$ID_len" -gt 22 ]; then
-      printf "%-15s ID | ⤵ \n %-5s $sshID \n"
-    else
-      printf "%-15s ID | $sshID \n"
-    fi
+      #| Wrap if ID length exceeds 22 characters"
+      ID_len="${#sshID}"
+      if [ "$ID_len" -gt 22 ]; then
+        printf "%-15s ID | ⤵ \n %-5s $sshID \n"
+      else
+        printf "%-15s ID | $sshID \n"
+      fi
 
-    read -r OPT
-    case $OPT in
-    n* | N*)
-      __ui__ --change
+      read -r OPT
+      case $OPT in
+        n* | N*)
+          __ui__ --change
+          ;;
+        y* | Y* | *)
+          return
+          ;;
+          # *)
+          #   __error__ --selection
+          #   __ui__ --confirm
+          # ;;
+      esac
       ;;
-    y* | Y* | *)
-      return
-      ;;
-      # *)
-      #   __error__ --selection
-      #   __ui__ --confirm
-      # ;;
-    esac
-    ;;
-  --change)
-    printf "
+    --change)
+      printf "
               Select Change Option
   |> ---------------------------------------- <|
                 1. ENV Key File
@@ -205,21 +205,21 @@ __ui__() {
                 5. Identity File
                 6. Cancel
             "
-    read -r n
-    case $n in
-    1) __ui__ --env ;;
-    2) __ui__ --host ;;
-    3) __ui__ --hostname ;;
-    4) __ui__ --user ;;
-    5) __ui__ --id_new ;;
-    6)
-      printf "%s" "Exiting $appName"
-      exit
+      read -r n
+      case $n in
+        1) __ui__ --env ;;
+        2) __ui__ --host ;;
+        3) __ui__ --hostname ;;
+        4) __ui__ --user ;;
+        5) __ui__ --id_new ;;
+        6)
+          printf "%s" "Exiting $appName"
+          exit
+          ;;
+        *) __error__ --selection ;;
+      esac
+      __ui__ --confirm
       ;;
-    *) __error__ --selection ;;
-    esac
-    __ui__ --confirm
-    ;;
   esac
 
   #| Enable user input display
@@ -252,9 +252,9 @@ __variables__() {
       fi
 
       case "$(printf "%s" "$sshHost" | tr '[:upper:]' '[:lower:]')" in
-      *github*) sshHostLabel="$GitHub" ;;
-      *gitlab*) sshHostLabel="$GitLab" ;;
-      *) ;;
+        *github*) sshHostLabel="$GitHub" ;;
+        *gitlab*) sshHostLabel="$GitLab" ;;
+        *) ;;
       esac
       _key="$HostName"
       if [ -n "$_key" ]; then
@@ -332,8 +332,8 @@ __variables__() {
         )"
 
         #| Archive exixting files
-        [ -f "$sshID" ] &&
-          for file in $FILEStoArchive; do
+        [ -f "$sshID" ] \
+          && for file in $FILEStoArchive; do
             bakDIR="${sshIDdir}/archive"
             mkdir --parents "$bakDIR"
             mv "$file" --backup=numbered --target-directory="$bakDIR"
@@ -375,15 +375,15 @@ __init__() {
 
   #| Generate public/private algorithm key pair, respectively.
   ssh-keygen -t ed25519 -a 100 -f "${sshID}" -C "$(INFor --label)"
-  ssh-keygen -y -f "${sshID}" >"${sshID}.pub"
+  ssh-keygen -y -f "${sshID}" > "${sshID}.pub"
 
   #| Start the ssh-agent and add the private key to it.
   eval "$(ssh-agent)" && ssh-add "${sshID}"
 
   printf \
     "Host %s\n  \tUser %s\n  \tHostName %s\n  \tIdentityFile %s\n" \
-    "$sshHost" "$sshName" "$sshHostName" "$sshID" |
-    tee --append "${sshDIR}/config"
+    "$sshHost" "$sshName" "$sshHostName" "$sshID" \
+    | tee --append "${sshDIR}/config"
 
   #| Send the contents of the public key to the clipboard
   clip-c "$(cat "$sshID.pub")"
@@ -394,19 +394,19 @@ __init__() {
 __valid_chars__() {
   while [ $# -ge 1 ]; do
     case "$1" in
-    --chars)
-      _chars="$2"
-      ;;
-    --text)
-      if [ "$2" = "" ]; then
-        __error__ --naked
-      else
-        _text="$2"
-      fi
-      ;;
-    *)
-      __error__ --required
-      ;;
+      --chars)
+        _chars="$2"
+        ;;
+      --text)
+        if [ "$2" = "" ]; then
+          __error__ --naked
+        else
+          _text="$2"
+        fi
+        ;;
+      *)
+        __error__ --required
+        ;;
     esac
     shift
   done
diff --git a/Modules/nixos/configurations/hosts/QBX/bin/utilities/first b/Modules/nixos/configurations/hosts/QBX/bin/utilities/first
--- a/Modules/nixos/configurations/hosts/QBX/bin/utilities/first
+++ b/Modules/nixos/configurations/hosts/QBX/bin/utilities/first
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 usage() {
-  cat <<EOF
+  cat << EOF
 Usage: first [OPTIONS] FILENAME
 Search for a file in directory tree, default is upward search
 
@@ -35,41 +35,41 @@ parse_arguments() {
   #@ Parse options
   while [ "$#" -gt 0 ]; do
     case "$1" in
-    --up)
-      direction="up"
-      shift
-      ;;
-    --down)
-      direction="down"
-      shift
-      ;;
-    --both)
-      direction="both"
-      shift
-      ;;
-    --direction)
-      shift
-      case "$1" in
-      up | down | both)
-        direction="$1"
+      --up)
+        direction="up"
+        shift
         ;;
-      *)
-        printf "%s" "Error: Invalid direction '$1'" >&2
+      --down)
+        direction="down"
+        shift
+        ;;
+      --both)
+        direction="both"
+        shift
+        ;;
+      --direction)
+        shift
+        case "$1" in
+          up | down | both)
+            direction="$1"
+            ;;
+          *)
+            printf "%s" "Error: Invalid direction '$1'" >&2
+            usage 1
+            ;;
+        esac
+        shift
+        ;;
+      -h | --help)
+        usage
+        ;;
+      -*)
+        printf "%s" "Error: Unknown option '$1'" >&2
         usage 1
         ;;
-      esac
-      shift
-      ;;
-    -h | --help)
-      usage
-      ;;
-    -*)
-      printf "%s" "Error: Unknown option '$1'" >&2
-      usage 1
-      ;;
-    *)
-      break
-      ;;
+      *)
+        break
+        ;;
     esac
   done
 
@@ -104,27 +104,27 @@ find_down() {
   dir="${1:-.}"
   path="$2"
 
-  if command -v fd >/dev/null 2>&1; then
+  if command -v fd > /dev/null 2>&1; then
     fd "$path" "$dir"
     return $?
   else
-    find "$dir" -name "$path" 2>/dev/null
+    find "$dir" -name "$path" 2> /dev/null
     return $?
   fi
 }
 
 perform_search() {
   case "$direction" in
-  up)
-    find_up "$PWD" "$pattern"
-    ;;
-  down)
-    find_down "$PWD" "$pattern"
-    ;;
-  both | *)
-    find_up "$PWD" "$pattern" ||
+    up)
+      find_up "$PWD" "$pattern"
+      ;;
+    down)
       find_down "$PWD" "$pattern"
-    ;;
+      ;;
+    both | *)
+      find_up "$PWD" "$pattern" \
+        || find_down "$PWD" "$pattern"
+      ;;
   esac
 }
 
diff --git a/Modules/nixos/configurations/hosts/QBX/bin/utilities/weatherin b/Modules/nixos/configurations/hosts/QBX/bin/utilities/weatherin
--- a/Modules/nixos/configurations/hosts/QBX/bin/utilities/weatherin
+++ b/Modules/nixos/configurations/hosts/QBX/bin/utilities/weatherin
@@ -35,56 +35,56 @@ initialize_variables() {
   #@ Parse arguments
   while [ $# -gt 0 ]; do
     case "$1" in
-    --location | --coordinates)
-      if [ -n "$2" ]; then
-        location="$2"
-        shift
-      else
-        printf "Error: --location requires a value.\n" >&2
-        usage
-        return 1
-      fi
-      ;;
-    --latitude)
-      if [ -n "$2" ]; then
-        latitude="$2"
-        shift 2
-      else
-        printf "Error: --latitude requires a value.\n" >&2
-        usage
-        return 1
-      fi
-      ;;
-    --longitude)
-      if [ -n "$2" ]; then
-        longitude="$2"
-        shift
-      else
-        printf "Error: --longitude requires a value.\n" >&2
-        usage
-        return 1
-      fi
-      ;;
-    -V | --verbose)
-      verbose=true
-      # debug=true
-      ;;
-    -d | --debug)
-      debug=true
-      ;;
-    -x | --test)
-      test=true
-      ;;
-    --show-gps)
-      show_gps=true
-      ;;
-    *)
-      if [ "$location" ]; then
-        location="${location} $1"
-      else
-        location="$1"
-      fi
-      ;;
+      --location | --coordinates)
+        if [ -n "$2" ]; then
+          location="$2"
+          shift
+        else
+          printf "Error: --location requires a value.\n" >&2
+          usage
+          return 1
+        fi
+        ;;
+      --latitude)
+        if [ -n "$2" ]; then
+          latitude="$2"
+          shift 2
+        else
+          printf "Error: --latitude requires a value.\n" >&2
+          usage
+          return 1
+        fi
+        ;;
+      --longitude)
+        if [ -n "$2" ]; then
+          longitude="$2"
+          shift
+        else
+          printf "Error: --longitude requires a value.\n" >&2
+          usage
+          return 1
+        fi
+        ;;
+      -V | --verbose)
+        verbose=true
+        # debug=true
+        ;;
+      -d | --debug)
+        debug=true
+        ;;
+      -x | --test)
+        test=true
+        ;;
+      --show-gps)
+        show_gps=true
+        ;;
+      *)
+        if [ "$location" ]; then
+          location="${location} $1"
+        else
+          location="$1"
+        fi
+        ;;
     esac
     shift
   done
@@ -123,10 +123,12 @@ initialize_utilities() {
     #DOC
     #DOC Example:
     #DOC   cleanup_location "Mandeville , Jamaica" => "Mandeville,Jamaica"
-    printf "%s" "$1" |
-      tr -s ' ' '+' |
+    printf "%s" "$1" \
+      | tr -s ' ' '+' \
+      |
       #? Convert spaces to plus
-      sed 's/,+/,/g' |
+      sed 's/,+/,/g' \
+      |
       #? Convert comma plus combination to a single comma
       sed 's/+,/,/g' #? Convert plus comma combination to a single comma
   }
@@ -178,10 +180,10 @@ initialize_utilities() {
 
     while [ "$#" -gt 0 ]; do
       case "$1" in
-      -h) show_usage ;;
-      --help) show_help ;;
-      --detailed) detailed=true ;;
-      *) _location="$1" ;;
+        -h) show_usage ;;
+        --help) show_help ;;
+        --detailed) detailed=true ;;
+        *) _location="$1" ;;
       esac
       shift
     done
@@ -259,20 +261,20 @@ Location: Warszawa, mazowieckie, RP [52.2318,21.0058]'
     #@ Parse the data into variables
     while IFS='=' read -r key value; do
       case "$key" in
-      condition_icon) condition_icon="$value" ;;
-      condition_name) condition_name="$value" ;;
-      condition_symbol) condition_symbol="$value" ;;
-      temperature_actual) temperature_actual="$value" ;;
-      temperature_feel) temperature_feel="$value" ;;
-      wind) wind="$value" ;;
-      humidity) humidity="$value" ;;
-      moon_phase) moon_phase="$value" ;;
-      moon_day) moon_day="$value" ;;
-      precipitation) precipitation="$value" ;;
-      pressure) pressure="$value" ;;
-      uv_index) uv_index="$value" ;;
+        condition_icon) condition_icon="$value" ;;
+        condition_name) condition_name="$value" ;;
+        condition_symbol) condition_symbol="$value" ;;
+        temperature_actual) temperature_actual="$value" ;;
+        temperature_feel) temperature_feel="$value" ;;
+        wind) wind="$value" ;;
+        humidity) humidity="$value" ;;
+        moon_phase) moon_phase="$value" ;;
+        moon_day) moon_day="$value" ;;
+        precipitation) precipitation="$value" ;;
+        pressure) pressure="$value" ;;
+        uv_index) uv_index="$value" ;;
       esac
-    done <<EOF
+    done << EOF
 $(printf '%s' "$_response_simple" | tr ' ' '\n')
 EOF
 
@@ -323,8 +325,8 @@ EOF
     # info="$(curl -s "$url_formatted")"
 
     case "$verbose" in
-    '' | 0) curl -s "$url_formatted" ;;
-    *) curl -s "https://wttr.in/${1}" ;;
+      '' | 0) curl -s "$url_formatted" ;;
+      *) curl -s "https://wttr.in/${1}" ;;
     esac
 
     #TODO: Handle response errors
@@ -351,8 +353,8 @@ EOF
     _location=$(cleanup_location "$1")
 
     #@ Skip if coordinates are already provided
-    printf "%s" "$_location" |
-      grep -qE '^-?[0-9]{1,3}(\.[0-9]+)?,-?[0-9]{1,3}(\.[0-9]+)?$' && {
+    printf "%s" "$_location" \
+      | grep -qE '^-?[0-9]{1,3}(\.[0-9]+)?,-?[0-9]{1,3}(\.[0-9]+)?$' && {
       printf "%s" "$_location"
       return 0
     }
@@ -373,15 +375,15 @@ EOF
     }
 
     #@ Extract coordinates, latitude and longitude
-    if command -v jq >/dev/null 2>&1; then
+    if command -v jq > /dev/null 2>&1; then
       _coordinates=$(printf "%s" "$_response" | jq -r '.features[].geometry.coordinates')
       _longitude=$(printf "%s" "$_coordinates" | jq -r '.[0]')
       _latitude=$(printf "%s" "$_coordinates" | jq -r '.[1]')
     else
       #@ Extract coordinates using grep and sed in a POSIX-friendly way
       _coordinates="$(
-        printf '%s' "$_response" |
-          sed -n 's/.*"coordinates":\s*\[\s*\([^,]*\)\s*,\s*\([^]]*\)\s*\].*/\1,\2/p'
+        printf '%s' "$_response" \
+          | sed -n 's/.*"coordinates":\s*\[\s*\([^,]*\)\s*,\s*\([^]]*\)\s*\].*/\1,\2/p'
       )"
 
       #@ Use sed to extract longitude and latitude, handling potential spaces
