fixed pout in absolute. moving absolute to enviro

diff --git a/Bin/shellscript/environment/enviro b/Bin/shellscript/environment/enviro
--- a/Bin/shellscript/environment/enviro
+++ b/Bin/shellscript/environment/enviro
@@ -14,19 +14,22 @@ main() {
 
 set_defaults() {
   #| Script Metadata
-  # cmd_PATH="$0"
-  cmd_NAME="absolute"
-  # cmd_NAME="$(basename "${cmd_PATH}")"
-  # cmd_HOME="$(dirname "${cmd_PATH}")"
+  cmd_NAME="enviro"
   cmd_VERSION="1.1.0"
   cmd_AUTHOR="Craole"
   cmd_USAGE="${cmd_NAME} [OPTIONS] <target_path>"
-  cmd_DESCRIPTION="normalizes a given target path by resolving symbolic links and removing redundant elements such as '.' and '..', essentially returning the absolute path."
+  cmd_DESCRIPTION="Handle paths"
 
   #| Operational Variables
   debug_pad=20 #? Positive integer
   delimiter="$(printf '\037')"
   IFS="${delimiter}"
+  verbosity_quiet=0
+  verbosity_error=1
+  verbosity_warn=2
+  verbosity_info=3
+  verbosity_debug=4
+  verbosity_trace=5
 
   #| Operational Modes
   set_modes --verbosity info
@@ -35,9 +38,11 @@ set_defaults() {
   #| Process Variables
   action="show"
   target_path="$(pwd -P)"
+  # print_raw=0
+  # paths=""
 
   #| Commands
-  cmd_list="$(list --build realpath readlink)"
+  cmd_list="$(list --build bat fd realpath readlink rg)"
 }
 
 set_modes() {
@@ -63,41 +68,41 @@ set_modes() {
 
   #@ Parse arguments
   case "$1" in
-    --verbosity)
-      #| Verbosity Level
-      case "${2:-}" in
-        0 | off | false | quiet | " ") verbosity=0 ;;
-        1 | err*) verbosity=1 ;;
-        2 | warn*) verbosity=2 ;;
-        3 | info*) verbosity=3 ;;
-        4 | debug) verbosity=4 ;;
-        5 | trace) verbosity=5 ;;
-        *)
-          pout --warn --key "Invalid verbosity level" "${2}"
-          pout "Valid options: " "${verbosity_options}"
-          pout "Default option: " "${verbosity}"
-          ;;
-      esac
+  --verbosity)
+    #| Verbosity Level
+    case "${2:-}" in
+    0 | off | false | quiet | " ") verbosity="${verbosity_quiet:-0}" ;;
+    1 | err*) verbosity="${verbosity_error:-1}" ;;
+    2 | warn*) verbosity="${verbosity_warn:-2}" ;;
+    3 | info*) verbosity="${verbosity_info:-3}" ;;
+    4 | debug) verbosity="${verbosity_debug:-4}" ;;
+    5 | trace) verbosity="${verbosity_trace:-5}" ;;
+    *)
+      pout --warn --key "Invalid verbosity level" "${2}"
+      pout "Valid options: " "${verbosity_options}"
+      pout "Default option: " "${verbosity}"
       ;;
-    --fail-on-error)
-      #| Script Operation Mode
+    esac
+    ;;
+  --fail-on-error)
+    #| Script Operation Mode
 
-      case "${2:-}" in
-        1 | true | on | enabled) fail_on_error=1 ;;
-        0 | false | off | disabled) fail_on_error=0 ;;
-        *)
-          pout --warn "Invalid 'fail_on_error' mode" ": ($2)" \
-            "\nValid options: " "${fail_on_error_options}" \
-            "\nDefault option: " "${fail_on_error}"
-          ;;
-      esac
+    case "${2:-}" in
+    1 | true | on | enabled) fail_on_error=1 ;;
+    0 | false | off | disabled) fail_on_error=0 ;;
+    *)
+      pout --warn "Invalid 'fail_on_error' mode" ": ($2)" \
+        "\nValid options: " "${fail_on_error_options}" \
+        "\nDefault option: " "${fail_on_error}"
       ;;
-    *) ;;
+    esac
+    ;;
+  *) ;;
   esac
 
   case "${fail_on_error:-}" in
-    1 | true | on | enabled) set -e ;;
-    *) ;;
+  1 | true | on | enabled) set -e ;;
+  *) ;;
   esac
 }
 
@@ -115,7 +120,7 @@ cache_commands() {
     pout --debug --key "[${cmd}] CMD_KEY" --val "${cmd_key}"
 
     #@ Retrieve the path, otherwise return empty string
-    cmd_val="$(command -v "${cmd}" 2> /dev/null || printf '')"
+    cmd_val="$(command -v "${cmd}" 2>/dev/null || printf '')"
     pout --debug --key "[${cmd}] CMD_VAL" --val "${cmd_val}"
 
     #@ Create the environment variable of the command's location
@@ -128,44 +133,56 @@ cache_commands() {
 parse_arguments() {
   while [ $# -gt 0 ]; do
     case $1 in
-      -h | --help) display_info --usage ;;
-      -v | --version) display_info --version ;;
-      -q | --quiet) verbosity=quiet ;;
-      -d=* | --verbose=*) verbosity="${1#*=}" ;;
-      -d | --verbose)
-        case "$2" in
-          */*) verbosity="debug" ;;
-          *)
-            if [ -n "${2:-}" ]; then
-              verbosity="$2"
-              shift
-            else
-              verbosity="debug"
-            fi
-            ;;
-        esac
+    -h | --help) display_info --usage ;;
+    -v | --version) display_info --version ;;
+    --quiet) verbosity=0 ;;
+    --error) verbosity=1 ;;
+    -d=* | --verbose=*) verbosity="${1#*=}" ;;
+    -d | --verbose)
+      case "$2" in
+      */* | .) verbosity="debug" ;;
+      *)
+        if [ -n "${2:-}" ]; then
+          verbosity="$2"
+          shift
+        else
+          verbosity="debug"
+        fi
         ;;
-      -*) terminate_process --error opt "$1" ;;
-      *) target_path="$1" ;;
+      esac
+      ;;
+    --path-show)
+      action="show"
+      ;;
+    --path-clean)
+      action="clean"
+      ;;
+    --path-check)
+      action="check"
+      ;;
+    --path-append)
+      action="append"
+      ;;
+    --path-prepend)
+      action="prepend"
+      ;;
+    --path-print)
+      # print_raw=1
+      ;;
+    -*) terminate_process --error opt "$1" ;;
+    *) target_path="$1" ;;
     esac
     shift
   done
 
   #@ Normalize the verbosity level
-  case "${verbosity:-}" in
-    0 | quiet | off | false) verbosity=0 ;;
-    1 | error) verbosity=1 ;;
-    2 | warn*) verbosity=2 ;;
-    5 | trace) verbosity=5 ;;
-    4 | debug) verbosity=4 ;;
-    3 | info | on | *) verbosity=3'' ;;
-  esac
+  set_modes --verbosity "${verbosity:-}"
 
   #@Set the current directory as the default path
   target_path="${target_path:-"$(pwd -P)"}"
 }
 
-execute_process() {
+get_absolute_path() {
   #@ Initialize variables
   _path="${1:-"${target_path:-}"}"
   pout --debug --key "Execute Process" --val "${_path}"
@@ -191,14 +208,14 @@ normalize_path() {
 
   #@ Handle absolute vs. relative paths
   case "${input_path}" in
-    /*) abs_path="${input_path}" ;;
-    *) abs_path="$(pwd)/${input_path}" ;;
+  /*) abs_path="${input_path}" ;;
+  *) abs_path="$(pwd)/${input_path}" ;;
   esac
 
   #@ Set initial slash for absolute paths
   case "${abs_path}" in
-    /*) result="/" ;;
-    *) ;;
+  /*) result="/" ;;
+  *) ;;
   esac
 
   #@ Save IFS and set new one for path splitting
@@ -275,7 +292,7 @@ resolve_path() {
   fi
 
   #@ Resolve the target directory and get its physical path
-  if ! physical_dir="$(cd -P "$(dirname "${target}")" 2> /dev/null && pwd -P)"; then
+  if ! physical_dir="$(cd -P "$(dirname "${target}")" 2>/dev/null && pwd -P)"; then
     #@ Return original if directory doesn't exist
     printf "%s" "${target}"
     return 1
@@ -291,8 +308,8 @@ resolve_path() {
 
     #@ Handle relative vs. absolute links
     case "${link_target}" in
-      /*) resolved_link="${link_target}" ;;
-      *) resolved_link="${physical_dir}/${link_target}" ;;
+    /*) resolved_link="${link_target}" ;;
+    *) resolved_link="${physical_dir}/${link_target}" ;;
     esac
 
     #@ Recursively resolve the link target with incremented depth
@@ -306,9 +323,9 @@ resolve_path() {
 
 terminate_process() {
   case "$1" in
-    --error) display_info "${1:-}-${2:-}" "${3:-}" ;;
-    --output) display_info "${1:-}" "${2:-}" ;;
-    *) ;;
+  --error) display_info "${1:-}-${2:-}" "${3:-}" ;;
+  --output) display_info "${1:-}" "${2:-}" ;;
+  *) ;;
   esac
 }
 
@@ -321,10 +338,10 @@ list() {
   #@ Parse arguments
   while [ "$#" -ge 1 ]; do
     case "$1" in
-      --create | --make | --build) action=build ;;
-      --parse) action=parse ;;
-      --delim* | --sep*) separator="${2:-}" shift ;;
-      *) list="${list:+${list}${delimiter}}$1" ;;
+    --create | --make | --build) action=build ;;
+    --parse) action=parse ;;
+    --delim* | --sep*) separator="${2:-}" shift ;;
+    *) list="${list:+${list}${delimiter}}$1" ;;
     esac
     shift
   done
@@ -342,19 +359,19 @@ list() {
   fi
 
   case "${action:-}" in
-    build)
-      printf "%s" "${list:-}"
-      ;;
-    parse)
-      #@ Parse the input string into an array-like output
-      old_IFS="${IFS}"
-      IFS="${delimiter}"
-      for item in ${list}; do
-        printf "%s\n" "${item}"
-      done
-      IFS="${old_IFS}"
-      ;;
-    *) ;;
+  build)
+    printf "%s" "${list:-}"
+    ;;
+  parse)
+    #@ Parse the input string into an array-like output
+    old_IFS="${IFS}"
+    IFS="${delimiter}"
+    for item in ${list}; do
+      printf "%s\n" "${item}"
+    done
+    IFS="${old_IFS}"
+    ;;
+  *) ;;
   esac
 }
 
@@ -369,43 +386,43 @@ pout() {
   #@ Parse message type and content
   while [ "$#" -gt 0 ]; do
     case "$1" in
-      -k | --key) key="$2" shift ;;
-      -v | --val) val="$2" shift ;;
-      -t | --trace)
-        if [ "${verbosity:-0}" -ge "${verbosity_trace:-5}" ]; then
-          tag="TRACE"
-        else return 0; fi
-        ;;
-      -d | --debug)
-        if [ "${verbosity:-0}" -ge "${verbosity_debug:-4}" ]; then
-          tag="DEBUG"
-        else return 0; fi
-        ;;
-      -i | --info)
-        if [ "${verbosity:-0}" -ge "${verbosity_info:-3}" ]; then
-          tag=" INFO"
-        else return 0; fi
-        ;;
-      -w | --warn)
-        if [ "${verbosity:-0}" -ge "${verbosity_warn:-2}" ]; then
-          tag=" WARN"
-        else return 0; fi
-        ;;
-      -e | --error)
-        if [ "${verbosity:-0}" -ge "${verbosity_error:-1}" ]; then
-          tag="ERROR"
-        else return 0; fi
-        ;;
-      --no-trim) trim="" ;;
-      --usage)
-        usage_guide
-        exit 0
-        ;;
-      --version)
-        printf "%s\n" "${cmd_VERSION}"
-        exit 0
-        ;;
-      *) msg="${msg:+${msg}${delimiter}}$1" ;;
+    -k | --key) key="$2" shift ;;
+    -v | --val) val="$2" shift ;;
+    -t | --trace)
+      if [ "${verbosity:-0}" -ge "${verbosity_trace:-5}" ]; then
+        tag="TRACE"
+      else return 0; fi
+      ;;
+    -d | --debug)
+      if [ "${verbosity:-0}" -ge "${verbosity_debug:-4}" ]; then
+        tag="DEBUG"
+      else return 0; fi
+      ;;
+    -i | --info)
+      if [ "${verbosity:-0}" -ge "${verbosity_info:-3}" ]; then
+        tag=" INFO"
+      else return 0; fi
+      ;;
+    -w | --warn)
+      if [ "${verbosity:-0}" -ge "${verbosity_warn:-2}" ]; then
+        tag=" WARN"
+      else return 0; fi
+      ;;
+    -e | --error)
+      if [ "${verbosity:-0}" -ge "${verbosity_error:-1}" ]; then
+        tag="ERROR"
+      else return 0; fi
+      ;;
+    --no-trim) trim="" ;;
+    --usage)
+      usage_guide
+      exit 0
+      ;;
+    --version)
+      printf "%s\n" "${cmd_VERSION}"
+      exit 0
+      ;;
+    *) msg="${msg:+${msg}${delimiter}}$1" ;;
     esac
     shift
   done
@@ -423,52 +440,52 @@ pout() {
     fi
 
     case "${tag}" in
-      *DEBUG* | *ERROR* | *WARN* | *INFO*)
-        #@ Define the separator
-        sep=" | "
+    *DEBUG* | *ERROR* | *WARN* | *INFO*)
+      #@ Define the separator
+      sep=" | "
 
-        #@ Calculate padding for label alignment
-        debug_pad="${debug_pad:-18}"
-        pad="$(printf "%*s" "$((debug_pad - ${#key}))" "")"
+      #@ Calculate padding for label alignment
+      debug_pad="${debug_pad:-18}"
+      pad="$(printf "%*s" "$((debug_pad - ${#key}))" "")"
 
-        #@ Format the tagged key-value pair
-        msg="$(
-          printf "[%s] /> %s <\ %s%s%s%s\n" \
-            "${tag}" "${cmd_NAME}" "${pad}" "${key}" "${sep}" "${val}"
-        )"
-        ;;
-      *)
-        #@ Define the separator
-        sep=": "
+      #@ Format the tagged key-value pair
+      msg="$(
+        printf "[%s] /> %s <\ %s%s%s%s\n" \
+          "${tag}" "${cmd_NAME}" "${pad}" "${key}" "${sep}" "${val}"
+      )"
+      ;;
+    *)
+      #@ Define the separator
+      sep=": "
 
-        #@ Print the key-value pair
-        msg="$(
-          printf "%s%s%s\n" "${key}" "${sep}" "${val}"
-        )"
-        ;;
+      #@ Print the key-value pair
+      msg="$(
+        printf "%s%s%s\n" "${key}" "${sep}" "${val}"
+      )"
+      ;;
     esac
   else
     case "${tag}" in
-      *DEBUG* | *ERROR* | *WARN* | *INFO*)
-        #@ Format the tagged message
-        msg="$(
-          printf "[%s] /> %s <\ %b\n" \
-            "${tag}" "${cmd_NAME}" "${msg}"
-        )"
-        ;;
-      *) msg="$(trim "${msg}")" ;;
+    *DEBUG* | *ERROR* | *WARN* | *INFO*)
+      #@ Format the tagged message
+      msg="$(
+        printf "[%s] /> %s <\ %b\n" \
+          "${tag}" "${cmd_NAME}" "${msg}"
+      )"
+      ;;
+    *) msg="$(trim "${msg}")" ;;
     esac
   fi
 
   #@ Print the message
   case "${tag}" in
-    ERROR | WARN) printf "%s\n" "${msg}" >&2 ;;
-    *) printf "%s\n" "${msg}" ;;
+  ERROR | WARN) printf "%s\n" "${msg}" >&2 ;;
+  *) printf "%s\n" "${msg}" ;;
   esac
 }
 
 sanitize_environment() {
-  #@ Remove varibles
+  #@ Remove variables
   unset verbosity
   unset target_path
   unset normalized_path
@@ -479,37 +496,37 @@ sanitize_environment() {
 
 display_info() {
   case "$1" in
-    --error*)
-      [ "${verbosity}" -eq 0 ] && return
-      case "$1" in
-        path) printf "Invalid path: %s" "$2" ;;
-        circ) printf "Circular symbolic link: %s" "$2" ;;
-        info) printf "Invalid verbosity level: %s" "$2" ;;
-        arg) printf "<target_path> required \nUsage: %s\n" "${cmd_USAGE}" ;;
-        opt) printf "Unrecognized option: %s" "$2" ;;
-        cd) printf "Change directory operation failed" ;;
-        *)
-          shift
-          printf "%b" "$*"
-          ;;
-      esac
+  --error*)
+    [ "${verbosity}" -eq 0 ] && return
+    case "$1" in
+    path) printf "Invalid path: %s" "$2" ;;
+    circ) printf "Circular symbolic link: %s" "$2" ;;
+    info) printf "Invalid verbosity level: %s" "$2" ;;
+    arg) printf "<target_path> required \nUsage: %s\n" "${cmd_USAGE}" ;;
+    opt) printf "Unrecognized option: %s" "$2" ;;
+    cd) printf "Change directory operation failed" ;;
+    *)
+      shift
+      printf "%b" "$*"
       ;;
-    --output)
-      case "${verbosity}" in
-        3 | on | info) printf "%s\n" "${normalized_path}" ;;
-        4 | debug | trace)
-          printf "    Verbosity: %s\n" "${verbosity}"
-          printf "  Target Path: %s\n" "${target_path}"
-          printf "Absolute Path: %s\n" "${normalized_path}"
-          ;;
-        0 | off | quiet | *) ;;
-      esac
+    esac
+    ;;
+  --output)
+    case "${verbosity}" in
+    3 | on | info) printf "%s\n" "${normalized_path}" ;;
+    4 | debug | trace)
+      printf "    Verbosity: %s\n" "${verbosity}"
+      printf "  Target Path: %s\n" "${target_path}"
+      printf "Absolute Path: %s\n" "${normalized_path}"
       ;;
-    --version)
-      printf "%s" "${cmd_VERSION}"
-      ;;
-    --usage)
-      cat << USAGE
+    0 | off | quiet | *) ;;
+    esac
+    ;;
+  --version)
+    printf "%s" "${cmd_VERSION}"
+    ;;
+  --usage)
+    cat <<USAGE
 ${cmd_NAME} [v.${cmd_VERSION}]
 
 DESCRIPTION:
@@ -522,7 +539,7 @@ OPTIONS:
   -h, --help       Show detailed help information and exit.
   -v, --version    Show the script version number and exit.
   -d, --verbose    Display additional information during execution: [current: "${verbosity}"].
-  -q, --quiet      Supress all output. Error flag will still work.
+  -q, --quiet      Suppress all output. Error flag will still work.
 
 ARGUMENTS:
   target_path      The path to normalize.
@@ -538,8 +555,8 @@ Examples:
   ${cmd_NAME} /var/run
 
 USAGE
-      ;;
-    *) printf "%s\n" "$*" ;;
+    ;;
+  *) printf "%s\n" "$*" ;;
   esac
 }
 
