changed #~@ to #{

diff --git a/Bin/shellscript/environment/fs b/Bin/shellscript/environment/fs
--- a/Bin/shellscript/environment/fs
+++ b/Bin/shellscript/environment/fs
@@ -11,7 +11,7 @@ cleanup() {
   [ -n "${tmp_file}" ] && rm -f -- "${tmp_file}"
 }
 
-#~@ Set up cleanup trap
+#{ Set up cleanup trap
 trap cleanup EXIT INT TERM HUP
 
 create_tmp_file() {
@@ -28,10 +28,10 @@ manage() {
     create_tmp_file yazi-cwd
     yazi "$@" --cwd-file="${tmp_file}"
     if [ -f "${tmp_file}" ]; then
-      #~@ Read path preserving whitespace
+      #{ Read path preserving whitespace
       IFS= read -r cwd <"${tmp_file}"
 
-      #~@ If the cwd is a valid directory
+      #{ If the cwd is a valid directory
       if [ -n "${cwd}" ] && [ -d "${cwd}" ]; then
         [ -n "${cwd}" ] && [ "${cwd}" != "${PWD}" ] && {
           printf "Entering directory: %s\n" "${cwd}"
diff --git a/Bin/shellscript/output/pout-tagged b/Bin/shellscript/output/pout-tagged
--- a/Bin/shellscript/output/pout-tagged
+++ b/Bin/shellscript/output/pout-tagged
@@ -12,94 +12,110 @@
 #DOC   --msg MESSAGE    The message content to display
 #DOC
 #DOC Examples:
-#DOC   pout_tagged --ctx "locate_dots" --tag "DEBUG" --msg "Found RC file: /path/to/file"
-#DOC   pout_tagged --ctx "manage_env" --tag "ERROR" --msg "Variable name is required"
+#DOC   pout-tagged --ctx "locate_dots" --tag "DEBUG" --msg "Found RC file: /path/to/file"
+#DOC   pout-tagged --ctx "manage_env" --tag "ERROR" --msg "Variable name is required"
 
-#~@ Set a safe delimiter (ASCII Unit Separator)
-: "${DELIMITER:="$(printf "\037")"}"
+#{ Set a safe delimiter (ASCII Unit Separator)
 
-#~@ Initialize with defaults
+#{ Initialize with defaults
+scr_path="${0##*/}"
+scr_name="${scr_path##*/}"
 ctx=""
 tag=""
 msg=""
+delimiter="$(printf "\037")"
 
-#~@ Parse named arguments
+#{ Parse named arguments
 while [ $# -gt 0 ]; do
   case "${1}" in
+  --ctx=*) ctx="${1#--ctx=}" ;;
   --ctx)
-    if [ $# -gt 1 ]; then
+    if [ "$#" -gt 1 ]; then
       ctx="$2"
       shift
     else
-      printf "Error: Missing value for --ctx\n" >&2
+      printf "Error: Missing value for %s\n" "$1" >&2
       return 1
     fi
     ;;
+  --tag=*) tag="${1#--tag=}" ;;
   --tag)
-    if [ $# -gt 1 ]; then
+    if [ "$#" -gt 1 ]; then
       tag="$2"
       shift
     else
-      printf "Error: Missing value for --tag\n" >&2
+      printf "Error: Missing value for %s\n" "$1" >&2
       return 1
     fi
     ;;
+  --tag-head-sep=*) ctx_head_sep="${1#--ctx_head_sep=}" ;;
+  --tag-head-sep)
+    if [ $# -gt 1 ]; then
+      ctx_head_sep="$2"
+      shift
+    else
+      printf "Error: Missing value for %s\n" "$1" >&2
+      return 1
+    fi
+    ;;
+  --tag-tail-sep=*) ctx_tail_sep="${1#--ctx_tail_sep=}" ;;
+  --tag-tail-sep)
+    if [ $# -gt 1 ]; then
+      ctx_tail_sep="$2"
+      shift
+    else
+      printf "Error: Missing value for %s\n" "$1" >&2
+      return 1
+    fi
+    ;;
+  --msg=*) msg="${1#--msg=}" ;;
   --msg)
     if [ $# -gt 1 ]; then
-      msg="$2"
+      msg="$(printf "%b" "$2")"
       shift
     else
       printf "Error: Missing value for --msg\n" >&2
       return 1
     fi
     ;;
-  --ctx=*)
-    ctx="${1#--ctx=}"
-    ;;
-  --tag=*)
-    tag="${1#--tag=}"
-    ;;
-  --msg=*)
-    msg="${1#--msg=}"
-    ;;
   --)
-    #~@ End of options, remaining args become message
+    #{ End of options, remaining args become message
     shift
     msg="$*"
     break
     ;;
-  --*)
-    #~@ Unknown option, ignore
-    ;;
+  --*) ;; #? Unknown option, ignore
   *)
-    #~@ If no explicit --msg flag, treat remaining args as message
-    if [ -z "${msg}" ]; then
-      msg="$*"
-      break
-    fi
+    # msg="${msg}${msg:+${delimiter}}${1}"
+    msg="${msg}${msg:+${delimiter}}$(printf "%b" "$1")"
     ;;
   esac
   shift
 done
 
-#~@ Return early if no message is provided
+echo "${msg}"
+exit 0
+
+#{ Return early if no message is provided
 if [ -z "${msg}" ]; then
   return 0
 fi
 
-#~@ Fallback to context variables if not set
-if [ -z "${ctx}" ]; then ctx="${fn_name:-}"; fi
-if [ -z "${ctx}" ]; then ctx="${scr_name:-}"; fi
-if [ -z "${ctx}" ]; then ctx="${scr_path:-}"; fi
-if [ -z "${ctx}" ]; then ctx="script"; fi
+#{ Update the context
+: "${ctx_head_sep:=" >>= "}"
+: "${ctx_tail_sep:=" =<< "}"
+if [ -n "${ctx:-}" ]; then
+  ctx="${ctx_head_sep}${ctx}${ctx_tail_sep}"
+fi
 
-#~@ Default tag to DEBUG if not provided
+#{ Update the tag
 if [ -z "${tag}" ]; then tag="DEBUG"; fi
 tag="$(printf "%s" "${tag}" | tr '[:lower:]' '[:upper:]')"
 
-#~@ Default separators
-: "${tag_head_sep:=" >>= "}"
-: "${tag_tail_sep:=" =<< "}"
-
-#~@ Format and print the message
-printf "\n%s%s%s%s%s\n" "${tag_head_sep}" "${tag}" "${tag_tail_sep}" "${ctx}" "${msg}"
+#{ Format and print the message
+ifs="${IFS}"
+IFS="${delimiter}"
+# shellcheck disable=SC2086
+set -- ${msg}
+printf "%s%s%s\n" "${tag}" "${ctx}" "$@"
+IFS="${ifs}"
diff --git a/Bin/shellscript/output/poutFIX b/Bin/shellscript/output/poutFIX
--- a/Bin/shellscript/output/poutFIX
+++ b/Bin/shellscript/output/poutFIX
@@ -141,16 +141,16 @@ set_verbosity() {
   #DOC     4: debug (verbose)
   #DOC     5: trace
 
-  #~@ Take defaults from system variables
+  #{ Take defaults from system variables
   _verbosity="${VERBOSITY:-"$VERBOSE"}"
   _quiet="${SILENT:-"$QUIET"}"
 
-  #~@ Take defaults from local variables
+  #{ Take defaults from local variables
   verbosity="${verbosity:-"$_verbosity"}"
   quiet="${quiet:-"$_quiet"}"
   case "${quiet:-"$_quiet"}" in true | 1 | on) verbosity=0 ;; esac
 
-  #~@ Set verbosity based on arguments or defaults
+  #{ Set verbosity based on arguments or defaults
   case "${1:-"$verbosity"}" in
   0 | quiet | false | off) verbosity=0 ;;
   1 | error | fail*) verbosity=1 ;;
@@ -162,7 +162,7 @@ set_verbosity() {
   *) verbosity=3 ;;
   esac
 
-  #~@ Parse arguments
+  #{ Parse arguments
   for arg in "$@"; do
     case "$arg" in
     -q | --quiet) verbosity=0 ;;
@@ -174,11 +174,11 @@ set_verbosity() {
     esac
   done
 
-  #~@ Clamp values
+  #{ Clamp values
   [ "$verbosity" -gt 5 ] && verbosity=5
   [ "$verbosity" -lt 0 ] && verbosity=0
 
-  #~@ Return verbosity level
+  #{ Return verbosity level
   printf "%s" "$verbosity"
 }
 
@@ -371,7 +371,7 @@ parse_arguments() {
     -*type)
       if [ "$2" ]; then
         __msg_type="$(validate "$2" "$__msg_types")"
-        #~@ Throw error if message type is invalid
+        #{ Throw error if message type is invalid
         [ -n "$__msg_type" ] || {
           templates --invalid "parse_arguments" "message type" "$2" "$__msg_types"
           __code=1
@@ -379,7 +379,7 @@ parse_arguments() {
         }
         shift
       else
-        #~@ Throw error if message type is not specified
+        #{ Throw error if message type is not specified
         pout --name "parse_arguments" --type error --msg "Message type not specified"
         __code=1
         exit "$__code"
@@ -463,10 +463,10 @@ print_blank() {
 }
 
 print_out() {
-  #~@ Return early if verbosity is set to 0/quiet
+  #{ Return early if verbosity is set to 0/quiet
   [ "$__level" -eq "$__level_quiet" ] && exit "$__code"
 
-  #~@ Format the title with consistent spacing and color handling
+  #{ Format the title with consistent spacing and color handling
   case "$__msg_type" in
   err*)
     [ "$__level" -ge "$__level_error" ] || exit "$__code"
@@ -499,12 +499,12 @@ print_out() {
   normal | simple | *) unset __title __tag __color ;;
   esac
 
-  #~@ Format the tag with proper color handling
+  #{ Format the tag with proper color handling
   [ "$__tag" ] && __tag="$(
     printf '%b%s%b' "$__highlight" " $__tag /> " "$__normal"
   )"
 
-  #~@ Define the output stream and exit "$__code" code
+  #{ Define the output stream and exit "$__code" code
   case "$__msg_type" in
   err* | fail*)
     __code="${__code:-1}"
@@ -518,20 +518,20 @@ print_out() {
     ;;
   esac
 
-  #~@ Print leading lines, if requested
+  #{ Print leading lines, if requested
   print_blank "$__lead_lines"
 
-  #~@ Print the message with proper formatting
+  #{ Print the message with proper formatting
   if [ "$__title" ] || [ "$__tag" ]; then
     printf '%s%s%s' "$__title" "$__tag" "$__msg" >&"$__stream"
   else
     printf '%s' "$__msg" >&"$__stream"
   fi
 
-  #~@ Print trailing lines, if requested
+  #{ Print trailing lines, if requested
   print_blank "$__trail_lines"
 
-  #~@ Return the exit code
+  #{ Return the exit code
   exit "$__code"
 }
 
