so much bash

diff --git a/Bin/shellscript/environment/pathman b/Bin/shellscript/environment/pathman
--- a/Bin/shellscript/environment/pathman
+++ b/Bin/shellscript/environment/pathman
@@ -4,7 +4,6 @@
 #TODO: Remove unused variables and replace get_absolute_path
 
 main() {
-  echo pathman
   set_defaults
   parse_arguments "$@"
   perform_action
@@ -28,38 +27,38 @@ set_defaults() {
   IFS="${delimiter}"
 
   #| Process Variables
-  # action="show"
+  action="show"
   print_raw=0
   paths=""
 
   #| Commands
-  cache_commands pathof bat fd realpath readlink rg
+  # cache_commands pathof bat fd realpath readlink rg
 }
 
 set_modes() {
   #| Verbosity
   case "${verbosity:-}" in
-    0 | off | false | quiet) verbosity=0 ;;
-    1 | err*) verbosity=1 ;;
-    2 | warn*) verbosity=2 ;;
-    3 | info*) verbosity=3 ;;
-    4 | debug) verbosity=4 ;;
-    5 | trace) verbosity=5 ;;
-    *) verbosity=3 ;;
+  0 | off | false | quiet) verbosity=0 ;;
+  1 | err*) verbosity=1 ;;
+  2 | warn*) verbosity=2 ;;
+  3 | info*) verbosity=3 ;;
+  4 | debug) verbosity=4 ;;
+  5 | trace) verbosity=5 ;;
+  *) verbosity=3 ;;
   esac
 
   #| Error Strictness
   case "${strict:-}" in
-    1 | on | yes | true)
-      set -e
-      set -u
-      ;;
-    0 | off | no | false) return ;;
-    *)
-      pout --error "Invalid 'strict' mode" ": [${strict}]" \
-        "\nAvailable modes are: 0, true, 1, false"
-      exit 1
-      ;;
+  1 | on | yes | true)
+    set -e
+    set -u
+    ;;
+  0 | off | no | false) return ;;
+  *)
+    pout --error "Invalid 'strict' mode" ": [${strict}]" \
+      "\nAvailable modes are: 0, true, 1, false"
+    exit 1
+    ;;
   esac
 
 }
@@ -74,7 +73,7 @@ cache_commands() {
     pout --debug --key "[${cmd}] CMD_KEY" --val "${cmd_key}"
 
     #@ Retrieve the path, otherwise return empty string
-    cmd_val="$(command -v "${cmd}" 2> /dev/null || printf '')"
+    cmd_val="$(command -v "${cmd}" 2>/dev/null || printf '')"
     pout --debug --key "[${cmd}] CMD_VAL" --val "${cmd_val}"
 
     #@ Create the environment variable of the command's location
@@ -87,62 +86,62 @@ cache_commands() {
 parse_arguments() {
   while [ "$#" -gt 0 ]; do
     case "$1" in
-      --debug)
-        debug="debug"
-        ;;
-      --error) verbosity=1 ;;
-      --quiet) verbosity=0 ;;
-      --action)
-        if [ -n "$2" ]; then
-          action="$2"
-          shift
-        else
-          pout --error "Missing argument for '$1'" \
-            "\nAvailable modes are: append, prepend, show"
-          return 1
-        fi
-        ;;
-      --path-show)
-        action="show"
-        ;;
-      --path-clean)
-        action="clean"
-        ;;
-      --path-check)
-        action="check"
-        ;;
-      --path-append)
-        action="append"
-        ;;
-      --path-prepend)
-        action="prepend"
-        ;;
-      --path-print)
-        print_raw=1
-        ;;
-      --dir*)
-        if [ -n "${2:-}" ]; then
-          shift
-          if [ -n "${paths}" ]; then
-            paths="$(printf '%s%s%s' "${paths}" "${delimiter}" "$(get_absolute_path "$1")")"
-          else
-            paths="$(get_absolute_path "$1")"
-          fi
-        else
-          printf "'%s' requires an argument\n" "$1"
-          return 1
-        fi
-        ;;
-      *)
-        if [ -f "$1" ]; then
-          make_exec "$1"
-          return 0
-        elif [ -n "${paths}" ]; then
+    --debug)
+      debug="debug"
+      ;;
+    --error) verbosity=1 ;;
+    --quiet) verbosity=0 ;;
+    --action)
+      if [ -n "$2" ]; then
+        action="$2"
+        shift
+      else
+        pout --error "Missing argument for '$1'" \
+          "\nAvailable modes are: append, prepend, show"
+        return 1
+      fi
+      ;;
+    --path-show)
+      action="show"
+      ;;
+    --path-clean)
+      action="clean"
+      ;;
+    --path-check)
+      action="check"
+      ;;
+    --path-append)
+      action="append"
+      ;;
+    --path-prepend)
+      action="prepend"
+      ;;
+    --path-print)
+      print_raw=1
+      ;;
+    --dir*)
+      if [ -n "${2:-}" ]; then
+        shift
+        if [ -n "${paths}" ]; then
           paths="$(printf '%s%s%s' "${paths}" "${delimiter}" "$(get_absolute_path "$1")")"
         else
           paths="$(get_absolute_path "$1")"
         fi
-        ;;
+      else
+        printf "'%s' requires an argument\n" "$1"
+        return 1
+      fi
+      ;;
+    *)
+      if [ -f "$1" ]; then
+        make_exec "$1"
+        return 0
+      elif [ -n "${paths}" ]; then
+        paths="$(printf '%s%s%s' "${paths}" "${delimiter}" "$(get_absolute_path "$1")")"
+      else
+        paths="$(get_absolute_path "$1")"
+      fi
+      ;;
     esac
     shift
   done
@@ -157,8 +156,14 @@ parse_arguments() {
 }
 
 perform_action() {
-  for path in ${paths}; do
-    case "${action:-}" in
+  case "${action:-}" in
+  check)
+    #TODO: Implement check
+    return 0
+    ;;
+  append | prepend)
+    for path in ${paths}; do
+      case "${action:-}" in
       append | prepend)
         #@ Validate that a directory was provided
         if [ -z "${paths}" ]; then
@@ -176,23 +181,33 @@ perform_action() {
       clean)
         clean_path
         ;;
-      show) show_bins ;;
+      show)
+        echo here
+        show_bins
+        ;;
       check | *)
         check_for_path() {
           case "${PATH}" in
-            "${path}:"* | *":${1:-}:"* | *":${1:-}")
-              printf '%s is in PATH\n' "${1:-}"
-              ;;
-            *)
-              printf '%s is not in PATH\n' "${1:-}"
-              ;;
+          "${path}:"* | *":${1:-}:"* | *":${1:-}")
+            printf '%s is in PATH\n' "${1:-}"
+            ;;
+          *)
+            printf '%s is not in PATH\n' "${1:-}"
+            ;;
           esac
         }
 
         check_for_path "${path}"
         ;;
-    esac
-  done
+      esac
+    done
+    ;;
+  show | *)
+    #@ Default action
+    show_bins
+    return 1
+    ;;
+  esac
 }
 
 get_absolute_path() {
@@ -233,7 +248,7 @@ set_paths() {
     EXCLUDE_PATTERNS="review temp tmp archive backup"
 
     #@ Collect paths
-    for find_path in $paths; do
+    for find_path in ${paths}; do
 
       #@ Skip non-existent paths
       [ -e "${find_path}" ] || continue
@@ -251,23 +266,23 @@ set_paths() {
 
         if [ -d "${find_path}" ]; then
           #@ Include the lookup path
-          printf "%s\n" "${find_path}" | tee -a "${DIRES}" > /dev/null
+          printf "%s\n" "${find_path}" | tee -a "${DIRES}" >/dev/null
 
           #@ Define the find options
           find_files="--type file ${find_omit}"
           find_dires="--type directory ${find_omit}"
         else
           #@ Include the lookup path
-          printf "%s\n" "${find_path}" | tee -a "${FILES}" > /dev/null
+          printf "%s\n" "${find_path}" | tee -a "${FILES}" >/dev/null
         fi
 
         #@ Update the directories file
-        eval "${find_cmd}" "${find_path}" "${find_dires}" \
-          | tee -a "${DIRES}" > /dev/null
+        eval "${find_cmd}" "${find_path}" "${find_dires}" |
+          tee -a "${DIRES}" >/dev/null
 
         #@ Update the files file
-        eval "${find_cmd}" "${find_path}" "${find_files}" \
-          | tee -a "${FILES}" > /dev/null
+        eval "${find_cmd}" "${find_path}" "${find_files}" |
+          tee -a "${FILES}" >/dev/null
       else
         #@ Define the base command
         find_cmd="find"
@@ -284,10 +299,10 @@ set_paths() {
       fi
 
       #@ Update the directories file
-      eval "${find_cmd}" "${find_path}" "${find_dires}" | tee -a "${DIRES}" > /dev/null
+      eval "${find_cmd}" "${find_path}" "${find_dires}" | tee -a "${DIRES}" >/dev/null
 
       #@ Update the files file
-      eval "${find_cmd} ${find_path} ${find_files}" | tee -a "${FILES}" > /dev/null
+      eval "${find_cmd} ${find_path} ${find_files}" | tee -a "${FILES}" >/dev/null
     done
 
     cat "${FILES}"
@@ -306,13 +321,13 @@ set_paths() {
 
 os_type() {
   case "$(uname -a | tr '[:upper:]' '[:lower:]')" in
-    *linux*) os_type="linux" ;;
-    *darwin*) os_type="mac" ;;
-    *) os_type="windows" ;;
+  *linux*) os_type="linux" ;;
+  *darwin*) os_type="mac" ;;
+  *) os_type="windows" ;;
   esac
 
   #TODO This is utterly inadequate, just temporary
-  printf "%s" "$os_type"
+  printf "%s" "${os_type}"
 }
 
 show_bins() {
@@ -320,9 +335,9 @@ show_bins() {
     printf "%s\n" "${PATH}"
     return
   else
-    printf "%s\n" "${PATH}" | tr ':' '\n' \
-      | eval "$(
-        if [ -n "${CMD_BAT}" ]; then
+    printf "%s\n" "${PATH}" | tr ':' '\n' |
+      eval "$(
+        if [ -n "${CMD_BAT:-}" ]; then
           printf "%s" "${CMD_BAT} --color=always --style=grid --plain --number"
         else
           printf "nl -s '  ' | less"
@@ -333,8 +348,8 @@ show_bins() {
 
 is_absolute_path() {
   case "$1" in
-    /*) return 0 ;; # Path starts with /, so it's absolute
-    *) return 1 ;;  # Otherwise, it's not absolute
+  /*) return 0 ;; # Path starts with /, so it's absolute
+  *) return 1 ;;  # Otherwise, it's not absolute
   esac
 }
 
@@ -363,7 +378,7 @@ clean_path() {
 make_exec() {
   _file=$1
   chmod_status=0
-  chmod +x "$_file" > /dev/null 2>&1
+  chmod +x "$_file" >/dev/null 2>&1
   chmod_status=$?
   [ "$verbosity" -gt 1 ] && {
     if [ "$chmod_status" -eq 0 ]; then
@@ -387,32 +402,32 @@ add_to_path_ORIG() {
 
   #@ Update PATH directories recursively
   recursive_paths "${paths}" | while IFS= read -r bin_path; do
-    [ -d "${bin_path}" ] \
-      && case ":${PATH}:" in
-        *:"${bin_path}":*) ;;
-        *)
-          case "${action:-}" in
-            prepend)
-              NEW_PATH="${bin_path}${PATH:+:${PATH}}"
-              _action="Appended"
-              ;;
-            append | *)
-              NEW_PATH="${PATH:+${PATH}:}${bin_path}"
-              _action="Perpended"
-              ;;
-          esac
-
-          [ "${verbosity}" -gt 1 ] \
-            && printf "    %s to PATH: %s\n" "$_action" "${bin_path}"
+    [ -d "${bin_path}" ] &&
+      case ":${PATH}:" in
+      *:"${bin_path}":*) ;;
+      *)
+        case "${action:-}" in
+        prepend)
+          NEW_PATH="${bin_path}${PATH:+:${PATH}}"
+          _action="Appended"
           ;;
+        append | *)
+          NEW_PATH="${PATH:+${PATH}:}${bin_path}"
+          _action="Perpended"
+          ;;
+        esac
+
+        [ "${verbosity}" -gt 1 ] &&
+          printf "    %s to PATH: %s\n" "$_action" "${bin_path}"
+        ;;
       esac
 
     #@ Make scripts executable
-    [ -f "${bin_path}" ] \
-      && case "$(os_type)" in windows) ;;
+    [ -f "${bin_path}" ] &&
+      case "$(os_type)" in windows) ;;
       *)
         chmod_status=0
-        chmod +x "${bin_path}" > /dev/null 2>&1
+        chmod +x "${bin_path}" >/dev/null 2>&1
         chmod_status=$?
 
         [ "$verbosity" -gt 1 ] && {
@@ -433,44 +448,44 @@ add_to_path_ORIG() {
 
 add_to_path() {
   tmp_path=$(mktemp) || return 1 #TODO: Use tempgen
-  recursive_paths "${paths}" > "${tmp_path}"
+  recursive_paths "${paths}" >"${tmp_path}"
 
   if [ "${debug}" ]; then
     counter=1
     while IFS= read -r bin_path; do
       printf "  %4d %s\n" "${counter}" "${bin_path}"
       counter=$((counter + 1))
-    done < "${tmp_path}"
+    done <"${tmp_path}"
     rm "${tmp_path}"
     return 0
   fi
 
   while IFS= read -r bin_path; do
-    [ -d "${bin_path}" ] \
-      && case ":${PATH}:" in
-        *:"${bin_path}":*) ;;
-        *)
-          case "${action}" in
-            prepend)
-              PATH="${bin_path}${PATH:+:${PATH}}"
-              action_str="Appended"
-              ;;
-            append | *)
-              PATH="${PATH:+${PATH}:}${bin_path}"
-              action_str="Perpended"
-              ;;
-          esac
-          [ -d "$bin_path" ] && umask 022 && chmod 755 "$bin_path" #TODO: This is not working. Files created after running the script are not automatically executable.
-          [ "${verbosity}" -gt 1 ] \
-            && printf "    %s to PATH: %s\n" "${action_str}" "${bin_path}"
+    [ -d "${bin_path}" ] &&
+      case ":${PATH}:" in
+      *:"${bin_path}":*) ;;
+      *)
+        case "${action}" in
+        prepend)
+          PATH="${bin_path}${PATH:+:${PATH}}"
+          action_str="Appended"
           ;;
+        append | *)
+          PATH="${PATH:+${PATH}:}${bin_path}"
+          action_str="Perpended"
+          ;;
+        esac
+        [ -d "$bin_path" ] && umask 022 && chmod 755 "$bin_path" #TODO: This is not working. Files created after running the script are not automatically executable.
+        [ "${verbosity}" -gt 1 ] &&
+          printf "    %s to PATH: %s\n" "${action_str}" "${bin_path}"
+        ;;
       esac
 
-    [ -f "${bin_path}" ] \
-      && case "$(os_type)" in windows) ;;
+    [ -f "${bin_path}" ] &&
+      case "$(os_type)" in windows) ;;
       *) make_exec "${bin_path}" ;;
       esac
-  done < "${tmp_path}"
+  done <"${tmp_path}"
 
   rm "${tmp_path}"
   [ "${verbosity}" -gt 1 ] && show_bins
@@ -484,15 +499,15 @@ update_path() {
   #@ Build updated path
   while IFS= read -r dir; do
     case "$TMP_PATH" in
-      *":$dir:"* | *":$dir:"* | *"$dir:"* | *"$dir"*) ;;
-      *)
-        case "$action" in
-          prepend) TMP_PATH="${dir}${TMP_PATH:+:$TMP_PATH}" ;;
-          append | *) TMP_PATH="${TMP_PATH:+${TMP_PATH}:}${dir}" ;;
-        esac
-        ;;
+    *":$dir:"* | *":$dir:"* | *"$dir:"* | *"$dir"*) ;;
+    *)
+      case "$action" in
+      prepend) TMP_PATH="${dir}${TMP_PATH:+:$TMP_PATH}" ;;
+      append | *) TMP_PATH="${TMP_PATH:+${TMP_PATH}:}${dir}" ;;
+      esac
+      ;;
     esac
-  done < "$DIRES"
+  done <"$DIRES"
   unset IFS
 
   #@ Print or export the PATH variable
@@ -508,18 +523,18 @@ update_path() {
 list() {
   while [ "$#" -ge 1 ]; do
     case "$1" in
-      --create | --make | --build)
-        action=build
-        ;;
-      *) item="${item:+${item}${delimiter}}$1" ;;
+    --create | --make | --build)
+      action=build
+      ;;
+    *) item="${item:+${item}${delimiter}}$1" ;;
     esac
     shift
   done
 
   case "${action}" in
-    build) printf "%s" "${item}" ;;
-    parse) ;;
-    *) ;;
+  build) printf "%s" "${item}" ;;
+  parse) ;;
+  *) ;;
   esac
 }
 
@@ -534,29 +549,29 @@ pout() {
   #@ Parse message type and content
   while [ "$#" -gt 0 ]; do
     case "$1" in
-      -k | --key) key="$2" shift ;;
-      -v | --val) val="$2" shift ;;
-      -d | --debug)
-        if [ "${verbosity:-0}" -ge 4 ]; then
-          tag="DEBUG"
-        else
-          return
-        fi
-        ;;
-      -e | --error) tag="ERROR" ;;
-      -w | --warn) tag=" WARN" ;;
-      --no-trim) unset trim ;;
-      --usage)
-        usage_guide
-        exit 0
-        ;;
-      --version)
-        printf "%s\n" "${cmd_VERSION}"
-        exit 0
-        ;;
-      *)
-        msg="${msg:-}${msg:+${delimiter}}${1}"
-        ;;
+    -k | --key) key="$2" shift ;;
+    -v | --val) val="$2" shift ;;
+    -d | --debug)
+      if [ "${verbosity:-0}" -ge 4 ]; then
+        tag="DEBUG"
+      else
+        return
+      fi
+      ;;
+    -e | --error) tag="ERROR" ;;
+    -w | --warn) tag=" WARN" ;;
+    --no-trim) unset trim ;;
+    --usage)
+      usage_guide
+      exit 0
+      ;;
+    --version)
+      printf "%s\n" "${cmd_VERSION}"
+      exit 0
+      ;;
+    *)
+      msg="${msg:-}${msg:+${delimiter}}${1}"
+      ;;
     esac
     shift
   done
@@ -574,47 +589,47 @@ pout() {
     fi
 
     case "${tag}" in
-      *DEBUG* | *ERROR* | *WARN* | *INFO*)
-        #@ Define the separator
-        sep=" | "
+    *DEBUG* | *ERROR* | *WARN* | *INFO*)
+      #@ Define the separator
+      sep=" | "
 
-        #@ Calculate padding for label alignment
-        debug_pad="${debug_pad:-18}"
-        pad="$(printf "%*s" "$((debug_pad - ${#key}))" "")"
+      #@ Calculate padding for label alignment
+      debug_pad="${debug_pad:-18}"
+      pad="$(printf "%*s" "$((debug_pad - ${#key}))" "")"
 
-        #@ Format the tagged key-value pair
-        msg="$(
-          printf "[%s] /> %s <\ %s%s%s%s\n" \
-            "${tag}" "${cmd_NAME}" "${pad}" "${key}" "${sep}" "${val}"
-        )"
-        ;;
-      *)
-        #@ Define the separator
-        sep=": "
+      #@ Format the tagged key-value pair
+      msg="$(
+        printf "[%s] /> %s <\ %s%s%s%s\n" \
+          "${tag}" "${cmd_NAME}" "${pad}" "${key}" "${sep}" "${val}"
+      )"
+      ;;
+    *)
+      #@ Define the separator
+      sep=": "
 
-        #@ Print the key-value pair
-        msg="$(
-          printf "%s%s%s\n" "${key}" "${sep}" "${val}"
-        )"
-        ;;
+      #@ Print the key-value pair
+      msg="$(
+        printf "%s%s%s\n" "${key}" "${sep}" "${val}"
+      )"
+      ;;
     esac
   else
     case "${tag}" in
-      *DEBUG* | *ERROR* | *WARN* | *INFO*)
-        #@ Format the tagged message
-        msg="$(
-          printf "[%s] /> %s <\ %b\n" \
-            "${tag}" "${cmd_NAME}" "${msg}"
-        )"
-        ;;
-      *) msg="$(trim "${msg}")" ;;
+    *DEBUG* | *ERROR* | *WARN* | *INFO*)
+      #@ Format the tagged message
+      msg="$(
+        printf "[%s] /> %s <\ %b\n" \
+          "${tag}" "${cmd_NAME}" "${msg}"
+      )"
+      ;;
+    *) msg="$(trim "${msg}")" ;;
     esac
   fi
 
   #@ Print the message
   case "${tag}" in
-    ERROR | WARN) printf "%s\n" "${msg}" >&2 ;;
-    *) printf "%s\n" "${msg}" ;;
+  ERROR | WARN) printf "%s\n" "${msg}" >&2 ;;
+  *) printf "%s\n" "${msg}" ;;
   esac
 }
 
