Working on the devshell and formatter integration

diff --git a/Bin/shellscript/environment/symbiolink b/Bin/shellscript/environment/symbiolink
--- a/Bin/shellscript/environment/symbiolink
+++ b/Bin/shellscript/environment/symbiolink
@@ -7,7 +7,7 @@ _cmd_VERSION="1.0"
 _cmd_DESCRIPTION="Create a symbolic link between files"
 _cmd_DEPENDENCIES="coreutils."
 _cmd_USAGEGUIDE="$(
-  cat << USAGE_GUIDE
+  cat <<USAGE_GUIDE
 |---------------------------------------------------->
   $_cmd_NAME>=> $_cmd_DESCRIPTION
 |---------------------------------------------------->
@@ -35,27 +35,27 @@ __version__() { printf "%s\n" "$_cmd_VERSION"; }
 #@ Accept user options/flags
 __opts__() {
   case "$1" in
-    -h | --help)
-      __help__
-      exit
-      ;;
-    -v | --version)
-      __version__
-      exit
-      ;;
-    -d | --verbose) verbose=true ;;
-    -q | --quiet) unset verbose ;;
-    -f | --force | --reset) force=true ;;
-    -s | --src | --source | --origin)
-      src_path="$2"
-      shift
-      ;;
-    -l | --lnk | --link | --destination)
-      lnk_path="$2"
-      shift
-      ;;
-    -*) __error__ --invalid-opt "$1" ;;
-    *) ;;
+  -h | --help)
+    __help__
+    exit
+    ;;
+  -v | --version)
+    __version__
+    exit
+    ;;
+  -d | --verbose) verbose=true ;;
+  -q | --quiet) unset verbose ;;
+  -f | --force | --reset) force=true ;;
+  -s | --src | --source | --origin)
+    src_path="$2"
+    shift
+    ;;
+  -l | --lnk | --link | --destination)
+    lnk_path="$2"
+    shift
+    ;;
+  -*) __error__ --invalid-opt "$1" ;;
+  *) ;;
   esac
 }
 
@@ -131,18 +131,18 @@ __mkdir__() {
       "$lnk_parent"
 
     case "$(read_char)" in
-      [Yy])
-        #@ Make directory
-        if [ "$owned" ]; then
-          mkdir --parents "$lnk_parent"
-        else
-          sudo mkdir --parents "$lnk_parent"
-        fi
-        ;;
-      *)
-        printf "Exiting...\n"
-        exit 1
-        ;;
+    [Yy])
+      #@ Make directory
+      if [ "$owned" ]; then
+        mkdir --parents "$lnk_parent"
+      else
+        sudo mkdir --parents "$lnk_parent"
+      fi
+      ;;
+    *)
+      printf "Exiting...\n"
+      exit 1
+      ;;
     esac
   done
 
@@ -184,13 +184,13 @@ __msg__() {
   linked="$lnk_path ==> $src_path"
 
   case $1 in
-    --valid) msg="Valid Link: $linked" ;;
-    --linked) msg="Established Link: $linked" ;;
-    --owned) msg="The destination directory is owned by the current user." ;;
-    --args) msg="::❗:: 2 arguments were expected but $# was given.\n" ;;
-    --no-source) msg="Source is undefined" ;;
-    --no-link) msg="Link is undefined" ;;
-    --create-parent) msg="Destination directory doesnt exist: $lnk_parent" ;;
+  --valid) msg="Valid Link: $linked" ;;
+  --linked) msg="Established Link: $linked" ;;
+  --owned) msg="The destination directory is owned by the current user." ;;
+  --args) msg="::❗:: 2 arguments were expected but $# was given.\n" ;;
+  --no-source) msg="Source is undefined" ;;
+  --no-link) msg="Link is undefined" ;;
+  --create-parent) msg="Destination directory doesnt exist: $lnk_parent" ;;
   esac
 
   printf "%s\n" "$msg"
@@ -198,34 +198,34 @@ __msg__() {
 
 __error__() {
   case $1 in
-    --args)
-      shift
-      printf "::❗:: 2 arguments were expected but %s was given.\n" "$@"
-      # __msg__ --args "$@"
-      ;;
-    --args-source) __msg__ --no-source ;;
-    --args-link) __msg__ --no-link ;;
-    --source)
-      shift
-      printf "Invalid source: %s\n" "$@"
-      ;;
-    --exists)
-      shift
-      [ "$verbose" ] && printf "Path Exists: %s\n" "$@"
-      ;;
-    --missing)
-      shift
-      [ "$verbose" ] && printf "Path Missing: %s\n" "$@"
-      ;;
-    --linkdir)
-      shift
-      printf "Destination directory doesnt exist: %s\n" "$(dirname "$@")"
-      ;;
-    --invalid-opt)
-      shift
-      printf "Unknown Option: %s\n" "$@"
-      ;;
-    *) ;;
+  --args)
+    shift
+    printf "::❗:: 2 arguments were expected but %s was given.\n" "$@"
+    # __msg__ --args "$@"
+    ;;
+  --args-source) __msg__ --no-source ;;
+  --args-link) __msg__ --no-link ;;
+  --source)
+    shift
+    printf "Invalid source: %s\n" "$@"
+    ;;
+  --exists)
+    shift
+    [ "$verbose" ] && printf "Path Exists: %s\n" "$@"
+    ;;
+  --missing)
+    shift
+    [ "$verbose" ] && printf "Path Missing: %s\n" "$@"
+    ;;
+  --linkdir)
+    shift
+    printf "Destination directory doesnt exist: %s\n" "$(dirname "$@")"
+    ;;
+  --invalid-opt)
+    shift
+    printf "Unknown Option: %s\n" "$@"
+    ;;
+  *) ;;
   esac
 
   __help__
@@ -234,8 +234,8 @@ __error__() {
 
 __exit__() {
   case "$1" in
-    --success) exit 0 ;;
-    --failure) exit 1 ;;
+  --success) exit 0 ;;
+  --failure) exit 1 ;;
   esac
 }
 
diff --git a/Bin/shellscript/packages/alias/ede b/Bin/shellscript/packages/alias/ede
--- a/Bin/shellscript/packages/alias/ede
+++ b/Bin/shellscript/packages/alias/ede
@@ -49,57 +49,57 @@ set_defaults() {
 parse_arguments() {
   while [ "$#" -ge 1 ]; do
     case "$1" in
-      -h | --help)
-        printf "%s\n" "$scr_HELP"
-        exit 0
-        ;;
-      -v | --version)
-        printf "%s\n" "$scr_VERSION"
-        exit 0
-        ;;
-      -q | --quiet) unset debug ;;
-      -d | --debug) debug=1 ;;
-      -t | --tui)
-        [ "$2" ] || {
-          printf "Error: '%s' requires an argument\n" "$1"
-          exit 2
-        }
-        while [ "$#" -ge 2 ]; do
-          case "$2" in
-            --*) break ;;
-            *) preferred_tui="${preferred_tui:+$preferred_tui${DELIMITER}}$2" ;;
-          esac
-          shift
-        done
-        ;;
-      -g | --gui)
-        [ "$2" ] || {
-          printf "Error: '%s' requires an argument\n" "$1"
-          exit 2
-        }
-        while [ "$#" -ge 2 ]; do
-          case "$2" in
-            --*) break ;;
-            *) preferred_gui="${preferred_gui:+$preferred_gui${DELIMITER}}$2" ;;
-          esac
-          shift
-        done
-        ;;
-      -e | --editor | --ede)
-        [ "$2" ] || {
-          printf "Error: '%s' requires an argument\n" "$1"
-          exit 2
-        }
-        while [ "$#" -ge 2 ]; do
-          case "$2" in
-            --*) break ;;
-            *) preferred_ede="${preferred_ede:+$preferred_ede${DELIMITER}}$2" ;;
-          esac
-          shift
-        done
-        ;;
-      --) ;;
-      *) args="${args:+$args${DELIMITER}}$2" ;;
+    -h | --help)
+      printf "%s\n" "$scr_HELP"
+      exit 0
+      ;;
+    -v | --version)
+      printf "%s\n" "$scr_VERSION"
+      exit 0
+      ;;
+    -q | --quiet) unset debug ;;
+    -d | --debug) debug=1 ;;
+    -t | --tui)
+      [ "$2" ] || {
+        printf "Error: '%s' requires an argument\n" "$1"
+        exit 2
+      }
+      while [ "$#" -ge 2 ]; do
+        case "$2" in
+        --*) break ;;
+        *) preferred_tui="${preferred_tui:+$preferred_tui${DELIMITER}}$2" ;;
+        esac
+        shift
+      done
+      ;;
+    -g | --gui)
+      [ "$2" ] || {
+        printf "Error: '%s' requires an argument\n" "$1"
+        exit 2
+      }
+      while [ "$#" -ge 2 ]; do
+        case "$2" in
+        --*) break ;;
+        *) preferred_gui="${preferred_gui:+$preferred_gui${DELIMITER}}$2" ;;
+        esac
+        shift
+      done
+      ;;
+    -e | --editor | --ede)
+      [ "$2" ] || {
+        printf "Error: '%s' requires an argument\n" "$1"
+        exit 2
+      }
+      while [ "$#" -ge 2 ]; do
+        case "$2" in
+        --*) break ;;
+        *) preferred_ede="${preferred_ede:+$preferred_ede${DELIMITER}}$2" ;;
+        esac
+        shift
+      done
+      ;;
+    --) ;;
+    *) args="${args:+$args${DELIMITER}}$2" ;;
     esac
     shift
   done
@@ -141,9 +141,9 @@ initialize_utilities() {
     input_delimiter="$1"
     output_delimiter="$2"
     shift 2
-    printf "%s" "$*" \
-      | sed "s/^$input_delimiter//" \
-      | sed "s/$input_delimiter/$output_delimiter/g"
+    printf "%s" "$*" |
+      sed "s/^$input_delimiter//" |
+      sed "s/$input_delimiter/$output_delimiter/g"
   }
 
   pout_highlight() {
@@ -174,31 +174,31 @@ initialize_utilities() {
     highlight_item="$3"
     input_list="$4"
 
-    pout_split "$input_delimiter" "$output_delimiter" "$input_list" \
-      | sed "s/\(^\|${output_delimiter}\)\($highlight_item\)\(,\|$\)/\1${FMT_HIGHLIGHT}${highlight_item}${FMT_NORMAL}\3/"
+    pout_split "$input_delimiter" "$output_delimiter" "$input_list" |
+      sed "s/\(^\|${output_delimiter}\)\($highlight_item\)\(,\|$\)/\1${FMT_HIGHLIGHT}${highlight_item}${FMT_NORMAL}\3/"
   }
 
   weHave() {
     [ "$#" -eq 0 ] && return 1
 
     case "$1" in
-      --first)
-        [ "$#" -ge 2 ] || {
-          printf "Error: --first requires an argument\n"
-          return 3
+    --first)
+      [ "$#" -ge 2 ] || {
+        printf "Error: --first requires an argument\n"
+        return 3
+      }
+      shift
+
+      for i in $(printf "%s" "$@" | tr " " "\n"); do
+        command -v "$i" >/dev/null 2>&1 && {
+          printf "%s" "$i"
+          return 0
         }
-        shift
+      done
 
-        for i in $(printf "%s" "$@" | tr " " "\n"); do
-          command -v "$i" > /dev/null 2>&1 && {
-            printf "%s" "$i"
-            return 0
-          }
-        done
-
-        return 1
-        ;;
-      *) command -v "$i" > /dev/null 2>&1 ;;
+      return 1
+      ;;
+    *) command -v "$i" >/dev/null 2>&1 ;;
     esac
   }
 }
diff --git a/Bin/shellscript/packages/defaults/SHell b/Bin/shellscript/packages/defaults/SHell
--- a/Bin/shellscript/packages/defaults/SHell
+++ b/Bin/shellscript/packages/defaults/SHell
@@ -38,7 +38,7 @@ __shell__() {
   }
   export PATH
 
-  type lsof 1> /dev/null 2>&1 || {
+  type lsof 1>/dev/null 2>&1 || {
     echo "lsof is required for this operation"
     exit 1
   }
@@ -52,21 +52,21 @@ __shell__() {
   }
 
   # shellcheck disable=SC2086
-  lsofstr="$(lsof -p $ppid)" \
-    || {
-      printf "%s\n" "lsof failed" "try: sudo lsof -p \`ps -p \$\$ -o ppid=\`"
+  lsofstr="$(lsof -p $ppid)" ||
+    {
+      printf "%s\n" "lsof failed" 'try: sudo lsof -p `ps -p $$ -o ppid=`'
       exit 1
     }
 
-  printf "%s\n" "${lsofstr}" \
-    | LC_ALL=C awk -v var="${awkstr}" '$NF ~ var {print $NF}'
+  printf "%s\n" "${lsofstr}" |
+    LC_ALL=C awk -v var="${awkstr}" '$NF ~ var {print $NF}'
 
 }
 
 # SHell
 case "$(__shell__)" in
-  *ash) neofetch ;;
-  *zsh) . "$RC_zsh" ;;
-  *fish) . "$RC_fish" ;;
-  *nu) . "$RC_nush" ;;
+*ash) neofetch ;;
+*zsh) . "$RC_zsh" ;;
+*fish) . "$RC_fish" ;;
+*nu) . "$RC_nush" ;;
 esac
diff --git a/Bin/shellscript/project/formatters/fmt_editorconfig b/Bin/shellscript/project/formatters/fmt_editorconfig
--- a/Bin/shellscript/project/formatters/fmt_editorconfig
+++ b/Bin/shellscript/project/formatters/fmt_editorconfig
@@ -189,8 +189,8 @@ initialize_mod_time_fetcher() {
     #DOC   Formatted date string on success
     #DOC   CODE_SYSTEM on failure
 
-    if _epoch=$(stat -f '%m' "$_path" 2> /dev/null); then
-      if _date=$(date -r "$_epoch" '+%Y-%m-%d %H:%M' 2> /dev/null); then
+    if _epoch=$(stat -f '%m' "$_path" 2>/dev/null); then
+      if _date=$(date -r "$_epoch" '+%Y-%m-%d %H:%M' 2>/dev/null); then
         printf "%s" "$_date"
         return "$CODE_SUCCESS"
       fi
@@ -212,8 +212,8 @@ initialize_mod_time_fetcher() {
     #DOC   Formatted date string on success
     #DOC   CODE_SYSTEM on failure
 
-    if _epoch=$(stat -c '%Y' "$_path" 2> /dev/null); then
-      if _date=$(date -d @"$_epoch" '+%Y-%m-%d %H:%M' 2> /dev/null); then
+    if _epoch=$(stat -c '%Y' "$_path" 2>/dev/null); then
+      if _date=$(date -d @"$_epoch" '+%Y-%m-%d %H:%M' 2>/dev/null); then
         printf "%s" "$_date"
         return "$CODE_SUCCESS"
       fi
@@ -238,17 +238,17 @@ initialize_mod_time_fetcher() {
     #DOC   Formatted date string on success
     #DOC   CODE_SYSTEM if all methods fail
 
-    if command -v perl > /dev/null 2>&1; then
-      if _epoch=$(perl -e 'printf("%d\n",(stat(shift))[9])' "$_path" 2> /dev/null); then
-        if _date=$(date -r "$_epoch" '+%Y-%m-%d %H:%M' 2> /dev/null); then
+    if command -v perl >/dev/null 2>&1; then
+      if _epoch=$(perl -e 'printf("%d\n",(stat(shift))[9])' "$_path" 2>/dev/null); then
+        if _date=$(date -r "$_epoch" '+%Y-%m-%d %H:%M' 2>/dev/null); then
           printf "%s" "$_date"
           return "$CODE_SUCCESS"
         fi
-        if _date=$(date -d @"$_epoch" '+%Y-%m-%d %H:%M' 2> /dev/null); then
+        if _date=$(date -d @"$_epoch" '+%Y-%m-%d %H:%M' 2>/dev/null); then
           printf "%s" "$_date"
           return "$CODE_SUCCESS"
         fi
-        if _date=$(perl -MPOSIX -e 'print strftime("%Y-%m-%d %H:%M", localtime(shift))' "$_epoch" 2> /dev/null); then
+        if _date=$(perl -MPOSIX -e 'print strftime("%Y-%m-%d %H:%M", localtime(shift))' "$_epoch" 2>/dev/null); then
           printf "%s" "$_date"
           return "$CODE_SUCCESS"
         fi
@@ -268,11 +268,11 @@ initialize_mod_time_fetcher() {
     test_file="/dev/null"
   fi
 
-  if stat -f '%m' "$test_file" > /dev/null 2>&1; then
+  if stat -f '%m' "$test_file" >/dev/null 2>&1; then
     MOD_TIME_FETCHER=get_mod_time_bsd
-  elif stat -c '%Y' "$test_file" > /dev/null 2>&1; then
+  elif stat -c '%Y' "$test_file" >/dev/null 2>&1; then
     MOD_TIME_FETCHER=get_mod_time_gnu
-  elif command -v perl > /dev/null 2>&1; then
+  elif command -v perl >/dev/null 2>&1; then
     MOD_TIME_FETCHER=get_mod_time_perl
   else
     MOD_TIME_FETCHER="" # fallback
@@ -303,14 +303,14 @@ initialize_utilities() {
     umask "$UMASK_USER"
 
     #@ Redirect stderr to /dev/null to suppress mktemp messages
-    if ! tmpfile=$(mktemp "${TMPDIR}/fmt.XXXXXX" 2> /dev/null); then
+    if ! tmpfile=$(mktemp "${TMPDIR}/fmt.XXXXXX" 2>/dev/null); then
 
       #@ Fallback to PID + random number
       tmpfile="${TMPDIR}/fmt.$$.$(awk \
-        'BEGIN {srand(); printf "%d", int(rand() * 1000000)}' 2> /dev/null)"
+        'BEGIN {srand(); printf "%d", int(rand() * 1000000)}' 2>/dev/null)"
 
       #@ Create the temporary file or return an error
-      if ! : > "$tmpfile"; then
+      if ! : >"$tmpfile"; then
         printf 'Failed to create temporary file\n' >&2
         return "$CODE_SYSTEM"
       fi
@@ -353,47 +353,47 @@ initialize_utilities() {
     #@ Parse arguments
     while [ $# -gt 0 ]; do
       case $1 in
-        -a | --file-a)
-          [ -z "$2" ] && {
-            printf 'Error: Missing argument for %s\n' "$1" >&2
-            return "$CODE_ARGS"
-          }
-
-          shift
-          file_a=$1
-          ;;
-        -b | --file-b)
-          [ -z "$2" ] && {
-            printf 'Error: Missing argument for %s\n' "$1" >&2
-            return "$CODE_ARGS"
-          }
-
-          shift
-          file_b=$1
-          ;;
-        -f | --filter)
-          [ -z "$2" ] && {
-            printf 'Error: Missing argument for %s\n' "$1" >&2
-            return "$CODE_ARGS"
-          }
-
-          shift
-          filter=$1
-          ;;
-        --help)
-          diff_sans_header__usage
-          return "$CODE_SUCCESS"
-          ;;
-        --)
-          shift
-          break
-          ;;
-        -*)
-          printf 'Unknown option: %s\n' "$1" >&2
-          diff_sans_header__usage >&2
+      -a | --file-a)
+        [ -z "$2" ] && {
+          printf 'Error: Missing argument for %s\n' "$1" >&2
           return "$CODE_ARGS"
-          ;;
-        *) break ;;
+        }
+
+        shift
+        file_a=$1
+        ;;
+      -b | --file-b)
+        [ -z "$2" ] && {
+          printf 'Error: Missing argument for %s\n' "$1" >&2
+          return "$CODE_ARGS"
+        }
+
+        shift
+        file_b=$1
+        ;;
+      -f | --filter)
+        [ -z "$2" ] && {
+          printf 'Error: Missing argument for %s\n' "$1" >&2
+          return "$CODE_ARGS"
+        }
+
+        shift
+        filter=$1
+        ;;
+      --help)
+        diff_sans_header__usage
+        return "$CODE_SUCCESS"
+        ;;
+      --)
+        shift
+        break
+        ;;
+      -*)
+        printf 'Unknown option: %s\n' "$1" >&2
+        diff_sans_header__usage >&2
+        return "$CODE_ARGS"
+        ;;
+      *) break ;;
       esac
       shift
     done
@@ -411,8 +411,8 @@ initialize_utilities() {
     }
 
     #@ Use diff to compare files, while filtering out header lines
-    diff -u "$file_a" "$file_b" \
-      | sed -e '/^---[[:space:]]/d' \
+    diff -u "$file_a" "$file_b" |
+      sed -e '/^---[[:space:]]/d' \
         -e '/^+++[[:space:]]/d' \
         ${filter:+-e} "${filter:-}"
   }
@@ -442,7 +442,7 @@ initialize_utilities() {
     #@ Update modification time using the cached fetcher.
     [ -e "$1" ] && {
       _path="$1"
-      _date="$("$MOD_TIME_FETCHER" "$_path" 2> /dev/null)"
+      _date="$("$MOD_TIME_FETCHER" "$_path" 2>/dev/null)"
     }
 
     #@ Return the date.
@@ -500,10 +500,10 @@ get_absolute_path() {
   #DOC   Absolute path to file
   _file="$1"
   _pwd=$(pwd)
-  cd "$(dirname "$_file")" > /dev/null 2>&1 || return "$CODE_SYSTEM"
+  cd "$(dirname "$_file")" >/dev/null 2>&1 || return "$CODE_SYSTEM"
   _cwd="$(pwd)"
   _path="$_cwd/$(basename "$_file")"
-  cd "$_pwd" > /dev/null 2>&1 || return "$CODE_SYSTEM"
+  cd "$_pwd" >/dev/null 2>&1 || return "$CODE_SYSTEM"
 
   printf "%s" "$_path"
 }
@@ -531,43 +531,43 @@ parse_arguments() {
   #@ Parse command line arguments
   while [ "$#" -gt 0 ]; do
     case $1 in
-      -d | --debug)
-        VERBOSITY=5
-        ACTION="check"
-        ;;
-      --lint | --check | --dry*) ACTION="check" ;;
-      -f | --fmt | --format) ACTION="format" ;;
-      --skip-sections) ALLOW_SECTION_SEPARATION=0 ;;
-      --skip-leading-space) ALLOW_LEADING_WHITESPACE_TRIM=0 ;;
-      --skip-trailing-space) ALLOW_TRAILING_WHITESPACE_TRIM=0 ;;
-      --skip-blank-lines) ALLOW_BLANK_LINE_REMOVAL=0 ;;
-      -s | --separate-sections) ALLOW_SECTION_SEPARATION=1 ;;
-      -l | --trim-leading-space) ALLOW_LEADING_WHITESPACE_TRIM=1 ;;
-      -t | --trim-trailing-space) ALLOW_TRAILING_WHITESPACE_TRIM=1 ;;
-      -w | --whitespace) ALLOW_BLANK_LINE_REMOVALEEZE=1 ;;
-      -b | --drop-blank-lines) ALLOW_BLANK_LINE_REMOVAL=1 ;;
-      --version)
-        printf '%s\n' "$SCR_VERSION"
-        exit 0
-        ;;
-      --)
-        shift
+    -d | --debug)
+      VERBOSITY=5
+      ACTION="check"
+      ;;
+    --lint | --check | --dry*) ACTION="check" ;;
+    -f | --fmt | --format) ACTION="format" ;;
+    --skip-sections) ALLOW_SECTION_SEPARATION=0 ;;
+    --skip-leading-space) ALLOW_LEADING_WHITESPACE_TRIM=0 ;;
+    --skip-trailing-space) ALLOW_TRAILING_WHITESPACE_TRIM=0 ;;
+    --skip-blank-lines) ALLOW_BLANK_LINE_REMOVAL=0 ;;
+    -s | --separate-sections) ALLOW_SECTION_SEPARATION=1 ;;
+    -l | --trim-leading-space) ALLOW_LEADING_WHITESPACE_TRIM=1 ;;
+    -t | --trim-trailing-space) ALLOW_TRAILING_WHITESPACE_TRIM=1 ;;
+    -w | --whitespace) ALLOW_BLANK_LINE_REMOVALEEZE=1 ;;
+    -b | --drop-blank-lines) ALLOW_BLANK_LINE_REMOVAL=1 ;;
+    --version)
+      printf '%s\n' "$SCR_VERSION"
+      exit 0
+      ;;
+    --)
+      shift
 
-        #@ Add remaining arguments after --
-        for arg; do
-          [ -f "$arg" ] && FILES="${FILES:+${FILES}${DELIMITER}}$arg"
-        done
-        break
-        ;;
-      -*)
-        printf 'Unknown option: %s\n' "$1" >&2
-        printf '%s\n' "$SCR_USAGE" >&2
-        exit 1
-        ;;
-      *)
-        #@ Only add if it's a real file
-        [ -f "$1" ] && FILES="${FILES:+${FILES}${DELIMITER}}$1"
-        ;;
+      #@ Add remaining arguments after --
+      for arg; do
+        [ -f "$arg" ] && FILES="${FILES:+${FILES}${DELIMITER}}$arg"
+      done
+      break
+      ;;
+    -*)
+      printf 'Unknown option: %s\n' "$1" >&2
+      printf '%s\n' "$SCR_USAGE" >&2
+      exit 1
+      ;;
+    *)
+      #@ Only add if it's a real file
+      [ -f "$1" ] && FILES="${FILES:+${FILES}${DELIMITER}}$1"
+      ;;
     esac
     shift
   done
@@ -738,23 +738,23 @@ execute_action() {
     sed_script=""
 
     #@ Build up script only if flags are explicitly set to 1
-    [ "$ALLOW_LEADING_WHITESPACE_TRIM" = "1" ] \
-      && sed_script="${sed_script:+$sed_script;}${PATTERN_LEADING_SPACE_TRIM}"
+    [ "$ALLOW_LEADING_WHITESPACE_TRIM" = "1" ] &&
+      sed_script="${sed_script:+$sed_script;}${PATTERN_LEADING_SPACE_TRIM}"
 
-    [ "$ALLOW_TRAILING_WHITESPACE_TRIM" = "1" ] \
-      && sed_script="${sed_script:+$sed_script;}${PATTERN_TRAILING_SPACE_TRIM}"
+    [ "$ALLOW_TRAILING_WHITESPACE_TRIM" = "1" ] &&
+      sed_script="${sed_script:+$sed_script;}${PATTERN_TRAILING_SPACE_TRIM}"
 
-    [ "$ALLOW_MULTIPLE_SPACE_SQUEEZE" = "1" ] \
-      && sed_script="${sed_script:+$sed_script;}${PATTERN_MULTIPLE_SPACE_SQUEEZE}"
+    [ "$ALLOW_MULTIPLE_SPACE_SQUEEZE" = "1" ] &&
+      sed_script="${sed_script:+$sed_script;}${PATTERN_MULTIPLE_SPACE_SQUEEZE}"
 
-    [ "$ALLOW_BLANK_LINE_REMOVAL" = "1" ] \
-      && sed_script="${sed_script:+$sed_script;}${PATTERN_BLANK_LINE_REMOVAL}"
+    [ "$ALLOW_BLANK_LINE_REMOVAL" = "1" ] &&
+      sed_script="${sed_script:+$sed_script;}${PATTERN_BLANK_LINE_REMOVAL}"
 
-    [ "$ALLOW_SECTION_SEPARATION" = "1" ] \
-      && sed_script="${sed_script:+$sed_script;}${PATTERN_SECTION_SPLIT}"
+    [ "$ALLOW_SECTION_SEPARATION" = "1" ] &&
+      sed_script="${sed_script:+$sed_script;}${PATTERN_SECTION_SPLIT}"
 
-    [ "$VERBOSITY" -ge 4 ] \
-      && printf "SED PATTERN: %s\n" "$sed_script"
+    [ "$VERBOSITY" -ge 4 ] &&
+      printf "SED PATTERN: %s\n" "$sed_script"
 
     #@ Skip if the sed script is empty
     [ -z "$sed_script" ] && return 0
@@ -769,7 +769,7 @@ execute_action() {
     tmp_new="${tmp}.formatted"
 
     #@ Apply the sed script to the temporary file
-    sed -e "$sed_script" "$tmp" > "$tmp_new" || {
+    sed -e "$sed_script" "$tmp" >"$tmp_new" || {
       printf "Sed formatting failed\n" >&2
       rm -f "$tmp_new"
       return "$CODE_FORMAT"
diff --git a/Bin/shellscript/project/formatters/fmtree b/Bin/shellscript/project/formatters/fmtree
--- a/Bin/shellscript/project/formatters/fmtree
+++ b/Bin/shellscript/project/formatters/fmtree
@@ -34,38 +34,38 @@ drop_env() {
 parse_arguments() {
   while [ "$#" -ge 1 ]; do
     case "$1" in
-      --config)
-        [ "$2" ] || {
-          printf "Error: Config file not specified." >&2
-          exit 1
-        }
+    --config)
+      [ "$2" ] || {
+        printf "Error: Config file not specified." >&2
+        exit 1
+      }
 
-        FMTREE_CFG="$2"
-        shift
-        ;;
-      --root)
-        [ "$2" ] || {
-          printf "Error: Root directory not specified." >&2
-          exit 1
-        }
+      FMTREE_CFG="$2"
+      shift
+      ;;
+    --root)
+      [ "$2" ] || {
+        printf "Error: Root directory not specified." >&2
+        exit 1
+      }
 
-        [ -d "$2" ] || {
-          printf "Error: Root directory not found." >&2
-          exit 1
-        }
+      [ -d "$2" ] || {
+        printf "Error: Root directory not found." >&2
+        exit 1
+      }
 
-        FMTREE_ARG="${FMTREE_ARG:+$FMTREE_ARG${DELIMITER}}--tree-root $2"
-        shift
-        ;;
-      --debug | --dry*)
-        FMTREE_DRY=1
-        ;;
-      -d | --verbose)
-        VERBOSITY=4
-        ;;
-      *)
-        FMTREE_ARG="${FMTREE_ARG:+$FMTREE_ARG${DELIMITER}}$1"
-        ;;
+      FMTREE_ARG="${FMTREE_ARG:+$FMTREE_ARG${DELIMITER}}--tree-root $2"
+      shift
+      ;;
+    --debug | --dry*)
+      FMTREE_DRY=1
+      ;;
+    -d | --verbose)
+      VERBOSITY=4
+      ;;
+    *)
+      FMTREE_ARG="${FMTREE_ARG:+$FMTREE_ARG${DELIMITER}}$1"
+      ;;
     esac
     shift
   done
@@ -111,8 +111,8 @@ execute_process() {
     "$(printf "%s" "$FMTREE_ARG" | tr "$DELIMITER" " ")")"
 
   #@ Print command
-  [ "$VERBOSITY" -ge 4 ] \
-    && printf '\033[1;36m[ INFO ]\033[0m Executing command => %s\n' "$FMTREE_CMD"
+  [ "$VERBOSITY" -ge 4 ] &&
+    printf '\033[1;36m[ INFO ]\033[0m Executing command => %s\n' "$FMTREE_CMD"
 
   #@ Run command
   [ "$FMTREE_DRY" -eq 0 ] && eval "$FMTREE_CMD"
diff --git a/Bin/shellscript/project/rust/cgoo b/Bin/shellscript/project/rust/cgoo
--- a/Bin/shellscript/project/rust/cgoo
+++ b/Bin/shellscript/project/rust/cgoo
@@ -3,7 +3,7 @@
 main() {
   scr_name="$(basename "$0")"
   scr_guide="$(
-    cat << EOF
+    cat <<EOF
 Usage:
   $(basename "$0") <MODES> [COMMAND/OPTION] -- <ARGUMENTS>
 
@@ -60,7 +60,7 @@ display_usage() {
     #@ No arguments
     exit_code=0
   else
-    if [ "$1" -eq "$1" ] 2> /dev/null; then
+    if [ "$1" -eq "$1" ] 2>/dev/null; then
       #@ The first argument is a number
       exit_code="$1"
       shift
@@ -70,8 +70,8 @@ display_usage() {
     fi
   fi
   #@ Display the error or custom message
-  [ "$*" ] \
-    && if [ "$exit_code" -ne 0 ]; then
+  [ "$*" ] &&
+    if [ "$exit_code" -ne 0 ]; then
       printf "Error: %s\n\n" "$*"
     else
       printf "%s\n\n" "$*"
@@ -86,7 +86,7 @@ display_usage() {
 
 cargo_cmd() {
   #@ Check if cargo is installed
-  cargo --help > /dev/null 2>&1 || {
+  cargo --help >/dev/null 2>&1 || {
     printf "%s\n%s" \
       "Please ensure 'cargo' is installed and in your PATH." \
       "See https://www.rust-lang.org/tools/install for more information."
@@ -94,7 +94,7 @@ cargo_cmd() {
   }
 
   if [ "$2" ]; then
-    printf "cargo watch --quiet --clear --exec \"%s\"" "$1"
+    printf 'cargo watch --quiet --clear --exec "%s"' "$1"
   else
     printf "cargo %s" "$1"
   fi
@@ -103,28 +103,28 @@ cargo_cmd() {
 get_option() {
   while [ $# -gt 0 ]; do
     case $1 in
-      -p* | --p*)
-        [ "$2" ] \
-          && if [ "$2" -eq "$2" ] 2> /dev/null; then
-            position="$2"
-            shift
-          else
-            printf "Error: Position not a number\n"
-            printf "Invalid position: %s\n" "$2"
-            exit 66 #? Developer Error - Script Logic Error
-          fi
-
-        ;;
-      -o* | --o*)
-        [ "$2" ] && {
-          options="$2"
+    -p* | --p*)
+      [ "$2" ] &&
+        if [ "$2" -eq "$2" ] 2>/dev/null; then
+          position="$2"
           shift
-        }
-        ;;
-      *)
-        options="${options:-$1}"
-        position="${position:-$2}"
-        ;;
+        else
+          printf "Error: Position not a number\n"
+          printf "Invalid position: %s\n" "$2"
+          exit 66 #? Developer Error - Script Logic Error
+        fi
+
+      ;;
+    -o* | --o*)
+      [ "$2" ] && {
+        options="$2"
+        shift
+      }
+      ;;
+    *)
+      options="${options:-$1}"
+      position="${position:-$2}"
+      ;;
     esac
     shift
   done
@@ -177,177 +177,177 @@ parse_arguments() {
   external() {
     while [ $# -gt 0 ]; do
       case "$1" in
-        -a*)
-          #> Command
-          cmd="add"
+      -a*)
+        #> Command
+        cmd="add"
 
-          #> Option
-          case "$(get_option "$1")" in
-            h)
-              opt="--help"
-              ;;
-          esac
-
-          #> Argument
-          unset arg
+        #> Option
+        case "$(get_option "$1")" in
+        h)
+          opt="--help"
           ;;
-        -b*)
-          cmd="build"
+        esac
 
-          case "$(get_option --opt "$1" --pos 2)" in
-            h)
-              opt="--help"
-              ;;
-            b)
-              if [ "$2" ]; then
-                opt="--bin"
-              else
-                opt="--bins"
-              fi
-              ;;
-            e)
-              if [ "$2" ]; then
-                opt="--example"
-              else
-                opt="--examples"
-              fi
-              ;;
-            l)
-              opt="--lib"
-              ;;
-            n)
-              if [ "$2" ]; then
-                opt="--bench"
-              else
-                opt="--benches"
-              fi
-              ;;
-            t)
-              if [ "$2" ]; then
-                opt="--test"
-              else
-                opt="--test $(basename "$PWD")"
-              fi
-              ;;
-            r | a) opt="--all-targets --all-features --release" ;;
-            w)
-              opt="--workspace"
-              ;;
-            x)
-              opt="--exclude"
-              ;;
-          esac
+        #> Argument
+        unset arg
+        ;;
+      -b*)
+        cmd="build"
 
-          while [ $# -gt 1 ]; do
-            case "$2" in --) break ;; -*) ;; *) opt="$opt $2" ;; esac
-            shift
-          done
+        case "$(get_option --opt "$1" --pos 2)" in
+        h)
+          opt="--help"
           ;;
-        -c*)
-          #@ Command
-          cmd="clean"
-
-          #@ Options
-          case "$(get_option "$1")" in
-            h) opt="--help" ;;
-            p)
-              shift
-              opt="$opt $*"
-              ;;
-          esac
-
-          #@ Arguments
-          unset arg
+        b)
+          if [ "$2" ]; then
+            opt="--bin"
+          else
+            opt="--bins"
+          fi
           ;;
-        -r*)
-          cmd="run"
-
-          case "$(get_option --opt "$1" --pos 2)" in
-            h) opt="--help" ;;
-            b) opt="--bin" ;;
-            e) opt="--example" ;;
-            j) opt="--jobs" ;;
-            p) opt="--package" ;;
-            o) opt="--profile" ;;
-            t) opt="--target" ;;
-            d) opt="--target-dir" ;;
-            r | a) opt="--all-features --release" ;;
-            u | g) opt="--unit-graph" ;;
-          esac
-
-          while [ $# -gt 1 ]; do
-            case "$2" in -*) ;; *) opt="$opt $2" ;; esac
-            shift
-          done
+        e)
+          if [ "$2" ]; then
+            opt="--example"
+          else
+            opt="--examples"
+          fi
           ;;
-        -t*)
-          cmd="test"
-
-          case "$(get_option --opt "$1" --pos 2)" in
-            h)
-              opt="--help"
-              ;;
-            b)
-              if [ "$2" ]; then
-                opt="--bin"
-              else
-                opt="--bins"
-              fi
-              ;;
-            e)
-              if [ "$2" ]; then
-                opt="--example"
-              else
-                opt="--examples"
-              fi
-              ;;
-            l)
-              opt="--lib"
-              ;;
-            n)
-              if [ "$2" ]; then
-                opt="--bench"
-              else
-                opt="--benches"
-              fi
-              ;;
-            t)
-              if [ "$2" ]; then
-                opt="--test"
-              else
-                opt="--test $(basename "$PWD")"
-              fi
-              ;;
-            a)
-              opt="--all-targets --all-features"
-              ;;
-            w)
-              opt="--workspace"
-              ;;
-            x)
-              opt="--exclude"
-              ;;
-          esac
-
-          while [ $# -gt 1 ]; do
-            case "$2" in --) break ;; -*) ;; *) opt="$opt $2" ;; esac
-            shift
-          done
-
-          [ "$3" ] && shift
-
-          arg="--nocapture --exact"
-          while [ $# -gt 1 ]; do
-            case "$2" in --) break ;; -*) ;; *) arg="$arg $2" ;; esac
-            shift
-          done
+        l)
+          opt="--lib"
           ;;
-        *)
-          case $1 in
-            -*D* | -*Q* | -*R* | -*W* | -H | --debug) ;;
-            *) cmd="$cmd $1" ;;
-          esac
+        n)
+          if [ "$2" ]; then
+            opt="--bench"
+          else
+            opt="--benches"
+          fi
           ;;
+        t)
+          if [ "$2" ]; then
+            opt="--test"
+          else
+            opt="--test $(basename "$PWD")"
+          fi
+          ;;
+        r | a) opt="--all-targets --all-features --release" ;;
+        w)
+          opt="--workspace"
+          ;;
+        x)
+          opt="--exclude"
+          ;;
+        esac
+
+        while [ $# -gt 1 ]; do
+          case "$2" in --) break ;; -*) ;; *) opt="$opt $2" ;; esac
+          shift
+        done
+        ;;
+      -c*)
+        #@ Command
+        cmd="clean"
+
+        #@ Options
+        case "$(get_option "$1")" in
+        h) opt="--help" ;;
+        p)
+          shift
+          opt="$opt $*"
+          ;;
+        esac
+
+        #@ Arguments
+        unset arg
+        ;;
+      -r*)
+        cmd="run"
+
+        case "$(get_option --opt "$1" --pos 2)" in
+        h) opt="--help" ;;
+        b) opt="--bin" ;;
+        e) opt="--example" ;;
+        j) opt="--jobs" ;;
+        p) opt="--package" ;;
+        o) opt="--profile" ;;
+        t) opt="--target" ;;
+        d) opt="--target-dir" ;;
+        r | a) opt="--all-features --release" ;;
+        u | g) opt="--unit-graph" ;;
+        esac
+
+        while [ $# -gt 1 ]; do
+          case "$2" in -*) ;; *) opt="$opt $2" ;; esac
+          shift
+        done
+        ;;
+      -t*)
+        cmd="test"
+
+        case "$(get_option --opt "$1" --pos 2)" in
+        h)
+          opt="--help"
+          ;;
+        b)
+          if [ "$2" ]; then
+            opt="--bin"
+          else
+            opt="--bins"
+          fi
+          ;;
+        e)
+          if [ "$2" ]; then
+            opt="--example"
+          else
+            opt="--examples"
+          fi
+          ;;
+        l)
+          opt="--lib"
+          ;;
+        n)
+          if [ "$2" ]; then
+            opt="--bench"
+          else
+            opt="--benches"
+          fi
+          ;;
+        t)
+          if [ "$2" ]; then
+            opt="--test"
+          else
+            opt="--test $(basename "$PWD")"
+          fi
+          ;;
+        a)
+          opt="--all-targets --all-features"
+          ;;
+        w)
+          opt="--workspace"
+          ;;
+        x)
+          opt="--exclude"
+          ;;
+        esac
+
+        while [ $# -gt 1 ]; do
+          case "$2" in --) break ;; -*) ;; *) opt="$opt $2" ;; esac
+          shift
+        done
+
+        [ "$3" ] && shift
+
+        arg="--nocapture --exact"
+        while [ $# -gt 1 ]; do
+          case "$2" in --) break ;; -*) ;; *) arg="$arg $2" ;; esac
+          shift
+        done
+        ;;
+      *)
+        case $1 in
+        -*D* | -*Q* | -*R* | -*W* | -H | --debug) ;;
+        *) cmd="$cmd $1" ;;
+        esac
+        ;;
       esac
       shift
     done
diff --git a/Bin/shellscript/utility/output/align b/Bin/shellscript/utility/output/align
--- a/Bin/shellscript/utility/output/align
+++ b/Bin/shellscript/utility/output/align
@@ -45,83 +45,83 @@ initialize_script() {
 parse_arguments() {
   while [ $# -gt 0 ]; do
     case "$1" in
-      -h | --help)
-        show_usage_guide
-        ;;
-      -v | --version)
-        print_version
-        exit
-        ;;
-      -d | --verbose) verbose=true ;;
-      -c | --center) alignment="center" ;;
-      -r | --right) alignment="right" ;;
-      -l | --left) alignment="left" ;;
-      -p | --pad | --char)
-        if [ "$2" ]; then
+    -h | --help)
+      show_usage_guide
+      ;;
+    -v | --version)
+      print_version
+      exit
+      ;;
+    -d | --verbose) verbose=true ;;
+    -c | --center) alignment="center" ;;
+    -r | --right) alignment="right" ;;
+    -l | --left) alignment="left" ;;
+    -p | --pad | --char)
+      if [ "$2" ]; then
 
-          validate_var \
-            --lbl "Padding Character" \
-            --var "$2" \
-            && pad_char="$2"
-          shift
-        else
-          show_usage_guide \
-            --lbl "Padding Character Error" \
-            --msg "Missing argument for '$1'." \
-            --opt "$1" \
-            --var "<CHAR>" \
-            --fatal
-        fi
-        ;;
-      --padl)
-        if [ "$2" ]; then
-          validate_var \
-            --lbl "Left Padding Character" \
-            --var "$2" \
-            && pad_char="$2"
-          shift
-        else
-          show_usage_guide \
-            --lbl "Padding Character [Left] Error" \
-            --msg "Missing argument for '$1'." \
-            --opt "$1" \
-            --var "<CHAR>" \
-            --fatal
-        fi
-        ;;
-      --padr)
-        label="Padding Character [Right]"
-        pad_char_r="$(
-          validate_var \
-            --lbl "Right Padding Character" \
-            --opt "$1" \
-            --var "$2" \
-            --type
-        )"
-        echo "$pad_char_r"
-        exit
-        # if [ "$2" ]; then
-        #   validate_var "$2"
-        #   # pad_char="$2"
-        #   shift
-        # else
-        #   show_usage_guide \
-        #     --lbl "$label" \
-        #     --msg "Missing argument for '$1'." \
-        #     --opt "$1" \
-        #     --var "<CHAR>" \
-        #     --fatal
-        # fi
-        ;;
-      --width)
-        if [ "$2" ]; then
-          term_width="$2"
-          shift
-        else
-          [ "$verbose" ] && printf "Error: Missing argument for %s\n" "$1"
-        fi
-        ;;
-      *) text="$1" ;;
+        validate_var \
+          --lbl "Padding Character" \
+          --var "$2" &&
+          pad_char="$2"
+        shift
+      else
+        show_usage_guide \
+          --lbl "Padding Character Error" \
+          --msg "Missing argument for '$1'." \
+          --opt "$1" \
+          --var "<CHAR>" \
+          --fatal
+      fi
+      ;;
+    --padl)
+      if [ "$2" ]; then
+        validate_var \
+          --lbl "Left Padding Character" \
+          --var "$2" &&
+          pad_char="$2"
+        shift
+      else
+        show_usage_guide \
+          --lbl "Padding Character [Left] Error" \
+          --msg "Missing argument for '$1'." \
+          --opt "$1" \
+          --var "<CHAR>" \
+          --fatal
+      fi
+      ;;
+    --padr)
+      label="Padding Character [Right]"
+      pad_char_r="$(
+        validate_var \
+          --lbl "Right Padding Character" \
+          --opt "$1" \
+          --var "$2" \
+          --type
+      )"
+      echo "$pad_char_r"
+      exit
+      # if [ "$2" ]; then
+      #   validate_var "$2"
+      #   # pad_char="$2"
+      #   shift
+      # else
+      #   show_usage_guide \
+      #     --lbl "$label" \
+      #     --msg "Missing argument for '$1'." \
+      #     --opt "$1" \
+      #     --var "<CHAR>" \
+      #     --fatal
+      # fi
+      ;;
+    --width)
+      if [ "$2" ]; then
+        term_width="$2"
+        shift
+      else
+        [ "$verbose" ] && printf "Error: Missing argument for %s\n" "$1"
+      fi
+      ;;
+    *) text="$1" ;;
     esac
     shift
   done
@@ -169,21 +169,21 @@ is_number() {
   lbl="$2"
 
   case $var in
-    '' | *[!0-9]*)
-      #TODO use pout for error handling to replace printf and exit
-      # printf "%s '%s', is not a valid number\n" "$lbl" "$var"
-      [ "$verbose" ] \
-        && embellish \
-          --reset --underline --bg-red --fg-white \
-          "$lbl Error:" \
-          --reset --space --bold --red --italic \
-          "$var" \
-          --reset --space \
-          "is not a valid number." \
-          --reset --new-line
-      exit 1
-      ;;
-    *) return 0 ;;
+  '' | *[!0-9]*)
+    #TODO use pout for error handling to replace printf and exit
+    # printf "%s '%s', is not a valid number\n" "$lbl" "$var"
+    [ "$verbose" ] &&
+      embellish \
+        --reset --underline --bg-red --fg-white \
+        "$lbl Error:" \
+        --reset --space --bold --red --italic \
+        "$var" \
+        --reset --space \
+        "is not a valid number." \
+        --reset --new-line
+    exit 1
+    ;;
+  *) return 0 ;;
   esac
 }
 
@@ -202,23 +202,23 @@ is_single_char() {
   fi
 
   case $var in
-    # Printable characters, including whitespace
-    [[:print:]]) return 0 ;;
-    *)
-      #TODO use pout for error handling to replace printf and exit
-      # printf "%s '%s', is not a valid single character\n" "$lbl" "$var"
-      embellish \
-        The \
-        --reset --space --bold --red --italic \
-        "$(printf "%s" "$lbl" | tr '[:upper:]' '[:lower:]')" \
-        --reset --space --underline --bg-red --fg-white \
-        ["$var"] \
-        --reset --space \
-        "is not a single character." \
-        --reset --new-line
+  # Printable characters, including whitespace
+  [[:print:]]) return 0 ;;
+  *)
+    #TODO use pout for error handling to replace printf and exit
+    # printf "%s '%s', is not a valid single character\n" "$lbl" "$var"
+    embellish \
+      The \
+      --reset --space --bold --red --italic \
+      "$(printf "%s" "$lbl" | tr '[:upper:]' '[:lower:]')" \
+      --reset --space --underline --bg-red --fg-white \
+      ["$var"] \
+      --reset --space \
+      "is not a single character." \
+      --reset --new-line
 
-      exit 1
-      ;;
+    exit 1
+    ;;
   esac
 }
 
@@ -227,23 +227,23 @@ validate_var() {
   func_usage="$func_name [OPTIONS] <Value>"
   while [ $# -gt 0 ]; do
     case $1 in
-      --lbl | --opt | --var | --type)
-        #@ Remove the leading hyphens from the option
-        variable_name=${1#--}
+    --lbl | --opt | --var | --type)
+      #@ Remove the leading hyphens from the option
+      variable_name=${1#--}
 
-        #@ Assign the value of $2 to the extracted variable name
-        if [ "$2" ]; then
-          eval "$variable_name=\"\$2\""
-          shift
-        else
-          printf "Error: Missing argument for %s\n" "$1"
-        fi
-        ;;
-      --*)
-        #TODO Use show_usage_guide
-        echo "Unknown option: $1"
-        ;;
-      *) var="$1" ;;
+      #@ Assign the value of $2 to the extracted variable name
+      if [ "$2" ]; then
+        eval "$variable_name=\"\$2\""
+        shift
+      else
+        printf "Error: Missing argument for %s\n" "$1"
+      fi
+      ;;
+    --*)
+      #TODO Use show_usage_guide
+      echo "Unknown option: $1"
+      ;;
+    *) var="$1" ;;
     esac
     shift
   done
@@ -323,27 +323,27 @@ validate_var() {
 
 get_len() {
   case $1 in
-    --term) stty size 2> /dev/null | awk '{print $2}' ;;
-    *) printf "%s" "${#1}" ;;
+  --term) stty size 2>/dev/null | awk '{print $2}' ;;
+  *) printf "%s" "${#1}" ;;
   esac
 }
 
 print_padded_text() {
   if [ "$padding_left" ] || [ "$padding_right" ]; then
     case "$alignment" in
-      center)
-        printf \
-          "%s %s %s\n" \
-          "${padding:-$padding_left}" \
-          "$text" \
-          "${padding:-$padding_right}"
-        ;;
-      right)
-        printf "%s %s\n" "$padding_left" "$text"
-        ;;
-      left | *)
-        printf "%s %s\n" "$text" "$padding_right"
-        ;;
+    center)
+      printf \
+        "%s %s %s\n" \
+        "${padding:-$padding_left}" \
+        "$text" \
+        "${padding:-$padding_right}"
+      ;;
+    right)
+      printf "%s %s\n" "$padding_left" "$text"
+      ;;
+    left | *)
+      printf "%s %s\n" "$text" "$padding_right"
+      ;;
     esac
   else
     printf "%s\n" "$text"
@@ -352,51 +352,51 @@ print_padded_text() {
 
 show_usage_guide() {
   case $1 in
-    -*)
-      while [ $# -gt 0 ]; do
-        case $1 in
-          -x | --fatal) exit_code="${2:-1}" ;;
-          --*)
-            #@ Assign the value of $2 to the extracted variable name
-            if [ "$2" ]; then
-              eval "$variable_name=\"\$2\""
-              shift
-            else
-              #TODO: handle better
-              printf "Error: Missing argument for %s\n" "$1"
-            fi
-            ;;
-        esac
-        shift
-      done
+  -*)
+    while [ $# -gt 0 ]; do
+      case $1 in
+      -x | --fatal) exit_code="${2:-1}" ;;
+      --*)
+        #@ Assign the value of $2 to the extracted variable name
+        if [ "$2" ]; then
+          eval "$variable_name=\"\$2\""
+          shift
+        else
+          #TODO: handle better
+          printf "Error: Missing argument for %s\n" "$1"
+        fi
+        ;;
+      esac
+      shift
+    done
 
-      #/> Label
-      embellish \
-        --reset --underline --bg-red --fg-white \
-        --space "${lbl:-$label} Error" --space \
-        --reset --new-line
+    #/> Label
+    embellish \
+      --reset --underline --bg-red --fg-white \
+      --space "${lbl:-$label} Error" --space \
+      --reset --new-line
 
-      #/> Message
-      [ "$msg" ] && embellish "$msg" --reset --new-line
+    #/> Message
+    [ "$msg" ] && embellish "$msg" --reset --new-line
 
-      #/> Usage Guide
-      [ "$var" ] && [ "$opt" ] && embellish \
-        "Usage: $scr_name $opt" \
-        --space --red \
-        "$var" \
-        --reset --space \
-        "[TEXT]" \
-        --reset --new-line
+    #/> Usage Guide
+    [ "$var" ] && [ "$opt" ] && embellish \
+      "Usage: $scr_name $opt" \
+      --space --red \
+      "$var" \
+      --reset --space \
+      "[TEXT]" \
+      --reset --new-line
 
-      #/> Additional information
-      embellish \
-        --reset --new-line \
-        "For more information, run" \
-        --reset --space --bold --italic \
-        "$scr_name --help" \
-        --reset --new-line
-      ;;
-    *) printf "%s\n" "$scr_usage" ;;
+    #/> Additional information
+    embellish \
+      --reset --new-line \
+      "For more information, run" \
+      --reset --space --bold --italic \
+      "$scr_name --help" \
+      --reset --new-line
+    ;;
+  *) printf "%s\n" "$scr_usage" ;;
   esac
 
   exit "$exit_code"
@@ -408,18 +408,18 @@ print_version() {
 
 print_verbose_info() {
   [ "$verbose" ] || return
-  cat << EOF
+  cat <<EOF
          Alignment: $alignment
     Terminal Width: $term_width characters
        Text Length: $text_length character(s)
             Buffer: $buffer_length space(s)
 EOF
   if [ "$padding" ]; then
-    cat << EOF
+    cat <<EOF
          Padding: $padding_length reps of '$pad_char'
 EOF
   else
-    cat << EOF
+    cat <<EOF
            Padding: $padding_length reps of '$pad_char_r' and '$pad_char_l'
 EOF
   fi
diff --git a/Bin/shellscript/utility/output/pout b/Bin/shellscript/utility/output/pout
--- a/Bin/shellscript/utility/output/pout
+++ b/Bin/shellscript/utility/output/pout
@@ -53,7 +53,7 @@ set_defaults() {
 
 is_number() {
   # validate --integer "$2" >/dev/null 2>&1
-  [ "$1" -eq "$1" ] 2> /dev/null
+  [ "$1" -eq "$1" ] 2>/dev/null
 }
 # sep="${__sep:-": "}"
 # padding="${__pad:-36}"
@@ -63,98 +63,98 @@ parse_arguments() {
   #@ Parse arguments
   while [ "$#" -gt 0 ]; do
     case $1 in
-      -h) show_info --usage ;;
-      --help) show_info --help ;;
-      -v | --version) show_info --version ;;
-      --quiet | --error | --warn | --info | --debug | --trace)
-        lvl=${1#--}
-        ln_trail=1
-        ;;
-      --hide-l*) hide_lvl=true ;;
-      --hide-t*) hide_time=true ;;
-      --hide-console | --log-only | --no-output | --no-print) target="log" ;;
-      --no-log | --print | --console-only) target="console" ;;
-      -L | --log)
-        [ "$2" ] && {
-          validate_file --parent "$2" || return 1
-          log="$2"
-          shift
-        }
-        ;;
-      -b | -ll | --line-l* | --lead*l*)
-        if [ "$2" ] && is_number "$2"; then
-          ln_lead="$2"
-          shift
-        else
-          ln_lead=1
-        fi
-        ;;
-      -n | -lt | --line-t* | --lead*t*)
-        if is_number "$2"; then
-          ln_trail="$2"
-          shift
-        else
-          ln_trail=1
-        fi
-        ;;
-      --key)
-        if [ "$2" ]; then
-          key="$2"
-          shift
-        else
-          pout --error "No key provided to --key"
-          return 1
-        fi
-        ;;
-      --val)
-        if [ "$2" ]; then
-          val="$2"
-          shift
-        else
-          val="{ Missing Value }"
-          val_fmt="${FMT_RED}${val}${FMT_NORMAL}"
-        fi
-        ;;
-      --sep*)
-        if [ "$2" ]; then
-          sep="$2"
-          shift
-        else
-          pout --error "No separator provided to --sep"
-          return 1
-        fi
-        ;;
-      -z | --end | --last*)
-        end=true
-        ;;
-      --pad)
-        pad=true
-        [ "$2" ] && valid_number "$2" && {
-          pad="$2"
-          shift
-        }
-        ;;
-      --delimiter)
-        list_delimiter="$2"
+    -h) show_info --usage ;;
+    --help) show_info --help ;;
+    -v | --version) show_info --version ;;
+    --quiet | --error | --warn | --info | --debug | --trace)
+      lvl=${1#--}
+      ln_trail=1
+      ;;
+    --hide-l*) hide_lvl=true ;;
+    --hide-t*) hide_time=true ;;
+    --hide-console | --log-only | --no-output | --no-print) target="log" ;;
+    --no-log | --print | --console-only) target="console" ;;
+    -L | --log)
+      [ "$2" ] && {
+        validate_file --parent "$2" || return 1
+        log="$2"
         shift
-        ;;
-      -m | --msg | --message)
-        [ "$2" ] && {
-          if [ "$msg" ]; then
-            msg="${msg}${delimiter}${2}"
-          else
-            msg="$2"
-          fi
-          shift
-        }
-        ;;
-      *)
+      }
+      ;;
+    -b | -ll | --line-l* | --lead*l*)
+      if [ "$2" ] && is_number "$2"; then
+        ln_lead="$2"
+        shift
+      else
+        ln_lead=1
+      fi
+      ;;
+    -n | -lt | --line-t* | --lead*t*)
+      if is_number "$2"; then
+        ln_trail="$2"
+        shift
+      else
+        ln_trail=1
+      fi
+      ;;
+    --key)
+      if [ "$2" ]; then
+        key="$2"
+        shift
+      else
+        pout --error "No key provided to --key"
+        return 1
+      fi
+      ;;
+    --val)
+      if [ "$2" ]; then
+        val="$2"
+        shift
+      else
+        val="{ Missing Value }"
+        val_fmt="${FMT_RED}${val}${FMT_NORMAL}"
+      fi
+      ;;
+    --sep*)
+      if [ "$2" ]; then
+        sep="$2"
+        shift
+      else
+        pout --error "No separator provided to --sep"
+        return 1
+      fi
+      ;;
+    -z | --end | --last*)
+      end=true
+      ;;
+    --pad)
+      pad=true
+      [ "$2" ] && valid_number "$2" && {
+        pad="$2"
+        shift
+      }
+      ;;
+    --delimiter)
+      list_delimiter="$2"
+      shift
+      ;;
+    -m | --msg | --message)
+      [ "$2" ] && {
         if [ "$msg" ]; then
-          msg="$msg $1"
+          msg="${msg}${delimiter}${2}"
         else
-          msg="$1"
+          msg="$2"
         fi
-        ;;
+        shift
+      }
+      ;;
+    *)
+      if [ "$msg" ]; then
+        msg="$msg $1"
+      else
+        msg="$1"
+      fi
+      ;;
     esac
     shift
   done
@@ -174,27 +174,27 @@ set_pair() {
 set_level() {
   #@ Append the level to the message.
   case "$lvl" in
-    error)
-      lvl_log="[ERROR] "
-      lvl_fmt="${FMT_ERROR}${lvl_log}${FMT_NORMAL}"
-      ;;
-    warn)
-      lvl_log="[ WARN] "
-      lvl_fmt="${FMT_WARN}${lvl_log}${FMT_NORMAL}"
-      ;;
-    info)
-      lvl_log="[ INFO] "
-      lvl_fmt="${FMT_INFO}${lvl_log}${FMT_NORMAL}"
-      ;;
-    debug)
-      lvl_log="[DEBUG] "
-      lvl_fmt="${FMT_DEBUG}${lvl_log}${FMT_NORMAL}"
-      ;;
-    trace)
-      lvl_log="[TRACE] "
-      lvl_fmt="${FMT_TRACE}${lvl_log}${FMT_NORMAL}"
-      ;;
-    *) unset lvl ;;
+  error)
+    lvl_log="[ERROR] "
+    lvl_fmt="${FMT_ERROR}${lvl_log}${FMT_NORMAL}"
+    ;;
+  warn)
+    lvl_log="[ WARN] "
+    lvl_fmt="${FMT_WARN}${lvl_log}${FMT_NORMAL}"
+    ;;
+  info)
+    lvl_log="[ INFO] "
+    lvl_fmt="${FMT_INFO}${lvl_log}${FMT_NORMAL}"
+    ;;
+  debug)
+    lvl_log="[DEBUG] "
+    lvl_fmt="${FMT_DEBUG}${lvl_log}${FMT_NORMAL}"
+    ;;
+  trace)
+    lvl_log="[TRACE] "
+    lvl_fmt="${FMT_TRACE}${lvl_log}${FMT_NORMAL}"
+    ;;
+  *) unset lvl ;;
   esac
 
   [ -n "$hide_lvl" ] && unset lvl
@@ -220,7 +220,7 @@ pout_repeat() {
   }
 
   is_valid_num() {
-    validate --positive "$1" > /dev/null 2>&1
+    validate --positive "$1" >/dev/null 2>&1
   }
 
   pout_repeat__print_guide() {
@@ -245,23 +245,23 @@ pout_repeat() {
   print_usage() {
     while [ "$#" -ge 1 ]; do
       case "$1" in
-        --args)
-          msg="$(
-            printf "Incorrect number of arguments. " >&2
-            printf "Expected at least %s but got %s\n" "$expected_args" "$2" >&2
-          )"
-          ;;
-        --pos)
-          msg="$(
-            printf "Unable to distinguih the pattern from the number of repetitions\n" >&2
-          )"
-          ;;
-        --reps)
-          msg="$(printf "Number of repetitions not defined\n" >&2)"
-          ;;
-        *)
-          exit_code="${1:-1}"
-          ;;
+      --args)
+        msg="$(
+          printf "Incorrect number of arguments. " >&2
+          printf "Expected at least %s but got %s\n" "$expected_args" "$2" >&2
+        )"
+        ;;
+      --pos)
+        msg="$(
+          printf "Unable to distinguih the pattern from the number of repetitions\n" >&2
+        )"
+        ;;
+      --reps)
+        msg="$(printf "Number of repetitions not defined\n" >&2)"
+        ;;
+      *)
+        exit_code="${1:-1}"
+        ;;
       esac
       shift
     done
@@ -288,8 +288,8 @@ pout_repeat() {
     #@ Script Options
     for arg in "$@"; do
       case "$arg" in
-        -h) print_usage 0 ;;
-        --help) print_guide ;;
+      -h) print_usage 0 ;;
+      --help) print_guide ;;
       esac
     done
 
@@ -299,41 +299,41 @@ pout_repeat() {
     #@ Process Options
     while [ "$#" -ge 1 ]; do
       case "$1" in
-        -d | --verbose | --debug)
-          debug=1
-          ;;
-        -n | -*num* | -r | -*rep*)
-          is_valid_num "$2" || print_usage --reps
-          repetitions="$2"
-          shift
-          ;;
-        -p | -*pat* | -c | -*char*)
-          [ -n "$2" ] || print_usage --args
-          pattern="$2"
-          shift
-          ;;
-        -l | --line)
-          pattern="\n"
-          repetitions="${2:-1}"
-          break
-          ;;
-        -s | --space)
-          pattern=" "
-          repetitions="${2:-1}"
-          break
-          ;;
-        *)
-          #@ Handle positional arguments
-          if [ -z "$repetitions" ] && [ -z "$pattern" ]; then
-            if is_valid_num "$1"; then
-              pattern="$2"
-              repetitions="$1"
-            elif is_valid_num "$2"; then
-              pattern="$1"
-              repetitions="$2"
-            fi
+      -d | --verbose | --debug)
+        debug=1
+        ;;
+      -n | -*num* | -r | -*rep*)
+        is_valid_num "$2" || print_usage --reps
+        repetitions="$2"
+        shift
+        ;;
+      -p | -*pat* | -c | -*char*)
+        [ -n "$2" ] || print_usage --args
+        pattern="$2"
+        shift
+        ;;
+      -l | --line)
+        pattern="\n"
+        repetitions="${2:-1}"
+        break
+        ;;
+      -s | --space)
+        pattern=" "
+        repetitions="${2:-1}"
+        break
+        ;;
+      *)
+        #@ Handle positional arguments
+        if [ -z "$repetitions" ] && [ -z "$pattern" ]; then
+          if is_valid_num "$1"; then
+            pattern="$2"
+            repetitions="$1"
+          elif is_valid_num "$2"; then
+            pattern="$1"
+            repetitions="$2"
           fi
-          ;;
+        fi
+        ;;
       esac
       shift
     done
diff --git a/Bin/shellscript/utility/output/poutFIX b/Bin/shellscript/utility/output/poutFIX
--- a/Bin/shellscript/utility/output/poutFIX
+++ b/Bin/shellscript/utility/output/poutFIX
@@ -36,65 +36,65 @@ set_defaults() {
 
   #| Attributes
   __normal=$(
-    tput sgr0 2> /dev/null \
-      || tput me 2> /dev/null \
-      || printf '%b' '\033[0m'
+    tput sgr0 2>/dev/null ||
+      tput me 2>/dev/null ||
+      printf '%b' '\033[0m'
   )
   __bold=$(
-    tput bold 2> /dev/null \
-      || tput md 2> /dev/null \
-      || printf '%b' '\033[1m'
+    tput bold 2>/dev/null ||
+      tput md 2>/dev/null ||
+      printf '%b' '\033[1m'
   )
   __underline=$(
-    tput smul 2> /dev/null \
-      || tput um 2> /dev/null \
-      || tput us 2> /dev/null \
-      || printf '%b' '\033[4m'
+    tput smul 2>/dev/null ||
+      tput um 2>/dev/null ||
+      tput us 2>/dev/null ||
+      printf '%b' '\033[4m'
   )
   __italic=$(
-    tput sitm 2> /dev/null \
-      || tput it 2> /dev/null \
-      || tput ti 2> /dev/null \
-      || printf '%b' '\033[3m'
+    tput sitm 2>/dev/null ||
+      tput it 2>/dev/null ||
+      tput ti 2>/dev/null ||
+      printf '%b' '\033[3m'
   )
   __blink=$(
-    tput blink 2> /dev/null \
-      || tput mb 2> /dev/null \
-      || printf '%b' '\033[5m'
+    tput blink 2>/dev/null ||
+      tput mb 2>/dev/null ||
+      printf '%b' '\033[5m'
   )
 
   #| Colors
   __black=$(
-    tput setaf 0 2> /dev/null \
-      || printf '%b' '\033[30m'
+    tput setaf 0 2>/dev/null ||
+      printf '%b' '\033[30m'
   )
   __red=$(
-    tput setaf 1 2> /dev/null \
-      || printf '%b' '\033[31m'
+    tput setaf 1 2>/dev/null ||
+      printf '%b' '\033[31m'
   )
   __green=$(
-    tput setaf 2 2> /dev/null \
-      || printf '%b' '\033[32m'
+    tput setaf 2 2>/dev/null ||
+      printf '%b' '\033[32m'
   )
   __yellow=$(
-    tput setaf 3 2> /dev/null \
-      || printf '%b' '\033[33m'
+    tput setaf 3 2>/dev/null ||
+      printf '%b' '\033[33m'
   )
   __blue=$(
-    tput setaf 4 2> /dev/null \
-      || printf '%b' '\033[34m'
+    tput setaf 4 2>/dev/null ||
+      printf '%b' '\033[34m'
   )
   __magenta=$(
-    tput setaf 5 2> /dev/null \
-      || printf '%b' '\033[35m'
+    tput setaf 5 2>/dev/null ||
+      printf '%b' '\033[35m'
   )
   __cyan=$(
-    tput setaf 6 2> /dev/null \
-      || printf '%b' '\033[36m'
+    tput setaf 6 2>/dev/null ||
+      printf '%b' '\033[36m'
   )
   __white=$(
-    tput setaf 7 2> /dev/null \
-      || printf '%b' '\033[37m'
+    tput setaf 7 2>/dev/null ||
+      printf '%b' '\033[37m'
   )
 
   #| Templates with overrides
@@ -152,25 +152,25 @@ set_verbosity() {
 
   #@ Set verbosity based on arguments or defaults
   case "${1:-"$verbosity"}" in
-    0 | quiet | false | off) verbosity=0 ;;
-    1 | error | fail*) verbosity=1 ;;
-    2 | warn*) verbosity=2 ;;
-    3 | info | normal) verbosity=3 ;;
-    4 | verbose | true | debug | on) verbosity=4 ;;
-    5 | trace) verbosity=5 ;;
-    *[0-9]* | *[0-9][0-9]*) verbosity="$1" ;;
-    *) verbosity=3 ;;
+  0 | quiet | false | off) verbosity=0 ;;
+  1 | error | fail*) verbosity=1 ;;
+  2 | warn*) verbosity=2 ;;
+  3 | info | normal) verbosity=3 ;;
+  4 | verbose | true | debug | on) verbosity=4 ;;
+  5 | trace) verbosity=5 ;;
+  *[0-9]* | *[0-9][0-9]*) verbosity="$1" ;;
+  *) verbosity=3 ;;
   esac
 
   #@ Parse arguments
   for arg in "$@"; do
     case "$arg" in
-      -q | --quiet) verbosity=0 ;;
-      -qe | --error) verbosity=1 ;;
-      -qw | --warn*) verbosity=2 ;;
-      -i | --info | --normal) verbosity=3 ;;
-      -vv | --verbose | -d | --debug*) verbosity=4 ;;
-      -V | -[dD][dD] | -[tT] | --trace*) verbosity=5 ;;
+    -q | --quiet) verbosity=0 ;;
+    -qe | --error) verbosity=1 ;;
+    -qw | --warn*) verbosity=2 ;;
+    -i | --info | --normal) verbosity=3 ;;
+    -vv | --verbose | -d | --debug*) verbosity=4 ;;
+    -V | -[dD][dD] | -[tT] | --trace*) verbosity=5 ;;
     esac
   done
 
@@ -184,31 +184,31 @@ set_verbosity() {
 
 set_format() {
   case "$1" in
-    black) printf "%s" "$__black" ;;
-    red) printf "%s" "$__red" ;;
-    green) printf "%s" "$__green" ;;
-    yellow) printf "%s" "$__yellow" ;;
-    blue) printf "%s" "$__blue" ;;
-    magenta) printf "%s" "$__magenta" ;;
-    cyan) printf "%s" "$__cyan" ;;
-    white) printf "%s" "$__white" ;;
-    bold) printf "%s" "$__bold" ;;
-    italic) printf "%s" "$__italic" ;;
-    underline) printf "%s" "$__underline" ;;
-    blink) printf "%s" "$__blink" ;;
-    success) printf "%s" "${__green}${__bold}" ;;
-    failure) printf "%s" "${__red}${__bold}" ;;
-    info) printf "%s" "${__blue}${__bold}" ;;
-    information) printf "%s" "${__blue}${__bold}" ;;
-    warn) printf "%s" "${__yellow}${__bold}" ;;
-    warning) printf "%s" "${__yellow}${__bold}" ;;
-    error) printf "%s" "${__red}${__bold}" ;;
-    debug) printf "%s" "${__magenta}${__bold}" ;;
-    trace) printf "%s" "${__cyan}${__bold}" ;;
-    highlight) printf "%s" "${__underline}${__bold}" ;;
-    emphasis) printf "%s" "${__italic}${__bold}" ;;
-    normal | reset) printf "%s" "$__normal" ;;
-    *) printf "%s" "$__normal" ;;
+  black) printf "%s" "$__black" ;;
+  red) printf "%s" "$__red" ;;
+  green) printf "%s" "$__green" ;;
+  yellow) printf "%s" "$__yellow" ;;
+  blue) printf "%s" "$__blue" ;;
+  magenta) printf "%s" "$__magenta" ;;
+  cyan) printf "%s" "$__cyan" ;;
+  white) printf "%s" "$__white" ;;
+  bold) printf "%s" "$__bold" ;;
+  italic) printf "%s" "$__italic" ;;
+  underline) printf "%s" "$__underline" ;;
+  blink) printf "%s" "$__blink" ;;
+  success) printf "%s" "${__green}${__bold}" ;;
+  failure) printf "%s" "${__red}${__bold}" ;;
+  info) printf "%s" "${__blue}${__bold}" ;;
+  information) printf "%s" "${__blue}${__bold}" ;;
+  warn) printf "%s" "${__yellow}${__bold}" ;;
+  warning) printf "%s" "${__yellow}${__bold}" ;;
+  error) printf "%s" "${__red}${__bold}" ;;
+  debug) printf "%s" "${__magenta}${__bold}" ;;
+  trace) printf "%s" "${__cyan}${__bold}" ;;
+  highlight) printf "%s" "${__underline}${__bold}" ;;
+  emphasis) printf "%s" "${__italic}${__bold}" ;;
+  normal | reset) printf "%s" "$__normal" ;;
+  *) printf "%s" "$__normal" ;;
   esac
 }
 
@@ -219,10 +219,10 @@ list_options() {
   _list_delimiter="${3:- }"
   _list_separator="${4:-, }"
 
-  printf "%s\n" "$_list_options" \
-    | tr "$_list_delimiter" '\n' \
-    | sort -u \
-    | awk -v def="$_list_default" -v sep="$_list_separator" '
+  printf "%s\n" "$_list_options" |
+    tr "$_list_delimiter" '\n' |
+    sort -u |
+    awk -v def="$_list_default" -v sep="$_list_separator" '
         BEGIN {first=1} {
           # Tag default option
           if ($0 == def) $0 = $0 " [default]"
@@ -246,10 +246,10 @@ list_options() {
   _list_delimiter="${3:- }"
   _list_separator="${4:-, }"
 
-  printf "%s" "$_list_options" \
-    | tr "$_list_delimiter" '\n' \
-    | sort -u \
-    | awk -v def="$_list_default" -v sep="$_list_separator" '
+  printf "%s" "$_list_options" |
+    tr "$_list_delimiter" '\n' |
+    sort -u |
+    awk -v def="$_list_default" -v sep="$_list_separator" '
     BEGIN { count = 0 }
     {
         # Tag the default option
@@ -277,24 +277,24 @@ list_options() {
 templates() {
   while [ "$#" -gt 0 ]; do
     case "$1" in
-      --invalid)
-        shift
+    --invalid)
+      shift
 
-        __msg_type="error"
-        __tag="$1"
-        _field="$2"
-        _option="$3"
-        _options="$4"
-        __msg="An invalid ${_field}, \"${__bold}${_option}${__normal},\" was provided. Instead, try one of the following: ${__italic}$(list_options "$_options")${__normal}."
+      __msg_type="error"
+      __tag="$1"
+      _field="$2"
+      _option="$3"
+      _options="$4"
+      __msg="An invalid ${_field}, \"${__bold}${_option}${__normal},\" was provided. Instead, try one of the following: ${__italic}$(list_options "$_options")${__normal}."
 
-        # pout --name "$fn_name" --type "$log_type" --msg \
-        #   "An invalid ${field}," \
-        #   "\"${__bold}${given_option}\"${__normal}," \
-        #   "was provided. Instead, try any of the following:" \
-        #   "$__italic$(
-        #     list_options "$valid_options"
-        #   )$__normal."
-        ;;
+      # pout --name "$fn_name" --type "$log_type" --msg \
+      #   "An invalid ${field}," \
+      #   "\"${__bold}${given_option}\"${__normal}," \
+      #   "was provided. Instead, try any of the following:" \
+      #   "$__italic$(
+      #     list_options "$valid_options"
+      #   )$__normal."
+      ;;
     esac
     shift
   done
@@ -331,114 +331,114 @@ tests() {
 parse_arguments() {
   while [ $# -gt 0 ]; do
     case "$1" in
-      -h)
-        printf '%s' "$scr_usage"
-        exit "$__code"
-        ;;
-      --help)
-        printf '%s' "$scr_guide"
-        exit "$__code"
-        ;;
-      -v)
-        printf '%s' "$scr_version"
-        exit "$__code"
-        ;;
-      --version)
-        printf "%s [ v.%s ]\n" "$scr_name" "$scr_version"
-        exit "$__code"
-        ;;
-      --quiet | --error | --warn | --info | --debug | --trace)
-        __msg_type=${1#--}
-        ;;
-      -*level | -*verb*)
-        if [ "$2" ]; then
-          set_verbosity "$2"
-          shift
-        else
-          set_verbosity
-        fi
-        ;;
-      -t | --tag | -N | --name)
-        if [ "$2" ]; then
-          __tag="$2"
-          shift
-        else
-          printf "ERROR: Tag not specified.\n"
-          __code=1
-          exit "$__code"
-        fi
-        ;;
-      -*type)
-        if [ "$2" ]; then
-          __msg_type="$(validate "$2" "$__msg_types")"
-          #@ Throw error if message type is invalid
-          [ -n "$__msg_type" ] || {
-            templates --invalid "parse_arguments" "message type" "$2" "$__msg_types"
-            __code=1
-            exit "$__code"
-          }
-          shift
-        else
-          #@ Throw error if message type is not specified
-          pout --name "parse_arguments" --type error --msg "Message type not specified"
-          __code=1
-          exit "$__code"
-        fi
-        ;;
-      -*lead*l* | --ll)
-        __lead_lines=1
-        [ -n "$2" ] && {
-          __lead_lines="$(validate --integer "$2" || {
-            printf "ERROR: Invalid leading line count: %s\n" "$2"
-            exit "$__code"
-          })"
-          shift
-        }
-        ;;
-      -*trail*l* | --tl)
-        __trail_lines=1
-        [ -n "$2" ] && {
-          __trail_lines="$(validate --integer "$2" || {
-            printf "ERROR: Invalid trailing line count: %s\n" "$2"
-            exit "$__code"
-          })"
-          shift
-        }
-        ;;
-      -*trail*s | --ts)
-        [ "$2" ] && {
-          __trail_sep="$2"
-          shift
-        }
-        ;;
-      -m | -*message | -*msg)
-        while [ "$#" -gt 1 ]; do
-          case "$2" in
-            -*) break ;;
-            *)
-              __msg="${__msg:+$__msg }$2"
-              shift
-              ;;
-          esac
-        done
-        ;;
-      -c | -*code)
-        if [ "$2" ]; then
-          __code="$2"
-          shift
-        else
-          __code=1
-        fi
-        ;;
-      --) ;;
-      -*)
-        printf 'ERROR: Unknown option '%s'\n' "$1" >&2
+    -h)
+      printf '%s' "$scr_usage"
+      exit "$__code"
+      ;;
+    --help)
+      printf '%s' "$scr_guide"
+      exit "$__code"
+      ;;
+    -v)
+      printf '%s' "$scr_version"
+      exit "$__code"
+      ;;
+    --version)
+      printf "%s [ v.%s ]\n" "$scr_name" "$scr_version"
+      exit "$__code"
+      ;;
+    --quiet | --error | --warn | --info | --debug | --trace)
+      __msg_type=${1#--}
+      ;;
+    -*level | -*verb*)
+      if [ "$2" ]; then
+        set_verbosity "$2"
+        shift
+      else
+        set_verbosity
+      fi
+      ;;
+    -t | --tag | -N | --name)
+      if [ "$2" ]; then
+        __tag="$2"
+        shift
+      else
+        printf "ERROR: Tag not specified.\n"
         __code=1
         exit "$__code"
-        ;;
-      *)
-        __msg="${__msg:+$__msg }$1"
-        ;;
+      fi
+      ;;
+    -*type)
+      if [ "$2" ]; then
+        __msg_type="$(validate "$2" "$__msg_types")"
+        #@ Throw error if message type is invalid
+        [ -n "$__msg_type" ] || {
+          templates --invalid "parse_arguments" "message type" "$2" "$__msg_types"
+          __code=1
+          exit "$__code"
+        }
+        shift
+      else
+        #@ Throw error if message type is not specified
+        pout --name "parse_arguments" --type error --msg "Message type not specified"
+        __code=1
+        exit "$__code"
+      fi
+      ;;
+    -*lead*l* | --ll)
+      __lead_lines=1
+      [ -n "$2" ] && {
+        __lead_lines="$(validate --integer "$2" || {
+          printf "ERROR: Invalid leading line count: %s\n" "$2"
+          exit "$__code"
+        })"
+        shift
+      }
+      ;;
+    -*trail*l* | --tl)
+      __trail_lines=1
+      [ -n "$2" ] && {
+        __trail_lines="$(validate --integer "$2" || {
+          printf "ERROR: Invalid trailing line count: %s\n" "$2"
+          exit "$__code"
+        })"
+        shift
+      }
+      ;;
+    -*trail*s | --ts)
+      [ "$2" ] && {
+        __trail_sep="$2"
+        shift
+      }
+      ;;
+    -m | -*message | -*msg)
+      while [ "$#" -gt 1 ]; do
+        case "$2" in
+        -*) break ;;
+        *)
+          __msg="${__msg:+$__msg }$2"
+          shift
+          ;;
+        esac
+      done
+      ;;
+    -c | -*code)
+      if [ "$2" ]; then
+        __code="$2"
+        shift
+      else
+        __code=1
+      fi
+      ;;
+    --) ;;
+    -*)
+      printf 'ERROR: Unknown option '%s'\n' "$1" >&2
+      __code=1
+      exit "$__code"
+      ;;
+    *)
+      __msg="${__msg:+$__msg }$1"
+      ;;
     esac
     shift
   done
@@ -468,35 +468,35 @@ print_out() {
 
   #@ Format the title with consistent spacing and color handling
   case "$__msg_type" in
-    err*)
-      [ "$__level" -ge "$__level_error" ] || exit "$__code"
-      __title="$(printf '%b[ERROR]%b' "$__error" "$__normal")"
-      ;;
-    warn*)
-      [ "$__level" -ge "$__level_warn" ] || exit "$__code"
-      __title="$(printf '%b[ WARN]%b' "$__warn" "$__normal")"
-      ;;
-    info*)
-      [ "$__level" -ge "$__level_info" ] || exit "$__code"
-      __title="$(printf '%b[ INFO]%b' "$__info" "$__normal")"
-      ;;
-    debug*)
-      [ "$__level" -ge "$__level_debug" ] || exit "$__code"
-      __title="$(printf '%b[DEBUG]%b' "$__debug" "$__normal")"
-      ;;
-    trace*)
-      [ "$__level" -ge "$__level_trace" ] || exit "$__code"
-      __title="$(printf '%b[TRACE]%b' "$__trace" "$__normal")"
-      ;;
-    succ*)
-      [ "$__level" -gt "$__level_quiet" ] || exit "$__code"
-      __title="$(printf '%b[SUCCESS]%b' "$__success" "$__normal")"
-      ;;
-    fail*)
-      [ "$__level" -gt "$__level_quiet" ] || exit "$__code"
-      __title="$(printf '%b[FAILURE]%b' "$__failure" "$__normal")"
-      ;;
-    normal | simple | *) unset __title __tag __color ;;
+  err*)
+    [ "$__level" -ge "$__level_error" ] || exit "$__code"
+    __title="$(printf '%b[ERROR]%b' "$__error" "$__normal")"
+    ;;
+  warn*)
+    [ "$__level" -ge "$__level_warn" ] || exit "$__code"
+    __title="$(printf '%b[ WARN]%b' "$__warn" "$__normal")"
+    ;;
+  info*)
+    [ "$__level" -ge "$__level_info" ] || exit "$__code"
+    __title="$(printf '%b[ INFO]%b' "$__info" "$__normal")"
+    ;;
+  debug*)
+    [ "$__level" -ge "$__level_debug" ] || exit "$__code"
+    __title="$(printf '%b[DEBUG]%b' "$__debug" "$__normal")"
+    ;;
+  trace*)
+    [ "$__level" -ge "$__level_trace" ] || exit "$__code"
+    __title="$(printf '%b[TRACE]%b' "$__trace" "$__normal")"
+    ;;
+  succ*)
+    [ "$__level" -gt "$__level_quiet" ] || exit "$__code"
+    __title="$(printf '%b[SUCCESS]%b' "$__success" "$__normal")"
+    ;;
+  fail*)
+    [ "$__level" -gt "$__level_quiet" ] || exit "$__code"
+    __title="$(printf '%b[FAILURE]%b' "$__failure" "$__normal")"
+    ;;
+  normal | simple | *) unset __title __tag __color ;;
   esac
 
   #@ Format the tag with proper color handling
@@ -506,16 +506,16 @@ print_out() {
 
   #@ Define the output stream and exit "$__code" code
   case "$__msg_type" in
-    err* | fail*)
-      __code="${__code:-1}"
-      __stream=2
-      ;;
-    warn*)
-      __stream=2
-      ;;
-    *)
-      __stream=1
-      ;;
+  err* | fail*)
+    __code="${__code:-1}"
+    __stream=2
+    ;;
+  warn*)
+    __stream=2
+    ;;
+  *)
+    __stream=1
+    ;;
   esac
 
   #@ Print leading lines, if requested
diff --git a/Bin/shellscript/utility/output/term_output b/Bin/shellscript/utility/output/term_output
--- a/Bin/shellscript/utility/output/term_output
+++ b/Bin/shellscript/utility/output/term_output
@@ -3,7 +3,7 @@
 
 __tput__() {
   #@ Ensure `tput` is available
-  type tput > /dev/null 2>&1 || return
+  type tput >/dev/null 2>&1 || return
 
   #@ Declare colors for supported terminals
   case "$TERM" in *-m) return ;; esac
@@ -106,20 +106,20 @@ __ansi__() {
 center_with_tput() {
   while [ $# -gt 0 ]; do
     case $1 in
-      -t | --text)
-        text="$2"
-        ;;
-      -s | --spacer)
-        if [ "${#2}" -ne 1 ]; then
-          echo "Error: Spacer must be a single character."
-          return 1
-        fi
-        spacer="$2"
-        ;;
-      *)
-        text="${text:-"$1"}"
-        spacer="${spacer:-" "}"
-        ;;
+    -t | --text)
+      text="$2"
+      ;;
+    -s | --spacer)
+      if [ "${#2}" -ne 1 ]; then
+        echo "Error: Spacer must be a single character."
+        return 1
+      fi
+      spacer="$2"
+      ;;
+    *)
+      text="${text:-"$1"}"
+      spacer="${spacer:-" "}"
+      ;;
     esac
     shift
   done
@@ -160,39 +160,39 @@ print_with_tput() {
   __print__() {
     while [ $# -gt 0 ]; do
       case $1 in
-        --reset) printf "%s" "$(tput sgr0)" ;;
-        --bold) printf "%s" "$(tput bold)" ;;
-        --dim) printf "%s" "$(tput dim)" ;;
-        --italic) printf "%s" "$(tput sitm)" ;;
-        --underline) printf "%s" "$(tput smul)" ;;
-        --invert) printf "%s" "$(tput smso)" ;;
-        --hidden) printf "%s" "$(tput invis)" ;;
-        --blink) printf "%s" "$(tput blink)" ;;
-        --fg-black) printf "%s" "$(tput setaf 0)" ;;
-        --fg-red) printf "%s" "$(tput setaf 1)" ;;
-        --fg-green) printf "%s" "$(tput setaf 2)" ;;
-        --fg-yellow) printf "%s" "$(tput setaf 3)" ;;
-        --fg-blue) printf "%s" "$(tput setaf 4)" ;;
-        --fg-magenta) printf "%s" "$(tput setaf 5)" ;;
-        --fg-cyan) printf "%s" "$(tput setaf 6)" ;;
-        --bg-black) printf "%s" "$(tput setab 0)" ;;
-        --fg-white) printf "%s" "$(tput setaf 7)" ;;
-        --bg-red) printf "%s" "$(tput setab 1)" ;;
-        --bg-green) printf "%s" "$(tput setab 2)" ;;
-        --bg-yellow) printf "%s" "$(tput setab 3)" ;;
-        --bg-blue) printf "%s" "$(tput setab 4)" ;;
-        --bg-magenta) printf "%s" "$(tput setab 5)" ;;
-        --bg-cyan) printf "%s" "$(tput setab 6)" ;;
-        --bg-white) printf "%s" "$(tput setab 7)" ;;
-        --newline) printf "\n" ;;
-        --space) printf " " ;;
-        --center)
-          [ "$2" ] && {
-            center_with_tput "$2"
-            shift
-          }
-          ;;
-        *) printf "%s" "$1" ;;
+      --reset) printf "%s" "$(tput sgr0)" ;;
+      --bold) printf "%s" "$(tput bold)" ;;
+      --dim) printf "%s" "$(tput dim)" ;;
+      --italic) printf "%s" "$(tput sitm)" ;;
+      --underline) printf "%s" "$(tput smul)" ;;
+      --invert) printf "%s" "$(tput smso)" ;;
+      --hidden) printf "%s" "$(tput invis)" ;;
+      --blink) printf "%s" "$(tput blink)" ;;
+      --fg-black) printf "%s" "$(tput setaf 0)" ;;
+      --fg-red) printf "%s" "$(tput setaf 1)" ;;
+      --fg-green) printf "%s" "$(tput setaf 2)" ;;
+      --fg-yellow) printf "%s" "$(tput setaf 3)" ;;
+      --fg-blue) printf "%s" "$(tput setaf 4)" ;;
+      --fg-magenta) printf "%s" "$(tput setaf 5)" ;;
+      --fg-cyan) printf "%s" "$(tput setaf 6)" ;;
+      --bg-black) printf "%s" "$(tput setab 0)" ;;
+      --fg-white) printf "%s" "$(tput setaf 7)" ;;
+      --bg-red) printf "%s" "$(tput setab 1)" ;;
+      --bg-green) printf "%s" "$(tput setab 2)" ;;
+      --bg-yellow) printf "%s" "$(tput setab 3)" ;;
+      --bg-blue) printf "%s" "$(tput setab 4)" ;;
+      --bg-magenta) printf "%s" "$(tput setab 5)" ;;
+      --bg-cyan) printf "%s" "$(tput setab 6)" ;;
+      --bg-white) printf "%s" "$(tput setab 7)" ;;
+      --newline) printf "\n" ;;
+      --space) printf " " ;;
+      --center)
+        [ "$2" ] && {
+          center_with_tput "$2"
+          shift
+        }
+        ;;
+      *) printf "%s" "$1" ;;
       esac
       shift
     done
diff --git a/Bin/shellscript/utility/path_convert3 b/Bin/shellscript/utility/path_convert3
--- a/Bin/shellscript/utility/path_convert3
+++ b/Bin/shellscript/utility/path_convert3
@@ -3,7 +3,7 @@
 
 scr_name="path_convert"
 scr_usage=$(
-  cat << HELP
+  cat <<HELP
 USAGE:
   $scr_name [OPTIONS] [STRING]
 
@@ -54,33 +54,33 @@ parse_input() {
 
   while [ $# -gt 0 ]; do
     case "$1" in
-      -h | --help)
-        print_help
-        exit
-        ;;
-      -d | --verbose)
-        verbosity=2
-        ;;
-      -p | --prefix)
-        prefix="$2"
-        shift
-        ;;
-      -c | --clip)
-        clip=true
-        ;;
-      -q | --quiet)
-        verbosity=0
-        ;;
-      *)
-        if [ "$1" ]; then
-          input_path="$(clean_path "$1")"
-          # input_path="$(validate_path "$1")"
-          input_path_type="$(validate_path --type "$1")"
-        else
-          printf "%s\n" "$scr_usage"
-          exit 1
-        fi
-        ;;
+    -h | --help)
+      print_help
+      exit
+      ;;
+    -d | --verbose)
+      verbosity=2
+      ;;
+    -p | --prefix)
+      prefix="$2"
+      shift
+      ;;
+    -c | --clip)
+      clip=true
+      ;;
+    -q | --quiet)
+      verbosity=0
+      ;;
+    *)
+      if [ "$1" ]; then
+        input_path="$(clean_path "$1")"
+        # input_path="$(validate_path "$1")"
+        input_path_type="$(validate_path --type "$1")"
+      else
+        printf "%s\n" "$scr_usage"
+        exit 1
+      fi
+      ;;
     esac
     shift
   done
@@ -104,19 +104,19 @@ clean_path() {
 
   #@ Check for Widsows path then default to Unix
   case "$clean_path" in
-    *:*)
-      #@ Remove the leading slash, if one exists (eg. /C:/ = C:/)
-      clean_path="${clean_path#/}"
+  *:*)
+    #@ Remove the leading slash, if one exists (eg. /C:/ = C:/)
+    clean_path="${clean_path#/}"
 
-      #@ Add a trailing slash if the path ends with colon (eg. C: = C:/)
-      [ "${clean_path#"${clean_path%?}"}" = ":" ] \
-        && clean_path="${clean_path}/"
-      ;;
-    *)
-      # Add a leading slash, if missing (eg. mnt/... = /mnt/...)
-      [ "${clean_path#/}" = "$clean_path" ] \
-        && clean_path="/$clean_path"
-      ;;
+    #@ Add a trailing slash if the path ends with colon (eg. C: = C:/)
+    [ "${clean_path#"${clean_path%?}"}" = ":" ] &&
+      clean_path="${clean_path}/"
+    ;;
+  *)
+    # Add a leading slash, if missing (eg. mnt/... = /mnt/...)
+    [ "${clean_path#/}" = "$clean_path" ] &&
+      clean_path="/$clean_path"
+    ;;
   esac
 
   printf "%s" "$clean_path"
@@ -127,18 +127,18 @@ validate_path() {
   #@ Parse the path input
   while [ $# -gt 0 ]; do
     case "$1" in
-      --type) check_type=true ;;
-      -w | --win*) path_type="Windows" ;;
-      -u | --unix) path_type="Unix" ;;
-      *)
-        #@ Check if the path is empty
-        if [ "$1" ]; then
-          path="$1"
-        else
-          printf "Missing path string"
-          return 1
-        fi
-        ;;
+    --type) check_type=true ;;
+    -w | --win*) path_type="Windows" ;;
+    -u | --unix) path_type="Unix" ;;
+    *)
+      #@ Check if the path is empty
+      if [ "$1" ]; then
+        path="$1"
+      else
+        printf "Missing path string"
+        return 1
+      fi
+      ;;
     esac
     shift
   done
@@ -162,38 +162,38 @@ validate_path() {
 
     #@ Check for Widsows path then default to Unix
     case "$path" in
-      *:*)
-        #@ Validate the Windows path
-        case "$path" in
-          [A-Za-z]:/*)
-            #@ Set Path Type
-            path_type="Windows"
-            ;;
-          *)
-            #@ Extract the drive letter (e.g., C)
-            drive=${path%%:*}
-
-            if [ -z "$drive" ]; then
-              msg="Missing Windowsdrive letter: $drive"
-            elif [ "${#drive}" -ne 1 ]; then
-              msg="Invalid Windows drive letter length: $drive"
-            elif ! printf "%s" "$drive" \
-              | grep --extended-regexp --quiet '^[A-Za-z]$'; then
-              msg="Invalid Windows drive letter character: $drive"
-            fi
-            printf "%s" "$msg"
-            return 1
-            ;;
-        esac
+    *:*)
+      #@ Validate the Windows path
+      case "$path" in
+      [A-Za-z]:/*)
+        #@ Set Path Type
+        path_type="Windows"
         ;;
       *)
-        # Add a leading slash, if missing (eg. mnt/... = /mnt/...)
-        [ "${path#/}" = "$path" ] \
-          && path="/$path"
+        #@ Extract the drive letter (e.g., C)
+        drive=${path%%:*}
 
-        #@ Set Path Type
-        path_type="Unix"
+        if [ -z "$drive" ]; then
+          msg="Missing Windowsdrive letter: $drive"
+        elif [ "${#drive}" -ne 1 ]; then
+          msg="Invalid Windows drive letter length: $drive"
+        elif ! printf "%s" "$drive" |
+          grep --extended-regexp --quiet '^[A-Za-z]$'; then
+          msg="Invalid Windows drive letter character: $drive"
+        fi
+        printf "%s" "$msg"
+        return 1
         ;;
+      esac
+      ;;
+    *)
+      # Add a leading slash, if missing (eg. mnt/... = /mnt/...)
+      [ "${path#/}" = "$path" ] &&
+        path="/$path"
+
+      #@ Set Path Type
+      path_type="Unix"
+      ;;
     esac
 
     if [ "$proc_type_check" ]; then
@@ -257,10 +257,10 @@ convert_to_linux_path() {
   path="$1"
 
   case "$path" in
-    *:/*)
-      printf "Invalid windows path (%s) missing :/" "$path"
-      return 1
-      ;;
+  *:/*)
+    printf "Invalid windows path (%s) missing :/" "$path"
+    return 1
+    ;;
   esac
 
   # Replace backslashes with forward slashes
@@ -282,8 +282,8 @@ convert_to_linux_path() {
 
   # Check if the drive letter contains only one letter and has a length of 1
   if
-    [ "${#drive}" -eq 1 ] \
-      && printf "%s" "$drive" | grep -Eq '^[A-Za-z]$'
+    [ "${#drive}" -eq 1 ] &&
+      printf "%s" "$drive" | grep -Eq '^[A-Za-z]$'
   then
     # Remove the colon from the drive letter
     drive=${drive%:}
@@ -316,16 +316,16 @@ convert_to_linux_path() {
 
 parse_output() {
   case "$verbosity" in
-    0) ;;
-    1) ;;
-    *)
-      printf "Path Input: %s\n" "$input_path"
-      printf "Path Input Type: %s\n" "$input_path_type"
-      printf "Path Output: %s\n" "$output_path"
-      printf "Path Output Type: %s\n" "$output_path_type"
-      echo "EXIT CODE: $exit_code"
-      echo "Check Type: $check_type"
-      ;;
+  0) ;;
+  1) ;;
+  *)
+    printf "Path Input: %s\n" "$input_path"
+    printf "Path Input Type: %s\n" "$input_path_type"
+    printf "Path Output: %s\n" "$output_path"
+    printf "Path Output Type: %s\n" "$output_path_type"
+    echo "EXIT CODE: $exit_code"
+    echo "Check Type: $check_type"
+    ;;
   esac
 
   [ "$clip" ] && send_to_clipboard "$path"
diff --git a/Bin/shellscript/utility/sshIt2 b/Bin/shellscript/utility/sshIt2
--- a/Bin/shellscript/utility/sshIt2
+++ b/Bin/shellscript/utility/sshIt2
@@ -5,18 +5,18 @@ appName="sshIt"
 appVersion="0.10"
 
 case "$1" in
-  -h | --help)
-    _HELP=true
-    ;;
-  -v | --version)
-    _VER=true
-    ;;
-  -e | --src | --env)
-    _SRC=true
-    shift
-    _ENV="$*"
-    ;;
-  *) ;;
+-h | --help)
+  _HELP=true
+  ;;
+-v | --version)
+  _VER=true
+  ;;
+-e | --src | --env)
+  _SRC=true
+  shift
+  _ENV="$*"
+  ;;
+*) ;;
 esac
 
 __help__() {
@@ -37,53 +37,53 @@ __main__() {
 __error__() {
   args=$(printf "%s" "$1" | tr '[:upper:]' '[:lower:]')
   case "$args" in
-    --required)
-      printf "%s" "🚩 This is ${error}required${reset}
+  --required)
+    printf "%s" "🚩 This is ${error}required${reset}
             "
-      exit 1
-      ;;
-    --naked)
-      printf "%s" "🚩 Invalid character(s): ${error}$_invalid${reset}
+    exit 1
+    ;;
+  --naked)
+    printf "%s" "🚩 Invalid character(s): ${error}$_invalid${reset}
             "
-      exit 1
-      ;;
-    --character)
-      printf "%s" "🚩 Invalid characters were removed:
+    exit 1
+    ;;
+  --character)
+    printf "%s" "🚩 Invalid characters were removed:
     🟥 $_invalid
     ✅ $_valid
             "
-      ;;
-    --selection)
-      printf "%s" "🚩 Invalid Selection
+    ;;
+  --selection)
+    printf "%s" "🚩 Invalid Selection
             "
-      ;;
-    --env)
-      shift
-      printf "%s" "🚩 The ${error}ENV file${reset} path is invalid: \"$_ENV\""
-      __ui__ --file
-      ;;
-    --id_exists)
-      shift
-      printf "%s" "
+    ;;
+  --env)
+    shift
+    printf "%s" "🚩 The ${error}ENV file${reset} path is invalid: \"$_ENV\""
+    __ui__ --file
+    ;;
+  --id_exists)
+    shift
+    printf "%s" "
 🚩 This ${error}identity file${reset} already exists:
 \"$*\"
             "
-      __ui__ --id_exists
-      ;;
-    --file)
-      shift
-      printf "%s
+    __ui__ --id_exists
+    ;;
+  --file)
+    shift
+    printf "%s
 🚩 Invalid File:
 \"$*\""
-      __ui__ --file
-      ;;
-    --path)
-      shift
-      printf "%s" "
+    __ui__ --file
+    ;;
+  --path)
+    shift
+    printf "%s" "
             🚩 Invalid Path:
             \"$*\""
-      __ui__ --path
-      ;;
+    __ui__ --path
+    ;;
   esac
 }
 
@@ -95,109 +95,109 @@ __ui__() {
 
   opts=$(printf "%s" "$*" | tr '[:upper:]' '[:lower:]')
   case "$opts" in
-    --host)
-      printf "%s " "${italic}Who is the ${success}host${reset}?"
-      read -r _INPUT
-      __valid_name__ "$_INPUT"
-      sshHost="$_valid"
-      ;;
-    --user)
-      printf "%s " "${italic}Who is the ${info}user${reset}?"
-      read -r _INPUT
-      __valid_name__ "$_INPUT"
-      sshName="$_valid"
-      ;;
-    --hostname)
-      printf "%s " "${italic}What is the ${info}hostname${reset}?"
-      read -r _INPUT
-      __valid_name__ "$_INPUT"
-      sshHostName="$_valid"
-      ;;
-    --id_new)
-      printf "%s " "${italic}Where should the ${info}Identity File${reset} be saved?"
-      read -r _INPUT
-      __valid_id__ "$_INPUT"
-      __valid_pathname__ "$_INPUT"
-      sshID="$_valid"
-      ;;
-    --id_default)
-      printf "%s " "${italic}Save the ${info}Identity File${reset} to the default location? [Y|n]
+  --host)
+    printf "%s " "${italic}Who is the ${success}host${reset}?"
+    read -r _INPUT
+    __valid_name__ "$_INPUT"
+    sshHost="$_valid"
+    ;;
+  --user)
+    printf "%s " "${italic}Who is the ${info}user${reset}?"
+    read -r _INPUT
+    __valid_name__ "$_INPUT"
+    sshName="$_valid"
+    ;;
+  --hostname)
+    printf "%s " "${italic}What is the ${info}hostname${reset}?"
+    read -r _INPUT
+    __valid_name__ "$_INPUT"
+    sshHostName="$_valid"
+    ;;
+  --id_new)
+    printf "%s " "${italic}Where should the ${info}Identity File${reset} be saved?"
+    read -r _INPUT
+    __valid_id__ "$_INPUT"
+    __valid_pathname__ "$_INPUT"
+    sshID="$_valid"
+    ;;
+  --id_default)
+    printf "%s " "${italic}Save the ${info}Identity File${reset} to the default location? [Y|n]
             ${defaultID}"
-      read -r OPT
-      case $OPT in
-        n* | N*)
-          __ui__ --id_new
-          ;;
-        y* | Y* | *)
-          _INPUT="${defaultID}"
-          ;;
-      esac
+    read -r OPT
+    case $OPT in
+    n* | N*)
+      __ui__ --id_new
       ;;
-    --id_exists)
-      printf "%s " "${italic}Overwrite the current ${bold}identity${reset} file [${bold}N${reset}|y]?"
-      read -r OPT
-      case $OPT in
-        y* | Y*)
-          _RESET=true
-          printf "%s" "Existing identity file archived"
-          ;;
-        n* | N*)
-          __ui__ --id_new
-          ;;
-        *)
-          __error__ --selection
-          __ui__ --id_exists
-          ;;
-      esac
+    y* | Y* | *)
+      _INPUT="${defaultID}"
       ;;
-    --env)
-      printf "%s " "${italic}What is the path to the ${info}ENV${reset} file?"
-      read -r _INPUT
-      __valid_env__ "$_INPUT"
+    esac
+    ;;
+  --id_exists)
+    printf "%s " "${italic}Overwrite the current ${bold}identity${reset} file [${bold}N${reset}|y]?"
+    read -r OPT
+    case $OPT in
+    y* | Y*)
+      _RESET=true
+      printf "%s" "Existing identity file archived"
       ;;
-    --file)
-      printf "%s " "${italic}Please enter a valid path to the ${bold}file${reset}."
-      read -r _INPUT
-      __valid_file__ "$_INPUT"
+    n* | N*)
+      __ui__ --id_new
       ;;
-    --path)
-      printf "%s " "${italic}Please enter a valid ${bold}path${reset}."
-      read -r _INPUT
-      __valid_pathname__ "$_INPUT"
+    *)
+      __error__ --selection
+      __ui__ --id_exists
       ;;
-    --confirm)
-      #| Print content before the ID
-      printf "%s
+    esac
+    ;;
+  --env)
+    printf "%s " "${italic}What is the path to the ${info}ENV${reset} file?"
+    read -r _INPUT
+    __valid_env__ "$_INPUT"
+    ;;
+  --file)
+    printf "%s " "${italic}Please enter a valid path to the ${bold}file${reset}."
+    read -r _INPUT
+    __valid_file__ "$_INPUT"
+    ;;
+  --path)
+    printf "%s " "${italic}Please enter a valid ${bold}path${reset}."
+    read -r _INPUT
+    __valid_pathname__ "$_INPUT"
+    ;;
+  --confirm)
+    #| Print content before the ID
+    printf "%s
         Continue with this SSH config? [Y|n]?
   |> ---------------------------------------- <|
               Host | $sshHost
           Hostname | $sshHostName
               User | $sshName\n"
 
-      #| Wrap if ID length exceeds 22 characters"
-      ID_len="${#sshID}"
-      if [ "$ID_len" -gt 22 ]; then
-        printf "%-15s ID | ⤵ \n %-5s $sshID \n"
-      else
-        printf "%-15s ID | $sshID \n"
-      fi
+    #| Wrap if ID length exceeds 22 characters"
+    ID_len="${#sshID}"
+    if [ "$ID_len" -gt 22 ]; then
+      printf "%-15s ID | ⤵ \n %-5s $sshID \n"
+    else
+      printf "%-15s ID | $sshID \n"
+    fi
 
-      read -r OPT
-      case $OPT in
-        n* | N*)
-          __ui__ --change
-          ;;
-        y* | Y* | *)
-          return
-          ;;
-          # *)
-          #   __error__ --selection
-          #   __ui__ --confirm
-          # ;;
-      esac
+    read -r OPT
+    case $OPT in
+    n* | N*)
+      __ui__ --change
       ;;
-    --change)
-      printf "
+    y* | Y* | *)
+      return
+      ;;
+      # *)
+      #   __error__ --selection
+      #   __ui__ --confirm
+      # ;;
+    esac
+    ;;
+  --change)
+    printf "
               Select Change Option
   |> ---------------------------------------- <|
                 1. ENV Key File
@@ -207,21 +207,21 @@ __ui__() {
                 5. Identity File
                 6. Cancel
             "
-      read -r n
-      case $n in
-        1) __ui__ --env ;;
-        2) __ui__ --host ;;
-        3) __ui__ --hostname ;;
-        4) __ui__ --user ;;
-        5) __ui__ --id_new ;;
-        6)
-          printf "%s" "Exiting $appName"
-          exit
-          ;;
-        *) __error__ --selection ;;
-      esac
-      __ui__ --confirm
+    read -r n
+    case $n in
+    1) __ui__ --env ;;
+    2) __ui__ --host ;;
+    3) __ui__ --hostname ;;
+    4) __ui__ --user ;;
+    5) __ui__ --id_new ;;
+    6)
+      printf "%s" "Exiting $appName"
+      exit
       ;;
+    *) __error__ --selection ;;
+    esac
+    __ui__ --confirm
+    ;;
   esac
 
   #| Enable user input display
@@ -257,9 +257,9 @@ __variables__() {
       fi
 
       case "$(printf "%s" "$sshHost" | tr '[:upper:]' '[:lower:]')" in
-        *github*) sshHostLabel="$GitHub" ;;
-        *gitlab*) sshHostLabel="$GitLab" ;;
-        *) ;;
+      *github*) sshHostLabel="$GitHub" ;;
+      *gitlab*) sshHostLabel="$GitLab" ;;
+      *) ;;
       esac
     }
 
@@ -324,8 +324,8 @@ __variables__() {
         )"
 
         #| Archive exixting files
-        [ -f "$sshID" ] \
-          && for file in $FILEStoArchive; do
+        [ -f "$sshID" ] &&
+          for file in $FILEStoArchive; do
             bakDIR="${sshIDdir}/archive"
             mkdir --parents "$bakDIR"
             mv "$file" --backup=numbered --target-directory="$bakDIR"
@@ -368,15 +368,15 @@ __init__() {
 
   #| Generate public/private algorithm key pair, respectively.
   ssh-keygen -t ed25519 -a 100 -f "${sshID}" -C "$(INFor --label)"
-  ssh-keygen -y -f "${sshID}" > "${sshID}.pub"
+  ssh-keygen -y -f "${sshID}" >"${sshID}.pub"
 
   #| Start the ssh-agent and add the private key to it.
   eval "$(ssh-agent)" && ssh-add "${sshID}"
 
   printf \
     "Host %s\n  \tUser %s\n  \tHostName %s\n  \tIdentityFile %s\n" \
-    "$sshHost" "$sshName" "$sshHostName" "$sshID" \
-    | tee --append "${sshDIR}/config"
+    "$sshHost" "$sshName" "$sshHostName" "$sshID" |
+    tee --append "${sshDIR}/config"
 
   #| Send the contents of the public key to the clipboard
   clip-c "$(cat "$sshID.pub")"
diff --git a/Bin/shellscript/utility/validators/goodgood b/Bin/shellscript/utility/validators/goodgood
--- a/Bin/shellscript/utility/validators/goodgood
+++ b/Bin/shellscript/utility/validators/goodgood
@@ -47,56 +47,56 @@ main() {
 parse_arguments() {
   while [ $# -ge 1 ]; do
     case "$1" in
-      -h | --help)
-        printf "%s" "$scr_usage"
-        exit
-        ;;
-      -v | --version)
-        printf "%s" "$scr_version"
-        exit
-        ;;
-      -d | --verbose)
-        verbosity=2
-        ;;
-      -q | --quiet)
-        verbosity=0
-        ;;
-      --type)
-        [ "$2" ] && {
-          case "$(printf "%s" "$2" | tr '[:upper:]' '[:lower:]')" in
-            int*) type="integer" ;;
-            char*) type="character" ;;
-            fl*) type="float" ;;
-            num*) type="number" ;;
-            str*) type="string" ;;
-            a*) type="array" ;;
-            f*) type="file" ;;
-            d*) type="directory" ;;
-            i*) type="ip_address" ;;
-            u*) type="url" ;;
-            r*)
-              [ "$3" ] && {
-                type="regex"
-                regex="$3"
-                shift
-              }
-              ;;
-            g*) type="git_repo" ;;
-            *)
-              printf "Error: Invalid type specified.\n\n%s\n" "$scr_usage"
-              exit 1
-              ;;
-          esac
-          shift
-        }
-        ;;
-      --var)
-        [ "$2" ] && {
-          var="$2"
-          shift
-        }
-        ;;
-      *) var="$1" ;;
+    -h | --help)
+      printf "%s" "$scr_usage"
+      exit
+      ;;
+    -v | --version)
+      printf "%s" "$scr_version"
+      exit
+      ;;
+    -d | --verbose)
+      verbosity=2
+      ;;
+    -q | --quiet)
+      verbosity=0
+      ;;
+    --type)
+      [ "$2" ] && {
+        case "$(printf "%s" "$2" | tr '[:upper:]' '[:lower:]')" in
+        int*) type="integer" ;;
+        char*) type="character" ;;
+        fl*) type="float" ;;
+        num*) type="number" ;;
+        str*) type="string" ;;
+        a*) type="array" ;;
+        f*) type="file" ;;
+        d*) type="directory" ;;
+        i*) type="ip_address" ;;
+        u*) type="url" ;;
+        r*)
+          [ "$3" ] && {
+            type="regex"
+            regex="$3"
+            shift
+          }
+          ;;
+        g*) type="git_repo" ;;
+        *)
+          printf "Error: Invalid type specified.\n\n%s\n" "$scr_usage"
+          exit 1
+          ;;
+        esac
+        shift
+      }
+      ;;
+    --var)
+      [ "$2" ] && {
+        var="$2"
+        shift
+      }
+      ;;
+    *) var="$1" ;;
     esac
     shift
   done
@@ -123,7 +123,7 @@ execute() {
   }
 
   is_integer() {
-    if [ "$1" -eq "$1" ] 2> /dev/null; then
+    if [ "$1" -eq "$1" ] 2>/dev/null; then
       return 0
     else
       return 1
@@ -131,7 +131,7 @@ execute() {
   }
 
   is_float() {
-    if type python > /dev/null 2>&1; then
+    if type python >/dev/null 2>&1; then
       python -c "import sys; value = sys.argv[1]; exit(1) if not (value.replace('.', '', 1).isdigit() or (value.startswith('-') and value[1:].replace('.', '', 1).isdigit())) else exit(0)" "$1"
     fi
   }
@@ -165,8 +165,8 @@ execute() {
   }
 
   is_url() {
-    printf "%s" "$1" \
-      | grep --extended-regexp --quiet '^(http|https|ftp|sftp)://'
+    printf "%s" "$1" |
+      grep --extended-regexp --quiet '^(http|https|ftp|sftp)://'
   }
 
   is_regex() {
@@ -174,45 +174,45 @@ execute() {
   }
 
   is_git_repo() {
-    [ -d "$1/.git" ] && git -C "$1" rev-parse --is-inside-work-tree > /dev/null 2>&1
+    [ -d "$1/.git" ] && git -C "$1" rev-parse --is-inside-work-tree >/dev/null 2>&1
   }
 
   #@ Validate the specified variable based on the chosen type
   case "$type" in
-    regex)
-      if is_regex "$var" "$regex" s; then
-        msg="Success - $var matches the regex pattern."
-      else
-        msg="Failed - $var does not match the regex pattern."
-        exit_code=1
-      fi
-      ;;
-    *)
-      if eval "is_${type} \"$var\""; then
-        msg="Success - $var is a valid $type."
-      else
-        msg="Failed - $var is not a valid $type."
-        exit_code=1
-      fi
-      ;;
+  regex)
+    if is_regex "$var" "$regex" s; then
+      msg="Success - $var matches the regex pattern."
+    else
+      msg="Failed - $var does not match the regex pattern."
+      exit_code=1
+    fi
+    ;;
+  *)
+    if eval "is_${type} \"$var\""; then
+      msg="Success - $var is a valid $type."
+    else
+      msg="Failed - $var is not a valid $type."
+      exit_code=1
+    fi
+    ;;
   esac
 }
 
 terminate() {
   #@ Display output based on verbosity level
   case "$verbosity" in
-    0) ;;
-    1)
-      printf "%s\n" "$var"
-      ;;
-    *)
-      printf "  VAR: %s\n" "$var"
-      [ "$regex" ] \
-        && printf "REGEX: %s\n" "$regex"
-      printf " TYPE: %s\n" "$type"
-      printf " CODE: %s\n" "$exit_code"
-      printf "  MSG: %s\n" "$msg"
-      ;;
+  0) ;;
+  1)
+    printf "%s\n" "$var"
+    ;;
+  *)
+    printf "  VAR: %s\n" "$var"
+    [ "$regex" ] &&
+      printf "REGEX: %s\n" "$regex"
+    printf " TYPE: %s\n" "$type"
+    printf " CODE: %s\n" "$exit_code"
+    printf "  MSG: %s\n" "$msg"
+    ;;
   esac
 
   #@ Exit with the specified exit code
diff --git a/Bin/shellscript/utility/wallpaper/wallter b/Bin/shellscript/utility/wallpaper/wallter
--- a/Bin/shellscript/utility/wallpaper/wallter
+++ b/Bin/shellscript/utility/wallpaper/wallter
@@ -3,7 +3,7 @@
 #TODO# Document usage information
 #TODO# Add an option to archive
 
-: << 'Documentation'
+: <<'Documentation'
 asd
 Documentation
 
@@ -41,38 +41,38 @@ init_metadata() { #@ Initalize script metadata
 init_arguments() { #@ Parse command-line arguments
   while [ $# -gt 0 ]; do
     case $1 in
-      -h | --help) end_process --usage ;;
-      -v | --version) end_process --version ;;
-      -q | --quiet) verbosity=quiet ;;
-      -d=* | --verbose=*) verbosity="${1#*=}" ;;
-      -d | --verbose)
-        case "$2" in
-          */*) verbosity="debug" ;;
-          *)
-            if [ "$2" ]; then
-              verbosity="$2"
-              shift
-            else
-              verbosity="debug"
-            fi
-            ;;
-        esac
+    -h | --help) end_process --usage ;;
+    -v | --version) end_process --version ;;
+    -q | --quiet) verbosity=quiet ;;
+    -d=* | --verbose=*) verbosity="${1#*=}" ;;
+    -d | --verbose)
+      case "$2" in
+      */*) verbosity="debug" ;;
+      *)
+        if [ "$2" ]; then
+          verbosity="$2"
+          shift
+        else
+          verbosity="debug"
+        fi
         ;;
-      -U | --unique) unique=true ;;
-      -D | --allow-dups) unset unique ;;
-      -p | --previous) wallpaper_action="previous" ;;
-      -n | --next) wallpaper_action="next" ;;
-      -a | --archive) wallpaper_action="archive" ;;
-      -f | --love | --fav) wallpaper_action="favorite" ;;
-      -i | -t | --info | --dry-run) unset wallpaper_action ;;
-      -s | --sorted) sorted=true ;;
-      -L | --lockscreen) lockscreen=true ;;
-      -r | --reset) reset=true ;;
-      -l | --log*) wallpaper_log_path="$2" ;;
-      -[wW] | --wal*) wallpaper_src_path="$2" ;;
-      --timed) timed="$2" ;;
-      -*) end_process --error opt "$1" ;;
-      *) wallpaper_src_path="$1" ;;
+      esac
+      ;;
+    -U | --unique) unique=true ;;
+    -D | --allow-dups) unset unique ;;
+    -p | --previous) wallpaper_action="previous" ;;
+    -n | --next) wallpaper_action="next" ;;
+    -a | --archive) wallpaper_action="archive" ;;
+    -f | --love | --fav) wallpaper_action="favorite" ;;
+    -i | -t | --info | --dry-run) unset wallpaper_action ;;
+    -s | --sorted) sorted=true ;;
+    -L | --lockscreen) lockscreen=true ;;
+    -r | --reset) reset=true ;;
+    -l | --log*) wallpaper_log_path="$2" ;;
+    -[wW] | --wal*) wallpaper_src_path="$2" ;;
+    --timed) timed="$2" ;;
+    -*) end_process --error opt "$1" ;;
+    *) wallpaper_src_path="$1" ;;
     esac
     shift
   done
@@ -91,10 +91,10 @@ init_defaults() { #@ Initalize default variables
   icon="${icon:-$icon_success}"
 
   case "$verbosity" in
-    error) verbosity=1 ;;
-    info) verbosity=2 ;;
-    debug) verbosity=3 ;;
-    *) unset verbosity ;;
+  error) verbosity=1 ;;
+  info) verbosity=2 ;;
+  debug) verbosity=3 ;;
+  *) unset verbosity ;;
   esac
 
 }
@@ -132,8 +132,8 @@ find_images() { #@ Recursively search for image files
       -name "*.png" -o \
       -name "*.svg" -o \
       -name "*.tiff" \
-      \) \
-      | sort --human-numeric-sort
+      \) |
+      sort --human-numeric-sort
   fi
 }
 
@@ -158,8 +158,8 @@ validate_hd_image() { #@ Check of a file is an HD image
   height=${dimensions#*x}
 
   #@ Return true if the image is HD
-  [ "$width" -ge "$min_width" ] && [ "$height" -ge "$min_height" ] \
-    && printf "%s" "$1"
+  [ "$width" -ge "$min_width" ] && [ "$height" -ge "$min_height" ] &&
+    printf "%s" "$1"
 }
 
 count_lines() { #@ Count lines in a given file
@@ -197,7 +197,7 @@ add_line() { #@ Append text to a file
   }
 
   #@ Process
-  printf "%s\n" "$2" >> "$1"
+  printf "%s\n" "$2" >>"$1"
 }
 
 #/> Execution                                       <\
@@ -244,8 +244,8 @@ log_wallpaper() {
 
     #@ Add default wallpaper, if valid but not in the log
     if
-      [ "$(pathof "$wallpaper_lnk_path")" != "$wallpaper_lnk_path" ] \
-        && [ -f "$wallpaper_lnk_path" ] && [ ! "$wallpaper_src_path" ]
+      [ "$(pathof "$wallpaper_lnk_path")" != "$wallpaper_lnk_path" ] &&
+        [ -f "$wallpaper_lnk_path" ] && [ ! "$wallpaper_src_path" ]
     then
       #@ Set wallpaper as default
       wallpaper="$(pathof "$wallpaper_lnk_path")"
@@ -292,8 +292,8 @@ log_wallpaper() {
     #@ Generate a new wallpaper or move up in the log
     [ "$wallpaper_action" = "next" ] && {
       if
-        [ ! "$(log_entry)" ] \
-          || [ "$(log_entry)" -eq "$(log_entries)" ]
+        [ ! "$(log_entry)" ] ||
+          [ "$(log_entry)" -eq "$(log_entries)" ]
       then
         # wallpaper_src_path="$(get_wallpaper)" && log__new
         get_wallpaper "$wallpaper_src_path" && log__new
@@ -330,11 +330,11 @@ set_wallpaper() {
   update_wallpaper() {
     #@ Set wallpaper based on display protocal
     if [ "$WAYLAND_DISPLAY" ]; then
-      weHave swaybg \
-        && swaybg --image "$wallpaper_src_path" --mode fill &
+      weHave swaybg &&
+        swaybg --image "$wallpaper_src_path" --mode fill &
     elif [ "$DISPLAY" ]; then
-      weHave feh \
-        && feh --bg-fill "$wallpaper_src_path" &
+      weHave feh &&
+        feh --bg-fill "$wallpaper_src_path" &
     fi
 
     # __msg__ --set-wallpaper
@@ -369,15 +369,15 @@ __msg__() {
   icon="$success"c
 
   case "$1" in
-    --log) msg="Wallpaper logged: $(log_entry) => $wallpaper_src_path" ;;
-    --log-init) msg="Log initialized" ;;
-    --log-default) msg="Addind default wallpaper to log" ;;
-    --set-default) msg="Default wallpaper updated" ;;
-    --set-wallpaper) msg="Wallpaper updated" ;;
-    --log-empty) msg="Unable to set previous wallpaper from log" icon="$error" ;;
-    --reset-wp) msg="Default wallpaper deleted" icon="$dead" ;;
-    --reset-log) msg="Wallpaper log deleted" icon="$dead" ;;
-    *) ;;
+  --log) msg="Wallpaper logged: $(log_entry) => $wallpaper_src_path" ;;
+  --log-init) msg="Log initialized" ;;
+  --log-default) msg="Addind default wallpaper to log" ;;
+  --set-default) msg="Default wallpaper updated" ;;
+  --set-wallpaper) msg="Wallpaper updated" ;;
+  --log-empty) msg="Unable to set previous wallpaper from log" icon="$error" ;;
+  --reset-wp) msg="Default wallpaper deleted" icon="$dead" ;;
+  --reset-log) msg="Wallpaper log deleted" icon="$dead" ;;
+  *) ;;
   esac
 
   printf "%s %s\n" "$icon" "$msg"
@@ -398,8 +398,8 @@ run_process() { #@ Change the wallpaper
 
 __cleanup__() {
   case "$1" in
-    --error) exit 1 ;;
-    *) exit 0 ;;
+  --error) exit 1 ;;
+  *) exit 0 ;;
   esac
 }
 
@@ -424,15 +424,15 @@ dry_run() { #@ Test
 end_process() { #@ Exit application gracefully
   #TODO differentiate between main processes and subproceses. exit for main and return for sub
   case "$1" in
-    --error)
-      #@ Throw errors based on options
-      display_info "${1}"-"${2}" "${3}"
+  --error)
+    #@ Throw errors based on options
+    display_info "${1}"-"${2}" "${3}"
 
-      #@ Set error status code
-      error_generated=true
-      ;;
-    --output) display_info "$1" "$2" ;;
-    *) ;;
+    #@ Set error status code
+    error_generated=true
+    ;;
+  --output) display_info "$1" "$2" ;;
+  *) ;;
   esac
 
   #@ Exit with an error status
@@ -456,34 +456,34 @@ sanitize_environment() { #@ Remove varibles
 display_info() { #@ Display infoirmation
 
   case "$1" in
-    --error*)
-      [ "$verbosity" = "quiet" ] && return
-      case "$1" in
-        --error-path) printf "Invalid path: %s" "$2" ;;
-        --error-circ) printf "Circular symbolic link: %s" "$2" ;;
-        --error-info) printf "Invalid verbosity level: %s" "$2" ;;
-        --error-arg) printf "<wallpaper_src_path> required \nUsage: %s\n" "$SCRIPT_USAGE" ;;
-        --error-opt) printf "Unrecognized option: %s" "$2" ;;
-        --error-cd) printf "Change directory operation failed" ;;
-        --reset-log) printf "Change directory operation failed" ;;
-      esac
+  --error*)
+    [ "$verbosity" = "quiet" ] && return
+    case "$1" in
+    --error-path) printf "Invalid path: %s" "$2" ;;
+    --error-circ) printf "Circular symbolic link: %s" "$2" ;;
+    --error-info) printf "Invalid verbosity level: %s" "$2" ;;
+    --error-arg) printf "<wallpaper_src_path> required \nUsage: %s\n" "$SCRIPT_USAGE" ;;
+    --error-opt) printf "Unrecognized option: %s" "$2" ;;
+    --error-cd) printf "Change directory operation failed" ;;
+    --reset-log) printf "Change directory operation failed" ;;
+    esac
+    ;;
+  --output)
+    case "$verbosity" in
+    quiet) ;;
+    info) printf "%s\n" "$normalized_path" ;;
+    debug)
+      printf "    Verbosity: %s\n" "$verbosity"
+      printf "  Target Path: %s\n" "$wallpaper_src_path"
+      printf "Absolute Path: %s\n" "$normalized_path"
       ;;
-    --output)
-      case "$verbosity" in
-        quiet) ;;
-        info) printf "%s\n" "$normalized_path" ;;
-        debug)
-          printf "    Verbosity: %s\n" "$verbosity"
-          printf "  Target Path: %s\n" "$wallpaper_src_path"
-          printf "Absolute Path: %s\n" "$normalized_path"
-          ;;
-      esac
-      ;;
-    --version)
-      printf "%s" "$SCRIPT_VERSION"
-      ;;
-    --usage)
-      cat << USAGE
+    esac
+    ;;
+  --version)
+    printf "%s" "$SCRIPT_VERSION"
+    ;;
+  --usage)
+    cat <<USAGE
 Description:
 '$SCRIPT_NAME' by $SCRIPT_AUTHOR $SCRIPT_DESCRIPTION
 
@@ -528,8 +528,8 @@ Examples:
   "$SCRIPT_NAME" /var/log/../lib --verbose info
   "$SCRIPT_NAME" /var/run
 USAGE
-      ;;
-    *) printf "%s\n" "$*" ;;
+    ;;
+  *) printf "%s\n" "$*" ;;
   esac
 }
 
diff --git a/Bin/shellscript/utility/weatherin b/Bin/shellscript/utility/weatherin
--- a/Bin/shellscript/utility/weatherin
+++ b/Bin/shellscript/utility/weatherin
@@ -21,34 +21,34 @@ usage() {
 fetch_weather() {
   while [ $# -gt 0 ]; do
     case "$1" in
-      --location)
-        if [ -z "$2" ]; then
-          printf "Error: --location requires a value.\n" >&2
-          usage
-          return 1
-        else
-          location="$2"
-          shift
-          #@ Replace '+' with ',' and remove spaces from the location
-          location=$(printf "%s" "$location" | tr '+' ',' | tr -d ' ')
-
-          #@ Validate location format
-          printf "%s" "$location" \
-            | grep --quiet --extended-regexp '^-?[0-9]{1,3}(\.[0-9]+)?,-?[0-9]{1,3}(\.[0-9]+)?$' || {
-            printf "Error: Invalid location format." >&2 \
-              && printf "Use format like '18.0431254,-77.50741' (float,float) or '18,-77' (int,int) without spaces.\n" >&2
-            return 1
-          }
-        fi
-        ;;
-      --verbose)
-        verbose=true
-        ;;
-      *)
-        printf "Error: Unknown option '%s'.\n" "$1" >&2
+    --location)
+      if [ -z "$2" ]; then
+        printf "Error: --location requires a value.\n" >&2
         usage
         return 1
-        ;;
+      else
+        location="$2"
+        shift
+        #@ Replace '+' with ',' and remove spaces from the location
+        location=$(printf "%s" "$location" | tr '+' ',' | tr -d ' ')
+
+        #@ Validate location format
+        printf "%s" "$location" |
+          grep --quiet --extended-regexp '^-?[0-9]{1,3}(\.[0-9]+)?,-?[0-9]{1,3}(\.[0-9]+)?$' || {
+          printf "Error: Invalid location format." >&2 &&
+            printf "Use format like '18.0431254,-77.50741' (float,float) or '18,-77' (int,int) without spaces.\n" >&2
+          return 1
+        }
+      fi
+      ;;
+    --verbose)
+      verbose=true
+      ;;
+    *)
+      printf "Error: Unknown option '%s'.\n" "$1" >&2
+      usage
+      return 1
+      ;;
     esac
     shift
   done
@@ -57,8 +57,8 @@ fetch_weather() {
   # https://wttr.in/52.2297,21.0122?format=%C+%t+%w+%h "Warsaw, Poland"
 
   case "$verbose" in
-    '' | 0) curl -s "https://wttr.in/${location}" ;;
-    *) curl -s "https://wttr.in/${location}?format=%C+%t+%w+%h" ;;
+  '' | 0) curl -s "https://wttr.in/${location}" ;;
+  *) curl -s "https://wttr.in/${location}?format=%C+%t+%w+%h" ;;
   esac
 }
 
@@ -106,39 +106,39 @@ initialize_() {
   #@ Parse arguments
   while [ $# -gt 0 ]; do
     case "$1" in
-      --latitude)
-        if [ -n "$2" ]; then
-          latitude="$2"
-          shift 2
-        else
-          printf "Error: --latitude requires a value.\n" >&2
-          usage
-          exit 1
-        fi
-        ;;
-      --longitude)
-        if [ -n "$2" ]; then
-          longitude="$2"
-          shift
-        else
-          printf "Error: --longitude requires a value.\n" >&2
-          usage
-          exit 1
-        fi
-        ;;
-      --verbose)
-        verbose=true
-        ;;
-      --debug)
-        debug=true
-        ;;
-      *)
-        if [ "$location" ]; then
-          location="${location},$1"
-        else
-          location="$1"
-        fi
-        ;;
+    --latitude)
+      if [ -n "$2" ]; then
+        latitude="$2"
+        shift 2
+      else
+        printf "Error: --latitude requires a value.\n" >&2
+        usage
+        exit 1
+      fi
+      ;;
+    --longitude)
+      if [ -n "$2" ]; then
+        longitude="$2"
+        shift
+      else
+        printf "Error: --longitude requires a value.\n" >&2
+        usage
+        exit 1
+      fi
+      ;;
+    --verbose)
+      verbose=true
+      ;;
+    --debug)
+      debug=true
+      ;;
+    *)
+      if [ "$location" ]; then
+        location="${location},$1"
+      else
+        location="$1"
+      fi
+      ;;
     esac
   done
 }
diff --git a/Bin/shellscript/utility/ytdon b/Bin/shellscript/utility/ytdon
--- a/Bin/shellscript/utility/ytdon
+++ b/Bin/shellscript/utility/ytdon
@@ -9,25 +9,25 @@ skip=false
 
 while [ "$1" != "" ]; do
   case $1 in
-    -m | --media)
-      shift
-      media=$1
-      ;;
-    -q | --quality)
-      shift
-      quality=$1
-      ;;
-    -l | --url)
-      shift
-      link=$1
-      ;;
-    -s | --skip)
-      skip=true
-      ;;
-    *)
-      echo "Invalid option: $1"
-      exit 1
-      ;;
+  -m | --media)
+    shift
+    media=$1
+    ;;
+  -q | --quality)
+    shift
+    quality=$1
+    ;;
+  -l | --url)
+    shift
+    link=$1
+    ;;
+  -s | --skip)
+    skip=true
+    ;;
+  *)
+    echo "Invalid option: $1"
+    exit 1
+    ;;
   esac
   shift
 done
@@ -69,20 +69,20 @@ handle_existing_file() {
     echo "3. Rename"
     read -r choice
     case $choice in
-      1) echo "Overwriting file..." ;;
-      2)
-        echo "Skipping file..."
-        return 1
-        ;;
-      3)
-        echo "Enter new file name:"
-        read -r new_file_name
-        file_name=$new_file_name
-        ;;
-      *)
-        echo "Invalid input. Skipping file..."
-        return 1
-        ;;
+    1) echo "Overwriting file..." ;;
+    2)
+      echo "Skipping file..."
+      return 1
+      ;;
+    3)
+      echo "Enter new file name:"
+      read -r new_file_name
+      file_name=$new_file_name
+      ;;
+    *)
+      echo "Invalid input. Skipping file..."
+      return 1
+      ;;
     esac
   fi
 }
@@ -99,7 +99,7 @@ download() {
     if [ "$quality" = "hd" ]; then
       yt-dlp -f bestaudio -o "$file_name" "$link"
     else
-      yt-dlp -f bestaudio[abr -o "$file_name" "$link" < =128]
+      yt-dlp -f bestaudio[abr -o "$file_name" "$link" <=128]
     fi
   fi
 }
