shell.nix created and tested

diff --git a/Bin/utility/files/pathman b/Bin/utility/files/pathman
--- a/Bin/utility/files/pathman
+++ b/Bin/utility/files/pathman
@@ -9,19 +9,20 @@ main() {
 
 initialize_env() {
   #@ set defaults
-  verbosity=3
+  verbosity=0
   action="show"
   bins=""
   debug=""
+  delimiter="$(printf '\037')"
 
   #@ Cache command checks at startup
   HAS_REALPATH=0
   HAS_FD=0
   command -v realpath >/dev/null 2>&1 && HAS_REALPATH=1
   command -v fd >/dev/null 2>&1 && HAS_FD=1
+  command -v bat >/dev/null 2>&1 && HAS_BAT=1
 }
 parse_arguments() {
-  delimiter="|"
   while [ "$#" -gt 0 ]; do
     case "$1" in
     --debug)
@@ -64,7 +65,10 @@ parse_arguments() {
       fi
       ;;
     *)
-      if [ "$bins" ]; then
+      if [ -f "$1" ]; then
+        make_exec "$1"
+        return 0
+      elif [ "$bins" ]; then
         bins="$(printf '%s%s%s' "$bins" "$delimiter" "$(resolved_path "$1")")"
       else
         bins="$(resolved_path "$1")"
@@ -123,23 +127,6 @@ recursive_paths() {
   done | sort
 }
 
-# recursive_paths() {
-#   printf '%s' "$1" | tr "$delimiter" '\n' | while IFS= read -r dir; do
-#     [ ! -d "$dir" ] && {
-#       printf "Error: '%s' is not a directory\n" "$dir" >&2
-#       continue
-#     }
-
-#     if [ "$HAS_FD" = 1 ]; then
-#       fd -H -t f . "$dir" 2>/dev/null
-#       printf '%s\n' "$dir"
-#     else
-#       find "$dir" -type f 2>/dev/null
-#       printf '%s\n' "$dir"
-#     fi
-#   done | sort
-# }
-
 os_type() {
   case "$(uname -a | tr '[:upper:]' '[:lower:]')" in
   *linux*) os_type="linux" ;;
@@ -150,7 +137,7 @@ os_type() {
   #TODO This is utterly inadequete, just temporary
   printf "%s" "$os_type"
 }
-add_to_path() {
+add_to_path_ORIG() {
   [ "$debug" ] && {
     counter=1
     recursive_paths "$bins" | while IFS= read -r bin_path; do
@@ -200,11 +187,20 @@ add_to_path() {
         }
         ;;
       esac
+
   done
+
+  #@ Return the new PATH
+  printf "%s\n" "$PATH"
 }
 
 show_bins() {
-  printf "%s\n" "${1:-"$PATH"}" | tr ':' '\n' | nl -s '  '
+  printf "%s\n" "${1:-"$PATH"}" | tr ':' '\n' |
+    eval "$(if [ "$HAS_BAT" ]; then
+      printf "bat --color=always --style=grid --plain --number"
+    else
+      printf "nl -s '  ' | less"
+    fi)"
 }
 
 is_absolute_path() {
@@ -234,6 +230,66 @@ clean_path() {
   #DOC   - Reconstructs PATH format
 
   printf '%s\n' "${PATH-}" | tr ':' '\n' | grep '^/' | paste -s -d ':'
+}
+
+make_exec() {
+  _file=$1
+  chmod_status=0
+  chmod +x "$_file" >/dev/null 2>&1
+  chmod_status=$?
+  [ "$verbosity" -gt 1 ] && {
+    if [ "$chmod_status" -eq 0 ]; then
+      printf "    Script initialized: %s\n" "${_file}"
+    else
+      printf "    Failed to make %s executable: %s\n" "${_file}" "$chmod_status"
+    fi
+  }
+}
+
+add_to_path() {
+  tmp_path=$(mktemp) || return 1
+  recursive_paths "$bins" >"$tmp_path"
+
+  if [ "$debug" ]; then
+    counter=1
+    while IFS= read -r bin_path; do
+      printf "  %4d %s\n" "$counter" "$bin_path"
+      counter=$((counter + 1))
+    done <"$tmp_path"
+    rm "$tmp_path"
+    return 0
+  fi
+
+  while IFS= read -r bin_path; do
+    [ -d "$bin_path" ] &&
+      case ":${PATH}:" in
+      *:"$bin_path":*) ;;
+      *)
+        case "$action" in
+        prepend)
+          PATH="${bin_path}${PATH:+:$PATH}"
+          _action="Appended"
+          ;;
+        append)
+          PATH="${PATH:+$PATH:}${bin_path}"
+          _action="Perpended"
+          ;;
+        esac
+        [ -d "$bin_path" ] && umask 022 && chmod 755 "$bin_path" #TODO: This is not working. Files created after running the script are not automatically executable.
+        [ "$verbosity" -gt 1 ] &&
+          printf "    %s to PATH: %s\n" "$_action" "${bin_path}"
+        ;;
+      esac
+
+    [ -f "$bin_path" ] &&
+      case "$(os_type)" in windows) ;;
+      *) make_exec "$bin_path" ;;
+      esac
+  done <"$tmp_path"
+
+  rm "$tmp_path"
+  [ "$verbosity" -gt 1 ] && show_bins
+  export PATH
 }
 
 #@ Execute the main function with the provided argument
